### ISSUE TITLE
bitpin co.

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#100]
##### نام شرکت
title: "بیت پین"

##### نام انگلیسی شرکت
name_en: "bitpin"

##### دسته‌ی فعالیت شرکت
industry: "کریپتوکارنسی ، صرافی آنلاین"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "1-50"

##### آدرس سایت شرکت
site: "https://bitpin.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بیت‌پین، محصول شرکت سنا ایمن مبادله از گروه شرکت‌های مطرح در حوزه فناوری اطلاعات و ارتباطات، مدیریت مالی و سرمایه‌گذاری و حقوقی به همراه تیمی از خبرگان حوزه فناوری و مدیریت مالی است. با توجه به اینکه بیت‌کوین و سایر ارزهای دیجیتال یک دارایی امن و مهم جهت سرمایه‌گذاری محسوب می‌شود، و از سوی دیگر امنیت و سادگی این معاملات در کشور از اهمیت بالایی برخوردار است، این تیم تصمیم به ایجاد یک سیستم امن، ساده و حرفه‌ای با در نظر گرفتن الزامات قانونی و حقوقی برای سرمایه‌گذاران، بازرگانان و فعالین کسب‌وکار جهت سرمایه‌گذاری و استفاده از ارزهای دیجیتال گرفت.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیت-پین/](https://tajrobe.github.io/%D8%A8%DB%8C%D8%AA-%D9%BE%DB%8C%D9%86/)
