### ISSUE TITLE
آرمان پژوهان سوبا

### ISSUE THREAD

**Issue by M-Mortaz** [tajrobe/tajrobe.github.io#101]
##### نام شرکت
title: "آرمان پژوهان سوبا"

##### نام انگلیسی شرکت
name_en: "sooba"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "http://apsooba.com/job-offers/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکتی بین المللی که در حوزه هوش مصنوعی و پایتون فعالیت می‌کند. مشتریان آن خارجی هستند و بخش بیزینس خارج از ایران است. "

**Comment by tajrobe** [comment]
[tajrobe.github.io/آرمان-سوبا/](https://tajrobe.github.io/%D8%A2%D8%B1%D9%85%D8%A7%D9%86-%D8%B3%D9%88%D8%A8%D8%A7/)
