### ISSUE TITLE
زنفی

### ISSUE THREAD

**Issue by KeyvanAghaie** [tajrobe/tajrobe.github.io#102]
##### نام شرکت
title: "زنفی"

##### نام انگلیسی شرکت
name_en: "zenphi"

##### دسته‌ی فعالیت شرکت
industry: "google aotumated service"

##### موقعیت مکانی شرکت
city: "Melbourn"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/زنفی/](https://tajrobe.github.io/%D8%B2%D9%86%D9%81%DB%8C/)
