### ISSUE TITLE
ذهن های زیبا

### ISSUE THREAD

**Issue by aramf99** [tajrobe/tajrobe.github.io#103]
##### نام شرکت
title: "ذهن های زیبا"

##### نام انگلیسی شرکت
name_en: "BMChains"

##### دسته‌ی فعالیت شرکت
industry: "بلاک‌چین"

##### موقعیت مکانی شرکت
city: "تهران، قلهک"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://bmco.tech/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ذهن-های-زیبا/](https://tajrobe.github.io/%D8%B0%D9%87%D9%86-%D9%87%D8%A7%DB%8C-%D8%B2%DB%8C%D8%A8%D8%A7/)
