### ISSUE TITLE
جوان فکران داده گستر (ویستا)

### ISSUE THREAD

**Issue by esa-kian** [tajrobe/tajrobe.github.io#104]
##### نام شرکت
title: "جوان فکران داده گستر (ویستا)"

##### نام انگلیسی شرکت
name_en: "vistaapp"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://vistaapp.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تولید کننده نرم افزار"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ویستا/](https://tajrobe.github.io/%D9%88%DB%8C%D8%B3%D8%AA%D8%A7/)
