### ISSUE TITLE
پیشگامان فولاد جنوب

### ISSUE THREAD

**Issue by nimakazemi** [tajrobe/tajrobe.github.io#105]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیشگامان-فولاد/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86-%D9%81%D9%88%D9%84%D8%A7%D8%AF/)
