### ISSUE TITLE
.

### ISSUE THREAD

**Issue by a-sohrabi** [tajrobe/tajrobe.github.io#106]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پرنیان-داده/](https://tajrobe.github.io/%D9%BE%D8%B1%D9%86%DB%8C%D8%A7%D9%86-%D8%AF%D8%A7%D8%AF%D9%87/)
