### ISSUE TITLE
مدیریت و توسعه فناوری اطلاعات آرمان

### ISSUE THREAD

**Issue by AbolfazlMehdi** [tajrobe/tajrobe.github.io#109]
##### نام شرکت
title: "مدیریت و توسعه فناوری اطلاعات آرمان"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "بانک توسعه صادرات"

##### موقعیت مکانی شرکت
city: "تهران ، میدان آرزانتین"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "http://www.armanitmd.com/about"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه ‎ای که در آذرماه 1387 و به منظور تأمین تمامی نیازمندی‎ های حوزه‎ ی فناوری اطلاعات بانک توسعه صادرات ایران و شرکت‎ های تابعه‎ ی آن"در قالب یک سازمان واحد " و به عنوان بازوی اجرایی فاوای بانک، مسیر خود را آغاز نمود و طی این سال‎ها، با رویکرد ارائه‎ ی چابک خدمات تخصصی به بانک توسعه صادرات ایران به‎عنوان مالک اصلی خود، تلاش نموده تا سرویس ‎هایی باکیفیت، کارا و بهینه را دراختیار تنها اگزیم ‎بانک کشور قراردهد."

**Comment by AbolfazlMehdi** [comment]
یه شرکت فوقالعاده پر از حاشیه و بی ثبات ، مدیراشون اصلا به نیروها شون اهمتی نمیدن ، تنها شرکتیه که دیدم مدیراش و تیم لیداش دنبال حاشیه درست کردن و تفرقه انداختن بین بچه هاس

**Comment by tajrobe** [comment]
[tajrobe.github.io/فناوری-آرمان/](https://tajrobe.github.io/%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%A2%D8%B1%D9%85%D8%A7%D9%86/)
