### ISSUE TITLE
بیمه سینا

### ISSUE THREAD

**Issue by arezupanahi** [tajrobe/tajrobe.github.io#110]
##### نام شرکت
title: "بیمه سینا"

##### نام انگلیسی شرکت
name_en: "sina insurance"

##### دسته‌ی فعالیت شرکت
industry: "insurance"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "1000"

##### آدرس سایت شرکت
site: "https://www.sinainsurance.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت بیمه سینا )سهامی عام( بر اساس قانون تأسیس مؤسسات بیمه غیردولتی و طی مجوز شماره
23167 بیمه مرکزی ایران با سرمایه اولیه 140 میلیارد ریال که تماماً پرداخت گردیده بود در 10 آبان
1382 تأسیس شد و فعالیت بیمهگری خود را رسماً از 28 آبان ماه 1382 آغاز نمود ."

**Comment by arezupanahi** [comment]
از این شرکت برای مصاحبه چندین بار با من تماس گرفتن ، همون دفعه ی اول من حداقل حقوق خودم رو اعلام کردم و بار دوم تماس گرفتند و گفتند که حضوری تشریف بیارید . مصاحبه حضوری اول بعد از پر کردن فرم استخدام که همون چیزهایی که دقیقا تو رزومه ذکر شده و مجدد باید دستنویس پر کنیم رو انجام دادم و اونجا مجدد حقوق رو پرسیدن و من عدد مدنظرم رو گفتم . بعد از یک هفته تماس گرفتن و مدیریت فنی  که خانم مذهبی ای بودن مجدد سوالات تکراری ای رو پرسیدن و من هم جواب دادم ، چند وقت بعد تماس گرفتن که تایید شدید، مجدد برای مصاحبه با hr بصورت حضوری رفتم و جالبه که سوالات تکراری مطرح شد و در اخر گفتن که باید یه مصاحبه با معاونت داشته باشید ، چند وقت بعد مصاحبه با مدیریت این شرکت محترم را رفتم و همون سوال و جواب های تکراری انجام شد. چند روز بعد مجدد تماس گرفتن و حقوقی که من واضح بصورت کتبی و شفاهی همون بار اول اعلام کردم رو پرسیدن و گفتن گویا اشتباهی شده و در رابطه با حقوق شما مشکلی بوجود امده . 
چند روز بعدش من  با  قسمت فنی این مجموعه تماس گرفتم که لطفا بفرمایید که نتیجه ی مصاحبه چه شد و گفتند که گویا در رابطه با حقوق شما مشکلی دارند که از قسمت منابع انسانی باهاتون تماس می گیرند اما هیچ تماسی از این شرکت مبنی بر تایید یا عدم تایید گرفته نشد و من واقعا متاسفم برای این شرکت هایی که ادعای بزرگی می کنند ولی حتی کوچکترین مسائل اخلاقی در رابطه با وقت و هزینه ای که فرد مصاحبه شونده می کند را رعایت نمی کنند . 
در اخر برای کسانی که نرم افزاری هستند توصیه می کنم که وقت با ارزششون رو برای چنین شرکت هایی هدر ندهند.

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیمه-سینا/](https://tajrobe.github.io/%D8%A8%DB%8C%D9%85%D9%87-%D8%B3%DB%8C%D9%86%D8%A7/)
