### ISSUE TITLE
آرکس

### ISSUE THREAD

**Issue by farideghbali** [tajrobe/tajrobe.github.io#111]
##### نام شرکت: آرکس - ارکس - پیزا 360
title: "آرکس- ارکس - پیزا 360"

##### نام انگلیسی شرکت: Arex - pizza360
name_en: "Arex - pizza360"

##### دسته‌ی فعالیت شرکت: کامپیوتر، فناوری اطلاعات و اینترنت
industry: "Programming and website design"

##### موقعیت مکانی شرکت: نامشخص
city: "Tehran/iran"

##### تعداد نفرات شرکت نامشخص
size: "Unknown"

##### آدرس سایت شرکت www.arexgo.com, www.pizza360.ir
site: "www.arexgo.com, www.pizza360.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش: اگر بصورت خیلی خلاصه میخواهید که از فعالیت‌های این شرکت باخبر شوید در یک جمله بهتون میگم که این شرکت از اون دسته از شرکت‌هایی است که وبسایت‌هایی رو تحت عنوان آزمون ورودی و استخدام مشروط ازتون میخواد طراحی کنید که خود این وبسایت پروداکت هست و به فروش میرسه و در آخر خیلی شیک و مجلسی به هر دلیل غیرمنطقی که فکرش رو هم نمیتونید بکنید بیرونتون میکنن(بدون هیچ دستمزدی). هیچ وقت اعضای تیم رو نمیبیند و شماره تماسشون رو ندارین و تنها از طریق سکرت چت تلگرام باهاتون در ارتباطن این شرکت طراحی وبسایت‌های خارج از کشور رو برعهده داره.

وبسایت‌ها: 
www.arexgo.com
www.pizza360.ir
با اسم‌های آرکس و پیزا360 فعالیت دارند. هیچ اکانت لینکدین فعالی ندارند (یا حداقل من پیدا نکردم)
معایب:
- تاخیر چند ماهه در بررسی رزومه و استخدام
- فرایند طولانی و کاملا مبهم استخدام؛ هیچ وقت هیچ چیز در مصاحبه شفاف نیست.
- پاسکاری بین اعضای تیم در ضمن استخدام (بیش از ده نفر)
- رزومه، صحبت‌ها، شرایط و حقوق درخواستی شما به هیچ عنوان براشون مهم نیست.
- دید شرکت به دولوپر اینکه دولوپر یک موجود کلاه‌بردار، به دردنخور، از زیرکار در رو، بی ارزش و مزاحمی هست که باید حمالی و بندگی شرکت رو بکنه و همیشه حرف‌هایی رو میشنوین و طرز بیانی دارند که مرتب احساس اضافه بودن بهتون دست میده.
- ابهام در سرتاسر کار به شرحی که حتی کوچکترین سوالات شما بدون پاسخ میمونه
**- هربار حرفشون عوض میشه؛ در فرایند مصاحبه یه حرفی میشنوید و در ادامه کار حرف‌های کاملا متفاوت از اونچه بهتون گفته شده**
- صفر تا صد پروژه از طراحی عکس، طراحی گرافیکی، طراحی تجربه و رابط کاربری، توسعه با وردپرس و حتی نوشتن متون کاملا مرتبط و ... با حقوق وزارت کار برعهده شماست.
- هرآنچه از ابزار در این شرکت هست برای ازیت کردن و سخت کردن کار شما سفارشی سازی شده.
- تمامی ارتباط‌ها از طریق سکرت چت تلگرام هست و هیچ رد تماسی ازشون ندارید.

مزایا: با ساختار شرکت‌های کلاه بردار آشنا میشین و در آینده از گزند این نوع شرکت‌ها در امان خواهید بود.

شرح مفصل:
اجازه بدین مفصل تجربه خودم رو باهاتون به اشتراک بزارم:
4 ماه بعد از ارسال رزومه باهام تماس گرفتن و گفتن که رزومه‌تون مورد قبول قرارگرفته و برای مصاحبه به یک گروه تلگرام دعوتم کردند. مصاحبه شامل سوالات تکراری (که داخل رزومه قید شده) و سوالاتی که به هیچ عنوان ارتباطی با شغلتون نداره هست. همینطور هم داخل رزومه قید کرده بودم و همینکه در مصاحبه عرض کردم که حداقل حقوق من (با تاکید به اینکه گفتن شرح وظایف توسعه دهنده فقط طراحی با صفحه ساز وردپرس هست ولاغیر) ساعتی 65 هزارتومان است.
ماجرا به همین ختم نشد و فرایند مصاحبه ادامه‌دار شد البته تنها چیزی که دربر داشت پاسکاری کردن به افراد مختلف بود. هیچ‌کس هیچ‌نوع سوالی از من نداشت فقط بین افراد مختلف پاسکاری میشدم که با حالتی طلبکارانه یک سری قوانین رو مطرح کنن و اطلاعات تماس نفر بعدی رو بهم بدن ولاغیر! هرگونه سوال بنده‌هم کاملا بدون جواب میموند یا با گفتن "سوپروایزرتون در آینده بهتون اطلاع میدن" به حاشیه کشیده میشد. فرایند استخدام یک ماه و نیم طول کشید!
بعد از چند روز در همون گروه اعلام کردند که در مصاحبه مورد تایید قرار گرفتید و باید یک وبسایت بصورت آزمایشی با موضوع گردشگری برروی هاست و دامنه خودمون طراحی کنید. بعد از طراحی وبسایت نهایتا به بنده اطلاع دادن که کارت خیلی خوب بوده اما برای اطمینان از مهارت‌های شما باید یک ماه مشروط کار کنید و در این مدت سوپروایزر شما رو تحت نظر داره و بسته به توانایی‌های شما حقوقتون رو از 4 تا 7 میلیون تومان(تمام وقت) تعیین میکنه.
سوال: اگر من آزمون ورودی دادم، یکماه مشروط برای چیه؟ اگر قراربود یکماه مشروط کار کنم چرا آزمون ورودی دادم؟
سوال دوم: مگر من بهشون حداقل قیمت ندادم، پس سوپروایزر چرا باید تعیین کنه(نصف قیمتی که تو بهشون دادی)؟
سوال سوم: چرا این بازه حقوقی رو قبل از طراحی وبسایت آزمون ورودی یا در همون مصاحبه ابتدایی نگفتن؟
بعد از اعتراض به مبلغ دریافتی عرض کردند که کار رو با همون حقوق بصورت پاره‌وقت انجام بدم.

در یک ماه مشروط وبسایتی رو با موضوع کارواش به بنده دادند که طراحی کنم که باید در 10 روز کاری و 80 ساعت (میانگین روی 8 ساعت) کار توسعه تموم بشه. عرض کردند تمام موارد طراحی وب از جمله: ایده‌پردازی، طراحی گرافیکی، جمع‌آوری تصاویر مرتبط با موضوع وبسایت(مثلا کارواش یا رستوران یا گردشگری)، توسعه و ... برعهده شماست و این موارد نباید از هیچ جایی کپی بشن!
سوال: مگر کار پاره‌وقت نبود الان چرا شد روزی 8 ساعت؟
سوال دوم: مگر من در جلسه مصاحبه گفته نشد که شرح وظایف بنده فقط طراحی با صفحه ساز وردپرس هست، مگر بنده توسعه دهنده نیستم، پس طراحی رابط کاربری یا جمع آوری محتوی بدون دریافت هیچ گونه هزینه اضافی چرا باید توسط من انجام بشه؟
از روی ناچاری (نیازم به پول جهت جراحی گلوی مادرم) شرایط رو قبول کردم اما بازهم در این مدت همه سوالات شما در گروه تلگرام سین میخوره اما جوابی بهتون نمیدن، اصلا توجهی به مواردی که شما مطرح میکنید ندارند
 همه وبسایتها باید برروی دامنه و هاست خودشون طراحی بشه و توسعه دهنده اجازه دسترسی به هیچگونه آپلود و یا حذف و اضافه‌ای نداره، حتی آپلود محتوی یا فونت و باید براشون ارسال کنید که خودشون براتون آپلود کنند(توجه کنید شما برروی یک زیردامنه در حال طراحی هستید و با کانفیگ خاصی غیر از شما هیچکس دسترسی به وبسایت نداره که توسعه دهنده خرابکاری کنه و کسی ببینه، اینا غیر از اینه که میخوان توسعه دهنده فشار روحی بهش وارد بشه و کار رو ادامه بده(خطای شناختی)).... حتی دسترسی به تمام امکانات صفحه ساز وردپرس و قالب رو ندارین.
یک کانفیک بهتون میدن که فقط با استفاده از اون میتونید به وبسایت لاگین کنید. و در اخرسرهم خیلی راحت دسترسی هاتون رو قطع میکنند و شما نمیتونید حتی وبسایتی که خودتون طراحی کردین و براش زحمت کشیدین رو ببینید!
از اون دسته از شرکت هایی هستند که دولوپر رو یک موجود مزاحم به درد نخور رو اعصاب و احمق فرض میکنند و کوچکترین بهایی بهش نمیدن.
بعد از اتمام طراحی، یک وبسایت درخور و بسیار زیبا با رعایت اصول سئو و ux تحویلشون دادم، اما به بهانه اینکه در چندتا از باکس‌های وبسایت از متون لورم اپیسوم استفاده کردم با این جمله (شما دانش و مهارت کافی ندارید) بیرونم کردند، و درآخر دسترسی‌هامو خیلی سریع قطع کردند از اغلب گروه‌های تلگرامی ریمو شدم و توسط تک تک اشخاصی که در فرایند استخدام باهاشون در تلگرام حرف زده بودم بلاک شدم. (دقت کنید فقط چند دقیقه بعد از تحویل وبسایت این اتفاق افتاد آیا فرصت کردند وبسایت رو بررسی کنند؟)
سوال: چرا باید بعد از چند دقیقه این تصمیم گرفته بشه؟
سوال دوم: آیا بازهم نمیشد متون لورم اپیسوم رو ویرایش کرد و متون مرتبط با کارواش رو براشون بزارم؟
سوال سوم: چرا بلاکم کردند؟
فکر کردن به این سوالات شمارو قطعا به این نتیجه میرسونه که این شرکت یک کلاهبردار تمام عیار هست که بدون استخدام افراد ازشون کار میکشه و نهایتا با بهانه‌های مختلف بیرونشون میکنن. اما اون چیزی که شمارو خیلی بیشتر باید به فکر بندازه اینه که:پ
وبسایت‌هایی که طراحی کردم به دامنه دیگری انتقال داده شده و احتمالا با قیمت بالایی به فروش رسیده
سوال: این وبسایت اگر به درد نمیخورد و من استخدام نشدم چرا انتقال داده شده؟
سوال دوم: بنظر شما برای هر وبسایت چند هزار دلار از مشتری گرفتن؟

برای اثبات حرف‌هام اسکرین شات هایی رو در ادامه قرار دادم
امیدوارم شما مورد سواستفاده شرکت #کلاه_بردار آرکس قرار نگیرید. بدرود

#111 #آرکس #ارکس #arex #pizza360 #تجربه کاری
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/آرکس/](https://tajrobe.github.io/%D8%A2%D8%B1%DA%A9%D8%B3/)
