### ISSUE TITLE
رهایافت

### ISSUE THREAD

**Issue by alishefaee** [tajrobe/tajrobe.github.io#112]
##### نام شرکت
title: "اندیش گستر رهایافت"

##### نام انگلیسی شرکت
name_en: "andish gostar rahayaft"

##### دسته‌ی فعالیت شرکت
industry: "web design"

##### موقعیت مکانی شرکت
city: "قم"

##### تعداد نفرات شرکت
size: "1"

##### آدرس سایت شرکت
site: "unavailable"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گرفتن سفارش طراحی سایت"

**Comment by alishefaee** [comment]
شرکت فوق ( البته نام شرکت را نمیتوان روی آن گذاشت ) با جذب نیروهای کارآموز و جونیور ( چون نیروی سنیور یک هفته‌ هم نمی ماند ) سعی در جذب و انجام پروژه های تحت وب دارد. و از بی تجربگی نیروهای تازه کار استفاده کرده و امضای قرارداد را به روزها و پروژه های آتی موکول میکنند.
همکاری با این شرکت جز هدر دادن یک ماه یا کم و بیشتر از عمر شما نیست.

**Comment by tajrobe** [comment]
[tajrobe.github.io/رهایافت/](https://tajrobe.github.io/%D8%B1%D9%87%D8%A7%DB%8C%D8%A7%D9%81%D8%AA/)
