### ISSUE TITLE
طرح ریزان حامی

### ISSUE THREAD

**Issue by MrKarimi9425** [tajrobe/tajrobe.github.io#113]
##### نام شرکت
title: "طرح ریزان حامی"

##### نام انگلیسی شرکت
name_en: "tarhrizan hami"

##### دسته‌ی فعالیت شرکت
industry: "برنامه نویسی"

##### موقعیت مکانی شرکت
city: "تهران انقلاب"

##### تعداد نفرات شرکت
size: "۱۰"

##### آدرس سایت شرکت
site: "no-et.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "سایت و اپلیکیشن"

**Comment by tajrobe** [comment]
[tajrobe.github.io/طرح-ریزان-حامی/](https://tajrobe.github.io/%D8%B7%D8%B1%D8%AD-%D8%B1%DB%8C%D8%B2%D8%A7%D9%86-%D8%AD%D8%A7%D9%85%DB%8C/)
