### ISSUE TITLE
مهندس شبکه-نهانت

### ISSUE THREAD

**Issue by FarzaadShojaei** [tajrobe/tajrobe.github.io#114]
##### نام شرکت
title: "نهانت"

##### نام انگلیسی شرکت
name_en: "Nahanet"

##### دسته‌ی فعالیت شرکت
industry: "Network"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "nahanet.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: " مصاحبش سه مرحلس،مرحله اول یه پیش مصاحبه منابع انسانی که چند تا سوال ساده مثل  نت تایپ و ... میپرسه
وضعیت نظام وظیفه و مهاجرت هم براشون مهمه. مصاحبه دوم یه مصاحبه اصلیه که هم سوال شبکه ای داره و هم سوال برنامه نویسی- مصاحبه سوم هم مصاحبه منابع انسانیه،امکان دورکاری هم فراهمه و محل شرکت هم تو یوسف آباد تهرانه"

**Comment by FarzaadShojaei** [comment]
مصاحبش سه مرحلس،مرحله اول یه پیش مصاحبه منابع انسانی که چند تا سوال ساده مثل نت تایپ و ... میپرسه
وضعیت نظام وظیفه و مهاجرت هم براشون مهمه. مصاحبه دوم یه مصاحبه اصلیه که هم سوال شبکه ای داره و هم سوال برنامه نویسی- مصاحبه سوم هم مصاحبه منابع انسانیه،امکان دورکاری هم فراهمه و محل شرکت هم تو یوسف آباد تهرانه

**Comment by tajrobe** [comment]
[tajrobe.github.io/نهانت/](https://tajrobe.github.io/%D9%86%D9%87%D8%A7%D9%86%D8%AA/)
