### ISSUE TITLE
سپهر افزار ایرانیان

### ISSUE THREAD

**Issue by codewithah** [tajrobe/tajrobe.github.io#115]
##### نام شرکت
title: "سپهر افزار ایرانیان"

##### نام انگلیسی شرکت
name_en: "Sain"

##### دسته‌ی فعالیت شرکت
industry: "Liferay Portal"

##### موقعیت مکانی شرکت
city: "Yazd"

##### تعداد نفرات شرکت
size: "+50"

##### آدرس سایت شرکت
site: "https://sain.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت سپهر افزار ایرانیان در سال  1380 با شعار دانش جهانی – خلاقیت ایرانی تاسیس گردیده است. در طول این سالها همواره از همکاری تیمی و شور و شوق ایجاد محصولات و خدمات نوین حفظ و پاسداری شده است و در بیست سال گذشته خدمات ومحصولات متنوعی به سازمانهای دولتی و غیردولتی و دانشگاه های برتر کشور ارائه گردیده است. در حال حاضر بیش از ۵۰ پرسنل متخصص در شرکت سپهر افزار ایرانیان در قالب تیم های مختلف فعالیت می کنند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سپهر-افزار/](https://tajrobe.github.io/%D8%B3%D9%BE%D9%87%D8%B1-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1/)
