### ISSUE TITLE
دکاشاپ

### ISSUE THREAD

**Issue by bellconnor7453** [tajrobe/tajrobe.github.io#116]
##### نام شرکت
title: "دکاشاپ"

##### نام انگلیسی شرکت
name_en: "dcashop"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه اینترنتی تجهیزات امنیتی و حفاظتی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "1-10"

##### آدرس سایت شرکت
site: "https://dcashop.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه دکاشاپ زیر مجموعه سایت اینترنتی دکا (DCA) می باشد که در سال 1386 فعالیت خود را با سایت بزرگترین بانک اطلاعاتی ساختمان آغاز نمود و پس از ارائه خدمات شامل اطلاعات کامل محصولات و مشخصات کامل آن و مقایسه با دیگر محصولات مورد اعتماد بسیاری از مشتریان قرار گرفت و سپس تصمیم به راه اندازی و ارائه فروش و خدمات گرفته شد که وبسایت دکاشاپ در دسترس قرار گرفته است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/دکاشاپ/](https://tajrobe.github.io/%D8%AF%DA%A9%D8%A7%D8%B4%D8%A7%D9%BE/)
