### ISSUE TITLE
فرزان فناوران پویان

### ISSUE THREAD

**Issue by Abdolali-Ahmadi** [tajrobe/tajrobe.github.io#117]
##### نام شرکت
title: "فرزان فناوران پویان"

##### نام انگلیسی شرکت
name_en: "farzan fanavaran poyan"

##### دسته‌ی فعالیت شرکت
industry: "طراحی سایت"

##### موقعیت مکانی شرکت
city: "بیرجند"

##### تعداد نفرات شرکت
size: "۱۰ - ۲۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Abdolali-Ahmadi** [comment]
ثبت شرکت < فرزان فناوران پویان >

**Comment by tajrobe** [comment]
[tajrobe.github.io/فرزان-فناوران/](https://tajrobe.github.io/%D9%81%D8%B1%D8%B2%D8%A7%D9%86-%D9%81%D9%86%D8%A7%D9%88%D8%B1%D8%A7%D9%86/)
