### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#118]

**Comment by pooooriya** [comment]
مشکل بیلد نشدنا چیه؟

**Comment by pooooriya** [comment]
راستی میدونستی از این به بعد تملپیت های nextjs هم میتونن داخل گیت هاب پیجز بیلد بشن !!! نظرت چیه یه ریفکتور کنیم سایت فعلیو یکم خوشگلش کنیم؟

**Comment by pooooriya** [comment]
https://github.com/gregrickaby/nextjs-github-pages

**Comment by tajrobe** [comment]
سلام. یه ایمیل داشتیم برای تغییر تجربه‌ی کاری، تغییر long text توی yml منجر به بیلدهای ناموفق میشد

**Comment by tajrobe** [comment]
در خصوص nextjs من تجربه‌ی کاربردی‌ای ندارم ولی جاوااسکریپت (بخصوص vanilla JS) بیشتر کار کردم. شخصا طراحی ساده و بدون js رو بیشتر می‌پسندم چرا که کمترین وابستگی به نسخه مرورگر رو داره؛ اما اگه فکر می‌کنی تغییر UI مفید باشه نظر من هم مساعده.👍
