### ISSUE TITLE
گروه صنعتی آفاق خودرو موتور

### ISSUE THREAD

**Issue by anuobis** [tajrobe/tajrobe.github.io#119]
##### نام شرکت
title: "گروه صنعتی آفاق خودرو موتور"

##### نام انگلیسی شرکت
name_en: "elig"

##### دسته‌ی فعالیت شرکت
industry: "لنت ترمز"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "https://elig.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "وارد کننده و فروشنده لنت ترمز سرامیکی ماشین و دیسک چرخ ماشین برند الیگ elig ژاپن با بهترین کیفیت و قیمت."

**Comment by tajrobe** [comment]
[tajrobe.github.io/آفاق-خودرو/](https://tajrobe.github.io/%D8%A2%D9%81%D8%A7%D9%82-%D8%AE%D9%88%D8%AF%D8%B1%D9%88/)
