### ISSUE TITLE
شرکت همگام رادین

### ISSUE THREAD

**Issue by mortezamsp** [tajrobe/tajrobe.github.io#120]
##### نام شرکت
title: "سامانه پردازان همگام رادین"

##### نام انگلیسی شرکت
name_en: "HamGam Radin"

##### دسته‌ی فعالیت شرکت
industry: "راه حل های مخابراتی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "http://www.hamgamradin.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت سامانه پردازان همگام رادین در فروردین ماه سال 1393 توسط گروهی از جوانان کارآزموده و تحصیل کرده تاسیس گردید و با تکیه بر کار تیمی و بکارگیری نیروی انسانی مجرب و مستعد در زمینه طراحی و پیاده سازی سامانه های مورد نیاز اقدام کند. این شرکت با هدف گام برداشتن در مرزهای جدیدترین فناوریهای اطلاعات و از آخرین ابزار و فناوریها در جهت اجرای پروژه های خود استفاده می‌نماید به این منظور با تربیت و آموزش نیروی انسانی شایسته و متخصص و ارتقاء جایگاه آنها همواره با تفویض اختیار مناسب، مسئولیت پذیری لازم را در سطوح مختلف سازمان گسترش می‌دهد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/همگام-رادین/](https://tajrobe.github.io/%D9%87%D9%85%DA%AF%D8%A7%D9%85-%D8%B1%D8%A7%D8%AF%DB%8C%D9%86/)
