### ISSUE TITLE
دفتر ترجمه رسمی پارسیس

### ISSUE THREAD

**Issue by mahdiiranpoor** [tajrobe/tajrobe.github.io#121]
**دفتر ترجمه رسمی پارسیس** به عنوان یک دفتر ترجمه فعال در ترجمه انواع مدارک و ترجمه های تخصصی انواع مقالات دانشگاهی بوده که قادر است در تمامی زبان های شاخص اقدام به [ترجمه رسمی](https://parsistrans.com/%D8%AA%D8%B1%D8%AC%D9%85%D9%87-%D8%B1%D8%B3%D9%85%DB%8C/) و ترجمه تخصصی توسط مترجمان انسانی نماید. دارالترجمه رسمی پارسیس با در اختیار داشتن بیش از 100 مترجم زبان و مترجم رسمی حضوری از سال 1384 تا به امروز فعالیت گسترده ای در ترجمه زبان های مختلف داشته است. اهم این فعالیت ها شامل برخی موارد زیر است:
ترجمه رسمی انواع مدارک برای اخذ ویزا از سفارت کشور مقصد
ترجمه تخصصی کتاب، ترجمه مقالات ژورنال
ترجمه رمان
ترجمه فیلم و زیرنویس
ترجمه شفاهی و مترجم تلفنی

https://parsistrans.com/

**Comment by tajrobe** [comment]
[tajrobe.github.io/پارسیس/](https://tajrobe.github.io/%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%B3/)
