### ISSUE TITLE
چاپ کارو (داریس)

### ISSUE THREAD

**Issue by ShahinGhamgosar** [tajrobe/tajrobe.github.io#122]
##### نام شرکت
title: ""
چاپ کارو (داریس)
##### نام انگلیسی شرکت
name_en: ""ChapKaro(Daris)

##### دسته‌ی فعالیت شرکت
industry: ""چاپ و طراحی

##### موقعیت مکانی شرکت
city: ""
تهران
##### تعداد نفرات شرکت
size: ""10

##### آدرس سایت شرکت
site: ""بهارستان

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""فعالیت در زمینه طراحی و چاپ بروشور و تراکت و ...

**Comment by ShahinGhamgosar** [comment]
شرکت چاپ کارو در زمینه‌ی چاپ و طراحی در محدوده بهارستان فعالیت می‌کنه. از بزرگترین معایب این شرکت نبود استراتژی و سیستم مدیریتی و نگاه از بالا به پایین است. در طول مصاحبه، وعده‌های زیادی اعم از پیشرفت شغلی و ارايه فرصت‌های جدید برای توسعه‌ مهارت‌ها داده می‌شه اما خب همش وعده است و در واقعیت معنا پیدا نمی‌کنن. بیمه نکردن، اضافه کاری زیاد حتی در دوران تعطیلات و محول کردن مسئولیت‌های جدید در پایان ساعات کاری و اجبار به کار بیش از 9 ساعت در شرکت و پرداخت نکردن اضافه کار است.

**Comment by tajrobe** [comment]
[tajrobe.github.io/داریس](https://tajrobe.github.io/%D8%AF%D8%A7%D8%B1%DB%8C%D8%B3/)
