### ISSUE TITLE
زی دکتر

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#123]
##### نام شرکت
title: "زی دکتر"

##### نام انگلیسی شرکت
name_en: "zi doctor"

##### دسته‌ی فعالیت شرکت
industry: "پزشکی و سلامت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-100"

##### آدرس سایت شرکت
site: "https://zidoctor.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تیم زی‌دکتر از جمعی از پزشکان، مهندسان حوزه تکنولوژی و متخصصان کسب و کار آنلاین تشکیل شده که هدف واحدشان همراهی شما در مسیر سلامت است. متخصصان هوش مصنوعی زی‌دکتر پا‌به‌پای پزشکان و دیگر متخصصان حوزه سلامت تلاش دارند شما را در سریع‌ترین زمان و با بالاترین دقت به تشخیص بیماری‌تان برسانند و پس از آن شما را به قابل‌اعتماد‌ترین متخصص مرتبط معرفی کنند."

**Comment by pooooriya** [comment]
داستان شرکتی که جیبم رو زد!
‌
🔸چند روز پیش توی [#جابینجا](https://www.linkedin.com/feed/hashtag/?keywords=%D8%AC%D8%A7%D8%A8%DB%8C%D9%86%D8%AC%D8%A7&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) چشمم به اسم شرکتی افتاد که جیبم رو زد! 🥷

🔹قضیه از این قرار بود که سال گذشته، من به صورت پاره‌وقت به تیم [#دیجیتال_مارکتینگ](https://www.linkedin.com/feed/hashtag/?keywords=%D8%AF%DB%8C%D8%AC%DB%8C%D8%AA%D8%A7%D9%84_%D9%85%D8%A7%D8%B1%DA%A9%D8%AA%DB%8C%D9%86%DA%AF&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) زی‌دکتر ([ZiDoctor](https://www.linkedin.com/company/zi-doctor/)) اضافه شدم. (متأسفانه! 😅)

🔸با اتمام ماه اول، از طولانی شدن پروسه پرداخت حقوق‌ها تعجب کردم.

🔹علت رو از مدیر عامل مجموعه ([Hamed Rezaei](https://www.linkedin.com/in/ACoAAAqAOiYBnHv9MbJNN0-VtXhi5Rfxp1eBtSQ)) جویا شدم که گفتن توی [#جریان_نقدی](https://www.linkedin.com/feed/hashtag/?keywords=%D8%AC%D8%B1%DB%8C%D8%A7%D9%86_%D9%86%D9%82%D8%AF%DB%8C&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) به مشکل خوردیم و تا انتهای هفته مشکلش حل می‌شه.

🔸با همکارم ([shohreh shamshiri](https://www.linkedin.com/in/ACoAADOcdooByxMmvRlBOyfzs4XDV5wluOUhuxI)) صحبت کردم و فهمیدم که ایشون و چند نفر دیگه هم چند ماهیه درگیر این مشکل هستن.

🔹بعد از چندین بار مراجعه به [#مدیرعامل](https://www.linkedin.com/feed/hashtag/?keywords=%D9%85%D8%AF%DB%8C%D8%B1%D8%B9%D8%A7%D9%85%D9%84&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) و وعده‌های مکرر هفته‌ آینده به بهانه‌های مختلف (روزنامه رسمی هنوز نیومده - پول نداریم - تو که هنوز کاری نکردی) بعد از یک ماه بهشون گفتم که مجبورم شکایتم بر عدم پرداخت حقوق و نبستن قرارداد رو از طریق [#وزارت_کار](https://www.linkedin.com/feed/hashtag/?keywords=%D9%88%D8%B2%D8%A7%D8%B1%D8%AA_%DA%A9%D8%A7%D8%B1&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) پیگیری کنم.

⭕ در این خصوص نکاتی که بهتره قبل از همکاری با شرکت‌ها مدنظر قرار بدیم رو اینجا هم میارم:

1️⃣ هرگز، هرگز و هرگز بدون بستن قرارداد کارتون رو شروع نکنید. (مدیر [#منابع_انسانی](https://www.linkedin.com/feed/hashtag/?keywords=%D9%85%D9%86%D8%A7%D8%A8%D8%B9_%D8%A7%D9%86%D8%B3%D8%A7%D9%86%DB%8C&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) مریض شده و کاغذامون تموم شده و مهر شرکت گم شده هم استثنای این قانون نیستن!)

2️⃣ ماده 34 قانون تامین اجتماعی می‌گه
در صورتی که بیمه شده برای دو یا چند کارفرما کار کند هر یک از کارفرمایان مکلفند به نسبت مزد یا حقوقی که می‌پردازند حق بیمه سهم‌بیمه شده را از مزد یا حقوق او کسر و به انضمام سهم خود به سازمان پرداخت نمایند.
پس اگر قصد دارید که به صورت همزمان در دو شرکت فعالیت کنید، بدونید که می‌تونید مطالبه‌ی بیمه رو از هر دو شرکت داشته باشید.

3️⃣ وزارت کار، در قدم اول در کنار کارمنده.
خیلی‌ها فکر می‌کنن که اگر مشکلی براشون پیش بیاد، با شکایت هم کاری از پیش نمی‌برن. این رو بدونید که وزارت [#کار](https://www.linkedin.com/feed/hashtag/?keywords=%DA%A9%D8%A7%D8%B1&highlightedUpdateUrns=urn%3Ali%3Aactivity%3A6974253029961179136) در قدم اول کنار شماست و با در دست داشتن قرارداد و یا حتی هزار تومان واریزی از حساب شرکت، احتمالا کارتون خیلی راحت پیش می‌ره.

**Comment by pooooriya** [comment]
https://www.linkedin.com/posts/shayan-shojaeian_aeuaepaeqahyaeuaeuaep-aexahyaeuahyaesaepaesabraetaepaezagpaesahyaeuagv-activity-6974253029961179136-4wI3/?utm_source=share&utm_medium=member_android

**Comment by tajrobe** [comment]
[tajrobe.github.io/زی-دکتر/](https://tajrobe.github.io/%D8%B2%DB%8C-%D8%AF%DA%A9%D8%AA%D8%B1/)
