### ISSUE TITLE
ارتباطات هوشمند هویار

### ISSUE THREAD

**Issue by vahidajorloo** [tajrobe/tajrobe.github.io#124]
##### نام شرکت
title: "ارتباطات هوشمند هویار"

##### نام انگلیسی شرکت
name_en: "ertebatat hooshmand hooyar"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "1-10"

##### آدرس سایت شرکت
site: "nadarad"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/هویار/](https://tajrobe.github.io/%D9%87%D9%88%DB%8C%D8%A7%D8%B1/)
