### ISSUE TITLE
دانش گستران ایرسا 

### ISSUE THREAD

**Issue by saedasadi296** [tajrobe/tajrobe.github.io#125]
##### نام شرکت
title: دانش گستران ایرسا

##### نام انگلیسی شرکت
name_en: dgirsa

##### دسته‌ی فعالیت شرکت
industry: طراحی سایت - درآمد انلاین

##### موقعیت مکانی شرکت
city: تهران

##### تعداد نفرات شرکت
size: ۲۷

##### آدرس سایت شرکت
site: Https://dgirsa.ir

##### توضیحی درباره شرکت و فعالیت‌هایش
content: دانش گستران ایرسا یک شرکت مولد است که از طریق طراحی سایت کسب و کار تولید می کند 
دارای برندهای توربین ، بیمه داد ، بیمه هاست ، ویزاگیتور و ... می باشد

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایرسا/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%B1%D8%B3%D8%A7/)
