### ISSUE TITLE
باگلوس | Bugloos

### ISSUE THREAD

**Issue by meyshad** [tajrobe/tajrobe.github.io#126]
##### نام شرکت
title: "باگلوس"

##### نام انگلیسی شرکت
name_en: "Bugloos"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://bugloos.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت باگلوس در سال ۲۰۰۶ در کشور هلند تأسیس شد. فعالیت خود را از سال ۲۰۱۴ در ایران، با هدف تشکیل، تمرکز و توسعه تیم جوان ایرانی در زمینه طراحی وب سایت، وب اپلیکیشن، موبایل اپلیکیشن، کنترل کیفیت و مشاوره در منطقه غرب تهران (گیشا) آغاز کرده است. پروژه های باگلوس از سراسر اروپا بوده و توسط تیم های ما در اروپا و ایران انجام می شود. برای نیل به این هدف از افراد مستعد، خلاق، مشتاق، قابل اعتماد و با تجربه دعوت به همکاری می نماییم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/باگلوس/](https://tajrobe.github.io/%D8%A8%D8%A7%DA%AF%D9%84%D9%88%D8%B3/)
