### ISSUE TITLE
تیکرو

### ISSUE THREAD

**Issue by hamedsadeghi190** [tajrobe/tajrobe.github.io#127]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/تیکرو/](https://tajrobe.github.io/%D8%AA%DB%8C%DA%A9%D8%B1%D9%88)
