### ISSUE TITLE
سرمایکس

### ISSUE THREAD

**Issue by imanabbasi** [tajrobe/tajrobe.github.io#129]
##### نام شرکت
title: "سرمایکس"

##### نام انگلیسی شرکت
name_en: "Sarmayex"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران, تهران"

##### تعداد نفرات شرکت
size: "11 تا 50 نفر"

##### آدرس سایت شرکت
site: "https://sarmayex.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "هلدینگ بین المللی سرمایکس بنا بر نیاز کاربران ایرانی و با استفاده از تجربه اندوخته شده و بهره گیری از نیروی با انگیزه، متعهد و متخصص و با رویکردی مدرن، فعالیت خود را در زمینه اطلاع رسانی کریپتوکارنسی، خرید و فروش و تبادل ارز دیجیتال، ارائه مشاوره های سرمایه گذاری و اجرای طرح های بلاکچین آغاز کرد و در کمترین زمان ممکن موفق شد اعتماد کاربران را جلب نماید. "

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرمایکس/](https://tajrobe.github.io/%D8%B3%D8%B1%D9%85%D8%A7%DB%8C%DA%A9%D8%B3/)
