### ISSUE TITLE
فالنیک (ایران اچ پی)

### ISSUE THREAD

**Issue by ehsan1211** [tajrobe/tajrobe.github.io#131]
##### نام شرکت
title: ""
فالنیک (ایران اچ پی)
##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
فناوری اطلاعات
##### موقعیت مکانی شرکت
city: ""
ایرانشهر
##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/فالنیک/](https://tajrobe.github.io/%D9%81%D8%A7%D9%84%D9%86%DB%8C%DA%A9/)
