### ISSUE TITLE
کاوش پردازان برسا

### ISSUE THREAD

**Issue by ehsan1211** [tajrobe/tajrobe.github.io#132]
##### نام شرکت
title: ""
کاوش پردازان برسا
##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
فناوری اطلاعات
##### موقعیت مکانی شرکت
city: ""
فاطمی
##### تعداد نفرات شرکت
size: ""
۲۵
##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/برسا/](https://tajrobe.github.io/%D8%A8%D8%B1%D8%B3%D8%A7/)
