### ISSUE TITLE
ارم نوش (آکوافینا)

### ISSUE THREAD

**Issue by ehsan1211** [tajrobe/tajrobe.github.io#133]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
نوشیدنی
##### موقعیت مکانی شرکت
city: ""
جاده مخصوص ، میرداماد
##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ارم-نوش/](https://tajrobe.github.io/%D8%A7%D8%B1%D9%85-%D9%86%D9%88%D8%B4/)
