### ISSUE TITLE
تلکام

### ISSUE THREAD

**Issue by ehsan1211** [tajrobe/tajrobe.github.io#134]
##### نام شرکت
title: ""
تلکام
##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
فروشگاه اینترنتی
##### موقعیت مکانی شرکت
city: ""
میدان ولیعصر
##### تعداد نفرات شرکت
size: ""
۳۰-۵۰
##### آدرس سایت شرکت
site: ""
telecomir
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/فروشگاه-تلکام/](https://tajrobe.github.io/%D9%81%D8%B1%D9%88%D8%B4%DA%AF%D8%A7%D9%87-%D8%AA%D9%84%DA%A9%D8%A7%D9%85/)
