### ISSUE TITLE
ثبت شرکت رایان تجارت نابغه

### ISSUE THREAD

**Issue by DasMergo** [tajrobe/tajrobe.github.io#136]
##### نام شرکت
title: "رایان تجارت نابغه"

##### نام انگلیسی شرکت
name_en: "Rayan Tejarat Nabeghe"

##### دسته‌ی فعالیت شرکت
industry: "دیجیتال مارکتینگ"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://boboko.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت بازرگانی در حیطه ی واردات انواع کامپیوتر و نوت بوک و قطعات کامپیوتر و موبایل سامسونگ و اپل و.."

**Comment by tajrobe** [comment]
[tajrobe.github.io/رایان-تجارت/](https://tajrobe.github.io/%D8%B1%D8%A7%DB%8C%D8%A7%D9%86-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA/)
