### ISSUE TITLE
سامانه نگار حامی بیمه

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#137]
##### نام شرکت
title: "گروه فناوری اطلاعات حامی بیمه (فنحاب)"

##### نام انگلیسی شرکت
name_en: "ّFanHubGroup"

##### دسته‌ی فعالیت شرکت
industry: "Insurance"

##### موقعیت مکانی شرکت
city: "Pardis-Tehran"

##### تعداد نفرات شرکت
size: "201-500"

##### آدرس سایت شرکت
site: "sanhab.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت سامانه نگار حامی بیمه با نام تجاری سنحاب، در سال ۱۳۹۴ به‌صورت شركت سهامي خاص تأسيس و طي شماره ۴۸۸۹۹۹ مورخ ۲۴ /۱۲/۱۳۹۴در اداره ثبت شركت‌ها و مؤسسات غیرتجاری تهران با سرمایه  ۱.۰۰۰.۰۰۰ ریال به ثبت رسيده‌ و  با تغییر اعضاء هیئت‌مدیره و مدیرعامل از سال ۱۳۹۸ فعالیت رسمی خود را به‌عنوان بازوی اجرایی فناوری اطلاعات و مجری پروژه‌های حاکمیتی بیمه مرکزی جمهوری اسلامی ایران و تأمین و طراحی و تولید زیرساخت‌ها، پلتفرم‌ها و سرویس‌های موردنیاز صنعت بیمه، شروع نموده است.

شرکت در راستای توسعه فعالیت‌های خود و دستیابی به منظر فناوری تحول دیجیتال بیمه علاوه بر اینکه امکان همکاری و مشارکت شرکت‌های تأمین‌کننده نرم‌افزار یکپارچه بیمه‌گری (Core Insurane) را در طراحی ، تولید و استقرار زیرساخت‌ها و پلتفرم‌های موردنیاز حاکمیتی و صنعت بیمه فراهم نموده، این امکان فراهم شده است که اینشورتک‌ها و استارت‌آپ‌های بیمه نیز بتوانند در راستای حل مسائل و چالش‌های صنعت بیمه، راهکارها و محصولات مبتنی بر فناوری خود را به شرکت معرفی نمایند تا پس از بررسی و تأیید ارزیابی فنی و کسب‌وکاری آن، قرارداد مشارکت در ارائه سرویس با شرکت سنحاب منعقد و راهکار یا محصول به صنعت بیمه ارائه شود."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سامانه-نگار/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%86%DA%AF%D8%A7%D8%B1/)
