### ISSUE TITLE
Zitel

### ISSUE THREAD

**Issue by ehsanderakhshan** [tajrobe/tajrobe.github.io#138]
##### نام شرکت
title: "فرابرد داده های ایرانیان"

##### نام انگلیسی شرکت
name_en: "Zitel"

##### دسته‌ی فعالیت شرکت
industry: "Telecom"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "200-500"

##### آدرس سایت شرکت
site: "zi-tel.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "4G Internet service provider"

**Comment by tajrobe** [comment]
[tajrobe.github.io/زیتل/](https://tajrobe.github.io/%D8%B2%DB%8C%D8%AA%D9%84/)
