### ISSUE TITLE
کارگزاری سهام بارز

### ISSUE THREAD

**Issue by Freegirl-dev** [tajrobe/tajrobe.github.io#139]
description:سهام بارز محیطی که به کارمندانش اجازه رشد نمیده و یک مدیر پذیرش انلاین و شعب داره که کارمندانش رو‌با دوربین به شدت کنترل میکنه و اجازه نمیده همکارا باهم ارتباط خوبی داشته باشن و شعارش اینه که تفرقه بنداز و حکومت کن،محیطی شبیه پادگان با یه مدیر انلاین پذیرش بی سواد که مدیریت شعب رو هم گرفته !!!اصلا در این شرکت شایسته سالاری وجود نداره و همه چی بر اساس روابط پیش میره

state: تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'سهام بارز

cons: محیط شبیه پادگان،مدیر بی درایت و بی سواد،

rate: ۳

**Comment by tajrobe** [comment]
[tajrobe.github.io/سهام-بارز/](https://tajrobe.github.io/%D8%B3%D9%87%D8%A7%D9%85-%D8%A8%D8%A7%D8%B1%D8%B2/)
