### ISSUE TITLE
در مرحله پست کردن فرم بعد از تکمیل مشکلی وجود داره لطفا بررسی کنید

### ISSUE THREAD

**Issue by ehsanderakhshan** [tajrobe/tajrobe.github.io#140]
در مرحله پست کردن فرم بعد از تکمیل مشکلی وجود داره لطفا بررسی کنید

**Comment by tajrobe** [comment]
سلام @pooooriya 🌹
بعد از پست شدن فرم، اگر دکمه submit تبدیل بشه به غیرفعال/نشان دادن «لطفا صبر کنید»/ لودینگ، به نظر من خیلی خوبه چون هم امکان سردرگمی هست هم بعضی وقتها فرم دو بار ارسال میشه.

**Comment by pooooriya** [comment]
اینو من خیلی وقته درست کردم ولی واقعا پابلیش گذاشتنش روی اینجا خیلیییی وقت میگیره و کلی داستان داره باید بشینم دستی ادیتش کنم ، فعلا مشکل خیلی خاصی نیست براش ولی وقت کردم حتما پابلیشش میزارم وگرنه خودش درست کردم

**Comment by matini3** [comment]
منم شرکت جدید ادد کردم اما تو لیست ها نمیااره @pooooriya

**Comment by tajrobe** [comment]
سلام @ehsanderakhshan 
فرم  ثبت تجربه تغییر کرده، احتمالا مشکلی که گفتید حل شده، من این issue رو می‌بندم، اگر مشکل جدید برخوردید یک issue جدید باز کنید.
