### ISSUE TITLE
تذرو افزار

### ISSUE THREAD

**Issue by arezupanahi** [tajrobe/tajrobe.github.io#141]
##### نام شرکت
title: "تذرو افزار"

##### نام انگلیسی شرکت
name_en: "Tazarv afzar"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزاری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۰-۱۰۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content:"bpms"

**Comment by tajrobe** [comment]
[tajrobe.github.io/تذرو-افزار/](https://tajrobe.github.io/%D8%AA%D8%B0%D8%B1%D9%88-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1/)
