### ISSUE TITLE
شرکت مهندسی ارتباطی پیام پرداز

### ISSUE THREAD

**Issue by morteza2a** [tajrobe/tajrobe.github.io#142]
##### نام شرکت
title: "شرکت مهندسی ارتباطی پیام پرداز"

##### نام انگلیسی شرکت
name_en: "PayamPardaz Co"

##### دسته‌ی فعالیت شرکت
industry: "امنیت اطلاعات و ارتباطات"

##### موقعیت مکانی شرکت
city: "اصفهان"

##### تعداد نفرات شرکت
size: "50-200"

##### آدرس سایت شرکت
site: "https://payampardaz.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "خیابان شریعتی، بالاتر از پل سیدخندان، خیابان شهید مجتبایی، کوچه دیانا، ابتدای کوچه بروجردی، پلاک ۴۴، واحد ۱۰. کد پستی: ۴۳۴۱۴-۱۵۴۳۸"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیام-پرداز/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%A7%D9%85-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2/)
