### ISSUE TITLE
بیمارستان صارم

### ISSUE THREAD

**Issue by Rodrigo-1997** [tajrobe/tajrobe.github.io#143]
##### نام شرکت
title: "بیمارستان صارم"

##### نام انگلیسی شرکت
name_en: "Sarem Hospital"

##### دسته‌ی فعالیت شرکت
industry: "خدمات درمانی"

##### موقعیت مکانی شرکت
city: " تهران، شهرک اکباتان ، انتهای فاز 3"

##### تعداد نفرات شرکت
size: "500"

##### آدرس سایت شرکت
site:"www.saremhospital.org"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فاز یک «بیمارستان فوق تخصصی صارم» دارای 100 تخت فعال و قسمت‌های: درمانی، آموزشی، پژوهشی و پشتیبانی به همراه بخش‌های بستری بیماران، اتاق‌های عمل، بخش زایمان و بخش‌های مختلف دیگر می‌باشد. آنچه این بیمارستان را از دیگر مراکز درمانی متمایز می‌کند، تخصص، دانش، سلیقه و منطق به کار گرفته شده در این مجموعه است تا بتواند بهترین خدمات را به مراجعان خود ارائه نموده و محیطی فرح بخش را به ارمغان آورد. همچنین، در راستای محرک‌های مثبت دیداری با هدف ایجاد روحیه و هیجان مثبت، چشم اندازهایی با الهام از طبیعت مانند: آبشار، نهرهای روان، گلکاری و درختکاری طراحی و ساخته شده است. ساختار فیزیکی و بنای بیمارستان به گونه‌ای طراحی شده تا محیطی با نشاط همراه با انرژی‌های مثبت و دلپذیر را برای همه همکاران جهت سرویس دهی بهتر فراهم آورد. این فاز دارای 6 طبقه (همکف، لابی و 4 طبقه) می‌باشد که واحدها و بخش‌های مختلف در این طبقات جانمایی شده‌اند. در انتهای راهروی بخش‌ها نیز درب خروج اضطراری جهت دسترسی به پله‌های فرار تعبیه شده است."

**Comment by Rodrigo-1997** [comment]
برای ثبت نظر کارکنان گرامی بیمارستان صارم ایجاد شده.

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیمارستان-صارم/](https://tajrobe.github.io/%D8%A8%DB%8C%D9%85%D8%A7%D8%B1%D8%B3%D8%AA%D8%A7%D9%86-%D8%B5%D8%A7%D8%B1%D9%85/)
