### ISSUE TITLE
Access to all companies name and search

### ISSUE THREAD

**Issue by MajideND** [tajrobe/tajrobe.github.io#144]
A few time ago I developed a chrome extension to browse reviews of Jobguy during apply for a job at jobinja, quera or jobvision.

As you now Jobguy is discontinued and this extension is not working anymore. So I'm asking for a way to search or find latest list of companies in your project to change the extension behavior and use your website.

Extension for chrome: https://chrome.google.com/webstore/detail/jobguy-discover/jbfljligpdamfclogiagjfgicibfamjm?hl=en&utm_source

**Comment by tajrobe** [comment]
سلام
این سایت از [GitHub-Pages](https://pages.github.com/) استفاده می‌کند و بعد از هر پوش صفحات به صورت استاتیک ساخته می‌شود. برای جستجو، ما یک لیست json از نام تمامی شرکتها داریم ([اینجا](https://tajrobe.github.io/assets/search.json)) که با فیلد url صفحه مورد نظر یافت می‌شود.
هر شرکت یک فایل markdown دارد و هر نظر ثبت شده هم در یک فولدر با نام slug شرکت ذخیره می‌شود. مثال [فایل شرکت دیجی‌کالا](https://github.com/tajrobe/tajrobe.github.io/blob/master/_posts/2021-02-22-%D8%AF%DB%8C%D8%AC%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7.md) و [فولدر نظرات درباره دیجی کالا](https://github.com/tajrobe/tajrobe.github.io/tree/master/_data/review/digikala)

**Comment by pooooriya** [comment]
خب این اوکیه ولی سینک نیست با جابینجا باید بشینی دستی این دو تا رو باهم مچ کنی ک اینو زد صفحه اش میشه این تو جابینجا ، چون اسلاگ های ما یکی نیستن با مال جابینجا یا اینکهcontains بزنی روی اسمش توی اون لیست جیسونی ببینی این با اون یکیه یا نه که کار زیاد جالبی بازم نیست بنظرم ، بهترین کار اینه که یه اسکریپت بنویسی که تمامی شرکت های جابینجا رو با این سینک کنه کار خیلی سختیم نیست ولی حداقل میدونی درست کار میکنه

**Comment by MajideND** [comment]
من راه حل های مختلفی رو بررسی کردم.
چیزی که درحال حاضر فکر میکنم چون هدف افزونه از اول این بود که کل سایت هارو پوشش بده داشتن یک لیست از شرکت ها با آدرس دامنشون هست که توی github page ها هم دامنه شرکت ها ثبت شده.
بر این اساس میشه توی هر سه سایت jobinja - jobvision - quora کار کنه.

**Comment by MajideND** [comment]
ولی برای اینکار به دو فیلد بیشتر نیاز دارم که بشه به صورت json دریافت کرد.
یکی totalRate  برای میانگین کل امتیاز ها.
و بعدی دامنه page.site رو بهتره داشته باشم ولی اگر نباشه باز هم با اسم (انگلیسی) شرکت میشه سینک کرد.

**Comment by tajrobe** [comment]
درست کردن یک json با فیلدهایی که شما نیاز داری اوکی هست، ولی میانگین امتیاز چون در زمان build هر صفحه‌ی شرکت [به صورت دستی](https://github.com/tajrobe/tajrobe.github.io/blob/05df0fbceb8574f86a3b70405fd7ea64e7f69765/_layouts/post.html#L50) با استفاده از [liquid](https://jekyllrb.com/docs/liquid/) محاسبه میشه عملا امکان گذاشتنش در لیست json  نیست، [این صفحه](https://github.com/tajrobe/tajrobe.github.io/blob/master/assets/search.json) مسئول ساختن لیست json برای سرچ هست که خروجی‌اش میشه [این](https://tajrobe.github.io/assets/search.json)؛ شما بگید که چه فیلدهایی به این لیست اضافه بشه؟

**Comment by thejimbow** [comment]
من با یه اسکریپت نوشتم این رو به نظرم میشه اینکار رو کرد که اکستنشن هم بتونه استفاده کنه

[Pull Request](https://github.com/tajrobe/tajrobe.github.io/pull/185)

**Comment by MajideND** [comment]
خیلی ممنونم از شما بررسی اولیه رو کردم به نظر همه چیز اوکیه. 👍 

به زودی من نسخه اولیه اکستنش رو توی گیت هاب میذارم و قبل از انتشار با شما در میون میذارم.

**Comment by MostafaSaadatnia** [comment]
دوستان یک نفر از لینکداین من یک پست رو کپی کرده و بدون اجازه و رضایت من اینجا گذاشته درباره شرکت پردازش اطلاعات مالی مبنا و من اون پست رو مدتهاست حذف کردم اما امکان حذف این پست از اینجا نیست ممکنه کسی من رو راهنمایی کنه.چون من رضایت ندارم بابت اینکار.

**Comment by tajrobe** [comment]
اکستنشن هنوز اوکی نشده؟ @MajideND

**Comment by saphir100** [comment]
سلام من الان ی شرکت ثبت کردم ولی اصلا تو سایتتون نشون نمیده و نمیاره

**Comment by tajrobe** [comment]
I closed this issue temporarily, if something new happens please open it.
