### ISSUE TITLE
موسسه وفور

### ISSUE THREAD

**Issue by itmysm** [tajrobe/tajrobe.github.io#145]
##### نام شرکت
title: "وفور مهر کامیار"

##### نام انگلیسی شرکت
name_en: "Vofour"

##### دسته‌ی فعالیت شرکت
industry: "Psychology group"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "50-200"

##### آدرس سایت شرکت
site: "https://vofour.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "
موسسه‌ی وفور یک مجموعه پیشرو در حوزه‌های مرتبط با روانشناسی بوده و حدود ۱۵ سال است در رشته آموزش‌های آنلاین عمومی و تخصصی روانشناسی و مشاوره، علوم رفتاری و تحولات انسانی کشور فعالیت میکند.
در این مجموعه تولید و استفاده از تکنولوژی و سامانه های نرم افزاری جایگاه ویژه‌ای دارند و مجموعه به طور آنلاین خدمات خود را به جامعه ارائه می دهد.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/وفور/](https://tajrobe.github.io/%D9%88%D9%81%D9%88%D8%B1/)
