### ISSUE TITLE
آپادانا کاوش ایرانیان

### ISSUE THREAD

**Issue by Mohammad-1995** [tajrobe/tajrobe.github.io#146]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/آپادانا-کاوش/](https://tajrobe.github.io/%D8%A2%D9%BE%D8%A7%D8%AF%D8%A7%D9%86%D8%A7-%DA%A9%D8%A7%D9%88%D8%B4/)
