### ISSUE TITLE
حذف نظرات غرض‌ورزانه

### ISSUE THREAD

**Issue by tajrobe** [tajrobe/tajrobe.github.io#147]
سلام @pooooriya 
بعضی تجربه‌ها با غرض‌ورزی نوشته می‌شوند؛ به نظرت باید پاکشون کنیم؟ به عنوان مثال [این دایرکتوری](https://github.com/tajrobe/tajrobe.github.io/tree/master/_data/review/etraab) رو نگاه کن، 4 تجربه در یک روز ثبت شده که عمدتا غرض‌ورزانه و به قصد تخریب نوشته شدند.

**Comment by tajrobe** [comment]
related to issue #58

**Comment by pooooriya** [comment]
ببخشید من تازه دیدم اینارو ، بنظرم کار خوبی کردی مشخصه ک غرض ورزانه است و بهتره ک پاک بشه چون فکت درستی نیاورده و صرفا فحش داده
