### ISSUE TITLE
شرکت چوب و هنر

### ISSUE THREAD

**Issue by soe1989** [tajrobe/tajrobe.github.io#148]
##### نام شرکت
title: "چوب و هنر"

##### نام انگلیسی شرکت
name_en: "choobohonar"

##### دسته‌ی فعالیت شرکت
industry: "تولید مبلمان و سایر مصنوعات چوبی"

##### موقعیت مکانی شرکت
city: "شهرک صنعتی پرند"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "https://choobohonar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکتی در حوزه تولیدات مبلمان و سرویس خواب و نهار خوری لوکس با قیمت بالا"

**Comment by soe1989** [comment]
با سلام
شرکتی با مدیریت خانوادگی دارای 4 مدیر که مشکلات فرمایشی با یکدیگر دارند
سوء استفاده کامل از کارکنان.قرارداد های 1 ماهه که هر زمان بهره مورد نظرشان گرفته شده قرارداد را تمدید نکرده و در واقع اخراج میکنند
کار مبلمان فصلی است و از این جهت هر سال در بازه زمانی پیک کار استخدام و 6 ماه بعد عدم تمدید قرارداد
من بمدت 6 ماه در پیک کار پست مدریتی داشتم و علیرغم رضایت کلامی خودشان بعد از افت کار بدلیل سیاست های کاری قراردادم تمدید نشد. چند ماه بعد دوباره آکهی کار دادند و این روند 3 سال است قابل مشاهده در سایت های استخدامی است
شرکتی با ظاهر خوب اما باطن کثیف و سوء استفتده محض از نیروی مجرب
ساعت کاری و روزهای کاری اعلامی در آگهی های استخدام نیز دروغ محظ است

**Comment by tajrobe** [comment]
[tajrobe.github.io/چوب-و-هنر/](https://tajrobe.github.io/%DA%86%D9%88%D8%A8-%D9%88-%D9%87%D9%86%D8%B1/)
