### ISSUE TITLE
پیشگامان آسیا

### ISSUE THREAD

**Issue by Ebrahimzarei** [tajrobe/tajrobe.github.io#149]
##### نام شرکت
title: "پیشگامان آسیا"

##### نام انگلیسی شرکت
name_en: "pishgaman asia"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار"

##### موقعیت مکانی شرکت
city: "شیراز"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "www.pishgamanasia.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "حوزه حمل و نقل حضور غیاب کارکنان و..."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیشگامان-آسیا/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86-%D8%A2%D8%B3%DB%8C%D8%A7/)
