### ISSUE TITLE
شرکت هلو 

### ISSUE THREAD

**Issue by atefeeskandari** [tajrobe/tajrobe.github.io#150]
##### نام شرکت
title: "شرکت هلو"

##### نام انگلیسی شرکت
name_en: "holoo"

##### دسته‌ی فعالیت شرکت
industry: "مالی و حسابداری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۲۰۰"

##### آدرس سایت شرکت
site: "https://holoo.co.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/هلو/](https://tajrobe.github.io/%D9%87%D9%84%D9%88/)
