### ISSUE TITLE
موج پژوه البرز

### ISSUE THREAD

**Issue by krsham** [tajrobe/tajrobe.github.io#151]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/موج-پژوه/](https://tajrobe.github.io/%D9%85%D9%88%D8%AC-%D9%BE%DA%98%D9%88%D9%87/)
