### ISSUE TITLE
شرکت رنگارنگ

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [tajrobe/tajrobe.github.io#152]
##### نام شرکت
title: "رنگارنگ"

##### نام انگلیسی شرکت
name_en: "rangarang"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار چاپ"

##### موقعیت مکانی شرکت
city: "اصفهان"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://rangarangsoft.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/رنگارنگ/](https://tajrobe.github.io/%D8%B1%D9%86%DA%AF%D8%A7%D8%B1%D9%86%DA%AF/)
