### ISSUE TITLE
شرکت چشم انداز آینده پارسیان

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [tajrobe/tajrobe.github.io#153]
##### نام شرکت
title: "چشم انداز آینده پارسیان"

##### نام انگلیسی شرکت
name_en: "cheshm andaz ayande parsian"

##### دسته‌ی فعالیت شرکت
industry: "راه کار ها و نرم افزار های کلان"

##### موقعیت مکانی شرکت
city: "اصفهان"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://i-cap.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/چشم-انداز-پارسیان/](https://tajrobe.github.io/%DA%86%D8%B4%D9%85-%D8%A7%D9%86%D8%AF%D8%A7%D8%B2-%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%A7%D9%86/)
