### ISSUE TITLE
دادفلامینگو

### ISSUE THREAD

**Issue by parsoon** [tajrobe/tajrobe.github.io#155]
##### نام شرکت
دادفلامینگو
title: "دادفلامینگو"

##### نام انگلیسی شرکت
name_en: "dadflamingo"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
تهران، بزرگراه همت، دهکده المپیک، بلوار ورزش، خیابان المپیک یازدهم، مرکز رشد و نوآوری دانشگاه علامه طباطبائی
city: "تهران"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://dadflamingo.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فعالیت های حقوقی و مالی
"

**Comment by parsoon** [comment]
فعالیت های حقوقی و مالی

**Comment by parsoon** [comment]
دوستانی که دنبال یه جای متفاوت هستند اسم این شرکت رو خوب به خاطر بسپارند.
کلا بیزینس این شرکت سواستفاده از کارآموزا هست.به صورت انبوه فارغ التحصیلان دانشگاه های برتر رو جذب کرده و پس از مدتی بیگاری کشیدن عذر اونها رو میخواد. 
ضمنا تو این شرکت مفهومی به اسم قانون کار اصلا وجود خارجی نداره. موقع مصاحبه وعده حقوق جذاب و پاداش بهتون داده میشه ولی همینکه جذب شدید اگه خیلی خوش شانس باشید یه قراداد وزارت کاری میدن دستتون. البته نوشتن قرارداد کاریشون هم دوسه ماهی طول میکشه. دوماه اول خبری از حقوق نیست. 
چیزی به اسم  اضافه کار تو این شرکت وجود خارجی نداره حتی اگه تا دیروقت سرکارباشید هرماه همون حقوق ثابتی که خودشون دلشون میخواد بهتون پرداخت میکنند(البته بعد از کسر بیمه و مالیات). شدت خساست تو این شرکت به حدی بالاست که حتی یه خط تلفن ثابت هم دراختیارتون قرارداده نمیشه و باید با خط موبایل خودتون تماس های کاری شرکت رو بگیرید. 
قوانین هم در نوع خودش در این شرکت به شکل جالبی اجرا میشه. چیزی به اسم دستگاه حضور و غیاب وجود خارجی نداره !یه سری افراد نه ورود و خروج میزنن نه قوانین مرخصی و .. براشون اجرا میشه! ساعت کاری یه سری از نیروها از یازده صبح شروع میشه و کسی هم حق اعتراض نداره. کلا تواین شرکت هرچی تنبل تر و کارنکن تر و بیسوادتر باشید عزیزترخواهید بود و دائما ازتون تجلیل خواهد شد. درعوض اگر فعال و کاری باشید و وجدان کاری داشته باشید مورد تمسخر و تحقیر قرارخواهید گرفت.
مخلص کلام اینکه گول ظاهرسازی های همچین شرکت هایی رو نخورید دروغ گوهای قهاری هستند.

**Comment by tajrobe** [comment]
[tajrobe.github.io/دادفلامینگو](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%81%D9%84%D8%A7%D9%85%DB%8C%D9%86%DA%AF%D9%88/)

**Comment by parsoon** [comment]
good
