### ISSUE TITLE
الوکانتنت

### ISSUE THREAD

**Issue by Narjes-Bahrainy** [tajrobe/tajrobe.github.io#156]
##### نام شرکت الوکانتنت
title: ""

##### نام انگلیسی شرکت
name_en: ""alocontent

##### دسته‌ی فعالیت شرکت تولید محتوا
industry: ""

##### موقعیت مکانی شرکت تهران
city: ""

##### تعداد نفرات شرکت 11-50
size: ""

##### آدرس سایت شرکتhttps://alocontent.com/
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/الوکانتنت/](https://tajrobe.github.io/%D8%A7%D9%84%D9%88%DA%A9%D8%A7%D9%86%D8%AA%D9%86%D8%AA/)
