### ISSUE TITLE
New Company | Phinix

### ISSUE THREAD

**Issue by mmrxa** [tajrobe/tajrobe.github.io#16]
##### نام شرکت
title: "فینیکس"

##### نام انگلیسی شرکت
name_en: "phinix"

##### دسته‌ی فعالیت شرکت
industry: "It, blockchain"

##### موقعیت مکانی شرکت
city: "تهران، سعادت آباد"

##### تعداد نفرات شرکت
size: "۱۰۰ - ۲۰۰"

##### آدرس سایت شرکت
site: "phinix.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "صرافی ارز های دیجیتال فینیکس"

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/%D9%81%DB%8C%D9%86%DB%8C%DA%A9%D8%B3/](https://tajrobe.github.io/%D9%81%DB%8C%D9%86%DB%8C%DA%A9%D8%B3/)
