### ISSUE TITLE
هلدینگ تاک

### ISSUE THREAD

**Issue by Narjes-Bahrainy** [tajrobe/tajrobe.github.io#160]
##### نام شرکت هلدینگ تاک
title: ""

##### نام انگلیسی شرکت
name_en: ""taak tech

##### دسته‌ی فعالیت شرکت فناوری اطلاعات
industry: ""

##### موقعیت مکانی شرکت مشهد 
city: ""

##### تعداد نفرات شرکت 50
size: ""

##### آدرس سایت شرکت https://taakgroup.org/
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/هلدینگ-تاک/](https://tajrobe.github.io/%D9%87%D9%84%D8%AF%DB%8C%D9%86%DA%AF-%D8%AA%D8%A7%DA%A9/)
