### ISSUE TITLE
فروشگاه زنجیره ای عطر و ادکلن وزرا

### ISSUE THREAD

**Issue by mahdiyahyaie** [tajrobe/tajrobe.github.io#161]
##### نام شرکت
title: "فروشگاه زنجیره ای عطر و ادکلن وزرا"

##### نام انگلیسی شرکت
name_en: "Vozara perfume chain store"

##### دسته‌ی فعالیت شرکت
industry: "آرایشی و بهداشتی"

##### موقعیت مکانی شرکت
city: "فروشگاه زنجیره ای"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "vozararoma.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه های زنجیره ای عطر و ادکلن وزرا به صورت تخصصی اقدام به فروش عطر و ادکلن می کند. این فروشگاه در سال ۱۳۸۴ تاسیس شد. دفتر مرکزی و اولین شعبه آن در شهر شاهرود در استان سمنان می باشد. مدیرعامل این شرکت مهندس نوید کرمی است."

**Comment by mahdiyahyaie** [comment]
فروشگاه زنجیره ای عطر و ادکلن وزرا مزایا و معایب زیادی دارد.
این عناوین مربوط به حوزه کاری فروشندگی با سمت سرپرست فروش (سطح ۳) در نظر گرفته شده است.
مزایا:
پرداخت بیمه بدون مشکل هست.
شامل دوره آموزشی می شود.
در صورتی که به شما نیاز داشته باشند، از روز اول آموزشی حقوق هم دارید.
کار به شدت سبک و با روحیه مثبت است.
مشتریان به صورت عمومی خوشحال و با روحیه مثبت هستند.
فرست خالی خیلی زیاد در بین کار وجود دارد. اگر مدیریت نشود فرسودگی ایجاد می کند.
در سالروز مرد و زن، هدایایی به کارمندان داده می شود.
کارمندان امکان خرید اقساطی دارند.
و مزیت آخر، همیشه خوشبو هستید.
معایب:
ساعت کاری در زمینه فروش ۱۰ ساعت است، ولی پرداخت طبق قانون ۷.۵ ساعت وزارت کار است.
جمعه ها و روزهای تعطیل عملا وجود ندارند و همیشه باید سر کار باشید.
پورسانت کالایی که در ابتدا وعده می دهند پوچ است. صرفا یک سری کالاهای در حال خراب شدن، کالاهای تولیدی که سود بالایی برایشان دارد، کارهای جدید که اصلا جا نیافتاده اند و کالاهایی که هیچ کس به صورت عادی نمیخرد شامل پورسانت کالایی آن هم ۳ تا ۱۰ درصد می شود.
در صورت تحقق تارگت های فروش، پاداش مسخره ای در حد نیم تا ۳ درصد فروش کل به کل فروشگاه داده می شود.
واحد منابع انسانی از قوانین روز اطلاعی ندارد.
تسویه حساب به موقع انجام نمی شود و ممکن چند ماه بدون حقوق بمانید.
مبلغی به عنوان ضمانت و حسن انجام کار در حدود ۱۵ تا ۲۰ درصد از کل حقوق به شما پرداخت نمی شود تا پس از ۶ ماه، در صورتی که خطا نداشته باشید، آن هم بعد از چندین ماه، به شما پرداخت شود.
هر ماه چندین برگه بابت تسویه حساب از شما گرفته می شود و اگر قبل از عید خروج کنید، عیدی و پاداشی در کار نیست.
وضعیت ارتباطی بین همکاران خوب نیست.
رده های داخلی شرکت باهم ارتباط صمیمانه ندارند و کارها به کندی و با پیگیری شدید پیش می رود.
و از همه مهم تر، همه تاییدیه ها باید به تایید مدیرعامل برسد و عملا واحد های شرکت بی مسئولیت هستند. به همین ترتیب یک‌کار ۱ ساعته، ممکن است ۴ ماه طول بکشد.
قراردادهای تمدید کار منطقی نبوده و در صورتی که به شدت نیاز به نیروی کار داشته باشند پیشنهاد بهتر می دهند.
کار به صورت دو شیفت بوده و علاوه بر ۱۰ ساعت شیفت، چندین ساعت در رفت و آمد هدر می شود.
در بدو ورود چند صد میلیون سفته از شما و از ضامن شما دریافت می شود.
قراردادی شامل ۷ سال عدم فعالیت در فعالیت های مشابه با شما بسته می شود تا خیال دور زدن وزرا و فعالیت در این حوزه و حوزه های مشابه را نداشته باشید، والا با شما برخورد قانونی می کنند.

**Comment by tajrobe** [comment]
سلام
لطفا تجربه کاری خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/عطر-وزرا/](https://tajrobe.github.io/%D8%B9%D8%B7%D8%B1-%D9%88%D8%B2%D8%B1%D8%A7/)
