### ISSUE TITLE
وستادژ

### ISSUE THREAD

**Issue by R1431EZA** [tajrobe/tajrobe.github.io#162]
##### نام شرکت
title: "وستادژ"

##### نام انگلیسی شرکت
name_en: "vestadezh"

##### دسته‌ی فعالیت شرکت
industry: "تولیدی "

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "500"

##### آدرس سایت شرکت
site: "vestadezh.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/وستادژ/](https://tajrobe.github.io/%D9%88%D8%B3%D8%AA%D8%A7%D8%AF%DA%98/)
