### ISSUE TITLE
سینا پخش ژن

### ISSUE THREAD

**Issue by ordinaryemployee** [tajrobe/tajrobe.github.io#163]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/سینا-پخش/](https://tajrobe.github.io/%D8%B3%DB%8C%D9%86%D8%A7-%D9%BE%D8%AE%D8%B4/)
