### ISSUE TITLE
Adding Missing Company ➕

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#164]
##### نام شرکت
title: "مهندسی هرمزان نیروی ایرانیان (مهنا)"

##### نام انگلیسی شرکت
name_en: "Mahna Group"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "mahnagroup.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مهندسی هرمزان نیروی ایرانیان (مهنا) در سال 1388 با هدف ارائه خدمات بر بستر فن آوری اطلاعات و انجام فعالیت های اجرایی، پژوهشی و مشاوره و توسعه فناوری مورد نیاز صنایع گوناگون از جمله برق، پترو شیمی، صنایع نفت و مخابرات تاسیس گردید . مهمترین فعالیت ها و خدمات این شرکت ارائه راهکارهای متنوع در حوزه ارتباطات مخابراتی و اینترنتی، تولید نرم افزارهای تخصصی و سفارش مشتری، تولید نرم افزارهای مبتنی بر سرویس های مکانی (GIS)، خدمات مراکز تماس، خدمات مراکز داده و امنیت اطلاعات و... است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/مهنا/](https://tajrobe.github.io/%D9%85%D9%87%D9%86%D8%A7/)
