### ISSUE TITLE
ثبت شرکت جدید

### ISSUE THREAD

**Issue by arohami** [tajrobe/tajrobe.github.io#166]
##### نام شرکت
title: "ایده کاوان (صنعت پردیس)"

##### نام انگلیسی شرکت
name_en: "Ide Kavan Sanaat Pardis"

##### دسته‌ی فعالیت شرکت
industry: "رباتیک"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "تهران، پردیس، پارک فناوری پردیس"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تولید ربات های بازرس و صنعتی"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایده-کاوان/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%AF%D9%87-%DA%A9%D8%A7%D9%88%D8%A7%D9%86/)
