### ISSUE TITLE
معرفی شرکت سالیار صنعت پارس

### ISSUE THREAD

**Issue by saied6153** [tajrobe/tajrobe.github.io#167]
##### نام شرکت
title: ""شرکت سالیار صنعت پارس

##### نام انگلیسی شرکت
name_en: ""Saliar Sanat Pars

##### دسته‌ی فعالیت شرکت
industry: ""تولید کننده جرثقیل های کامیونی

##### موقعیت مکانی شرکت
city: ""مشهد

##### تعداد نفرات شرکت
size: ""۷۰

##### آدرس سایت شرکت
site: ""Www.Saliar.com

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""شرکت در زمینه ساخت جرثقیل های هیدرولیک فعالیت دارد.
تولید انواج جرثقیل کامیونی در دو مدل تلسکوپی و مفصلی از ۳تن الی ۲۵ تن

**Comment by saied6153** [comment]
سلام دوستان
حدود ۳ سال پیش برای پوزیشن طراح سایت به این شرکت اومدم و شروع به کار کردم، امروز به عنوان مدیر واحد It مشغول به فعالیت هستم، شرکت با وجود تحریم ها و سختی های داخلی، پیش رفت خیلی خوبی تو این مدت داشته، مدیران این شرکت عقیده دارن که  همینطور که شرکت پیش رفت میکنه باید کارکنان شرکت هم پیش رفت کنن و تو این زمینه خیلی به کارکنان کمک کرده. تا این لحظه همیشه هوای کارکنان رو داشته و تجربه من تو این شرکت بسیار عالی بوده و همچنان هست.

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت ثبت کنید:

[tajrobe.github.io/سالیار/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%84%DB%8C%D8%A7%D8%B1/)
