### ISSUE TITLE
pishgamvira

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#168]
##### نام شرکت
title: "پیشگام ویرا"

##### نام انگلیسی شرکت
name_en: "pishgamvira"

##### دسته‌ی فعالیت شرکت
industry: "it software"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "40"

##### آدرس سایت شرکت
site: "https://pishgamvira.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "امان داده و فناوری ویرا از جمله شرکت های فعال در حوزه دیجیتال مارکتینگ و خدمات مربوط به کسب و کارهای اینترنتی است. ویرا سعی داشته با نیروی های جوان، مستعد و توانمند بستری را برای علاقمندان کسب و کارهای اینترنتی و حضور در این دنیای بی انتها را فراهم کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیشگامان-ویرا/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85%D8%A7%D9%86-%D9%88%DB%8C%D8%B1%D8%A7/)
