### ISSUE TITLE
پاکلین

### ISSUE THREAD

**Issue by farhadzaresani** [tajrobe/tajrobe.github.io#170]
##### نام شرکت
title: "پاکلین"

##### نام انگلیسی شرکت
name_en: "paklean"

##### دسته‌ی فعالیت شرکت
industry: " خدمات آنلاین"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۲۰"

##### آدرس سایت شرکت
site: "paklean.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "خشک شویی آنلاین"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پاکلین/](https://tajrobe.github.io/%D9%BE%D8%A7%DA%A9%D9%84%DB%8C%D9%86/)
