### ISSUE TITLE
Nizek

### ISSUE THREAD

**Issue by thejimbow** [tajrobe/tajrobe.github.io#173]
##### نام شرکت
title: "نایزک"

##### نام انگلیسی شرکت
name_en: "Nizek"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "بین المللی - تهران"

##### تعداد نفرات شرکت
size: "51-200"

##### آدرس سایت شرکت
site: "http://nizek.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نایزک یک تیم متحد و یک فرهنگ دوستانست که در قالب یک برند تجاری مشغول طراحی و تولید راهکارهای دیجیتال در حوزه‌ی تجارت الکترونیک و مشخصاً فروشگاه‌های آنلاینه. محصولات نایزک در کویت و به کشورهای اتحادیه GCC ارائه‌ می‌شه. نایزک تونسته در سال‌های اخیر به یکی از شرکت‌های مطرح این حوزه تبدیل بشه.

توی نایزک فرهنگ اهمیت بالایی داره و براش وقت و انرژی زیادی صرف می‌کنیم چرا که باور داریم فرهنگ سازمانی خوب مثل درختیه که ثمرش یادگیری، خلاقیت و نوآوری انسان‌هاست.
مقصد نایزک در بی‌نهایت، کمک به همدیگه هست، برای اینکه بتونیم ارزش ذاتی خودمون رو در نظام هستی بهتر و بیشتر درک کنیم و نهایتا حس بهتری از خودمون داشته باشیم.

ارزش‌های ما
دوستی، دلسوزی، همدلی، درک متقابل و ارتباط موثر.
رقابت‌های درون سازمانی رو از خودمون دور می‌کنیم و در کنار هم برای گسترش صنعت تلاش می‌کنیم.
دیسیپلین و نظم از قلب هر نایزکی تولید و منتشر می‌شه، نه از درون آیین‌نامه‌ها!
حس خوب امروز رو فدای آینده‌ نمی‌کنیم، بلکه امروز با حس رضایت از خود، فردای خودمون و اطرافیانمون رو می‌سازیم.

نایزک یک شغل نیست. نایزک مقصدیه برای آدمایی که می‌خوان در مسیر تعالی خودشون قرار بگیرن و حس خوب امروز رو در کنار دوستای دلسوز و حرفه‌ای تجربه کنن."

**Comment by tajrobe** [comment]
[tajrobe.github.io/نایزک/](https://tajrobe.github.io/%D9%86%D8%A7%DB%8C%D8%B2%DA%A9/)
