### ISSUE TITLE
نوآوران سرآمد شریف

### ISSUE THREAD

**Issue by nightelf1363** [tajrobe/tajrobe.github.io#174]
##### نام شرکت
title: "نوآوران سرآمد شریف"

##### نام انگلیسی شرکت
name_en: "noavaran saramad sharif"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by nightelf1363** [comment]
انتهای فکر یک کارمند همکاری خوب با دکتر کسب و کار و مدرس دانشگاه شریف هست اما این تجربه تمامی ذهنیت مثبت یک کارمند رو کاملا منفی می کنه !
مدیریت دستپاچه ، تغییر روزانه استراتژی شرکت ، عدم اعتماد به نیروها ، تعویض روزانه نیروها و ...
هیچوقت فکر نکنید شریف شرافت میاره !

**Comment by tajrobe** [comment]
لطفا تجربه‌ی خود را در صفحه شرکت ثبت کنید:

[tajrobe.github.io/سرآمد-شریف/](https://tajrobe.github.io/%D8%B3%D8%B1%D8%A2%D9%85%D8%AF-%D8%B4%D8%B1%DB%8C%D9%81/)
