### ISSUE TITLE
پیشتازان اقتصاد پویا

### ISSUE THREAD

**Issue by aliraam** [tajrobe/tajrobe.github.io#175]
##### نام شرکت
title: "پیشتازان اقتصاد پویا"

##### نام انگلیسی شرکت
name_en: "Pishtazan Eqtesad Pouya"

##### دسته‌ی فعالیت شرکت
industry: " متاایکامـرس (متاورس و ایکامرس)"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "بیش از هزار نفر"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "با توجه به اهمیت حوزه های ایکامرس و متاورس در هـزاره سوم، گـروه توسعـه سرمایـه گذاری انتخاب بر آن شد تا جهت برقراری ارتباط مجازی خود با مشتریان، یک استارتآپ بین المللـی در حوزه متاایکامـرس (متاورس و ایکامرس) ایجاد کند. شرکت پیشتازان اقتصاد پویا متشکل از نخبگان و متخصصان حوزه دانش بنیان، هوش مصنوعی، واقعیت افزوده، فناوری اطلاعات و فعالان حوزه تولید محتوا است که هدف آن ایجاد یک اکوسیستم در فضای متاورس و ایکامرس بوده که متشکل از قریب به ۴۰ زیرسیستم به هم پیوسته می باشد هـدف های مختلف اعم از محصولات اکـوسیستم گذر از دوران تعاملات حضـوری به تعاملات ترکیبی و غیر حضوری در حوزه تولیدی و خدمات خواهد بود."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیشتازان-اقتصاد-پویا/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%D8%AA%D8%A7%D8%B2%D8%A7%D9%86-%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF-%D9%BE%D9%88%DB%8C%D8%A7/)
