### ISSUE TITLE
گروه صنعتی ظفران 

### ISSUE THREAD

**Issue by msErfani** [tajrobe/tajrobe.github.io#176]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ظفران/](https://tajrobe.github.io/%D8%B8%D9%81%D8%B1%D8%A7%D9%86/)
