### ISSUE TITLE
نگاه بانک

### ISSUE THREAD

**Issue by Moh3enDev** [tajrobe/tajrobe.github.io#177]
##### نام شرکت
title: "نگاه بانک"

##### نام انگلیسی شرکت
name_en: "Negah Bank"

##### دسته‌ی فعالیت شرکت
industry: "بانکی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "150"

##### آدرس سایت شرکت
site: "negah-bank.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت نگاه بانک پیش برنده ماموریت‌های بانکی هلدینگ فناوری نگاه است که با هدف ارتقا و ساماندهی زیرساخت‌های فني بانک کارآفرین و توسعه و طراحی خدمات و محصولات متمایز برای مشتریان فعلی و آینده بانک کارآفرین شکل گرفته است"

**Comment by tajrobe** [comment]
[tajrobe.github.io/نگاه-بانک/](https://tajrobe.github.io/%D9%86%DA%AF%D8%A7%D9%87-%D8%A8%D8%A7%D9%86%DA%A9/)
