### ISSUE TITLE
شرکت نوآوران افراتک هوشمند

### ISSUE THREAD

**Issue by afratechooshmand** [tajrobe/tajrobe.github.io#178]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by afratechooshmand** [comment]
[افراتک](https://afratec.ir/) با بهره‌گیری از ارتباطات قوی با شرکای تجاری بین‌المللی، در زمینه تأمین تجهیزات معتبر خارجی، خدماتی قابل اطمینان و متناسب با نیاز سازمان‌ها و شرکت‌ها را ارائه می‌نماید.

امروزه با پیشرفت‌ فناوری اطلاعات و ظهور نیازمندی‌های خاص این عصر، اتکای بخش دولتی و خصوصی کشور به فضای تبادل اطلاعات درحال افزایش است. ازطرفی پیچیدگی روزافزون فناوری اطلاعات، سازمان‌ها را با مجموعه‌ای از چالش‌ها و تهدیداتی مواجه کرده است. همچنین با توجه به مقتضیات کشورما (همچون تحریم‌های همه جانبه)، دغدغه‌هایی جدید، با ماهیت و کیفیت متفاوت در زمینه رفع این چالش‌ها ایجاد شده است. برطرف‌سازی این مخاطرات و گام برداشتن در راستای تأمین خدمات امن و یکپارچه درسطح خدمات حساس و حیاتی، نه تنها نیازمند اشراف به تهدیدات روزافزون، بلکه مستلزم آشنایی با چالش‌های بخش دولتی و خصوصی کشور است. [شرکت نوآوران افراتک هوشمند](https://afratec.ir/) در راستای برآورده‌سازی نیازمندی‌های سازمان‌ها در فضای تبادل اطلاعات از سال ۱۳۹۳  وارد عرصه خدمت شده است.

**Comment by tajrobe** [comment]
[tajrobe.github.io/افراتک/](https://tajrobe.github.io/%D8%A7%D9%81%D8%B1%D8%A7%D8%AA%DA%A9/)
