### ISSUE TITLE
سرچ فن

### ISSUE THREAD

**Issue by Zahrabayat12** [tajrobe/tajrobe.github.io#179]
##### نام شرکت
title: ""سرچ فن

##### نام انگلیسی شرکت
name_en: ""searchfan

##### دسته‌ی فعالیت شرکت
industry: "" خدمات سئو

##### موقعیت مکانی شرکت
city: ""تهران

##### تعداد نفرات شرکت
size: ""!

##### آدرس سایت شرکت
site: ""searchfan.ir

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "" بازددید سایت و ریچ اسنیپت.
بیمه نداشت. سنوات نداشت.  عیدی نداشت. نوع برخورد مدیر همراه با توهین و تحقیر.

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرچ-فن/](https://tajrobe.github.io/%D8%B3%D8%B1%DA%86-%D9%81%D9%86/)
