### ISSUE TITLE
سرچ فن

### ISSUE THREAD

**Issue by Zahrabayat12** [tajrobe/tajrobe.github.io#180]
##### نام شرکت
title: ""سرچ فن

##### نام انگلیسی شرکت
name_en: ""searchfan

##### دسته‌ی فعالیت شرکت
industry: "" بازدید. کامنت

##### موقعیت مکانی شرکت
city: ""تهران.

##### تعداد نفرات شرکت
size: ""!

##### آدرس سایت شرکت
site: ""تهران

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "" بیمه نداشت. سنوات نداشت. عیدی نداشت. حقوق به درستی پرداخت نشد. نوع برخورد مدیر همراه با توهین و تحقیر. تجربه بسیار تلخی بود و ای کاش این دوسال از زندگی من حذف میشد...

**Comment by Zahrabayat12** [comment]
تجربه تلخی بود که حق و حقموقم خورده شد و هر شرکت دیگه ای رفته بودم خیلی موفق بودم

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرچ-فن/](https://tajrobe.github.io/%D8%B3%D8%B1%DA%86-%D9%81%D9%86/)
