### ISSUE TITLE
گروه مالی کاریزما

### ISSUE THREAD

**Issue by SadafMoradi** [tajrobe/tajrobe.github.io#181]
##### نام شرکت
title: ""
گروه مالی کاریزما
##### نام انگلیسی شرکت
name_en: ""
Charisma Financial Group
##### دسته‌ی فعالیت شرکت
industry: ""
بورس
##### موقعیت مکانی شرکت
city: ""
تهران
##### تعداد نفرات شرکت
size: ""
200
##### آدرس سایت شرکت
site: ""
https://charisma.ir/
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
گروه مالی کاریزما به پشتوانه تجربه بالا در زمینه فعالیت در بازار سرمایه و نیروی انسانی متخصص، دارای زنجیره کامل خدمات مالی و با بیش از ۳۰۰ هزار میلیارد ریال دارایی تحت مدیریت و دارای متنوع ترین صندوق های سرمایه گذاری، به عنوان یک هلدینگ مالی آماده ارائه خدمات متنوع به مشتریان حقیقی و حقوقی خود می باشد. گروه مالی کاریزما در حال حاضر متشکل از هشت شرکت تخصصی و بیش از ۴۰۰ نفر پرسنل فعال می باشد که زنجیره خدمات کاریزما را برای مشتریان گرامی ایجاد کرده اند.

**Comment by tajrobe** [comment]
[tajrobe.github.io/کاریزما/](https://tajrobe.github.io/%DA%A9%D8%A7%D8%B1%DB%8C%D8%B2%D9%85%D8%A7/)
