### ISSUE TITLE
گروه توسعه بن‌ دا

### ISSUE THREAD

**Issue by Mrji95** [tajrobe/tajrobe.github.io#183]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/بن-دا/](https://tajrobe.github.io/%D8%A8%D9%86-%D8%AF%D8%A7/)
