### ISSUE TITLE
شبکه بانان پاژ

### ISSUE THREAD

**Issue by matini3** [tajrobe/tajrobe.github.io#184]
##### نام شرکت
title: "شبکه بانان پاژ"

##### نام انگلیسی شرکت
name_en: "Pazh"

##### دسته‌ی فعالیت شرکت
industry: "شبکه"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://www.pazhnetwork.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فعالت اصلی شرکت در بخش آی تی است پیاده سازی فایروال  ،دیتا سنتر  و پیاده سازو ... است "

**Comment by tajrobe** [comment]
[tajrobe.github.io/بانان-پاژ/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%86%D8%A7%D9%86-%D9%BE%D8%A7%DA%98/)
