### ISSUE TITLE
چرتکه

### ISSUE THREAD

**Issue by beahuman4ever** [tajrobe/tajrobe.github.io#186]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by beahuman4ever** [comment]
انتشارات چرتکه یا وبسایت butterflygp.com که در کشور کانادا فعال است و انتشارات چرتکه به عنوان مرکز انجام امور مربوط به سایت در ایران فعالیت دارد.

**Comment by tajrobe** [comment]
[tajrobe.github.io/انتشارات-چرتکه/](https://tajrobe.github.io/%D8%A7%D9%86%D8%AA%D8%B4%D8%A7%D8%B1%D8%A7%D8%AA-%DA%86%D8%B1%D8%AA%DA%A9%D9%87/)
