### ISSUE TITLE
انتشارات چرتکه

### ISSUE THREAD

**Issue by beahuman4ever** [tajrobe/tajrobe.github.io#187]
##### نام شرکت
title: "چرتکه"

##### نام انگلیسی شرکت
name_en: "butterflygp.com"

##### دسته‌ی فعالیت شرکت
industry: "چاپ آنلاین"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-20"

##### آدرس سایت شرکت
site: "Butterflygp.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "انتشارات چرتکه در اصل مرکز برنامه نویسی و تولید و مارکتینگ و مدیریت چاپخانه اینترنتی است که در کشور کانادا و شهر تورنتو فعالیت دارند . "

**Comment by tajrobe** [comment]
[tajrobe.github.io/انتشارات-چرتکه/](https://tajrobe.github.io/%D8%A7%D9%86%D8%AA%D8%B4%D8%A7%D8%B1%D8%A7%D8%AA-%DA%86%D8%B1%D8%AA%DA%A9%D9%87/)
