### ISSUE TITLE
Add new Company

### ISSUE THREAD

**Issue by codewithah** [tajrobe/tajrobe.github.io#188]
##### نام شرکت
title: "پیشرو اندیشه پرداز سی پل"

##### نام انگلیسی شرکت
name_en: "CPOL"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار،مخابرات،وب"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://cpol.co"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "سی پل سازمانی قدرتمند با هدف ارائه محصولات و خدمات متنوع در زمینه فناوری اطلاعات و ارتباطات تاسیس گردیده است. این گروه با ساماندهی افراد متخصص و مستعد و بهره گیری از دانش روز دنیا، فعالیت گسترده ای در زمینه تولید و ارائه نرم افزار ها، تجهیزات و خدمات تخصصی در چارچوب فناوری‌های نوین دارد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سی-پل/](https://tajrobe.github.io/%D8%B3%DB%8C-%D9%BE%D9%84/)
