### ISSUE TITLE
مهر مام میهن

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#189]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/مهر-مام-میهن/](https://tajrobe.github.io/%D9%85%D9%87%D8%B1-%D9%85%D8%A7%D9%85-%D9%85%DB%8C%D9%87%D9%86/)
