### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by aliraghebi** [tajrobe/tajrobe.github.io#19]
##### نام شرکت
title: "فرغون"

##### نام انگلیسی شرکت
name_en: "Forghoon"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه آنلاین"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-30"

##### آدرس سایت شرکت
site: "https://forghoon.co"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه آنلاین مصالح ساختمانی"

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/فرغون/](https://tajrobe.github.io/%D9%81%D8%B1%D8%BA%D9%88%D9%86/)
