### ISSUE TITLE
مهر مام میهن

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#190]
##### نام شرکت
title: "مهر مام میهن"

##### نام انگلیسی شرکت
name_en: "Mom Fertility and Infertility Center"

##### دسته‌ی فعالیت شرکت
industry: "درمان ناباروری و باروری"

##### موقعیت مکانی شرکت
city: "تهران شیراز جنوبی پایین تر از همت خ 68  شرقی "

##### تعداد نفرات شرکت
size: "400"

##### آدرس سایت شرکت
site: "www.https://mom.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/مهر-مام-میهن/](https://tajrobe.github.io/%D9%85%D9%87%D8%B1-%D9%85%D8%A7%D9%85-%D9%85%DB%8C%D9%87%D9%86/)
