### ISSUE TITLE
Hasin Group's website url has changed

### ISSUE THREAD

**Issue by thejimbow** [tajrobe/tajrobe.github.io#191]
Hello
Recently I've been exploring your data and saw a flaw in it. Hasin Group's website has changed to hasin.ir.

**Comment by tajrobe** [comment]
It has been [updated](https://tajrobe.github.io/%DA%AF%D8%B1%D9%88%D9%87-%D8%AD%D8%B5%DB%8C%D9%86/). 

Thanks @thejimbow 🙏
