### ISSUE TITLE
سینا پیشگام دارو نوین

### ISSUE THREAD

**Issue by samannnn** [tajrobe/tajrobe.github.io#192]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "دارو"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "امیراباد"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by samannnn** [comment]
بهتون توصیه میکنم اصلا اینجا برای کار نرید، حقوق بسیار بسیار پایین، بطوریکه نگاه میکنن کی کمتر میگیره تا اونو استخدام کنند، محیط زیراب زنی و. فقط ظاهرش خوشگله

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/سینا-پیشگام/](https://tajrobe.github.io/%D8%B3%DB%8C%D9%86%D8%A7-%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85/)
