### ISSUE TITLE
اتومیت کردن اسکریپت بیلد برای دیتای خروجی اکستنشن ها

### ISSUE THREAD

**Issue by thejimbow** [tajrobe/tajrobe.github.io#193]
میشه با گیتهاب اکشن یه حرکتی زد که هربار تغییری روی برنچ مین داشتیم یه بارم ران کنه اسکریپت رو که دیتا همیشه آپدیت باشه

**Comment by tajrobe** [comment]
سلام
ممنون از مشارکت شما
توی این ریپازیتوری از گیتهاب اکشن برای بیلد jekyll استفاده می‌شه ([مثال](https://github.com/tajrobe/tajrobe.github.io/actions/runs/4976898083/jobs/8905381283)). درخصوص اینکه پشتیبانی از node داشته باشه بطور پیش‌فرض یا بشه بهش اضافه کرد اطلاع زیادی ندارم. شما تجربه‌ای در این زمینه دارید؟

**Comment by hnaderi** [comment]
سلام
بله، به صورت پیشفرض روی رانرها نصب هست، اگه یه جاب جدید ساخته بشه توش میشه اون اسکریپت رو هم ران کرد، ولی لازمه ش اینه که برنچ سایت عوض بشه، این شکلی که آدم ها main رو تغییر میدن و اون اکشنه برمیداره اسکریپت رو روش ران میکنه و خروجی رو روی یه برنچ دیگه پوش میکنه و سایت از اون برنچ تغذیه میشه.

البته اگه سورس سایت رو بزارید روی گیتهاب اکشن، باید تولید سایت رو هم دستی توی اکشن انجام داد و این طوری توی یه مرحله قابل انجامه

**Comment by tajrobe** [comment]
بله خیلی هم عالی
سالهای گذشته که بیلد صفحات استاتیک خارج از گیتهاب انجام میشد یه برنچ github_pages داشتیم که بعد از بیلد خروجی push میشد اونجا؛
فقط برای تست و باقی کارها باید یه fork از پروژه بگیرید تا فایل yml نهایی برای دیپلوی رو آماده کنیم.

**Comment by hnaderi** [comment]
پیشنهاد انجام شده رو پیاده کردم و مرج ریکوئست دادم.
برای اینکه سایت از خروجی CI استفاده کنه باید تو تنظیمات pages انتخاب کنید که source از github actions باشه
بقیه ش اتوماتیک انجام میشه روی هر کامیت.

**Comment by tajrobe** [comment]
ممنون از شما  🙏
