### ISSUE TITLE
پژوهشگاه توسعه فناوری‌های پیشرفته

### ISSUE THREAD

**Issue by aliraam** [tajrobe/tajrobe.github.io#194]
##### نام شرکت
title: "پژوهشگاه توسعه فناوری‌های پیشرفته"

##### نام انگلیسی شرکت
name_en: "Research Center on Developing Advanced Technologies"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "201-500"

##### آدرس سایت شرکت
site: "https://rcdat.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پژوهشگاه توسعه فناوری‌های پیشرفته در سال 1371 بعنوان یک مرکز تحقیقاتی تاسیس گردید و از پیشگامان حرکت در مسیر تحقیق و توسعه کاربردی در کشور بوده‌ است.
این مرکز با دراختیار داشتن نیروهای خبره و مجموعه ای با بیش از 400 نفر پرسنل فعال، به طراحی و پیاده سازی پروژه های مختلف در صنعت ICT و سایر صنایع مشغول است. حضور فارغ التحصیلان برتر کشور و اجرای پروژه ها و پژوهشهای کاربردی و ملی کشور، به پژوهشگاه فرصت داده است تا در حوزه های جدید دانش وارد شده و تحقیق و توسعه را به معنای واقعی به اجرا در آورد.
پژوهشگاه از ابتدای تاسیس تلاش نموده است تا محیطی علمی و پژوهشی، پویا، پیشرونده و بدون حاشیه ایجاد نماید. رشد توامان پژوهشگاه و نیروی انسانی، همواره در گرو همکاری تمامی پرسنل بوده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پژوهشگاه-فناوری/](https://tajrobe.github.io/%D9%BE%DA%98%D9%88%D9%87%D8%B4%DA%AF%D8%A7%D9%87-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C/)
