### ISSUE TITLE
پرداخت الکترونیک سامان کیش(سپ)

### ISSUE THREAD

**Issue by aliraam** [tajrobe/tajrobe.github.io#195]
##### نام شرکت
title: "پرداخت الکترونیک سامان کیش(سپ)"

##### نام انگلیسی شرکت
name_en: "Saman Electronic Payment"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "بیش از ۱۰۰۰ نفر"

##### آدرس سایت شرکت
site: "https://www.sep.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پرداخت الکترونیک سامان کیش با استفاده از نیروی انسانی متخصص، فناوری‌های امنیتی روز دنیا و بهره‌گیری از ابزارهای نوین پرداخت نظیر کارت، کارتخوان، درگاه اینترنتی و تلفن همراه توانسته است با ارائه خدمات با کیفیت و مطمئن، رضایت مشتریان و پیمانکاران خود را جلب نموده و سهم مناسبی از بازارهای خرد و کلان تجارت الکترونیک در کشور را به خود اختصاص دهد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سپ/](https://tajrobe.github.io/%D8%B3%D9%BE/)
