### ISSUE TITLE
edit commit message for new tajrobe

### ISSUE THREAD

**Issue by tajrobe** [tajrobe/tajrobe.github.io#196]
سلام
برای اینکه بتونیم لیستی از آخرین تجربه‌های ثبت شده توی سایت نشون بدیم، اگه commit message مربوط به اونها ویرایش بشه و slug شرکت داخل اون قرار بگیره، این کر قابل انجام هست؛ برای مثال الان برای [این کامیت](https://github.com/tajrobe/tajrobe.github.io/commit/b12be33bf91cb481c19f3936531d2c7033f7d311) commit message به شکل زیر هست:

> new tajrobe for compony rayaneh-komak

که اگه به شکل زیر دربیاد مشکل حل میشه:
> new tajrobe for compony /رایانه-کمک

با این روش میشه با استفاده از جاوا اسکریپت و [این API از گیت‌هاب](https://api.github.com/repos/tajrobe/tajrobe.github.io/commits?per_page=10) لیست مثلا 10 آخرین تجربه‌های ثبت شده توی سایت نشون بدیم

**Comment by pooooriya** [comment]
خیلی سرم شلوغه بدبختی و مسئله بدتر اینه ک بیلد گرفتنش باید بعد ادیت بزنم تا درست شه که میزارم تو ریپو خودش سه چهار ساعت تایم میگیره بتونم این چن وقت برات انجامش میدم یه لیست برام از کارایی ک اونور باید بکنم اگ ایمیل کنی میشینم یه روزه پاش درستش میکنم

**Comment by tajrobe** [comment]
خسته نباشی 🌸، کار زیادی نیست، فقط همون تغییر commit message به slug شرکت.
بقیه‌اش رو قبلا گفتم که من انجام میدم، چون نیاز به آزمون و خطا داره. 🙏

**Comment by tajrobe** [comment]
سلام 
یه برنامه کوچک nodejs نوشتم و فعلا به صورت آزمایشی گذاشتم روی سرور cyclic.sh برای گرفتن تجربه‌ها و پوش کردن در ریپازیتوری. فعلا به نظر درست کار می‌کنه، برای همین با اجازه شما، فرم قدیمی رو به review-p تغییر دادم. همچنین پیام‌های کامیت رو هم slug شرکت گذاشتم تا در روزهای آتی شاید بتونیم قسمت آخرین تجربه‌ها رو به صفحه اصلی اضافه کنم.

فعلا این isuue رو می‌بندم.
