### ISSUE TITLE
بلوهاست

### ISSUE THREAD

**Issue by mehdibarmas** [tajrobe/tajrobe.github.io#198]
##### نام شرکت
title: "بلوهاست"

##### نام انگلیسی شرکت
name_en: "Bluhost"

##### دسته‌ی فعالیت شرکت
industry: "hosting"

##### موقعیت مکانی شرکت
city: "mashhad"

##### تعداد نفرات شرکت
size: "10-20"

##### آدرس سایت شرکت
site: "bluhost.dev"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اولین پلتفرم ایرانی هاستینگ"

**Comment by tajrobe** [comment]
[tajrobe.github.io/بلوهاست/](https://tajrobe.github.io/%D8%A8%D9%84%D9%88%D9%87%D8%A7%D8%B3%D8%AA/)
