### ISSUE TITLE
توزیع داروهای دامی دراوپخش

### ISSUE THREAD

**Issue by samannnn** [tajrobe/tajrobe.github.io#199]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/دامی-داروپخش/](https://tajrobe.github.io/%D8%AF%D8%A7%D9%85%DB%8C-%D8%AF%D8%A7%D8%B1%D9%88%D9%BE%D8%AE%D8%B4/)
