### ISSUE TITLE
بای چک

### ISSUE THREAD

**Issue by AmirhosseinFazlikhani** [tajrobe/tajrobe.github.io#2]
##### نام شرکت
title: "بای چک"

##### نام انگلیسی شرکت
name_en: "ByCheck"

##### دسته‌ی فعالیت شرکت
industry: "فروش اقساطی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "100-200"

##### آدرس سایت شرکت
site: "bycheck.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پشتیبانی فروش اقساطی فروشگاه ها"

**Comment by tajrobe** [comment]
Done :)
https://tajrobe.github.io/%D8%A8%D8%A7%DB%8C-%DA%86%DA%A9/
