### ISSUE TITLE
اراکان آرا تجارت البرز

### ISSUE THREAD

**Issue by samannnn** [tajrobe/tajrobe.github.io#200]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ارکان-آرا/](https://tajrobe.github.io/%D8%A7%D8%B1%DA%A9%D8%A7%D9%86-%D8%A2%D8%B1%D8%A7/)
