### ISSUE TITLE
هیرا

### ISSUE THREAD

**Issue by msErfani** [tajrobe/tajrobe.github.io#201]
##### نام شرکت
title: "هیرا"

##### نام انگلیسی شرکت
name_en: "Hira"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by msErfani** [comment]
من سابقه کار در این شرکت به عنوان **برنامه نویس** رو دارم
**مزایا :** محیط شرکت دوستانه هستش، حقوق کافی، ساعت کاری منعطف (برای برنامه نویسان)
**معایب :** مانیتورینگ سیستم ها، کنترل پرسنل با دوربین، بسته بودن usb سیستم ها

**Comment by tajrobe** [comment]
@msErfani  لطفا تجربه خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/هیرا/](https://tajrobe.github.io/%D9%87%DB%8C%D8%B1%D8%A7/)
