### ISSUE TITLE
ثبت اطلاعات شرکت "شبکه مترجمین اشراق"

### ISSUE THREAD

**Issue by reza-akbari** [tajrobe/tajrobe.github.io#202]
##### نام شرکت
title: "شبکه مترجمین اشراق"

##### نام انگلیسی شرکت
name_en: "Eshragh Translators Network"

##### دسته‌ی فعالیت شرکت
industry: "ترجمه"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "51-100 نفر"

##### آدرس سایت شرکت
site: "https://eshraghtrans.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شبکه مترجمین اشراق به منظور کمک به فرهیختگان و دانش پژوهان و اساتید دانشگاهها از سال 1393 اقدام به ارائه خدمات آنلاین یا ترجمه تخصصی کتب و مقالات به صورت حرفه ای کرد. این موسسه به دلیل نیاز جامعه دانشگاهی برای ترجمه متون تخصصی و علمی پژوهشی تاسیس شد و هم اکنون بخش وسیعی از جامعه علمی و دانشگاهی را پوشش می دهد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/مترجمین-اشراق/](https://tajrobe.github.io/%D9%85%D8%AA%D8%B1%D8%AC%D9%85%DB%8C%D9%86-%D8%A7%D8%B4%D8%B1%D8%A7%D9%82/)
