### ISSUE TITLE
شرکت پیام آوا پردازش

### ISSUE THREAD

**Issue by BagheriMohsen** [tajrobe/tajrobe.github.io#203]
##### نام شرکت
title: "شرکت پیام آوا پردازش"

##### نام انگلیسی شرکت
name_en: "Payam ava pardazesh"

##### دسته‌ی فعالیت شرکت
industry: "Tech,Crypto"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://payamava.net/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی سایت ، طراحی رابط و تجربه کاربری ، دیجیتال مارکتینگ"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیام-آوا/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%A7%D9%85-%D8%A2%D9%88%D8%A7/)
