### ISSUE TITLE
مرکز گسترش فناوری اطلاعات (مگفا)

### ISSUE THREAD

**Issue by aria-tcp** [tajrobe/tajrobe.github.io#204]
title: "مرکز گسترش فناوری اطلاعات (مگفا)"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### تهران
city: " تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: " دو روز پیش رفتم مگفا تو تهران شرکت دولتی رفتیم مصاحبه و جلسه فنی اوکی بودم .بعدش
زنگ زد گفت برا مصاحبه فنی بیشتر باز جلسه میزاریم
رفتیم امروز مصاحبه دیدیم طرف پرهام منوچهری شروع به سوالات از نظر خودش روانشناسی کرد مثلا. یه برگه جلوش خط خطی میکرد و نتایج را می نوشت. دوزاریم افتاد بلافاصله.
نمیدونم چه رنگی دوس داری. بعد یکم رفت جلو گفت فکر کن من خواستم برم باغ بخرم نتونستم شما جای من رفتی مثلا از پشت تلفن باغ را توصیف کن ...neutral_faceroflroflroflمن برگشتم گفتم داداش ما خودمون قبلا مدیر فنی بودیم از ملت تست روانشناسی استاندارد با کامپیوتر می گرفتیم. مدل شخصیت طرف تقریبا دربیاد اصلا شما مدرکت چیه بر گشته می گه من روابط عمومی علامه طباطبایی ارشد خوندمroflrofl
چرا ازدواج نکردی!گفتم چه ربطی به شرکت شما داره؟ یه دلیلش حقوق پایینی است که شرکتا مثل شماها میدن roflrofl
کلی سوال چرت و پرت دیگه کار به کشتی نوح و نجات حیوانا از انقراض هم کشید
هیچی دیگه منم گفتم داداش بیخیال من نیم ساعته نشستم وقت ندارم .انتظار سوال فنی لینوکس اینا داشتم.
خلاصه از سایت درپیت جابینجا دنبال کار نگردین. که سرکاریه .اگر از این سایت هم کسی اینجا است باید بگم
کاش امتیاز دهی به شرکتها را فعال می کردن تا مردم وقت و تایمشان برا شرکتای سرکاری که دنبال نیرو نیستن ففط اگهی فیک می زنن که خودشان را تبلیغ کنن یا دنبال اچار فرانسه هستن نرن
"

**Comment by aria-tcp** [comment]
دو روز پیش رفتم مگفا تو تهران شرکت دولتی رفتیم مصاحبه و جلسه فنی اوکی بودم .بعدش  
 زنگ زد گفت  برا مصاحبه فنی بیشتر باز جلسه میزاریم 
رفتیم امروز مصاحبه دیدیم طرف پرهام منوچهری  شروع به سوالات از نظر خودش روانشناسی کرد مثلا. یه برگه جلوش خط خطی میکرد  و نتایج را می نوشت. دوزاریم افتاد بلافاصله.
نمیدونم چه رنگی دوس داری. بعد یکم رفت جلو گفت فکر کن من خواستم برم باغ بخرم نتونستم شما جای من رفتی مثلا از پشت تلفن باغ را توصیف کن ...😐🤣🤣🤣من برگشتم گفتم داداش ما خودمون قبلا مدیر فنی بودیم از ملت تست روانشناسی استاندارد با کامپیوتر می گرفتیم. مدل شخصیت طرف تقریبا دربیاد اصلا شما مدرکت چیه بر گشته می گه من روابط عمومی علامه طباطبایی ارشد خوندم🤣🤣
چرا ازدواج نکردی!گفتم چه ربطی به شرکت شما داره؟ یه دلیلش حقوق پایینی است که شرکتا مثل شماها میدن 🤣🤣
کلی سوال چرت و پرت دیگه کار به کشتی نوح و نجات حیوانا از انقراض هم کشید
هیچی دیگه منم گفتم داداش بیخیال من نیم ساعته نشستم وقت ندارم .انتظار سوال فنی لینوکس اینا داشتم.
خلاصه از سایت درپیت جابینجا دنبال کار نگردین. که سرکاریه      .اگر از این سایت هم کسی اینجا است باید بگم 
کاش امتیاز دهی به شرکتها را فعال می کردن تا مردم وقت و تایمشان برا شرکتای سرکاری که دنبال نیرو نیستن ففط اگهی فیک می زنن که خودشان را تبلیغ کنن  یا دنبال  اچار فرانسه هستن  نرن

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/مگفا/](https://tajrobe.github.io/%D9%85%DA%AF%D9%81%D8%A7/)
