### ISSUE TITLE
مرکز گسترش فناوری اطلاعات (مگفا)

### ISSUE THREAD

**Issue by aria-tcp** [tajrobe/tajrobe.github.io#205]
##### نام شرکت
title: "مرکز گسترش فناوری اطلاعات (مگفا)"

##### نام انگلیسی شرکت
name_en: "magfa"

##### دسته‌ی فعالیت شرکت
industry: "ای تی "

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/مگفا/](https://tajrobe.github.io/%D9%85%DA%AF%D9%81%D8%A7/)
