### ISSUE TITLE
آهن دپو

### ISSUE THREAD

**Issue by baharbigi90** [tajrobe/tajrobe.github.io#206]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by baharbigi90** [comment]
من به مدت یک سال در [آهن دپو](https://ahandepo.com/) فعالیت کردم. می تونم بگم یکی از شرکت هایی بود که تونستم داخلش با خیال راحت فقط کار کنم. فضای آروم مهربون و دوستانه ای داشت. حتی روز مصاحبه منو اذیت نکردن و برای پیشرفت بهم فضا دادن. ممنون از همتون

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/آهن-دپو/](https://tajrobe.github.io/%D8%A2%D9%87%D9%86-%D8%AF%D9%BE%D9%88/)
