### ISSUE TITLE
آسه تجارت آسیا

### ISSUE THREAD

**Issue by ghanimimohammad** [tajrobe/tajrobe.github.io#207]
##### نام شرکت
title: "آسه تجارت آسیا"

##### نام انگلیسی شرکت
name_en: "Aseh Tejarat Asia"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "600"

##### آدرس سایت شرکت
site: "asehtejaratasia.co"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فعال در زمینه تبرید و سردخانه"

**Comment by tajrobe** [comment]
[tajrobe.github.io/آسه-تجارت/](https://tajrobe.github.io/%D8%A2%D8%B3%D9%87-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA/)
