### ISSUE TITLE
کانال تخفیف

### ISSUE THREAD

**Issue by offchannel** [tajrobe/tajrobe.github.io#208]
##### نام شرکت
title: کانال تخفیف

##### نام انگلیسی شرکت
name_en: offch.com

##### دسته‌ی فعالیت شرکت
industry: کد تخفیف

##### موقعیت مکانی شرکت
city: اصفهان

##### تعداد نفرات شرکت
size: بین 10 تا 15 نفر

##### آدرس سایت شرکت
site: https://www.offch.com/

##### توضیحی درباره شرکت و فعالیت‌هایش
content: کانال تخفیف یا آفچنل یک پلتفرم رایگان است که به عنوان مرجع کوپن و کد تخفیف فروشگاه های آنلاین و کسب و کارهای اینترنتی عمل می کند. با استفاده از بستر تبلیغاتی بر پایه بن هدیه و آفر، فروشگاه ها می توانند به بهبود شناخت و جذب مشتریان خود کمک کنند و در عین حال بازدیدها و فروش های خود را افزایش دهند. با ارائه کدهای تخفیف و کوپن های اختصاصی، کانال تخفیف به مشتریان این امکان را می دهد تا از تجربه خریدی لذت بخش و ارزان تر بهره مند شوند. همچنین، استفاده از این پلتفرم برای فروشگاه ها در کاهش هزینه های تبلیغات و ایجاد رقابتی سالم در بازار آنلاین نیز موثر است.

**Comment by tajrobe** [comment]
[tajrobe.github.io/کانال-تخفیف/](https://tajrobe.github.io/%DA%A9%D8%A7%D9%86%D8%A7%D9%84-%D8%AA%D8%AE%D9%81%DB%8C%D9%81)
