### ISSUE TITLE
اتصال یکپارچه

### ISSUE THREAD

**Issue by maorojloo** [tajrobe/tajrobe.github.io#209]
##### نام شرکت
title: "اتصال یکپارچه"

##### نام انگلیسی شرکت
name_en: "Etesal Yekparcheh Co."

##### دسته‌ی فعالیت شرکت
industry: "IT Services and IT Consulting"

##### موقعیت مکانی شرکت
city: "ُTehran"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://ettesal.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: " فعالیت اصلی این شرکت توسعه راهکارهای فناورانه به منظور تسهیل ارتباطات گروهی نظیر ویدئوکنفرانس، ویدئو وبینار می‌باشد. محصول اصلی این شرکت سرویس ویدعوکیک است"

**Comment by tajrobe** [comment]
[tajrobe.github.io/اتصال-یکپارچه/](https://tajrobe.github.io/%D8%A7%D8%AA%D8%B5%D8%A7%D9%84-%DB%8C%DA%A9%D9%BE%D8%A7%D8%B1%DA%86%D9%87/)
