### ISSUE TITLE
درایت پویان نسل آفتاب (دپنا)

### ISSUE THREAD

**Issue by vhasany** [tajrobe/tajrobe.github.io#211]
##### نام شرکت
title: " درایت پویان نسل آفتاب (دپنا)"

##### نام انگلیسی شرکت
name_en: "DPNA"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "یزد"

##### تعداد نفرات شرکت
size: "۱۱ تا ۵۱"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه درایت پویان نسل آفتاب(دپنا) با سرمایه گذاری بخش خصوصی از سال 1386 فعالیت خود را در زمینه ی فناوری اطلاعات و تولیدات نرم افزاری آغاز نمود و سپس با چندین سال تجربه در سال 1395 با ثبت شرکت درایت پویان نسل آفتاب(دپنا) بصورت رسمی خود را معرفی کرد. این شرکت با اتکاء بر دانش، تجربه و بهره گیری از کارشناسان و اساتید مجرب در زمینه تولید نرم افزارهای کامپیوتری پا به عرصه تلاش و فعالیت نهاده است. نوآوری و نشاط اولین تصویری است که از دپنا به چشم می‌خورد. پویایی و تلاش برای نیل به اهداف در طول حیات شرکت باعث گسترش توانایی‌ها شده و استفاده از ابزار مناسب، زیرساخت‌های محکمی در شرکت بنیان نهاده است. ما به سازمان‌ها در بهینه‌کردن بهره‌وری به منظور افزایش کارآیی یاری می‌رسانیم. در طول حیات شرکت، بر روی نیازمندی‌های آشکار و پنهان بازار هدف متمرکز شده‌ایم و به این ترتیب با ارائه راهکارهای خلاق و بومی‌سازی شده، پاسخگوی مشکلات سازمان‌ها هستیم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/دپنا/](https://tajrobe.github.io/%D8%AF%D9%BE%D9%86%D8%A7/)
