### ISSUE TITLE
خدمات ارتباطی رایتل

### ISSUE THREAD

**Issue by MerajCyberSec** [tajrobe/tajrobe.github.io#212]
##### نام شرکت
title: "خدمات ارتباطی رایتل"

##### نام انگلیسی شرکت
name_en: "RighTel"

##### دسته‌ی فعالیت شرکت
industry: "Telecom"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "2000"

##### آدرس سایت شرکت
site: "https://rightel.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ارائه دهنده خدمات موبایل"

**Comment by tajrobe** [comment]
[tajrobe.github.io/رایتل/](https://tajrobe.github.io/%D8%B1%D8%A7%DB%8C%D8%AA%D9%84/)
