### ISSUE TITLE
بهینه سازان سرزمین هوشمند

### ISSUE THREAD

**Issue by maorojloo** [tajrobe/tajrobe.github.io#213]
##### نام شرکت
title: "بهینه سازان سرزمین هوشمند"

##### نام انگلیسی شرکت
name_en: "Smart Land Optimizers"

##### دسته‌ی فعالیت شرکت
industry: "it"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://sarzaminhooshmand.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: " شرکت نرم افزاری بهینه سازان سرزمین هوشمند با ساختار آموزشی پروژه محور، دارای اختراعات مختلف در زمینه کامپیوتر و نرم افزار است. این شرکت، با سابقه 15 ساله در زمینه های مختلف صنایع IT و هوش مصنوعی (AI) و نرم افزار (Software) و طراحی وبسایت اختصاصی و طراحی سایت فروشگاهی و برندسازی در حوزه محصولات و صنایع، به فعالیت حرفه ای مشغول میباشد. در این شرکت فرصت های شغلی خوبی برای افراد با سطوح توانایی های مختلف موجود میباشد. از علاقه مندان در حوزه های مطرح دعوت به همکاری میگردد. - کار کردن در شرکت بهینه سازان سرزمین هوشمند، فرصتی است متفاوت برای آنها که هدفشان حرفه ای شدن است"

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرزمین-هوشمند/](https://tajrobe.github.io/%D8%B3%D8%B1%D8%B2%D9%85%DB%8C%D9%86-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF/)
