### ISSUE TITLE
شرکت هماپلاس

### ISSUE THREAD

**Issue by khoramism** [tajrobe/tajrobe.github.io#214]
##### نام شرکت
title: "مشاوران مدیریت هماپلاس"

##### نام انگلیسی شرکت
name_en: "homaplus"

##### دسته‌ی فعالیت شرکت
industry: "تحلیل کلان داده های فضای مجازی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "15"

##### آدرس سایت شرکت
site: "https://8tag.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مشاوران مدیریت هماپلاس به عنوان یک شرکت دانش‌بنیان از سال ۱۳۸۷ به صورت کاملا تخصصی و با گرد هم آوردن فارغ‌التحصیلان دانشگاه‌های برتر کشور در زمینه‌های هوش مصنوعی و علوم داده، اقدام به توسعه ابزارهای جمع‌آوری و آنالیز داده‌ی خاص زبان فارسی برای پردازش محتوای رسانه‌ها و شبکه‌های اجتماعی نموده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/هماپلاس/](https://tajrobe.github.io/%D9%87%D9%85%D8%A7%D9%BE%D9%84%D8%A7%D8%B3/)
