### ISSUE TITLE
سوپرپایپ اینترنشنال

### ISSUE THREAD

**Issue by Theknownman** [tajrobe/tajrobe.github.io#215]
##### نام شرکت
title: ""
سوپرپایپ اینترنشنال
##### نام انگلیسی شرکت
name_en: superpipe International 

##### دسته‌ی فعالیت شرکت
industry: ""تاسیسات مکانیکی

##### موقعیت مکانی شرکت
city: ""تهران

##### تعداد نفرات شرکت
size: ""
حدود 200
##### آدرس سایت شرکت
site: ""
superpipe.ir
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
تاسیسات مکانیکی حوزه فعالیت شرکت است. 
کارخانه اصلی در قشم اما در تهران دفتر خدمات دارند.

**Comment by Theknownman** [comment]
سلام. 
تجربه ارسال رزومه برای شرکت رو دارم و حتما بقیه می تونن استفاده کنن چون رفتار غیرحرفه ای این شرکت واقعا زننده بود. 
برای فرصت شغلی که تطابق کامل با آگهی داشتم رزومه فرستادم و مسئول گزینشش یه خانومی بود که بعدا از لینکدین فهمیدم کیه، رزومه امو رد کرد. 
به مدیرش از لینکدین پیام دادم، گفت باهات تماس می گیره، ظهر کارشناس شرکتشون برای مصاحبه تلفنی زنگ زد. یک مصاحبه عجیب و کاملا غیرحرفه ای بر خلاف آگهی که ذکر کرده بودن، فقط می خواست از سر خودش باز کنه و توجیه و علت تراشی برای رد رزومه ام پیدا کنه. بهش گفتم چیزهایی که می پرسین تو آگهی بعنوان مسئولیت هایی که می خپای ذکر نشده، گفت سیاست شرکت ما اینه! 
مورد دقیقا تحربه کاری بود، فرصت شغلیشون کارآموزی بود و هیچ تحربه ای تو آگهی ذکر نشده بود اما خانم کارشناس برای اینکه یه دلیلی برای رد رزومه بیاره روی این مورد محکم ایستاد. 
بعد گفت زبانت در چه حد هست؟ گفتم مسلطم
رفت سراغ حقوق پیشنهادی، که من گفتم همون اشل نرمالی که خودتون قرار دادید اما پلسخ عجیبش این بود که با سیاست شرکت همخونی نداره! 
خنده دار نیست؟ 
مبلغی که خودشون توی آگهی بعنوان حقوق زدند رو میگه با شرایط شرکت همخونی نداره. 
خلاصه گفت بهت خبر میدم، البته من چون آدم پیگیری بودم به مدیرش که اول پیام داده بودم یک متن طولانی انگلیسی فرستادم تا سطح زبانم هم بدونه و بفهمه کارمندش چه عتیقه ای هست. 
با نهایت تعجب مدیرش هم همون دو تا جواب رو دقیقا داد که تجربه کاری نداری و حقپقت با رنج شرکت هماهنگ نیست! فهمیدم چه خبره توی شرکت. 
سرتون درد نیارم، همین شرکت توی سایتش چند صفحه درباره تعهد های اخلاقی و مسئولیت پذیری و...  متن نوشته. 
شرکت در مسیر بررسی رزومه سه اشتباه فاحش کرد
یک. رزومه ای که تطابق کامل با شرایط آگهی داشت رد کرد. 
دو. بعد از پیگیری من اقدام به اصلاح نکرد و به اشتباه اول خودش پافشاری کرد
سه.  گفته بود بابت جواب مصاحبه بهم خبر میده که خبر ندادن. 
خلاصه حتما مد نظر داشته باشید این تجربه ارو.

**Comment by tajrobe** [comment]
[tajrobe.github.io/سوپرپایپ/](https://tajrobe.github.io/%D8%B3%D9%88%D9%BE%D8%B1%D9%BE%D8%A7%DB%8C%D9%BE/)
