### ISSUE TITLE
فناوری های پیشرفته تبادل امن (فپنتا)

### ISSUE THREAD

**Issue by ErfanNahidi** [tajrobe/tajrobe.github.io#217]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/فپتا/](https://tajrobe.github.io/%D9%81%D9%BE%D8%AA%D8%A7/)
