### ISSUE TITLE
تکدو

### ISSUE THREAD

**Issue by takdoo** [tajrobe/tajrobe.github.io#219]
##### نام شرکت
title: "تکدو"

##### نام انگلیسی شرکت
name_en: "takdoo"

##### دسته‌ی فعالیت شرکت
industry: "فروش اینترنتی"

##### موقعیت مکانی شرکت
city: "آذربایجان غربی تکاب"

##### تعداد نفرات شرکت
size: "13"

##### آدرس سایت شرکت
site: "https://takdoo.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تکدو در ابتدا سعی نموده که تمامی کالاهای موجود در سایت را بدون توجه به مقدار سود آن و یا مقدار قیمت به‌صورت کاملاً اختصاصی تشریح دهد با توجه به اینکه در فضای مجازی گله اکثر کاربران بر این مورد است که کالای دریافتی با عکس و نوع محصول دریافتی متفاوت است اما در تکدو این مشکل تا حد 99.9 درصد برطرف گردیده است زیرا به‌صورت عکس و فیلم واقعی از محصول و نمایش آن در سایت کاربر متوجه نوع کالای دریافتی خود میگردد و این به نوبه خود یک نوع اعتماد سازی کامل برای خریدار است "

**Comment by takdoo** [comment]
تکدو در ابتدا سعی نموده که تمامی کالاهای موجود در سایت را بدون توجه به مقدار سود آن و یا مقدار قیمت به‌صورت کاملاً اختصاصی تشریح دهد
 با توجه به اینکه در فضای مجازی گله اکثر کاربران بر این مورد است که کالای دریافتی با عکس و نوع محصول دریافتی متفاوت است اما در تکدو این مشکل تا حد 99.9 درصد برطرف گردیده است زیرا به‌صورت عکس و فیلم واقعی از محصول و نمایش آن در سایت کاربر متوجه نوع کالای دریافتی خود میگردد و این به نوبه خود یک نوع اعتماد سازی کامل برای خریدار است

**Comment by tajrobe** [comment]
[tajrobe.github.io/تکدو/](https://tajrobe.github.io/%D8%AA%DA%A9%D8%AF%D9%88/)

**Comment by tajrobe** [comment]
[tajrobe.github.io/تکدو/](https://tajrobe.github.io/%D8%AA%DA%A9%D8%AF%D9%88/)
