### ISSUE TITLE
add new company

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#220]
##### نام شرکت
title: "وبجار"

##### نام انگلیسی شرکت
name_en: "Webjar"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران، تهران"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "https://webjar.site/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "وبــجار از سال 1399 بعد از بـررسی و شناسایی نیازهای اصلـی بـازار به عـنوان شـرکت ارائه دهنده خدمات نرم افزاری در تهران فعالیت خود را آغـاز نمود. با گـسترش و فـراگیر شدن استفاده از اینترنت در ایران شرکت وبجار با تمرکز بر دانش فنی، تخصص و ایده‌های نوین، سعی در بهبود روند کار و‌ کسب‌های بازار ایـران دارد، در همین راستـا خدمات خـود را به تحلیل و ارزش‌گـذاری کسب‌وکارهای اینترنتی، ارائه راهکا‌ر نوین بازاریابی، بـهینه‌سازی وب سایت (سئو)، سایت ‌ساز وبجار، باشگاه مشتریان بوم‌جار و دیـگر محصـولات مرتبـط گسترش دادیم. فعالیت تیـم وبــجار همیشـه در مسیری خواهد بـود تا بستـری برای سـاخت شعبه آنلاین و اختصاصی کسب‌وکارها باشد. ما به کسب و کارها در موفقیت آنلاین کمک می‌کنیم. شرکت ما دائما در حال رشد است و ما همیشه به دنبال افراد با استعداد برای پیوستن به تیم وبجار هستیم"

**Comment by tajrobe** [comment]
[tajrobe.github.io/وبجار/](https://tajrobe.github.io/%D9%88%D8%A8%D8%AC%D8%A7%D8%B1/)
