### ISSUE TITLE
شرکت فوکس ایرانیان

### ISSUE THREAD

**Issue by ilia58** [tajrobe/tajrobe.github.io#221]
شرکت روغن  فوکس ایرانیان
title: ""
FUCHS Iranian
name_en: ""

#####  روغن و روانکار
industry: ""

جردن
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/روغن-فوکس/](https://tajrobe.github.io/%D8%B1%D9%88%D8%BA%D9%86-%D9%81%D9%88%DA%A9%D8%B3/)
