### ISSUE TITLE
داده گستر امن برنا

### ISSUE THREAD

**Issue by emtadeveloper** [tajrobe/tajrobe.github.io#223]
##### نام شرکت
title: "داده گستر امن برنا"

##### نام انگلیسی شرکت
name_en: "DGAB"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "آدرس: میدان فلسطین، خیابان سرپرست، بن‌بست پارس، پلاک ۱، واحد ۳ و ۴ "

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://dadehgostar.net/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "
![logo-2-e1674479092401](https://github.com/tajrobe/tajrobe.github.io/assets/47769965/f32e0f94-4f4b-42a5-99fd-ba1ff103029e)

"

**Comment by emtadeveloper** [comment]
به عنوان برنامه نویس مشغول به کار بودم دوستان به هیچ وجه داخل این شرکت پاا نزارین 6 ماه حقوق عقب افتاده دارم که بعد 7 ماه دیرکرد در پرداخت بهم چک دادن که چک هاهم داخل حساب شرکت پوول نبود و برگشت خورد و سعی داشتن با قوانین چک و چرب زمونی حسابدار سرم کلاه بزارن وارد شدن به این شرکت یعنی فشار کاری شدید و عدم تعهد در پرداخت کوچک ترین حق و حقوق شما شدیدا در ظاهر سازی مهارت دارند اگه اعصاب و روان و آینده شغلی تون براتون مهمه وارد همچین محیط سمی نشین

**Comment by tajrobe** [comment]
[tajrobe.github.io/داده-گستر-برنا/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%DA%AF%D8%B3%D8%AA%D8%B1-%D8%A8%D8%B1%D9%86%D8%A7/)
