### ISSUE TITLE
شرکت ایران خودرو

### ISSUE THREAD

**Issue by aramrahmani** [tajrobe/tajrobe.github.io#224]
##### نام شرکت
title: "ایران خودرو"

##### نام انگلیسی شرکت
name_en: "Ikco"

##### دسته‌ی فعالیت شرکت
industry: "خودرو سازی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۳۱۰۰۰"

##### آدرس سایت شرکت
site: "www.ikco.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت ایران خودرو بزرگترین خودرو ساز خاورمیانه"

**Comment by aramrahmani** [comment]
Add new companyName

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایران-خودرو/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%AE%D9%88%D8%AF%D8%B1%D9%88/)
