### ISSUE TITLE
شرکت مهاجرتی ادیسه

### ISSUE THREAD

**Issue by Theknownman** [tajrobe/tajrobe.github.io#225]
##### نام شرکت
title: "" شرکت مهاجرتی ادیسه

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
مهاجرت به کانادا
##### موقعیت مکانی شرکت
city: "" شهرک غرب

##### تعداد نفرات شرکت
size: "" 
حدثد 60 نفر

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Theknownman** [comment]
سلام
تجربه ی مصاحبه کارشناس منابع انسانی داشتم. 
در واقع اصلا مصاحبه ای شکل نگرفت، مصاحبه کننده خودش گفت من منابع انسانی تجربی هستم و فقط درباره شرایط کار توضیح داد. جلسه کاملا غیرحرفه ای بود، اصلا هیچ معیار و متری برای سنجش ندارند، فکر می کنم تنها هدفشون برای مصاحبه این هست که بیای و ببینی به تیپ و فاز شرکت تناسب داری یا خیر. 
فرم های استخدام کاملا سنتی بود، سابقه ی کاری هم برای این جایگاه شغلی ملاک نبود، با وجود اشرافی که به فرآیندها داشتم و با شرح شغلی که در آگهی ذکر شده بود هم تناسب کامل داشتم، هیچ تماسی برای مراحل بعدی گرفته نشد. 
فضای شرکت کاملا خوشحال و خوش و خرم، تعداد زیادی نیروی فروش که احتمالا از لحاظ حقوق هم شرایط خوبی دارند، اگه برای پوزیشن فروش مصاحبه میرید و معیار حقوق براتون عامل مهمی هست و البته از لحاظ فرهنگ با محیط شرکت همسو هستید، گزینه بی دردسری هست. 
محیط و فرهنگ شرکت هم خوش و خرم و گل و بلبل هست. 
دورهمی و پارتی فرم. 
اما اگه حرفه ای بودن و یادگیری و توسعه براتون اهمیت داره اصلا سمت این شرکت نیاین.

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت وارد کنید:

[tajrobe.github.io/ادیسه/](https://tajrobe.github.io/%D8%A7%D8%AF%DB%8C%D8%B3%D9%87/)
