### ISSUE TITLE
ایران هاست

### ISSUE THREAD

**Issue by asghari111** [tajrobe/tajrobe.github.io#226]
##### نام شرکت
title: "ایران هاست"

##### نام انگلیسی شرکت
name_en: "iranhost"

##### دسته‌ی فعالیت شرکت
industry: "هاستینگ"

##### موقعیت مکانی شرکت
city: "مطهری"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://iranhost.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "قدیمی ترین شرکت هاستینگ ایران"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایران-هاست/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D9%87%D8%A7%D8%B3%D8%AA/)
