### ISSUE TITLE
شرکت فناوری های مالی کارآفرینی امید فنام

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#227]
##### نام شرکت
title: "شرکت فناوری های مالی کارآفرینی امید فنام"

##### نام انگلیسی شرکت
name_en: "Fanam"

##### دسته‌ی فعالیت شرکت
industry: "حوزه فناوری های مالی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "40 الی 70"

##### آدرس سایت شرکت
site: "http://www.fanamco.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فنام در حوزه های مالی فعالیت خود را از سال 1398 آغاز کرد و افتخار دارد که تا کنون موفق به اجرای چند پروژه ی موفق در سطح ملی شده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فنام/](https://tajrobe.github.io/%D9%81%D9%86%D8%A7%D9%85/)
