### ISSUE TITLE
مالکشو

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#228]
##### نام شرکت
title: "مالکشو"

##### نام انگلیسی شرکت
name_en: "malecksho"

##### دسته‌ی فعالیت شرکت
industry: "بورسی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10 الی 20"

##### آدرس سایت شرکت
site: "https://maaleksho.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "در این شرکت، به دنبال توسعه پروژه‌ای در حوزه بورس لوازم ساختمانی هستم. "

**Comment by tajrobe** [comment]
[tajrobe.github.io/مالک-شو/](https://tajrobe.github.io/%D9%85%D8%A7%D9%84%DA%A9-%D8%B4%D9%88/)
