### ISSUE TITLE
نیلپر

### ISSUE THREAD

**Issue by Saaraagh** [tajrobe/tajrobe.github.io#229]
description: 'شرح تجربه‌ی شما'
سه جلسه مصاحبه باهاشون رفتم 
مصاحبه اول با مدیر مستقیم تخصصی بود خوب بود
مصاحبه دوم با مشاور شرکت بود و به شدت فضا استرس زا و پر تنش بود 
مصاحبه سوم با منابع انسانی 
کلا فضای صنعتی دارن و تجربه مصاحبه باهاشون جذاب نبود خیلی 
state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'نام شرکت'
نیلپر
pros: 'مزایا - با کاما (,) جدا شود'
ناهار٫ بیمه٫ بیمه تکمیلی٫ سرویس٫ ارزاق هر سه ماه که پولش واریز میشه٫ 
cons: 'مزایا - با کاما (,) جدا شود'
پروسه مصاحبه سنتی٫ رفتار مصاحبه کننده خشک و استرس زا٫ فیدبک مصاحبه گر در خود مصاحبه
rate: بین 1.0 تا 5.0
0.2

**Comment by tajrobe** [comment]
@Saaraagh 
لطفا نظر خود را در صفحه شرکت بنویسید:
[tajrobe.github.io/نیلپر/](https://tajrobe.github.io/%D9%86%DB%8C%D9%84%D9%BE%D8%B1/)
