### ISSUE TITLE
کاربین

### ISSUE THREAD

**Issue by pixelate0** [tajrobe/tajrobe.github.io#230]
##### نام شرکت
title: "کاربین"

##### نام انگلیسی شرکت
name_en: "Karbin"

##### دسته‌ی فعالیت شرکت
industry: "مهاجرت"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://karbinco.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مهاجرتی"

**Comment by tajrobe** [comment]
[tajrobe.github.io/کاربین/](https://tajrobe.github.io/%DA%A9%D8%A7%D8%B1%D8%A8%DB%8C%D9%86/)
