### ISSUE TITLE
ریفکت

### ISSUE THREAD

**Issue by morisfa2** [tajrobe/tajrobe.github.io#231]
##### نام شرکت
title: "ریفکت"

##### نام انگلیسی شرکت
name_en: "refact"

##### دسته‌ی فعالیت شرکت
industry: "marketing"

##### موقعیت مکانی شرکت
city: "unknown"

##### تعداد نفرات شرکت
size: "10-50"

##### آدرس سایت شرکت
site: "https://refact.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "دیجیتال مارکتینگ "

**Comment by tajrobe** [comment]
[tajrobe.github.io/ریفکت/](https://tajrobe.github.io/%D8%B1%DB%8C%D9%81%DA%A9%D8%AA/)
