### ISSUE TITLE
آداکارنو

### ISSUE THREAD

**Issue by gatehubb** [tajrobe/tajrobe.github.io#233]
آداکارنو نام شرکت
title: "آداکارنو"

##### نام انگلیسی شرکت
name_en: "Adakarno"

##### دسته‌ی فعالیت شرکت
industry: "تولید دستگاههای چاپ"

##### موقعیت مکانی شرکت
city: "شهرقدس"

##### تعداد نفرات شرکت
size: "50 نفر"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by gatehubb** [comment]
کلا این شرکت یه گارگاه بوده که بعد از چند سال با اضافه کردن چندتا شریک و نیرو شده یه شرکت کوچولو 
اگه کلی بخوام توضیح بدم یه کارگاه بزرگ با چهارتا شریک که هر چهارتاشون هم 24 ساعت اونجان, البته از نظر شخصیتی انسان های خوبی هستن ولی به طور کل جو اونجا اصلا برای افرادی که توی شرکت های بزرگ کار کردن خوب نیست.
حقوق هم یکم بالاتر از وزارت کار که برای نیروهای فنی اصلا خوب نیست

**Comment by tajrobe** [comment]
[tajrobe.github.io/آداکارنو/](https://tajrobe.github.io/%D8%A2%D8%AF%D8%A7%DA%A9%D8%A7%D8%B1%D9%86%D9%88/)
