### ISSUE TITLE
درمانكده

### ISSUE THREAD

**Issue by freeman1991** [tajrobe/tajrobe.github.io#234]
##### نام شرکت
title: ""درمانكده

##### نام انگلیسی شرکت
name_en: ""
darmankade
##### دسته‌ی فعالیت شرکت
industry: ""
خدمات و سلامتی
##### موقعیت مکانی شرکت
city: ""
tehran
##### تعداد نفرات شرکت
size: ""
40
##### آدرس سایت شرکت
site: ""
www.darmankade.com
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""خدمات نوبت دهی آنلاین مشاوره های آنلاین و مطب پزشكان

**Comment by freeman1991** [comment]
در محیط كار ممكنه افرادی باشن كه جو رو به هم بریزن
ممكنه شما فردی رو ببینید كه خاله زنكه
ممكنه همكاری داشته باشید كه پشت سرتون یه جور و جلوی روی شما یه جور دیگست
ممكنه در جو مسموم كار كنید و خیلی موارد دیگه
تجربه ی كاری من در این شركت شامل تمام موارد بالا میشد اما از طرف مدیریت
یعنی چی؟
یعنی تمام این خصوصیات بالا رو مدیریت اونجا داشت و داره
كسی كه ادعای خدا و پیغمبرش میشه ولی كل اعضای شركت رو به جون هم انداخته
كسی كه خاله زنكه و با دخترا انقدر لاس میزنه كه طرف فرار میكنه
به رنگ مو و ناخن خانم ها و آرایششون خیلی توجه میكنه
من هیچ مردی رو ندیدم اونجا كه به اندازه ی مدیر مثلا مومن درمانكده نگاهش توی پر و پاچه ی زنا باشه
خیلی راحت این فرهنگ كه بقیه همو مسخره كنن توسط مدیریت جا افتاده بود
كسی كه اگر 2 بار یك لباس رو بپوشی بهت میگه نكنه میخوای شناساییت كنیم كه كجایی؟
كسی كه وقتی سطحی بشناسیش میگی اوه اوه چه آدم موجه و درستیه ولی وقتی میری درمانكده و كار میكنی میبینی عجب آدم دو روییه
تمام شركت به لطف ایشون (آقای م.ص) نقش پلیس بد و پلیس خوب رو بازی میكنن برای هم
جو نا امن (از نظر كاری) و مسموم
به هر كی حرف بزنی 30 ثانیه بعد منابع انسانی فهمیده و میان باهات صحبت میكنن
همش احساس گناه میدن بهت كه اگه شركت توی بحرانه شماها تلاش نكردین
توی كار بچه ها رو به جون هم میندازن و این كارشون باعث میشه از تیم بودن خارج بشن و جو بشه زیر آب زنی
من انقدر از تجربه ی كارم در این شركت پیش خودم شرمنده و ناراحتم كه داخل رزومم این مدت رو نوشتم در اسنپ كار میكردم با اینكه ماشین ندارم
از همه مهمتر پولش كه اصلا بركت نداره

**Comment by tajrobe** [comment]
[tajrobe.github.io/درمانکده/](https://tajrobe.github.io/%D8%AF%D8%B1%D9%85%D8%A7%D9%86%DA%A9%D8%AF%D9%87/)
