### ISSUE TITLE
درمانكده

### ISSUE THREAD

**Issue by freeman1991** [tajrobe/tajrobe.github.io#235]
##### نام شرکت
title:درمانكده
##### نام انگلیسی شرکت
name_en: ""
darmankade
##### دسته‌ی فعالیت شرکت
industry: ""
helth
##### موقعیت مکانی شرکت
city: ""
تهران
##### تعداد نفرات شرکت
size: ""
30-40
##### آدرس سایت شرکت
site: ""
https://www.darmankade.com
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
نوبت دهی آنلاین خدمات پزشكی

**Comment by freeman1991** [comment]
همه ی ما طی تجارب كاری مختلف ممكنه در محل كار با آدم دو رو، خاله زنك، دو به هم زن، مریض و اذیت كن، هیز، دورغگو، مسخره كن و مزخرفی رو به رو بشیم. ولی داشتن تمامی این خصوصیات در یك مجموعه یا بهتره بگم در یك مدیر مجموعه واقعا عجیبه.
انقدری بگم كه تجربه كار در این شركت رو از رزومه خودم بیرون آوردم و به جاش شغل آزاد رو ثبت كردم.
خجالت آوره برای مدیریت (آقای م ص) كه جوی این مدلی توی مجموعه درمانكده درست كنه
شما در این شركت به هیچ كسی نمیتونی حرف بزنی
چون با طرز فكر پلیس بد و پلیس خوب همه خبرچین هستن
توی این شركت اگه یه لباس رو دوبار بپوشی توسط مدیریت مسخره میشی و بهت میگن مگه میخوای راحت پیدات كنیم كه یه لباس رو میپوشی؟
توی این شركت اگه موهاتو رنگ كنی، ناخن هاتو درست كنی، دماغتو عمل كنی، ابروهاتو درست كنی یا هر چیز دیگه ای توسط مدیریت كامنت میگیری و نظر ایشون با تمسخر و به قول خودشون شوخی روی شما می مونه
جو كاری به شدت مسموم و عین مهد كودك
انتظار كاری بالا
دادن احساس گناه توسط مدیریت به اعضا
بركت نداشتن حقوق
عدم احساس امنیت شغلی
و اعصاب خوردی های زیاد از جمله مواردیه كه قبل از مصاحبه با مدیران باید در نظر داشته باشین
تنها چیزی كه شما یاد میگیرین در درمانكده اینه كه چطور پا روی خودتون بزارید و خود خوری كنین
آخرشم با حس بی ارزشی و مورد سو استفاده قرار گرفتن میاید بیرون
درمانكده جاییه كه اگر شما در مصاحبه ها خودتون رو فردی مستعد پیشرفت و پر انرژی و كار بلد نشون بدید استخدام میشید و در نهایت به دلیل ضعف مدیریت به شكل سرخورده و ناراحت و عصبی و داغون میاید بیرون و به این فكر میكنین كه چرا عمرتونو اینجا تلف كردین

**Comment by tajrobe** [comment]
[tajrobe.github.io/درمانکده/](https://tajrobe.github.io/%D8%AF%D8%B1%D9%85%D8%A7%D9%86%DA%A9%D8%AF%D9%87/)
