### ISSUE TITLE
add new company "Cactus Computer"

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#236]
---
layout: post
title: کاکتوس کامپیوتر
name_en: Cactus Computer
company_slug: Cactus Computer
logo: 
cover: 
company_count:
founded:
location: ""
total_review: 
total_interview: 
salary_avg: 
salary_min: 
salary_max: 
rate: 
view_count: 
industry: کامپیوتر، فناوری اطلاعات و اینترنت
city: تهران, تهران
size_en: VS
size: 11-50 نفر
site: https://cactus.ir
---

شركت كاكتوس كامپیوتر، با مسئولیت محدود طی شماره 100476 در تهران به ثبت رسیده است. فعالیت عملی این شركت در سال 1374 آغاز گردید. این شركت از بدو تاسیس، دارای مجوز شورای عالی انفورماتیک كشور بوده است. تولید و فروش و پشتیبانی از نرم افزارهای مالی و حسابداری و منابع انسانی و... با تکنولوژی روز دنیا و با بیش از 25 سال سابقه فعالیت در این حوزه مارا به یکی از قدیمی ترین و در حین حال به روزترین شرکت ها در زمینه نرم افزارهای حسابداری و حسابرسی تبدیل کرده است.
همچنین شرکت کاکتوس کامپیوتر جزو 10 شرکت برتر در حوزه نرم افزارهای مالی و حسابداری در ایران محسوب می شود و گواهینامه های بسیاری تاکنون کسب کرده که از جمله آن می توان به گواهی نرم افزار برتر برای سه سال متوالی از نظر اداره دارایی و درجه الف برای نسل آخر نرم افزارهای این شرکت در سال 1399 را اشاره کرد
از مشخصه های اصلی شرکت کاکتوس کامپیوتر محیطی پویا و شاد می باشد.
اگر به دنبال پیشرفت شغلی مناسب و تجربه ای متفاوت از کار در محیطی حرفه ای و جذاب هستید، به ما بپیوندید

**Comment by tajrobe** [comment]
[tajrobe.github.io/کاکتوس-کامپیوتر/](https://tajrobe.github.io/%DA%A9%D8%A7%DA%A9%D8%AA%D9%88%D8%B3-%DA%A9%D8%A7%D9%85%D9%BE%DB%8C%D9%88%D8%AA%D8%B1/)
