### ISSUE TITLE
add new company "Ilya Web"

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#237]
---
layout: post
title: ایلیا وب
name_en: Ilya Web
company_slug: Ilya Web
logo: 
cover: 
company_count:
founded:
location: ""
total_review: 
total_interview: 
salary_avg: 
salary_min: 
salary_max: 
rate: 
view_count: 
industry: کامپیوتر، فناوری اطلاعات و اینترنت
city: تهران, تهران
size_en: VS
size: 2-10 نفر
site: http://ilyaweb.com/
---

گروه نرم افزاری ایلیا در حوزه ، طراحی و برنامه نویسی سایت واپلیکیشن های موبایل ، و همچنین طراحی بازی های مولتی پلتفرم مشغول به فعالیت بوده و در این زمینه ها تمایل به همکاری با افراد صاحب نظر و متخصص میباشد..

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایلیا-وب/](https://tajrobe.github.io/%D8%A7%DB%8C%D9%84%DB%8C%D8%A7-%D9%88%D8%A8/)
