### ISSUE TITLE
add new company "Alphatik"

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#238]
---
layout: post
title: آلفاتیک
name_en: Alphatik
company_slug: Alphatik
logo: 
cover: 
company_count:
founded:
location: ""
total_review: 
total_interview: 
salary_avg: 
salary_min: 
salary_max: 
rate: 
view_count: 
industry: کامپیوتر، فناوری اطلاعات و اینترنت
city: تهران, تهران
size_en: VS
size: 11-50 نفر
site: https://alphatik.com/
---

شرکت آلفاتیک از حدود ۵ سال پیش فعالیت خودش را در فضای نرم افزاری بین المللی آغاز کرده است. این شرکت با هدف انجام پروژه های نرم افزاری وارد بازار بزرگ ترکیه شد و در این مدت موفق به انجام پروژه های دولتی و خصوصی بسیاری شده است.این شرکت دارای دو بخش اصلیست :
بخش اول Game Studio قدرتمند این شرکت است که تا الان ۲ بازی با مجموع دانلود بالای ۲ میلیون نفر تولید کرده است.
بخش دوم بخش نرم افزاری شرکت که تا الان بیش از ۴۳ پروژه نرم افزاری در ترکیه را با موفقیت انجام داده است.
این شرکت ۱ سالی است در حال فعالیت در بازارهای کشورهای انگلستان، هلند و سوییس نیز هست تا به واسطه ارتباطات خود، از این کشورها نیز پروژه بگیرد.

**Comment by tajrobe** [comment]
[tajrobe.github.io/آلفاتیک/](https://tajrobe.github.io/%D8%A2%D9%84%D9%81%D8%A7%D8%AA%DB%8C%DA%A9/)
