### ISSUE TITLE
add new company "Sureze"

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#239]
---
layout: post
title: سورز
name_en: Sureze
company_slug: Sureze
logo: 
cover: 
company_count:
founded:
location: ""
total_review: 
total_interview: 
salary_avg: 
salary_min: 
salary_max: 
rate: 
view_count: 
industry: کامپیوتر، فناوری اطلاعات و اینترنت
city: تهران, تهران
size_en: VS
size: 2-10 نفر
site: https://sureze.com/
---

شرکت Sureze شرکت فعال در حوزه برنامه های بیمارستانی واقع در مالزی میباشد. هم اکنون ما در حال اسخدام برنامه نویس از سرتاسر دنیا هستیم و به صورت ریموت تمایل به همکاری داریم. امکان صدور ویزای کاری به مالزی بعد از همکاری حداقل 6 ماهه الی 1 ساله وجود دارد.

**Comment by tajrobe** [comment]
[tajrobe.github.io/سورز/](https://tajrobe.github.io/%D8%B3%D9%88%D8%B1%D8%B2/)
