### ISSUE TITLE
سانوفی

### ISSUE THREAD

**Issue by Poor-employee** [tajrobe/tajrobe.github.io#240]
##### نام شرکت
title: ""

##### نام انگلیسی ش 
name: "Sanofi"

##### دسته‌ی فعالیت شرکت
industry: "pharma"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[فajrobe.github.io/سانوفی/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%86%D9%88%D9%81%DB%8C/)

**Comment by tajrobe** [comment]
[tajrobe.github.io/سانوفی/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%86%D9%88%D9%81%DB%8C/)
