### ISSUE TITLE
رهپویان پردازش گستر صحرا

### ISSUE THREAD

**Issue by SimaPaztarian** [tajrobe/tajrobe.github.io#243]
##### نام شرکت
title: "رهپویان پردازش گستر صحرا"

##### نام انگلیسی شرکت
name_en: "rahpooyan pardazesh gostar sahra"

##### دسته‌ی فعالیت شرکت
industry: "financial"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "50-200"

##### آدرس سایت شرکت
site: "https://www.esahra.ir/home"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by SimaPaztarian** [comment]
add new company (sahra)

**Comment by tajrobe** [comment]
[tajrobe.github.io/رهپویان-صحرا/](https://tajrobe.github.io/%D8%B1%D9%87%D9%BE%D9%88%DB%8C%D8%A7%D9%86-%D8%B5%D8%AD%D8%B1%D8%A7/)
