### ISSUE TITLE
داروسازی دانش

### ISSUE THREAD

**Issue by Hadittttttt** [tajrobe/tajrobe.github.io#244]
داروسازی دانش##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "" دارو

##### موقعیت مکانی شرکت
city: "" تهران کیلومتر ۱۳ لشگری

##### تعداد نفرات شرکت
size: "۷۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Hadittttttt** [comment]
من به مدت یک سال در بخش تحقیقات شرکت داروسازی دانش واقع در کیلومتر ۱۳ اتوبان لشگری کار کردم.
از اون زمان تا ب حال مدیریت اون بخش از مجموعه تغییر نکرده و مدیر اونجا تنها مشکل اونجا بود.
بسیار بی ادب،قدر نشناس و خود شیفته.
نمیدونم سطح دانش ایشون در چه سطحی هست اما مدیریت ایشون افتضاح هستش و هر مشکلی پیش میومد میگفت این مسائل رو نمیتوم کاری بکنم!
چه افراد با سودای اومدن و رفتن ولی این خانوم هستش و توپ هم تکونش نمیده.
بخش QC نرید که فاجعس،بخش تحقیقاتش خیلی بهتره.

**Comment by tajrobe** [comment]
[tajrobe.github.io/داروسازی-دانش/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%B1%D9%88%D8%B3%D8%A7%D8%B2%DB%8C-%D8%AF%D8%A7%D9%86%D8%B4/)
