### ISSUE TITLE
بهاوران زرین مژده 

### ISSUE THREAD

**Issue by Hadittttttt** [tajrobe/tajrobe.github.io#245]
##### نام شرکت
title: ""بهاوران زرین مژده 

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
کشاورزی
##### موقعیت مکانی شرکت
city: ""
اشتهارد
##### تعداد نفرات شرکت
size: ""۵۰

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
تولید کود و سموم کشاورزی

**Comment by Hadittttttt** [comment]
به عنوان تحصیل کرده هیچ جایگاهی در اون شرکت ندارید،چرا؟
به چند دلیل،یکیش این که صاحب شرکت خودش بی سواد هستش و با احترام زیاد به این قشر از جامعه،این فرد بی سواد درک بسیار کمی از علم و تحصیلات آکادمیک و طرز برخورد با تحصیل کرده هارو داره.
انقدر این شخص علاقه به اشخاص کم سواد داره که باورتان نمیشه مدیر کارخونه یه پسره هستش که ۱۰ ساله براش کار میکنه و مطمئنم ک دیپلم هم نداره،نه لباس درستی تنشه نه برخورد درستی داره و به شدت با نیروی تحصیل کرده لج میکنه چون ضعف داره چون از جایگاهش میترسه،اینجوری بگم که تا حالا هیچ نیروی تحصیل کرده ای بالای دو سال دووم نیاورده.
تازه این فقط یکی از مشکلاتشه.
این مدیر کارخونه برادرش رئیس تولیده که سرباز خط مقدم مدیر کارخونه که هم ن برادرش باشه هست.
تمام بزن بزنها و ضربه هارو این میزنه و برادر دیگه که مدیر باشه کارش نقشه کشیدنه.
نه قرارداد امضا میشه،نه ساعت کاری معلومه.
پسر صاحب کارخونه که منم براتون یک انسان توخالی،فقط همین.

**Comment by tajrobe** [comment]
[tajrobe.github.io/زرین-مژده/](https://tajrobe.github.io/%D8%B2%D8%B1%DB%8C%D9%86-%D9%85%DA%98%D8%AF%D9%87/)
