### ISSUE TITLE
‌بامن

### ISSUE THREAD

**Issue by marziyeh-sa** [tajrobe/tajrobe.github.io#247]
##### نام شرکت
title: ""
بامن 
##### نام انگلیسی شرکت
name_en: "" Baman

##### دسته‌ی فعالیت شرکت
industry: ""  نرم افزار

##### موقعیت مکانی شرکت
city: "" تهران

##### تعداد نفرات شرکت
size: ""
۵۰-۷۰
##### آدرس سایت شرکت
site: "" جردن

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
در حوزه کش بک و پلتفرم باشگاه مشتریان فعالیت داره

**Comment by marziyeh-sa** [comment]
شرکت بامن

**Comment by tajrobe** [comment]
[tajrobe.github.io/بامن/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%85%D9%86/)
