### ISSUE TITLE
اطلاعات شرکت آدورا طب

### ISSUE THREAD

**Issue by mrx1313** [tajrobe/tajrobe.github.io#248]
##### نام شرکت
title: "شرکت آدورا طب "

##### نام انگلیسی شرکت
name_en: "adrateb"

##### دسته‌ی فعالیت شرکت
industry: "پخش و توزیع دارو"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "بالای 500 نفر"

##### آدرس سایت شرکت
site: "https://adorateb.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نام شرکت آدوراطب از کلمه آدورا که یک واژه اصیل ایرانى و به معناى کمک رسان و یارى کننده مى باشد، گرفته شده است. شرکت آدوراطب به عنوان شرکت پخش سراسرى گروه کوبل از سال 1388 فعالیت خود را در حوزه ى فروش و توزیع محصولات دارویى، مکمل و تجهیزات پزشکی در سراسرایران آغاز کرد. آدوراطب با رعایت استانداردهاى جهانى نگهدارى و توزیع دارو به عنوان برترین شرکت پخش سراسرى خصوصى دارو، بیش از دوازده هزار داروخانه، بیمارستان و مرکز درمانى را تحت پوشش توزیع مویرگى قرار مى دهد. سبد توزیع آدوراطب، شامل محصولات وارداتى و تولیدى شرکت هاى برتر همچون کوبل دارو، داروسازى دکتر عبیدى، سانوفى، آسترازنکا، و … مى باشد."

**Comment by Aisa-Asghari** [comment]
This company already exists, New information added
tajrobe.github.io/آدوراطب/

**Comment by Aisa-Asghari** [comment]
This company already exists, New information added
[tajrobe.github.io/آدوراطب/](https://tajrobe.github.io/%D8%A2%D8%AF%D9%88%D8%B1%D8%A7%D8%B7%D8%A8/)
