### ISSUE TITLE
ثبت شرکت جدید

### ISSUE THREAD

**Issue by sarah-gh** [tajrobe/tajrobe.github.io#249]
##### نام شرکت
title: " مرداس نوین همراه ایرانیان (وکیل باشی)"

##### نام انگلیسی شرکت
name_en: "VakilBashi"

##### دسته‌ی فعالیت شرکت
industry: "وکالت و حقوقی"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "https://vakilbashi.org/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "وکیل باشی، سامانه هوشمند و الکترونیک حقوقی است که قراردادها، فرم‌ها و لوایح قضایی را به همراه آموزش‌های تصویری در اختیار افراد قرار می‌دهد که همگی توسط وکلای متخصص و پایه یک ارائه شده است. همچنین این امکان برای افراد فراهم است تا سؤالات حقوقی خود را به صورت رایگان در سامانه چراغ بپرسند و بهترین پاسخ را دریافت کنند؛ یا با بهترین وکیل در زمینه‌ی موضوع خود به صورت آنلاین مشاوره انجام دهند.
مجموعه وکیل‌باشی با تیم جوان و پویای خود تلاش می‌کند در راستای رسالت اجتماعی خود، دسترسی افراد به خدمات تخصصی حقوقی را تسهیل بخشد و مناسب‌ترین امکانات آنلاین برای حل موضوع را به آن‌ها ارائه کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/وکیل-باشی/](https://tajrobe.github.io/%D9%88%DA%A9%DB%8C%D9%84-%D8%A8%D8%A7%D8%B4%DB%8C/)
