### ISSUE TITLE
پالاز موکت

### ISSUE THREAD

**Issue by babak2316** [tajrobe/tajrobe.github.io#25]
##### نام شرکت
title: "پالاز موکت"

##### نام انگلیسی شرکت
name_en: "palaz"

##### دسته‌ی فعالیت شرکت
industry: "نساجی"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "300"

##### آدرس سایت شرکت
site: "www.palaz.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پالاز، بزرگترین تولید کننده انواع موکت تافتینگ کات و لوپ، و تنها تولید کننده سیستم کف های هیبریدی، دنیایی متفاوت از انواع پوشش های مدرن و کلاسیک فضاهای مختلف را در دسترس شما قرار می دهد."

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/پالاز-موکت/](https://tajrobe.github.io/%D9%BE%D8%A7%D9%84%D8%A7%D8%B2-%D9%85%D9%88%DA%A9%D8%AA/)
