### ISSUE TITLE
ابر فردوسی

### ISSUE THREAD

**Issue by ghalandar** [tajrobe/tajrobe.github.io#250]
##### نام شرکت
title: "ابرفردوسی"

##### نام انگلیسی شرکت
name_en: "Ferdowsi Cloud"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://Ferdowsi.cloud"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/رایانش-فردوسی/](https://tajrobe.github.io/%D8%B1%D8%A7%DB%8C%D8%A7%D9%86%D8%B4-%D9%81%D8%B1%D8%AF%D9%88%D8%B3%DB%8C/)
