### ISSUE TITLE
شرکت سیما الکترو طب

### ISSUE THREAD

**Issue by amirreza-fathi** [tajrobe/tajrobe.github.io#251]
##### نام شرکت
title: "سیما الکترو طب"

##### نام انگلیسی شرکت
name_en: "SET Eng. co."

##### دسته‌ی فعالیت شرکت
industry: "مهندسی برق و الکترونیک و نورپردازی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "کمتر از ۱۰"

##### آدرس سایت شرکت
site: "http://setamazing.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مهندسی برق و الکترونیک و نورپردازی"

**Comment by tajrobe** [comment]
[tajrobe.github.io/سیما-الکتروطب/](https://tajrobe.github.io/%D8%B3%DB%8C%D9%85%D8%A7-%D8%A7%D9%84%DA%A9%D8%AA%D8%B1%D9%88%D8%B7%D8%A8/)
