### ISSUE TITLE
شرکت تبلیغاتی بلزا

### ISSUE THREAD

**Issue by Mehrad15** [tajrobe/tajrobe.github.io#252]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Mehrad15** [comment]
یک دفتر کوچک در جنوب میدان شوش، دسترسی بسیار سخت و مشکلات رفت و آمد در کنار امنیت پایین به سبب وجود سارقین و معتادان زیاد آن منطقه
این ها البته مشکل جایی به نام بلزا نیستند، چرا به هر حال تعداد زیادی کسب و کار هم در آن منطقه فعال و زنده هستند، مشکل بلزا کسی است که به عنوان مدیر جایگاه اشغال کرده و ابدا به هیچ تخصصی در هیچ زمینه ی شغلی نداشته و صرفا به دلیل روابط با کارخانه mgs
حقوق و مزایا دریافت می کند و نمی توان تصور کرد که یک گرافیست و یا حتی طراح مبتدی بتواند با شخصیت منفی و ناسالم وی تعاملی بیش از یک یا دو ماه داشته باشد.
این فرد به قدری ناکارآمد و غیرعادیست که در شرایطی که گرافیست به سبب میزان و حجم سنگین کار، در پایان ماه توقع پاداش و تشویق را دارد، متوجه می شود درست در روزهایی که در نهایت فشارو  استرس و در زیر نظر یک فرد ناسپاس انبوهی پروژه را پیش برده و تحویل داده، این فرد همان روزها با درج آگهی بی آنکه نیروهای شرکت بدانند در تلاش برای جذب و وعده وعیده برای نیروی های جدید بوده تا قبل از ورود نیروی جدید، قبلی ها را به چنان شرایطی روحی برساند که خودشان دیگر قادر به ادامه کار نباشند و به این صورت راه برای جایگزینی باز شود.

به هر روی متاسفانه با رویه فعلی چنین کسانی همچنان مبالغ سنگین حقوق دریافت می کنند و مدیران و صاحبان برند هم از همه جا بی خبر، با اعتماد نابجا، مهر تاییدی به روش و منش غیراخلاقی و غیرحرفه ای این ها می زنند.
و شوربختانه هزینه ای هم جز درج آگهی پرداخت نمی کنند.

امیدوارم سیستم بلزا روزی به دست کسانی اداره شود که در کنار توانمندی فنی، وجدان و انسانیت هم داشته باشند.
و خاطره و کامنت های نیروی های آن مجموعه حتی در صورت عدم همکاری دوستی و مهربانی و اخلاق حرفه ای باشد

**Comment by tajrobe** [comment]
[tajrobe.github.io/بلزا/](https://tajrobe.github.io/%D8%A8%D9%84%D8%B2%D8%A7/)
