### ISSUE TITLE
hpds

### ISSUE THREAD

**Issue by mohiazaddel** [tajrobe/tajrobe.github.io#253]
description: 'من ۱ سال در شرکت مشغول بودم
مصاحبه:
- مراحل مصاحبه واقعا راحت پیش رفت برام یک جلسه صحبت بود بعد تماس سوالای پایتون و الگوریتم بود تقریبا ۴۰ ۵۰ تا هم سخت داشت هم آسون  و بعد هم یه تسک بود که واقعا مثل تسکای شرکتای دیگه وقت گیر که دو روز بزنی آخرم بدون فیدبک ولت کنن حس الاف شدن بگیری که چرا ۲ روز نشستم زدم نبود و ۳ ۴ ساعت اکی بود براش و بعد هم تو کار دیدم این مواردی که توی تسک و سوالای پایتون بودش رو واقعا نیاز داشتن

مزایا:
- بیمه تکمیلی نامحدود فقط دندون تا ۵ تومن بود(بیمه آسیا نامحدود دانشگاه شریف شامل میشد) این مورد واقعا برای من عالی بودش و همه خرج بیمارستان آزمایش و عمل هم ۸۰ درصد کم شدش
- حقوق کاملا به موقع پرداخت میشد 
- یک سری مبالغ هم یهو بهتون میدادن مثلا برای تولد کارت ۴۰۰ میداد شرکت و یا برای شب یلدا یهو ۱ تومن دادن علاوه بر پکی که تو شرکتا رایج هستش و خب یهو یه پولی که انتظار نداشتی هر چند مبلغ کم به کار میومد یا یهو گوشت میدادن
- یکی از مزیت های عالیش برای من کنار اومدن با شرایطم بود که بعد از مدتی برای پدرم مشکلی پیش اومد و دو روز نمیتونستم بیام حتی دورکاری و خب کاملا اکی شد با صحبت
- دکتر قره یاضی زمان من تیم فنی زیر نظرش بود و واقعا راحت بودم باهاش و هواتونو داره میتونین از لحاظ فنی هم برین لینکدینشون رو ببینین که اینجا توضیح اضافه نذارم(فنی)
- میشد برای استراحت بیای تو حیاط دانشگاه دور بزنی شاید کوچک باشه این مورد ولی واقعا دیگه پشت بوم هر روز برای استراحت و ارامش چشما خسته کنندست یا قهوه سازا وندور ماشین یا سلف دانشگاه استفاده کنی(واقعا مزیت نیست ولی طولانی مدت حس میکنن این رفرش در فضای سبز چقدر عالیه)
- ۸ صبحم برین صبحونه میدادن ولی برای جغدایی مثل من اینا مهم نبود فقط خواب در خد نونو مربا یا تخم مرغ 
- در هفته دو بار میوه مثلا موز سیب میدادن 
- عدم نگرانی برای جای پارک مثل شرکتای وسط شهر پارکینگ دانشگاه رو میتونین استفاده کنین ولی اگه ظرفیت پر بود بیرون تو خیابون گذاشتین حتما قفل بزنین دزد ماشین زیاده اون سمت
- نگران این که تسکا بیشتر از توانتون باشه یا بیرونتون کنن نباشین خیلی اکی بود از این جهت(دوره تست ۳ ماه بود و بعدش قرارداد یکساله)(فنی)
- یه سری امکانات دانشگاه شریفم میدادن مثل  شنا یا فوتسال یه بار در هفته در سالنای اونجا
- فنی هم خوب بود سطح ادج نبود مثلا بگم رو کوبرن یا ... ولی واقعا وقت میکردین خودتون یاد بگیرین چیزایی که میخواینو(فنی)  
-۵شنبه تعطیل بود و روزایی که دانشگاه تعطیل میشد هم تعطیل بودین
- خیلی با لینوکس و پایتون پیور درگیر خواهین شد (فنی)
- حتی بعد از جدا شدنم از تیم دعوتم کردن برای قدر دانی و ناهار در کنار تیم بودم و یه هدیه در حد ۲۰۰ ۳۰۰ تومن هم دادن(یه بخار ساز) واقعا حس خوبی بود که حتی جدا هم شدی و عملا دیگه سودی براشون نداری قدردانی کنن از تایمی که بودی 

معایب:
- ساعت حضور ۸ صبحه شناوری تا ۹.۵ بود ولی خب اگه میخواین تا ۱۱ ۱۲ بخوابین بعد برین کار خوب نیست اینجا
- امکان ریموت کار کردن نبود تا موقعی که بودم مگه در موارد خاص مثلا اعتراضات یا کرونا 
- جو قسمت اداریش خیلی دولتی طور و قدیمی بود ولی نگران اون نباشید بخش فنی کلا جوش اونجوری نبود و عالی بود و خود مسیول تیما بحثای اداری رو جلو میبردن برات
- اگر مصاحبه اکی شد و وارد شدین گروه واتس آپ ادتون میکنن کلا اونجا گروه نیست بیشتر برای اعلامیه فوتو و چیزای خسته کنندست
- وضعیت سرویسا خوب نبود و از یه زمانی آب گرم قطع شد ولی خب شرکت تا حدی که دستش بود درست کرده بود دست خشککن دستمال اینا بودش( کلا سرویسای دانشگاه قدیمین) 
- مانیتور کوچک
- روی پوشش خانم ها یه آیین نامه طور داشتن چون داخل دانشگاه بود و میگفتن اینجوری باشه ولی گیر خاصی نبود اینم و میومدن بچه ها  ولی خب اطلاع دقیقی ندارم از این چون دیدم و میخواستم همه چیو کفته باشم اینم اشاره کردم

نه مثبت نه منفی(همینطوری)
- ملاک ساعت حضور بود یعنی باید انگشت میزدی و کسری کارو اینا طبق اون بود
- یه فوتبال دستی هم داشتن البته فقط بعد از ۵ میتونین بازی کنین من راستش نه با فوستال حال میکردیم نه سیاست های ساعتی 
- سه ۴ تا تیم فنی بود و خب مثلا ما تو تیم دو تا بکند بودیم ۱ دواپس(لینوکس کارای  ci/cd  و ...) ۱ نفر فرانت ۲ تا تست
- رنج حقوق  مثل شرکتای مالی یا کافه اینا بالا نیست مثل استارت آپم نیست و سعی میکنن تو رقابت بمونن با قیمتای بازار
- وسایل بهتون یه مانیتوز میز و کیس داده میشه 

در کل میگم این یکسال من راضی بودم و کلیم چیزای جدید فنی یاد گرفتم و جای خوبیه براتون آرامش ذهنی دارین تو زندگی تون'

state: پاره وقت|تمام وقت

job_name: 'backend developer'

company_slug: 'hpds'

pros: 'بیمه تکمیلی ,صبحانه,حقوق به موقع,محیط دوستانه, '

cons: 'دریافت سفته

rate: 4.4

**Comment by tajrobe** [comment]
[/tajrobe.github.io/پردازش-و-ذخیره-سازی-سریع-داده-پرسا](https://tajrobe.github.io/%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%D8%B4-%D9%88-%D8%B0%D8%AE%DB%8C%D8%B1%D9%87-%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B3%D8%B1%DB%8C%D8%B9-%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%B3%D8%A7/#:~:text=backend%20developer%20%7C%20%D8%AA%D9%85%D8%A7%D9%85%20%D9%88%D9%82%D8%AA)
