### ISSUE TITLE
همراه کسب و کارهای هوشمند

### ISSUE THREAD

**Issue by eliassarband** [tajrobe/tajrobe.github.io#254]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/همراه-هوشمند/](https://tajrobe.github.io/%D9%87%D9%85%D8%B1%D8%A7%D9%87-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF/)
