### ISSUE TITLE
اسنپ دکتر

### ISSUE THREAD

**Issue by ypy-pasha** [tajrobe/tajrobe.github.io#255]
##### نام شرکت
title: "اسنپ دکتر"

##### نام انگلیسی شرکت
name_en: "Snapp Doctor"

##### دسته‌ی فعالیت شرکت
industry: "Service"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "30-60"

##### آدرس سایت شرکت
site: "https://snapp.doctor/contact-us/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اسنپ‌‎دکتر ارائه‎‌دهنده خدمات پزشکی آنلاین و پل ارتباطی میان کاربران با ارائه‎‌دهندگان خدمات مشاوره پزشکی و روانشناسی و همچنین خدمات پزشکی و پرستاری در منزل است. اسنپ‎‌دکتر راهکاری ساده و سریع و ۲۴ ساعته برای دسترسی به خدمات پزشکی است. با ورود به سرویس پزشک و مشاور اسنپ دکتر و مشخص کردن نیاز خود در حوزه پزشکی، روانشناسی یا نسخه‏‌ی دارو، می‌‏توانید دسترسی سریع و آسان به خدمات پزشکی و سلامت را تجربه کنید."

**Comment by tajrobe** [comment]
[tajrobe.github.io/اسنپ-دکتر/](https://tajrobe.github.io/%D8%A7%D8%B3%D9%86%D9%BE-%D8%AF%DA%A9%D8%AA%D8%B1/)
