### ISSUE TITLE
ایران فاوا گسترش

### ISSUE THREAD

**Issue by BEHROUZ6134** [tajrobe/tajrobe.github.io#256]
##### نام شرکت
title: "ایران فاوا گسترش"

##### نام انگلیسی شرکت
name_en: "Iran Fava Gostaresh"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "5 cm"

##### آدرس سایت شرکت
site: "ww.iranfava.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "SAP"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایران-فاوا/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D9%81%D8%A7%D9%88%D8%A7/)
