### ISSUE TITLE
گلدیران سنتر

### ISSUE THREAD

**Issue by ali2023dxc** [tajrobe/tajrobe.github.io#258]
فروشگاه اینترنتی گلدیران سنتر نام شرکت
title: ""

goldirancenter نام انگلیسی شرکت
name_en: "goldirancenter"

فروشگاه انلاین دسته‌ی فعالیت شرکت
industry: "online shop"

البرز موقعیت مکانی شرکت
city: "Karaj"

10 تعداد نفرات شرکت
size: "10"

www.goldirancenter.com آدرس سایت شرکت
site: "[خرید اقساطی دوو](https://goldirancenter.com/)"

فروش اینترنتی لوازم خانگی دوو و اسنوا - فروشگاه اینترنتی گلدیران سنتر توضیحی درباره شرکت و فعالیت‌هایش
content: " ... دوو اعم از تلویزیون دوو، لباسشویی دوو ، ساید بای ساید دوو ، یخچال دوو ، ظرفشویی دوو و اجاق گاز دوو بهره مند شوید. فروشگاه اینترنتی انتخاب سنتر علاوه بر فروش ...
فروش اینترنتی لوازم خانگی دوو و اسنوا - فروشگاه اینترنتی گلدیران سنتر"

**Comment by tajrobe** [comment]
[tajrobe.github.io/گلدیران-سنتر/](https://tajrobe.github.io/%DA%AF%D9%84%D8%AF%DB%8C%D8%B1%D8%A7%D9%86-%D8%B3%D9%86%D8%AA%D8%B1/)
