### ISSUE TITLE
فروشگاه اینترنتی حاجی گیم

### ISSUE THREAD

**Issue by ali2023dxc** [tajrobe/tajrobe.github.io#259]
فروشگاه اینترنتی حاجی گیم نام شرکت
title: " فروشگاه اینترنتی حاجی گیم "

hajigame نام انگلیسی شرکت
name_en: " hajigame "

فروشگاه آنلاین دسته‌ی فعالیت شرکت
industry: "shoping center"

تهران موقعیت مکانی شرکت
city: "tehran"

35 تعداد نفرات شرکت
size: "35"

www.hajigame.ir آدرس سایت شرکت
site: "[فروش ویژه انواع صندلی گیمینگ و فروش ویژه انواع میز گیمینگ](https://hajigame.ir/)"

حاجی گیم مرجعی جامع مخصوص علاقه مندان به حوزه سرگرمی و گیمینگ و ارائه دهنده انواع کنسول بازی، اکانت قانونی بازی و

 توضیحی درباره شرکت و فعالیت‌هایش
content: "حاجی گیم مرجعی جامع مخصوص علاقه مندان به حوزه سرگرمی و گیمینگ و ارائه دهنده انواع کنسول بازی، اکانت قانونی بازی و

"

**Comment by tajrobe** [comment]
[tajrobe.github.io/حاجی-گیم/](https://tajrobe.github.io/%D8%AD%D8%A7%D8%AC%DB%8C-%DA%AF%DB%8C%D9%85/)
