### ISSUE TITLE
رسمیو

### ISSUE THREAD

**Issue by masoodsh77** [tajrobe/tajrobe.github.io#26]
##### نام شرکت
title: "رسمیو"

##### نام انگلیسی شرکت
name_en: "rasmio"

##### دسته‌ی فعالیت شرکت
industry: "موتور جستجو شرکت ها"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "25"

##### آدرس سایت شرکت
site: "http://rasm.io"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by masoodsh77** [comment]
add new company

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/رسمیو/](https://tajrobe.github.io/%D8%B1%D8%B3%D9%85%DB%8C%D9%88/)
