### ISSUE TITLE
جی پلاس سنتر

### ISSUE THREAD

**Issue by ali2023dxc** [tajrobe/tajrobe.github.io#260]
فروشگاه اینترنتی جی پلاس سنتر نام شرکت
title: "gpluscenter"

gpluscenter نام انگلیسی شرکت
name_en: "gpluscenter"

فروشگاه آنلاین دسته‌ی فعالیت شرکت
industry: "online shoping"

کرج موقعیت مکانی شرکت
city: "karaj"

16 تعداد نفرات شرکت
size: "16"

www.gpluscenter.ir آدرس سایت شرکت
site: "[gpluscenter](https://gpluscenter.ir/)"
[
خرید آنلاین محصولات جی پلاس](https://gpluscenter.ir/)، لوازم خانگی، یخچال ساید بای ساید، ماشین ظرفشویی، تلویزیون، کولر، موبایل و مانیتور با گارانتی گلدیران و ارسال رایگان.
 توضیحی درباره شرکت و فعالیت‌هایش
content: "خرید آنلاین محصولات جی پلاس، لوازم خانگی، یخچال ساید بای ساید، ماشین ظرفشویی، تلویزیون، کولر، موبایل و مانیتور با گارانتی گلدیران و ارسال رایگان.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/جی-پلاس-سنتر/](https://tajrobe.github.io/%D8%AC%DB%8C-%D9%BE%D9%84%D8%A7%D8%B3-%D8%B3%D9%86%D8%AA%D8%B1/)
