### ISSUE TITLE
کلینیک جراحی زیبایی دکتر نیازی

### ISSUE THREAD

**Issue by ali2023dxc** [tajrobe/tajrobe.github.io#261]
کلینیک جراحی زیبایی دکتر نیازی نام شرکت
title: "Dr. Niazi's cosmetic surgery clinic"

Dr. Niazi's cosmetic surgery clinic نام انگلیسی شرکت
name_en: "Dr. Niazi's cosmetic surgery clinic"

کلینیک جراحی زیبایی دسته‌ی فعالیت شرکت
industry: "cosmetic surgery clinic"

تهران موقعیت مکانی شرکت
city: "Tehran"

20 تعداد نفرات شرکت
size: "20"

[cosmetic surgery clinic](https://drfniazi.com/) آدرس سایت شرکت
site: "https://drfniazi.ir/"

... فیض الله نیازی شهرکی فوق تخصص جراحی پلاستیک متخصص جراحی عمومی تهران + نوبت دهی مطب دکتر فیض الله نیازی شهرکی. ... بیمارستان. تهرانسعادت آباد - بالاتر از میدان ...
 توضیحی درباره شرکت و فعالیت‌هایش
content: "دکتر نیازی فوق تخصص جراحی زیبایی و پلاستیک بهترین جراح زیبایی لیپوساکشن لیپوماتیک پیکرتراشی جراحی سینه و ژنیکوماستی برای مردان و زنان.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/کلینیک-نیازی/](https://tajrobe.github.io/%DA%A9%D9%84%DB%8C%D9%86%DB%8C%DA%A9-%D9%86%DB%8C%D8%A7%D8%B2%DB%8C/)
