### ISSUE TITLE
بلوبانک | blu Bank

### ISSUE THREAD

**Issue by davarf** [tajrobe/tajrobe.github.io#262]
##### نام شرکت
title: "بلوبانک | blu Bank"

##### نام انگلیسی شرکت
name_en: "blubank"

##### دسته‌ی فعالیت شرکت
industry: "Banking"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "۲۰۱ تا ۵۰۰ نفر"

##### آدرس سایت شرکت
site: "https://blubank.sb24.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بلو، یک پلتفرم دیجیتال بانکی است که در روزهای پایانی سال 1398 متأثر از کرونا، آغاز به‌کار کرد، اما این بار بدون نیاز به شعب، فرم‌های کاغذی و فرآیندهای معمول و همچنین با درک بهتر نیاز مشتریان. شاید نهایت بلو را بتوان تجربه‌ی جدیدی دانست که فاقد اصطکاک‌های معمول و پیچیدگی‌های بانک‌های سنتی است و سعی کرده خود را به نیازهای نسل جوان امروزی از یک بانک نزدیک کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بلوبانک/](https://tajrobe.github.io/%D8%A8%D9%84%D9%88%D8%A8%D8%A7%D9%86%DA%A9/)
