### ISSUE TITLE
فروشگاه تجهیزات رفاهی و نظافتی جهان پاک

### ISSUE THREAD

**Issue by jahanpak1246** [tajrobe/tajrobe.github.io#263]
##### نام شرکت
title: "جهان پاک"

##### نام انگلیسی شرکت
name_en: "jahanpak"

##### دسته‌ی فعالیت شرکت
industry: "Hotel equipment and cleaning"

##### موقعیت مکانی شرکت
city: "Alborz, Karaj"

##### تعداد نفرات شرکت
size: "5"

##### آدرس سایت شرکت
site: "jahanpak.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه تجهیزات رفاهی و نظافتی جهان پاک به عنوان یکی از عرضه کنندگان مستقیم محصولات نظافتی دارای بیش از 3 دهه فعالیت در این زمینه می باشد. این مجموعه کلیه محصولات تولیدی و تامینی خود را با بهترین قیمت ها و بالاترین کیفیت به مشتریان خود تقدیم می نماید. از مهم ترین خدمات این مجموعه می توان به تضمین قیمت و تضمین کیفیت کالاها اشاره نمود. همچنین لازم به ذکر است که کلیه تجهیزات مجموعه جهان پاک دارای گارانتی معتبر شرکتی بوده و مشتریان عزیز می توانند با خیال راحت اقلام مورد نیاز خود را تهیه نمایند.
فروشگاه جهان پاک از سال 1398 به جهت رفاه حال مشتریان خود اقدام به عرضه محصولات خود به صورت آنلاین نموده است. این مجموعه در حال حاضر در استان البرز و شهر کرج مستقر بوده و کلیه محصولات خود را به سراسر کشور ارسال می نماید. همچنین مجموعه جهان پاک دارای نماد اعتماد الکترونیکی از مرکز توسعه تجارت الکترونیکی وزارت صنعت، معدن و تجارت می باشد. شما عزیزان در فروشگاه مجموعه براحتی می توانید انواع تجهیزات نظافتی و رفاهی هتلی، بیمارستانی، اداری، تجاری و ... را با بهترین قیمت ها تهیه نمایید. همچنین کلیه تجهیزات نظافتی ساختمانی و صنعتی نیز در فروشگاه مجموعه موجود است.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/جهان-پاک/](https://tajrobe.github.io/%D8%AC%D9%87%D8%A7%D9%86-%D9%BE%D8%A7%DA%A9/)
