### ISSUE TITLE
شرکت پیشگام دامپرور سپاهان

### ISSUE THREAD

**Issue by Ayande123** [tajrobe/tajrobe.github.io#264]
من تو این شرکت متوجه شدم که حقوقت رو دور از جون مثل سگ میندازن جلوت ، یجور با التماس باید یه قرون یه قرون ازشون بگیری، اصلا کار و زحمتت برای مدیر عامل ارزشمند نیست، اگر آدم فهمیده ای باشی اخراج میشی، مشکل این شرکت مدیران میانی نیستند خود مدیر عامل هست اون باید عوض بشه وگرنه هیچ وقت پیشرفت نمیکنه، برادر و زن برادر مدیر عامل جلو پیشرفت شرکت رو میگیرن و نمیزارن بقیه دست و پا باز کنند.

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'نام شرکت'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیشگام-دامپرور/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%DA%AF%D8%A7%D9%85-%D8%AF%D8%A7%D9%85%D9%BE%D8%B1%D9%88%D8%B1/)
