### ISSUE TITLE
خدمات انفورماتیک نوین کیش

### ISSUE THREAD

**Issue by f95fatehi** [tajrobe/tajrobe.github.io#265]
##### نام شرکت
title: "خدمات انفورماتیک نوین کیش"

##### نام انگلیسی شرکت
name_en: "Modern ISC"

##### دسته‌ی فعالیت شرکت
industry: "پرداخت بانکی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "150"

##### آدرس سایت شرکت
site: "www.modernisc.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت خدمات انفورماتیک نوین کیش به صورت شرکت سهامی خاص در ششم شهریورماه ۱۳۹۰ تحت شماره ۹۴۳۴ در اداره ثبت شرکت‌ها و مالکیت‌های صنعتی در منطقه آزاد کیش به ثبت رسید و به استناد صورتجلسه هیأت مدیره مورخ ۲۱ آبان ۱۳۹۰ شعبه شرکت در تهران تاسیس شد و مرکز اصلی آن در کیش واقع است. در حال حاضر این شرکت جزو واحدهای تجاری شرکت خدمات انفورماتیک (سهامی عام) بوده و واحد نهایی گروه نیز شرکت ملی انفورماتیک است.

نتیجه تلاش‌های کارشناسان این شرکت در نخستین سال فعالیت به تولید اولین سیستم هسته‌ای بانکی تکمیل شده با فناوری بومی در ایران با نام نرم‌افزار جامع بانکی (ABIS ـ Advanced Banking Integrated Services) منجر و با موفقیت در چندین نهاد مالی پیاده‌‎سازی و عملیاتی شد. این محصول سرآغاز حرکت رو به رشد شرکت خدمات انفورماتیک نوین کیش بود به طوری که در سال‌های بعد محصولات و خدمات متنوع دیگری به شبکه بانکی کشور ارائه کرد.

موضوع فعالیت شرکت

موضوع فعالیت شرکت بر اساس ماده ۲ اساسنامه عبارت است از ارائه خدمات کامپیوتری، مکانیزاسیون، مطالعه، تحلیل، طراحی، ساخت و پیاده‌سازی سامانه‌های نرم‌افزاری و سخت‌افزاری، طراحی و تولید و ارائه و پشتیبانی نرم‌افزارهای رایانه‌ای اعم از سفارش مشتری و بسته‌های نرم‌افزاری، فعالیت در زمینه سیستم‌های ویژه رایانه‌ای نظیر اتوماسیون صنعتی و کارت‌های هوشمند و مشاوره و نظارت بر اجرای پروژه‌های انفورماتیکی، فعالیت در زمینه شبکه‌های رایانه‌ای و امنیت شبکه، انجام خدمات مشاوره و آموزش در زمینه‌های فناوری اطلاعات، پژوهش، مشاوره و انتقال تکنولوژی و نصب و راه‌اندازی و تعمیر و نگهداری و تولید و ساخت و پشتیبانی در زمینه تجهیزات رایانه‌ای، ارائه خدمات در زمینه تجارت الکترونیک، بانکداری الکترونیک و اتوماسیون سیستم بانکی، انعقاد قرارداد با اشخاص حقیقی و حقوقی و شرکت در مناقصه‌ها و مزایده‌های دولتی و خصوصی در زمینه موضوع فعالیت شرکت و سرمایه‌گذاری در زمینه موضوع فعالیت شرکت در سایر شرکت‌ها از طریق تأسیس یا خرید و تعهد سهام شرکت‌های جدید و یا شرکت‌های موجود، واردات و صادرات انواع کالاهای مرتبط با صنعت بانکی و امور فن‌آوری و اطلاعات و ارتباطات و خرید و فروش انواع کالاها و خدمات در زمینه موضوع فعالیت شرکت و به طور کلی انجام کلیه امور مجاز اقتصادی و بازرگانی در زمینه موضوع فعالیت شرکت.

چشم انداز

ارائه‌کننده ‌ممتاز خدمات نوین بانکی مبتنی بر فناوری ‌اطلاعات، با استفاده از برترین فناوری‌های تثبیت‌شده بر اساس یک معماری اطلاعاتی پیشرفته، امن، قابل اطمینان و منعطف، قابل استفاده برای کلیه ذی‌نفعان با تأکید بر مشتریان، با حداکثر چالاکی و متشکل از نیروی انسانی مدبّر، باتجربه و کارآمد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/خدمات-انفورماتیک-نوین-کیش/](https://tajrobe.github.io/%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D8%A7%D9%86%D9%81%D9%88%D8%B1%D9%85%D8%A7%D8%AA%DB%8C%DA%A9-%D9%86%D9%88%DB%8C%D9%86-%DA%A9%DB%8C%D8%B4/)
