### ISSUE TITLE
شبکه گستران آریا سامانه

### ISSUE THREAD

**Issue by mahdikhodaparastyazdi** [tajrobe/tajrobe.github.io#269]
##### نام شرکت
title: "شبکه گستران آریا سامانه"

##### نام انگلیسی شرکت
name_en: "navatel
![80a3389b-4f44-49cc-ba33-b19beecdf255](https://github.com/tajrobe/tajrobe.github.io/assets/107419479/a9b2c672-2679-436d-ac69-02aff71d6f80)
, "

##### دسته‌ی فعالیت شرکت
industry: " فناوری اطلاعات / نرم افزار و سخت افزار
اینترنت / تجارت الکترونیک / خدمات آنلاین
تلکام "

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "۵۰ تا ۱۰۰ نفر"

##### آدرس سایت شرکت
site: "تقاطع طالقانی و شریعتی ساختمان نواتل"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "
![80a3389b-4f44-49cc-ba33-b19beecdf255](https://github.com/tajrobe/tajrobe.github.io/assets/107419479/255eac1f-c29e-45bf-a3cf-be49449ff96e)
درباره شرکت مهندسی شبکه گستران آریاسامانه - نواتل
[navatel.ir](https://navatel.ir/)
شرکت دانش بنیان " شبکه گستران آریا سامانه " از پیشگامان ارائه ی خدمات ارتباطی و تلفن اینترنتی ویپ (VoIP) در ایران است که از سال 1380 فعالیت خود را با تمرکز بر ارائه ی خدمات اینترنت و تلفن بین الملل آغاز نمود. این شرکت در سال 1393 با توجه به توانمندیهای فنی و اجرایی خود و نیاز بازار، سوپر اپلیکیشن مالتی پلتفرم "شبکه هوشمند نوا" را در دستور کار خود قرار داد و از سال 1397 مطالعه و توسعه نخستین سرویس ارتباط یکپارچه ابری برای کسب و کارها (UCaaS) را با برند "نواتل" در ایران آغاز نمود. این سرویس در دیماه سال 1399 به عنوان تنها بازیگر حوزه UCaaS وارد بازار گردید و مورد استقبال کسب و کارها قرار گرفت.   "

**Comment by tajrobe** [comment]
[tajrobe.github.io/آریاسامانه/](https://tajrobe.github.io/%D8%A2%D8%B1%DB%8C%D8%A7%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87/)
