### ISSUE TITLE
Missin dev files

### ISSUE THREAD

**Issue by hatamiarash7** [tajrobe/tajrobe.github.io#27]
As I mentioned [here](https://github.com/tajrobe/tajrobe.github.io/issues/8), We should have `Gemfile` in the repository. The old `.gitignore` file was fixed by [this](https://github.com/tajrobe/tajrobe.github.io/commit/fa12eec7905740dc08a13cb7396e66e1196442b2) commit but these files are still not available.  
Can you add & push them again?

**Comment by tajrobe** [comment]
سلام.
همانطور که در توضیحات [قبلی](https://github.com/tajrobe/tajrobe.github.io/issues/8#issuecomment-983320189) نوشتیم، این پروژه [گیتهاب‌پیج ](https://pages.github.com/)هست که بدون وجود `Gemfile` در ریپو همین الان داره کار می‌کنه و بیلد می‌شه. فقط اسم پلاگین‌های `Gem` در فایل [_config.yml](https://raw.githubusercontent.com/tajrobe/tajrobe.github.io/master/_config.yml) آورده شده که هنگام build، اونها دانلود میشن، چیزی مثل دانلود فایل‌های jar در بیلد پروژه‌ی جاوا، یا دانلود ماژولnode در حین پروژه‌های جاوااسکریپتی. برای build این پروژه نیازی به `Gemfile` نیست.
