### ISSUE TITLE
منشورسیمین

### ISSUE THREAD

**Issue by nouri1360** [tajrobe/tajrobe.github.io#271]
description: 'جهنم رو در این دنیا تجربه می کنید'

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'همه نوع کار رو باید انجام بدی'

company_slug: 'منشورسیمین'

pros: 'کسب تجربه برای زندگی در جهنم,چطور یاد بگیریم زیراب بزنیم,کسب تجربه در زمینه کلاهبرداری'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by nouri1360** [comment]
جهنم رو در این دنیا تجربه می کنید

محیط پرحاشیه و پر تنش ، همه نوع کار رو باید یک نفر انجام بدی از باربری گرفته تا برنامه نویسی ،از یک نفر به اندازه 5 نفر کار کشیده میشه،حق نداری سرت رو بجنبانی فقط و فقط کار،اخراج در کسری از ثانیه در صورت مشاهده نگاه در گوشی،محیط سمی

مزایا: کسب تجربه برای زندگی در جهنم,چطور یاد بگیریم زیراب بزنیم,کسب تجربه در زمینه کلاهبرداری

**Comment by tajrobe** [comment]
@nouri1360 
لطفا تجربه‌ی خود را در صفحه شرکت مربوطه بنویسید.

[tajrobe.github.io/منشور-سیمین/](https://tajrobe.github.io/%D9%85%D9%86%D8%B4%D9%88%D8%B1-%D8%B3%DB%8C%D9%85%DB%8C%D9%86/)
