### ISSUE TITLE
منشور سیمین

### ISSUE THREAD

**Issue by nouri1360** [tajrobe/tajrobe.github.io#272]
##### نام شرکت
title: "منشور سیمین"

##### نام انگلیسی شرکت
name_en: "manshooreSimin"

##### دسته‌ی فعالیت شرکت
industry: "بردهای الکترونیکی بی کیفیت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "dedj.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تولید و مونتاژ بردهای بی کیفیت الکترونیکی و قفل های نو ودست دوم سخت افزاری"

**Comment by tajrobe** [comment]
[tajrobe.github.io/منشور-سیمین/](https://tajrobe.github.io/%D9%85%D9%86%D8%B4%D9%88%D8%B1-%D8%B3%DB%8C%D9%85%DB%8C%D9%86/)
