### ISSUE TITLE
قاصدک سامانه

### ISSUE THREAD

**Issue by M-aghashiri** [tajrobe/tajrobe.github.io#273]
##### نام شرکت
title: "قاصدک سامانه"

##### نام انگلیسی شرکت
name_en: "ghasedak"

##### دسته‌ی فعالیت شرکت
industry: "Telecom"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "10-15"

##### آدرس سایت شرکت
site: "ghasedak.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت قاصدک سامانه، در سال ۱۳۷۸ توسط جمعی از مهندسین کارآزموده، باتجربه و جوان تاسیس گردیده و از ابتدای تاسیس بعنوان یکی از پیشگامان عرصه‏ ی فناوری اطلاعات IT در ایران مطرح بوده ‏است. این شرکت با بهره‏ گیری از گروهی از متخصصین مجرب توانسته‏ است طی سالهای گذشته ‏ارائه کننده ‏ی ایده‏هایی نوین و بدیع در صنعت IT کشور باشد.
قاصدک یکی از اعضای فعال سازمان نظام صنفی رایانه ای کشور و انجمن انفورماتیک بوده و دارای تائیدیه شورای عالی انفورماتیک کشور و نیز مجوز تاسیس واحد فنی و مهندسی از وزارت صنایع و معادن می‏باشد که هم‏ اکنون بعنوان یکی از پیمانکاران بسیاری از سازمان‏های مشهور دولتی و خصوصی شناخته می‏شود. قاصدک همچنین عضو انجمن صنفی سرویس دهندگان اینترنت و دارای مجوز ISP از سازمان تنظیم مقررات و ارتباطات رادیوئی می‏باشد.
شرکت قاصدک سامانه با هدف گام برداشتن در مرزهای فناوری اطلاعات تاسیس شده ‏است و از آخرین ابزارها و فناوری ‏ها، در جهت اجرای پروژه ‏هـای IT استفاده می‏کند.  "

**Comment by tajrobe** [comment]
[tajrobe.github.io/قاصدک-سامانه/](https://tajrobe.github.io/%D9%82%D8%A7%D8%B5%D8%AF%DA%A9-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87/)
