### ISSUE TITLE
اوژن مشرق پارس - OMPFinex

### ISSUE THREAD

**Issue by MR-Mostafa** [tajrobe/tajrobe.github.io#275]
##### نام شرکت
title: "اوژن مشرق پارس - OMPFinex"

##### نام انگلیسی شرکت
name_en: "OMPFinex"

##### دسته‌ی فعالیت شرکت
industry: "ارز دیجیتال و بلاک‌چین"

##### موقعیت مکانی شرکت
city: "مشهد و تهران"

##### تعداد نفرات شرکت
size: "51-200"

##### آدرس سایت شرکت
site: "https://www.ompfinex.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "صرافی دانش بنیان OMPFinex اولین پلتفرم آنلاین معاملات ارزهای دیجیتال با قابلیت ربات معامله‌گر در ایران است که به پشتوانه تیم جوان، خلاق و حرفه‌ای خود توانسته ضمن فراهم کردن حداکثر امنیت، محصولی کم‌نظیر و هم تراز با صرافی‌های جهانی به همراه ابزارهای معاملاتی نوین برای معامله‌گران ایرانی فراهم کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/اوژن-مشرق-پارس/](https://tajrobe.github.io/%D8%A7%D9%88%DA%98%D9%86-%D9%85%D8%B4%D8%B1%D9%82-%D9%BE%D8%A7%D8%B1%D8%B3/)
