### ISSUE TITLE
موسسه پژوهش نوین رایانه

### ISSUE THREAD

**Issue by Asghar13r** [tajrobe/tajrobe.github.io#277]
##### نام شرکت
title: "موسسه پژوهش نوین رایانه"

##### نام انگلیسی شرکت
name_en: "pnr"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار و شبکه الکترونیک"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۳۰"

##### آدرس سایت شرکت
site: "pnr.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "امریه الکترونیک و نرم افزار"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پژوهش-نوین-رایانه/](https://tajrobe.github.io/%D9%BE%DA%98%D9%88%D9%87%D8%B4-%D9%86%D9%88%DB%8C%D9%86-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86%D9%87/)
