### ISSUE TITLE
شرکت جدید

### ISSUE THREAD

**Issue by gombeh** [tajrobe/tajrobe.github.io#278]
##### نام شرکت
title: "فناوری و مدیریت روز ایرانیان"

##### نام انگلیسی شرکت
name_en: "imtmc"

##### دسته‌ی فعالیت شرکت
industry: "طراحی سایت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "11 تا 50"

##### آدرس سایت شرکت
site: "https://imtmc.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فناوری و مدیریت روز ایرانیان در سال 1387 به هدف انجام خدمات تخصصی فعالیت‌های طراحی و مهندسی، مطالعات اقتصادی و اجتماعی و مدیریتی، مدیریت پروژه، مشاوره و نظارت فنی در بخش‌های مختلف اقتصادی کشور تشکیل شد.
این شرکت دانش بنیان در طی سالها فعالیت در زمینه اینترنت اشیا و طراحی پلتفرم های اختصاصی موفق شده است تیمی از برنامه نویسان جوان و موفق را گرد هم جمع کند تا از سینرژی این تیم ایده های کسب و کارهای نوین را پیاده سازی کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فناوری-روز-ایرانیان/](https://tajrobe.github.io/%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%B1%D9%88%D8%B2-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%DB%8C%D8%A7%D9%86/)
