### ISSUE TITLE
اسمارتک

### ISSUE THREAD

**Issue by 1mehdifaraji** [tajrobe/tajrobe.github.io#279]
##### نام شرکت
title: "اسمارتک"

##### نام انگلیسی شرکت
name_en: "Smartech"

##### دسته‌ی فعالیت شرکت
industry: "Software"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "1000"

##### آدرس سایت شرکت
site: "https://smartech.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اسمارتک (Smartech) در واپسین روزهای سال ۱۳۹۶ و از یک تیم کوچک، پرانگیزه، توانمند و باتجربه شروع شد. چیزی که آن‌ها را گرد هم آورد، کلیدواژه‌های تیم، مقیاس‌پذیری و نرم‌افزار بود.
تیم کوچک اسمارتک در زمینه‌ی مارکتینگ تکنولوژی (مارتک) پس از سعی‌وخطاهای مرسوم شرکت‌های نوپا، به ساخت محصول مارکتینگ اتومیشن روی آورد. این محصول که با نام اینترک (inTrack) به بازار عرضه شد توانست پابه‌پای رقبای نام‌آشنای بین‌المللی‌اش از بازار سهم بگیرد.
تقریباً هم‌زمان با انتشار اینترک در سال ۱۴۰۰ و تثبیت جایگاه آن نزد اولین مشتریان شرکت، اسمارتک تصمیم گرفت سبد محصولاتش در زمینه‌ی مارتک را تکمیل کند.
اسمارتک از اواسط سال ۱۴۰۰ سه تیم اَدوِرج (AdVerge)، اَفیلیو (Affilio) و دیپین ('deepin)، که به ترتیب شبکه‌ی تبلیغات دیجیتال (Digital Ad-Network)، سیستم همکاری در فروش (Affiliate Management System) و پلتفرم داده مشتریان (Customer Data Platform) هستند را تشکیل داد.
اسمارتک هم‌جهت با استراتژی‌های اولیه‌اش تصمیم گرفت یک پلتفرم موبایل اتریبیوشن را بسازد یا بخرد. اوایل سال ۱۴۰۱، اسمارتک ادتریس را خرید و با سایر محصولاتش ادغام کرد. این خرید و ادغام زنجیره‌ی ارزش اسمارتک را تقریباً کامل و توانمندی اسمارتک را در خلق ارزش برای مشتریانش بیشتر کرد.
اسمارتکِ ۱۴۰۲ به تبع کلان‌روندهای کشور و با درک نیاز مشتریانش درصدد است تا با ایجاد تمرکز و افزایش کارآمدی، محصولات پنج‌گانه‌اش را در قالب دو سرویس Adtech Solutions شامل ادورج و افیلیو و Martech Solutions شامل ادتریس، اینترک و دیپین عرضه کند. برای مشتریان، این به معنای دریافت خدمات بهتر با هزینه‌‌ای ارزنده‌ و بار فنی کمتر سمت مشتری خواهد بود."

**Comment by tajrobe** [comment]
[tajrobe.github.io/اسمارتک/](https://tajrobe.github.io/%D8%A7%D8%B3%D9%85%D8%A7%D8%B1%D8%AA%DA%A9/)
