### ISSUE TITLE
Ainfluencer

### ISSUE THREAD

**Issue by MajidNajafi** [tajrobe/tajrobe.github.io#280]
##### نام شرکت
title: "ای اینفلوئنسر"

##### نام انگلیسی شرکت
name_en: "Ainfluencer"

##### دسته‌ی فعالیت شرکت
industry: "Business"

##### موقعیت مکانی شرکت
city: "Ontario, Canada"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://ainfluencer.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پلتفرمی برای اتصال برندها با اینفلوئنسرها"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ای-اینفلوئنسر/](https://tajrobe.github.io/%D8%A7%DB%8C-%D8%A7%DB%8C%D9%86%D9%81%D9%84%D9%88%D8%A6%D9%86%D8%B3%D8%B1/)
