### ISSUE TITLE
ثبت شرکت جدید

### ISSUE THREAD

**Issue by MostafaSaadatnia** [tajrobe/tajrobe.github.io#281]
##### نام شرکت
title: "پایا زینو کیش"

##### نام انگلیسی شرکت
name_en: "Zino Kish"

##### دسته‌ی فعالیت شرکت
industry: "Software"

##### موقعیت مکانی شرکت
city: "Kish Island"

##### تعداد نفرات شرکت
size: "0-50"

##### آدرس سایت شرکت
site: "https://zinotech.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پس از دو سال تحقیق و بررسی علمی و میدانی، در سال 1398 شرکت زینو به پشتوانه نیروهای توانمند و حرفه ای خود در جزیره زیبای کیش به صورت رسمی فعالیت خود را آغاز کرد و در همین مدت کوتاه با پشتکار و بهره گرفتن از فکر و تلاش ایرانی ، مسیر سخت و دشواری را پشت سر گذاشته و به مجموعه ای پویا و معتمد در بازار فناوری اطلاعات ایران تبدیل شده است. زینو با شعار "بیایید کاری کنیم که همه برنده باشیم" مسیری متفاوت را آغاز کرده و در هر گام آن تفکر همراهی جمعی و استفاده از ظرفیت های تیمی را سر لوحه برنامه ریزی های خود قرارداده است. کیفیت و ارائه محصول رقابتی در زینو یک عادت بوده و هست. راه اندازی استودیو بسیار مجهز زینو آرت و همین طور افزودن بخش های تحقیق و توسعه به شرکت، هدفی آینده نگرانه و برنامه ریزی شده برای رقابت در بیرون از مرزهای ایران را ایجاد کرده است. از دیگر فعالیت های زینو سرمایه"

**Comment by MostafaSaadatnia** [comment]
افزودن شرکت جدید

**Comment by tajrobe** [comment]
[tajrobe.github.io/پایا-زینو-کیش/](https://tajrobe.github.io/%D9%BE%D8%A7%DB%8C%D8%A7-%D8%B2%DB%8C%D9%86%D9%88-%DA%A9%DB%8C%D8%B4/)
