### ISSUE TITLE
او ام پی فینکس

### ISSUE THREAD

**Issue by MostafaSaadatnia** [tajrobe/tajrobe.github.io#282]
##### نام شرکت
title: "اوژن مشرق پارس"

##### نام انگلیسی شرکت
name_en: "OMP Finex"

##### دسته‌ی فعالیت شرکت
industry: "exchange"

##### موقعیت مکانی شرکت
city: "Tehran - Mashhad"

##### تعداد نفرات شرکت
size: "51-200"

##### آدرس سایت شرکت
site: "https://www.ompfinex.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "صرافی دانش بنیان OMPFinex اولین پلتفرم آنلاین معاملات ارزهای دیجیتال با قابلیت ربات معامله‌گر در ایران است که به پشتوانه تیم جوان، خلاق و حرفه‌ای خود توانسته ضمن فراهم کردن حداکثر امنیت، محصولی کم‌نظیر و هم تراز با صرافی‌های جهانی به همراه ابزارهای معاملاتی نوین برای معامله‌گران ایرانی فراهم کند.

اوام‌پی‌فینکس به صورت رسمی از سال 1399 بنیان‌گذاری شده و این خانواده هم اکنون از بیش از 300 نفر متخصص در زمینه بلاک‌چین، برنامه‌نویسی، معامله‌گری، دیجیتال مارکتینگ و پشتیبانی تشکیل شده‌است.
آینده را با ما مبادله کنید..."

**Comment by tajrobe** [comment]
already exists: [tajrobe.github.io/اوژن-مشرق-پارس/](https://tajrobe.github.io/%D8%A7%D9%88%DA%98%D9%86-%D9%85%D8%B4%D8%B1%D9%82-%D9%BE%D8%A7%D8%B1%D8%B3/)
