### ISSUE TITLE
گسترش فناوری های نوین

### ISSUE THREAD

**Issue by saphir100** [tajrobe/tajrobe.github.io#286]
#####  گسترش فناوری های نوین
title: "گسترش فناوری های نوین"

##### Novin High Tech Solution
name_en: "Novin High Tech Solution"

##### بانکی
industry: "Banking"

##### آرش مهر ، جلال، تهران
city: "Tehran"

##### 200
size: "200"

##### http://www.htsc.ir/
site: "http://www.htsc.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by saphir100** [comment]
با سلام به همه دوستان

**Comment by tajrobe** [comment]
[tajrobe.github.io/گسترش-فناوری-نوین/](https://tajrobe.github.io/%DA%AF%D8%B3%D8%AA%D8%B1%D8%B4-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D9%86%D9%88%DB%8C%D9%86/)
