### ISSUE TITLE
هر چه در وصف تو گویم به خدا باز کم است

### ISSUE THREAD

**Issue by alihajiloo** [tajrobe/tajrobe.github.io#287]
##### نام شرکت
title: "سورپرازین"

##### نام انگلیسی شرکت
name_en: "surprisin"

##### دسته‌ی فعالیت شرکت
industry: "توسعه تجارت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "15"

##### آدرس سایت شرکت
site: "surprisin.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اینجا ما یه فروشگاه اینترنتی توسعه دادیم که مشابه مالتینا و ایگرد هست. فضای شرکت خیلی دوستانه و حرفه ای هست. من اینجا معنای واقعی کار تیمی رو فهمیدم. از تکنولوژی های روز دنیا برای توسعه نرم افزار استفاده شده. و بنظرم مهمترین مزیت این شرکت قدردان بودن از کارمندان هست که من خودم به شخصه تو شرکت های ایرانی نظیرشو ندیدم. حقوق هامون همیشه سر ماه و به موقع پرداخت میشه. صبحانه و ناهار داریم. آشپز داریم تو شرکت که همیشه غذا های خوشمزه درست میکنه. و همچنین یکی از مزیت های اینجا آرامش کاری هست که واقعا تو شهری مثل تهران که پر از تنش و استرس هست اینجا نقطه امن منه. مدیران شرکت چینی هستند و درک درستی از بیزنس دارند و به هیچ وجه خواسته های غیر واقعی ندارن. بابت کار هایی هم که وظیفم نیست و انجام میدم پاداش دریافت میکنم و خیلی قدر دان هستند. تنبیه اینجا جایگاهی نداره همیشه برای کوچک ترین کار ها پاداش داریم.

خلاصه بعد از ۱۰ سال تجربه کاری میتونم به جرأت بگم بهترین شرکتی هست از کار کردن توش لذت میبرم و هر روز صبح با فشار و کتک از خواب بیدار نمیشم و هر روز ذوق سرکار رفتن دارم. به قول یکی از همکارام اینجا کار کنی دیگه نمیتونی بری یه شرکت دیگه.

بحث آینده شغلی هم که برای هر کارمندی مهمه اینجا خیلی قابل لمسه. بیشتر بخوام بگم هر روز اینجا چیزای جدید یاد میگیری و مجبور نیستی فقط تسک هاتو انجام بدی و بری (روتین روزانه وجود نداره) و بعد از بیرون اومد از هر چالشی به خودت افتخار میکنی و حس اینکه یه شخص قدر شناس داره از نتیجه زحماتت بهره میبره و قدردان تلاش هات هست واقعا حس خوبیه که تو شرکت های ایرانی که همیشه درحال سرکوب شدن هستی نمیتونی هیچ وقت بفهمی چه مزه ای داره. امیدوارم برای هر کسی که دنبال پیشرفت و موفقیت هست این فرصت پیش بیاد با تیم خوب سورپرازین همکاری کنه. "

**Comment by tajrobe** [comment]
[tajrobe.github.io/سورپرازین/](https://tajrobe.github.io/%D8%B3%D9%88%D8%B1%D9%BE%D8%B1%D8%A7%D8%B2%DB%8C%D9%86/)
