### ISSUE TITLE
آترین فناوران

### ISSUE THREAD

**Issue by msbsoft2** [tajrobe/tajrobe.github.io#288]
##### نام شرکت
title: "آترین فناوران زنده رود"

##### نام انگلیسی شرکت
name_en: "atrin co"

##### دسته‌ی فعالیت شرکت
industry: "programming"

##### موقعیت مکانی شرکت
city: "اصفهان"

##### تعداد نفرات شرکت
size: "4"

##### آدرس سایت شرکت
site: "اصفهان - ارگ جهان نما - طبقه 3"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "انجام پروژه های شرکت با پایین ترین کیفیت بدون ضمانت و با شعار انجام پروژه با فریم ورک و در اصل انجام با وردپرس"

**Comment by msbsoft2** [comment]
تجربه همکاری من با آترین فناوران با مدیریت صادقی

**Comment by tajrobe** [comment]
[tajrobe.github.io/آترین-فناوران/](https://tajrobe.github.io/%D8%A2%D8%AA%D8%B1%DB%8C%D9%86-%D9%81%D9%86%D8%A7%D9%88%D8%B1%D8%A7%D9%86/)
