### ISSUE TITLE
تسهیل گستر

### ISSUE THREAD

**Issue by info4saeed** [tajrobe/tajrobe.github.io#289]
##### نام شرکت
title: "تسهیل گستر"

##### نام انگلیسی شرکت
name_en: "Tas'hil Gostar"

##### دسته‌ی فعالیت شرکت
industry: "توسعه نرم افزار"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "۲۰"

##### آدرس سایت شرکت
site: "https://www.tashilgostar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "کسب و کار الکترونیکی جامع و یکپارچه متناسب با نیاز شما را ایجاد می‌کنند و با پشتیبانی و ارائه خدمات مورد نیاز، در مسیر درست الکترونیکی شدن کسب و کارتان، همراهی‌تان می‌کنند"

**Comment by info4saeed** [comment]
ثبت عنوان شرکت حدید

**Comment by tajrobe** [comment]
[tajrobe.github.io/تسهیل-گستر](https://tajrobe.github.io/%D8%AA%D8%B3%D9%87%DB%8C%D9%84-%DA%AF%D8%B3%D8%AA%D8%B1/)

**Comment by info4saeed** [comment]
لطفاً اسم این شرکت اضافه گردد
