### ISSUE TITLE
هیواوب

### ISSUE THREAD

**Issue by saeid-teroda-2020** [tajrobe/tajrobe.github.io#29]
##### نام شرکت
title: "هیواوب"

##### نام انگلیسی شرکت
name_en: "HiwaWeb"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "آذربایجان غربی، ارومیه"

##### تعداد نفرات شرکت
size: "۳-۸ نفر"

##### آدرس سایت شرکت
site: "http://hiwaweb.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "آژانس دیجیتال مارکتینگ هیوا وب با تجربه 12 ساله در زمینه طراحی سایت، اپلیکیشن موبایل، نرم افزار های سفارشی، سئو و بهینه سازی، بازاریابی اینترنتی و همچنین برگزاری دوره های آموزش برنامه نویسی ویژه بازار کار در خدمت عموم هموطنان گرامی می باشد ."

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/هیوا-وب/](https://tajrobe.github.io/%D9%87%DB%8C%D9%88%D8%A7-%D9%88%D8%A8/)
