### ISSUE TITLE
ترندیول

### ISSUE THREAD

**Issue by aminkaragoz** [tajrobe/tajrobe.github.io#290]
##### نام شرکت
title: "ترندیول"

##### نام انگلیسی شرکت
name_en: "trendyolshop"

##### دسته‌ی فعالیت شرکت
industry: "پوشاک"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "25"

##### آدرس سایت شرکت
site: "https://trendyolshop.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت ترندیول در زمینه پوشاک و لباس، لوازم آرایشی و بهداشتی فعالیت دارد. بازاریابی شرکت ترندیول مبتنی بر با پوشاک به روز و با کیفیت ایرانیان بوده‌ است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فروشگاه-ترندیول/](https://tajrobe.github.io/%D9%81%D8%B1%D9%88%D8%B4%DA%AF%D8%A7%D9%87-%D8%AA%D8%B1%D9%86%D8%AF%DB%8C%D9%88%D9%84/)
