### ISSUE TITLE
زانیس xaniis

### ISSUE THREAD

**Issue by blue4blue** [tajrobe/tajrobe.github.io#291]
##### نام شرکت
title: "زانیس"

##### نام انگلیسی شرکت
name_en: "xaniis"

##### دسته‌ی فعالیت شرکت
industry: "بازار سرمایه"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "25"

##### آدرس سایت شرکت
site: "https://www.xaniis.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت زانیس فعال در تولید نرم افزار های بازار سرمایه به مدیریت احمد زندی از سال ۱۳۹۹ فعالیت خود را شروع کرده و دارای محصولات سامانه معاملاتی آنلاین و بک آفیس میباشد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/زانیس/](https://tajrobe.github.io/%D8%B2%D8%A7%D9%86%DB%8C%D8%B3/)
