### ISSUE TITLE
هیکو

### ISSUE THREAD

**Issue by hmahmoudi3025** [tajrobe/tajrobe.github.io#292]
##### نام شرکت
title: "هیکو"

##### نام انگلیسی شرکت
name_en: "Hico"

##### دسته‌ی فعالیت شرکت
industry: "تولید نرم افزارهای مدیریت پسماند"

##### موقعیت مکانی شرکت
city: "قم"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://www.hico.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "این شرکت در راستای تولید نرم افزارهای مدیریت پسماندهای شهری و پسماندهای پالایشگاه هایی فعالیت می کند"

**Comment by tajrobe** [comment]
[tajrobe.github.io/هیکو/](https://tajrobe.github.io/%D9%87%DB%8C%DA%A9%D9%88/)
