### ISSUE TITLE
پویش اکس. فناوری اطلاعات بانک رسالت

### ISSUE THREAD

**Issue by Mani-rahimi1921** [tajrobe/tajrobe.github.io#293]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Mani-rahimi1921** [comment]
https://fapa-co.ir/Home
شرکت فناوری اطلاعات و ارتباطت بانک رسالت . پویش آکس

**Comment by Mani-rahimi1921** [comment]
فرایند استخدام خیلی زمان بر و گرفتن تعهدات و وثیقه های سنگین عیب بزرگ این شرکت هستش

**Comment by tajrobe** [comment]
[tajrobe.github.io/پویش-آکس/](https://tajrobe.github.io/%D9%BE%D9%88%DB%8C%D8%B4-%D8%A2%DA%A9%D8%B3/)

**Comment by GHAVAMIISBAD** [comment]
> فرایند استخدام خیلی زمان بر و گرفتن تعهدات و وثیقه های سنگین عیب بزرگ این شرکت هستش

تجربه ات رو داخل لینک بنویس
[tajrobe.github.io/پویش-آکس/](https://tajrobe.github.io/%D9%BE%D9%88%DB%8C%D8%B4-%D8%A2%DA%A9%D8%B3/)
