### ISSUE TITLE
pink swan-tajrobe

### ISSUE THREAD

**Issue by citayesh** [tajrobe/tajrobe.github.io#294]
##### نام شرکت
title: "پینک سوان دیجیتال"

##### نام انگلیسی شرکت
name_en: "pinkswan"

##### دسته‌ی فعالیت شرکت
industry: "web development"

##### موقعیت مکانی شرکت
city: "france"

##### تعداد نفرات شرکت
size: "15"

##### آدرس سایت شرکت
site: "pinkswan.ch"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "Development
Programming and development of your software, business applications, website, and e-commerce shop."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پینک-سوان/](https://tajrobe.github.io/%D9%BE%DB%8C%D9%86%DA%A9-%D8%B3%D9%88%D8%A7%D9%86/)
