### ISSUE TITLE
شرکت Mhs

### ISSUE THREAD

**Issue by sajjad755** [tajrobe/tajrobe.github.io#296]
##### نام انگلیسی mhs"
mhs
##### موقعیت مکانی شرکت
city: اسکندری

##### تعداد نفرات شرکت
size: 7

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""  یه شرکت صوری و کلاه برداری که به عنوان جذب کاراموز دیجیتال مارکتینگ عمرتونو هدر میده این شرکت هیچ نیروی متخصصی نداره و حتی توی سایت خودشرکت ریدن   اگ ایندتون براتون مهمه نرید سمت این شرکت

**Comment by tajrobe** [comment]
[tajrobe.github.io/هلدینگ-MHS/](https://tajrobe.github.io/%D9%87%D9%84%D8%AF%DB%8C%D9%86%DA%AF-MHS/)

**Comment by javadkordani-afk** [comment]
خیلی شرکت خوبی برای کسب تجربه در حوزه ی بازارهای بین المللی مخصوصا سهام آمریکاست. مخصوصا برای دانشجویان که بتونن پیشرفت کنن. فضای دوستانه ای در شرکت هست و سریع با شرکت مانوس میشید. 

اگر اولویتتون رشد و یادگیری و پیشرفت هست اینجا جای مناسبی براتون هست. من در حوزه سرمایه گذاری این شرکت فعالیت دارم.
