### ISSUE TITLE
جنرال کابین

### ISSUE THREAD

**Issue by Fonix360** [tajrobe/tajrobe.github.io#297]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/جنرال-کابین/](https://tajrobe.github.io/%D8%AC%D9%86%D8%B1%D8%A7%D9%84-%DA%A9%D8%A7%D8%A8%DB%8C%D9%86/)
