### ISSUE TITLE
ژاهو

### ISSUE THREAD

**Issue by pegahgoodarzi** [tajrobe/tajrobe.github.io#298]
##### نام شرکت
title: "ژاهو"

##### نام انگلیسی شرکت
name_en: "zhahoo"

##### دسته‌ی فعالیت شرکت
industry: "branding"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "2-10"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ژاهو/](https://tajrobe.github.io/%DA%98%D8%A7%D9%87%D9%88/)
