### ISSUE TITLE
آسیاتک

### ISSUE THREAD

**Issue by bawback** [tajrobe/tajrobe.github.io#3]
##### نام شرکت
title: "آسیاتک"

##### نام انگلیسی شرکت
name_en: "Asiatech"

##### دسته‌ی فعالیت شرکت
industry: "ارتباطات"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "http://www.asiatech.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ارائه دهنده خدمات اینترنت"

**Comment by tajrobe** [comment]
Done :)
https://tajrobe.github.io/%D8%A2%D8%B3%DB%8C%D8%A7%D8%AA%DA%A9/
