### ISSUE TITLE
شرکت داده پردازی نیلرام

### ISSUE THREAD

**Issue by mehrsasaadat1372** [tajrobe/tajrobe.github.io#300]
نیلرام
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by mehrsasaadat1372** [comment]
این شرکت زیرمجموعه شرکت نیلپر است که خدمات کامپیوتری و IT آن را انجام می دهد . عدم هماهنگی مدیر عامل و سرپرست بخش ها که باعث عدم رضایت مدیرعامل و توهین به کارکنان می شد.سطح حقوقی پایین در شرکت و دیر حقوق می دهند بعضا دهم تا پانزدهم ماه. عدم موافقت با مرخصی های استحقاقی. جو به شدت بد بطوریکه پشت سرت بد میگن . تسویه حساب بسیار دیر و در دو چک برای دو سه ماه بعد میدن(حدودا چهار تا شش ماه بعد از خروج از شرکت)

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مورد نظر بنویسید: @mehrsasaadat1372 

[tajrobe.github.io/داده-پردازی-نیلرام/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%DB%8C-%D9%86%DB%8C%D9%84%D8%B1%D8%A7%D9%85/)
