### ISSUE TITLE
Hamravesh

### ISSUE THREAD

**Issue by abexamir** [tajrobe/tajrobe.github.io#301]
##### نام شرکت
title: "هم‌روش"

##### نام انگلیسی شرکت
name_en: "Hamravesh"

##### دسته‌ی فعالیت شرکت
industry: "Cloud Infrastructure"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "~50"

##### آدرس سایت شرکت
site: "hamravesh.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/هم-روش/](https://tajrobe.github.io/%D9%87%D9%85-%D8%B1%D9%88%D8%B4/)
