### ISSUE TITLE
تجربه کار در شرکت توسعه خدمات الکترونیکی آدونیس

### ISSUE THREAD

**Issue by neginkavand** [tajrobe/tajrobe.github.io#305]
description: 'شرح تجربه‌ی شما'

افتضاح، کلاه بردار، دزد
ماه هاست که معوقه ها برداخت نمیشه
حقوق هام با تاخیرای 15- 20 روز پرداخت میشه
بیمه درمانی پرداخت نمیشه
محیط کار کاملا غیر حرفه ای و تکنولوژی های سطح پایین
30 درصد از نیروهای قدیمی شرکت رفتن و علنا آینده شرکت نا مشخصه
state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت
تمام وقت
job_name: 'عنوان شغلی شما'
-
company_slug: 'نام شرکت'
توسعه خدمات الکترونیکی آدونیس
pros: 'مزایا - با کاما (,) جدا شود'
-
cons: 'مزایا - با کاما (,) جدا شود'
-
1

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/توسعه-خدمات-الکترونیکی-آدونیس/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D8%A7%D9%84%DA%A9%D8%AA%D8%B1%D9%88%D9%86%DB%8C%DA%A9%DB%8C-%D8%A2%D8%AF%D9%88%D9%86%DB%8C%D8%B3/)
