### ISSUE TITLE
پوبر

### ISSUE THREAD

**Issue by 09194437564** [tajrobe/tajrobe.github.io#306]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پوبر/](https://tajrobe.github.io/%D9%BE%D9%88%D8%A8%D8%B1/)
