### ISSUE TITLE
نیکد - نیکو داده مجازی زیگوارت

### ISSUE THREAD

**Issue by mdaneshamoz** [tajrobe/tajrobe.github.io#307]
##### نام شرکت
title: "نیکد - نیکو داده مجازی زیگوارت"

##### نام انگلیسی شرکت
name_en: "nicode - nico dade majazi zigoart"

##### دسته‌ی فعالیت شرکت
industry: "توسعه نرم افزار و  بیمه - software engineering and insurance"

##### موقعیت مکانی شرکت
city: "شهر اصفهان"

##### تعداد نفرات شرکت
size: "4"

##### آدرس سایت شرکت
site: "nicode.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فعال در توسعه نرم افزار و ازجمله شرکت های خلاق. یک نرم افزار دارند به اسم کارگزار من"

**Comment by tajrobe** [comment]
[tajrobe.github.io/نیکو-داده/](https://tajrobe.github.io/%D9%86%DB%8C%DA%A9%D9%88-%D8%AF%D8%A7%D8%AF%D9%87/)
