### ISSUE TITLE
سوئیس رز

### ISSUE THREAD

**Issue by Hanniballllll** [tajrobe/tajrobe.github.io#308]
##### نام شرکت
title:سوئیس رز ""

##### نام انگلیسی شرکت
name_en: swiss rose ""

##### دسته‌ی فعالیت شرکت
industry: مواد بهداشتی و شوینده""

##### موقعیت مکانی شرکت
city: برج ساعی گلرنگ""

##### تعداد نفرات شرکت
size: ۲۰ - ۵۰""

##### آدرس سایت شرکت
site:https://swissroseco.com/ ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content:شرکت سوئیس رز واقع در برج ساعی شرکت گلرنگ تحت پوشش شرکت سوئیسی در بازار عراق در زمینه کالای بهداشتی و شوینده فعالیت دارد. ""
تجربه کار کردن در شرکت سوئیس رز بسیار نامید کننده بود برای من، تجربه برخورد زننده و طلب کارانه مدیرعامل پرهام پدرام، و وعده های هیچگاه محقق نشده توسط شرکت، باعث شد سازمان رو ترک کنم، فضای این شرکت بسیار سمی هست.

**Comment by tajrobe** [comment]
لطفا تجربه خود را بدون نام بردن از اشخاص حقیقی در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/سوئیس-رز/](https://tajrobe.github.io/%D8%B3%D9%88%D8%A6%DB%8C%D8%B3-%D8%B1%D8%B2/)
