### ISSUE TITLE
XaaS Cloud Computing

### ISSUE THREAD

**Issue by arman-shafiei** [tajrobe/tajrobe.github.io#309]
##### نام شرکت
title: "ابر زس"

##### نام انگلیسی شرکت
name_en: "XaaS"

##### دسته‌ی فعالیت شرکت
industry: "سرور ابری، ابر"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20-30"

##### آدرس سایت شرکت
site: "https://xaas.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ".شرکت ابر زس در زمینه پردازش و ارایه خدمات ابری فعالیت میکند"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ابر-زس/](https://tajrobe.github.io/%D8%A7%D8%A8%D8%B1-%D8%B2%D8%B3/)
