### ISSUE TITLE
add salpaco database to your project

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#31]
hi 
thanks for this cool project
I scrapped all data on [salpco site](https://salpaco.com/) 
[salpco.com](https://salpaco.com/) also is the same as jobguy.com
could you accept my PR to this repo?

**Comment by tajrobe** [comment]
سلام پوریا 👋

 بسیار از شما سپاسگزاریم و از پیشنهاد شما بسیار استقبال می‌کنیم.

برای یک PR درست که منجر به build موفق پروژه شود، داده‌های شما باید به شکل زیر باشد:
### 1. در این پروژه برای هر شرکت یه فایل مارک داون وجود دارد در آدرس زیر
[tajrobe.github.io/tree/master/_posts/](https://github.com/tajrobe/tajrobe.github.io/tree/master/_posts)

فرمت فایل به صورت مارک داون هست و کلید یکتای slug (به صورت String) هم در آن قرار دارد. [مثال](https://github.com/tajrobe/tajrobe.github.io/blob/341d2aabb99e8264f9f20243b90c99c91a282da3/_posts/2021-02-22-%D8%AF%DB%8C%D8%AC%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7.md?plain=1#L5)

### 2. تجربه‌های کاربری هر شرکت هم در یک پوشه با اسم slug که قبلا گفتیم در آدرس زیر قرار دارند:

[tajrobe.github.io/tree/master/_data/review/](https://github.com/tajrobe/tajrobe.github.io/tree/master/_data/review)


 برای مثال بیشتر [صفحه‌ی اطلاعات شرکت دیجی کالا](https://github.com/tajrobe/tajrobe.github.io/blob/master/_posts/2021-02-22-%D8%AF%DB%8C%D8%AC%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7.md) و پوشه‌ی شامل[ تجربه‌های کاربری دیجی‌کالا](https://github.com/tajrobe/tajrobe.github.io/tree/master/_data/review/digikala) را ببینید.

**Comment by pooooriya** [comment]
Thank you, I need to write a script that converts the Excel into yml files then contribute to your repository.
but I have a question
some interviews or reviews may have been written over the years
is it ok ?

**Comment by tajrobe** [comment]
اگر تجربه‌های کاری یا مصاحبه دارای تاریخ (فرمت timestamp) باشد مشکلی نیست :)

**Comment by pooooriya** [comment]
hi again
tonight I wrote the script and change all excel records to YAML files 
can you check out my branch and give me a feedback 
if it is ok 
I can contribute to your repo 
https://github.com/pooooriya/salpaco_tajrobe

**Comment by tajrobe** [comment]
سلام پوریا
خسته نباشی 🙏
تقریبا همه چیز برای یک PR عالی آماده است به جز ۲ نکته:
۱. توی ریپوی شما slug شرکتها دقیقا مشابه لیست شرکتهای این پروژه نیست و باید یه وقتی به ما بدی که تمام شرکتهای ناموجود رو اضافه کنیم و slug اون شرکتها که فقط از نظر املاییی با slug پروژه متفاوته رو پیدا کنیم. 
[salpa_company_slug.txt](https://github.com/tajrobe/tajrobe.github.io/files/7898800/salpa_company_slug.txt)
[tajrobe_company_slug.txt](https://github.com/tajrobe/tajrobe.github.io/files/7898801/tajrobe_company_slug.txt)

۲. چون دیتای سالپو امتیاز نداره باید صفحه تجربه‌های هر شرکت هم تغییر کنه و تجربه‌های سالپو از فرآیند معدل گیری از امتیاز مستثنی بشن. 

هر موقع این دو تا رو انجام دادیم بهت میگیم که PR بزنی.
بازم ممنون از زحمتی که کشیدی.  🙏

**Comment by pooooriya** [comment]
salam in mozo roosh kar nakardin???

**Comment by pooooriya** [comment]
نه تفاوتی نداره نیاز به PR  نیست ولی اگز نیاز به کمک هست من هم میتونم بهتون کمک کنم که زودتر انجام بشه 
فقط اگ میشه توضیح مختصری راجبش بهم بدید فقط همینه که باید فولدر جدید ساخته بشه یا هست این تجربه ها اضافه بشه  ؟ 
یا چیز پیچیده تری وجود داره؟

**Comment by tajrobe** [comment]
سلام 
ممنون از شما، که پیگیر کار هستید 🌹
هر شرکت باید یه فایل مارک‌داون داشته باشه داخل فولدر posts_ در روت پروژه، توی اون فایل مارک‌داون، اطلاعات شرکت مثل اسم فارسی شرکت و بقیه اطلاعات وجود داره، بعد company_slug هم باید مشابه اون اسمی باش که شما برای فولدر تجربیات هر شرکت گذاشتی، ما باید برای تمام نام‌های فولدر هر شرکت (slug) که شما گذاشتی رو توی پروژه‌ی فعلی بگردیم، اگه از لحاظ املایی متفاوت باشه برای یه شرکت خاص، یکی کنیم اون دو تا slug رو. تا اینجا [این شرکتها](https://github.com/tajrobe/tajrobe.github.io/files/8050345/company_pages.zip) جدید بودن و فایل مارک‌داون‌اش ساخته شده همچنین این فایل [متنی](https://github.com/tajrobe/tajrobe.github.io/files/8050362/salpa_company_slug.txt) هم لیست slugهای ریپوی شماست که اونا که لازم به تغییر نام هستند رو توش با علامت فلش نام جدید نوشتیم.
ما راه اتوماتیکی برای تولید مشخصات شرکت از اسم slug (نام فولدرها در ریپوی شما) پیدا نکردیم و این کار رو دای دستی انجام میدیم. همونطور که گفتیم تقریبا ثلث کار انجام شده.

**Comment by pooooriya** [comment]
بعد یه داستان دیگم هست من تاریخشو نتونستم از اسکرپ دیتا در بیارم یعنی مثلا زده بود اسفند 97 نهایتا و چیزی نبود که اینو بشه با رجکسی چیزی دتکت کرد و مثلا بیاد ی جوری تبدیلش کنه به utc   و برای همین همه دیت تایم هارو  برابر تایم اجرای اسکریپتم گذاشتم میتونیم اونو هم مثلا حذف کنیم از نشون دادن یا بالاش یه لیبل بزنیم که اینا از سالپا برداشتیم ؟
راجب این مواردیم که گفتی من اوکیم میتونم کمک کنم تا هر کدومش بشه  انجام میدم میفرستم

**Comment by pooooriya** [comment]
مورد ساخت  md  هم نیازی به نظرم به دستی بودنش نیست  من برا اونم یه اسکریپت مینویسم  فقط باید اون تعداد که جدیدن رو پیک کنم  فک کنم این قسمتش فقط دستی باشه

**Comment by pooooriya** [comment]
[samecompony.txt](https://github.com/tajrobe/tajrobe.github.io/files/8051656/samecompony.txt)
این کمپانی های مشابه دو تا ریپو هست

**Comment by tajrobe** [comment]
سلام @pooooriya 
در خصوص ففایلهای md به راه‌حلی رسیدیم که الان می‌توانیم  با  دو فیلد title و company_slug این فایلها را بسازیم. 
احتمالا طی چند روز آینده تکمیل می‌شود و شما می‌توانید تجربه‌های سالپا را در قالب یک PR به این مخزن اضافه کنید.
[این لیست](https://github.com/tajrobe/tajrobe.github.io/files/8111084/rename-slug.txt) شامل slugهایی است که باید rename کنید (تغییر نام فولدر در ریپازیتوری شما)

**Comment by tajrobe** [comment]
سلام @pooooriya 
لیست شرکتهای سالپا با موفقیت push شد. 💪
شما باید در ریپازیتوری خودت، [اسم این شرکت‌ها](https://github.com/tajrobe/tajrobe.github.io/files/8119003/rename-slug.1.txt) (slug یا نام پوشه‌ها)رو تغییر بدی.
دو فیلد date و rate در فایلهای yml رو مقدار خالی ست کن. مثل زیر:
```yml
rate: ''
date: ''
```
منتظر PR شما هستیم. ❤️

**Comment by tajrobe** [comment]
@pooooriya

**Comment by pooooriya** [comment]
ببخشید من این چند روز درگیر بیماری پدرم هستم انشاله بعد از عملشون این مورد
رو انجام میدم چون متاسفانه اسکریپت قبلی که نوشتم پاک شده نتونستم پیداش کنم

**Comment by pooooriya** [comment]
سلام همه شرکت ها اضافه نشدن ؟؟؟

**Comment by pooooriya** [comment]
نمونه 
کارگزاری آگاه 
ابر بازار

**Comment by pooooriya** [comment]
باقی شرکت ها هم اضافه نشدن هنوز یکی نیستن این دوتا باهم
من اطلاعات کمپانی هارم دارم میتونم فایل پروفایلشونم بسازم 
ولی خواهشا این مورد اعلام کنین من الان اسکریپت رو نوشتم و فایل هارو درست کردم

**Comment by pooooriya** [comment]
لینک ریپو اصلاح شده 
https://github.com/pooooriya/salpaco_final
لطفا کمپانی ها رو کامل اضافه کنین یا به من بگید اون اطلاعاتی که ازشون دارم براتون پروفایل بسازم 
این اطلاعات چک کنین حتما تو ریپو

**Comment by tajrobe** [comment]
همه شرکتها وجود دارند؛ برای مثال همون دوتا شرکتی که گفتید:
[tajrobe.github.io/ابربازار/](https://tajrobe.github.io/%D8%A7%D8%A8%D8%B1%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1/)
[tajrobe.github.io/کارگزاری-آگاه/](https://tajrobe.github.io/%DA%A9%D8%A7%D8%B1%DA%AF%D8%B2%D8%A7%D8%B1%DB%8C-%D8%A2%DA%AF%D8%A7%D9%87/)

**Comment by tajrobe** [comment]
هر شرکتی که شک کردید وجود ندارد کافیه اسم فوبدر (slug) رو توی همین ریپازیتوری جستجو کنید. مثل [+](https://github.com/tajrobe/tajrobe.github.io/search?q=agah) و [+](https://github.com/tajrobe/tajrobe.github.io/search?q=agah)

**Comment by tajrobe** [comment]
فقط چیزی که توی ریپازتوری  https://github.com/pooooriya/salpaco_final دیدیم این هست که هنوز این renameها رو انجام نشده است:

[لیست شرکتهایی که باید slugشان تغییر کند](https://github.com/tajrobe/tajrobe.github.io/files/8119003/rename-slug.1.txt)

**Comment by pooooriya** [comment]
بله مرسی متوجه شدم 
این PR  چک بفرمایید 
#55

**Comment by tajrobe** [comment]
PR #55 has been Merged. 🚀
