### ISSUE TITLE
راهکارهای جامع ارشن

### ISSUE THREAD

**Issue by neginbd** [tajrobe/tajrobe.github.io#310]
##### نام شرکت
title: "راهکارهای جامع ارشن"

##### نام انگلیسی شرکت
name_en: "Ershan Total Solutions"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "40"

##### آدرس سایت شرکت
site: "https://www.nahayatnegar.com/homePage/ershan"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "راهکارهای جامع ارشن (سهامی خاص) در سال 1393 به ثبت رسید تا پاسخی به نیاز روزافزون سرمایه‌گذاران بازار سرمایه، به منظور تصمیم‌گیری درست و به موقع در انجام معاملات باشد. این شرکت با الهام از پیشروان و بزرگان این حوزه در جهان و با سرمایه‌گذاری [خدمات مالی نهایت‌نگر](https://www.nahayatnegar.com/)، تولید راهکارهای نرم‌افزاری شایسته به منظور توسعه‌ی خدمات حرفه‌ای آن کارگزاری به سرمایه‌گذاران را در دستور کار قرار داد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/راهکارهای-جامع-ارشن/](https://tajrobe.github.io/%D8%B1%D8%A7%D9%87%DA%A9%D8%A7%D8%B1%D9%87%D8%A7%DB%8C-%D8%AC%D8%A7%D9%85%D8%B9-%D8%A7%D8%B1%D8%B4%D9%86/)
