### ISSUE TITLE
شرکت بهاران گستر انید

### ISSUE THREAD

**Issue by mohammadzeyghami** [tajrobe/tajrobe.github.io#312]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/بهاران-گستر-امید/](https://tajrobe.github.io/%D8%A8%D9%87%D8%A7%D8%B1%D8%A7%D9%86-%DA%AF%D8%B3%D8%AA%D8%B1-%D8%A7%D9%85%DB%8C%D8%AF/)
