### ISSUE TITLE
بانک پارسیان

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#313]
##### نام شرکت
title: "بانک پارسیان"

##### نام انگلیسی شرکت
name_en: "Parsian Bank"

##### دسته‌ی فعالیت شرکت
industry: "بانکداری"

##### موقعیت مکانی شرکت
city: "شعب سراسر کشور"

##### تعداد نفرات شرکت
size: "501 تا 1000 نفر"

##### آدرس سایت شرکت
site: "https://parsian-bank.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بانک پارسیان، دومین بانک خصوصی ایرانی، شرکت خدمات مالی و بانکداری ایرانی است، که با در اختیار داشتن شبکه ای از 350 شعبه و 16 باجه بانکداری در سراسر ایران، به عنوان یکی از بانک های خصوصی ایران شناخته می شود. بانک پارسیان در سال 1380 به عنوان دومین بانک خصوصی ایرانی، فعالیت خود را آغاز نمود."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بانک-پارسیان/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%86%DA%A9-%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%A7%D9%86/)
