### ISSUE TITLE
بانک ملت

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#314]
##### نام شرکت
title: "بانک ملت"

##### نام انگلیسی شرکت
name_en: "Mellat Bank"

##### دسته‌ی فعالیت شرکت
industry: "بانکداری"

##### موقعیت مکانی شرکت
city: "شعب سراسر کشور"

##### تعداد نفرات شرکت
size: "بیش از 5000 نفر"

##### آدرس سایت شرکت
site: "https://bankmellat.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بانک ملت، شرکت خدمات مالی و بانکداری ایرانی است که با 1٬413 شعبه در سراسر ایران فعالیت می نماید.این بانک در سال 1396 در فهرست 100 شرکت برتر ایرانی، منتشرشده توسط سازمان مدیریت صنعتی، رتبه نخست از بزرگترین شرکت های خصوصی را به خود اختصاص داد و در سال مالی 1398 رتبهٔ ششم را دارد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بانک-ملت/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%86%DA%A9-%D9%85%D9%84%D8%AA/)
