### ISSUE TITLE
بانک تجارت

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#315]
##### نام شرکت
title: "بانک تجارت"

##### نام انگلیسی شرکت
name_en: "Tejarat Bank"

##### دسته‌ی فعالیت شرکت
industry: "بانکداری"

##### موقعیت مکانی شرکت
city: "شعب سراسر کشور"

##### تعداد نفرات شرکت
size: "بیش از 5000 نفر"

##### آدرس سایت شرکت
site: "https://tejaratbank.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "بانک تجارت، شرکت خدمات مالی و بانکداری ایرانی است. بانک تجارت به عنوان یکی از بزرگترین بانک های فعال در شبکه بانکی کشور که نقش انکارناپذیری در رشد و اعتلای اقتصاد ملی دارد ، به موجب مصوبه مورخ 1358/7/25 مجمع عمومی بانک ها از ادغام 11 بانک ایران و انگلیس ، بین المللی ایران و ژاپن ، تجارتی ایران و هلند، ایران و خاورمیانه ، اعتبارات ایران، بازرگانی ایران، ایرانشهر، صنایع ایران، شهریار، ایرانیان و کار با سرمایه ای بالغ بر 39 میلیارد ریال در تاریخ 1358/9/29 و در قالب شرکت سهامی خاص با مالکیت دولت جمهوری اسلامی ایران در اداره ثبت شرکت ها به ثبت رسید و در سال 1360 بانک ایران و روس به آن ملحق شد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بانک-تجارت/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%86%DA%A9-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA/)
