### ISSUE TITLE
سیمان ممتازان کرمان

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#316]
##### نام شرکت
title: "سیمان ممتازان کرمان"

##### نام انگلیسی شرکت
name_en: "Momtazan Cement Company"

##### دسته‌ی فعالیت شرکت
industry: "ساختمان / مصالح و تجهیزات ساختمانی"

##### موقعیت مکانی شرکت
city: "کرمان"

##### تعداد نفرات شرکت
size: "201 تا 500 نفر"

##### آدرس سایت شرکت
site: "https://momtazancement.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت سیمان ممتازان (سهامی عام) مورخ 1381/05/24 با ظرفیت تولید 3300 تن کلینکر در روز (معادل یک میلیون تن در سال) به هدف تولید سیمان مورد نیاز استان و کشور و اشتغال زایی در سطح استان کرمان، تاسیس شده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سیمان-ممتازان/](https://tajrobe.github.io/%D8%B3%DB%8C%D9%85%D8%A7%D9%86-%D9%85%D9%85%D8%AA%D8%A7%D8%B2%D8%A7%D9%86/)
