### ISSUE TITLE
مادیران

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#317]
##### نام شرکت
title: "شرکت صنایع ماشینهای اداری ایران (مادیران)"

##### نام انگلیسی شرکت
name_en: "Maadiran Industries Holding"

##### دسته‌ی فعالیت شرکت
industry: "کالاهای الکتریکی و لوازم خانگی"

##### موقعیت مکانی شرکت
city: "سراسر کشور"

##### تعداد نفرات شرکت
size: "1001 تا 5000 نفر"

##### آدرس سایت شرکت
site: "https://maadiran.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه مادیران با سابقه درخشان 50 ساله که از بدو تولد در سال 1343 با ماشین های اداری و در ادامه پیشگام تولید وعرضه بهترین لوازم صوتی و تصویری و لوازم خانگی در ایران بوده است. کیفیت تولید، فروش و ارائه خدمات پس از فروش، برند مادیران را به عنوان یکی از 100 برند برتر ایران معرفی می کند. در حال حاضر مادیران، صنایع بسیاری را از لوازم خانگی تا زیست تخریب، پلاستیک، سرمایه گذاری ساختمانی و … پوشش میدهد."

**Comment by GHAVAMIISBAD** [comment]
![96cd41a4-60c0-4ebf-8a53-d88185db7b38](https://github.com/tajrobe/tajrobe.github.io/assets/108418164/d731955f-64e9-4c7d-a1a8-e73239e10fb9)

**Comment by tajrobe** [comment]
[tajrobe.github.io/مادیران/](https://tajrobe.github.io/%D9%85%D8%A7%D8%AF%DB%8C%D8%B1%D8%A7%D9%86/)
