### ISSUE TITLE
آواپرداز

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#318]
##### نام شرکت
title: "گروه فناوری آواپرداز کیهان کریمان (مبیت ، زودکس ، پی بای ، حسابرو ، راهکارصنعت ، آوینوکس ، عصرارتباط "

##### نام انگلیسی شرکت
name_en: "Ava Pardaz Keyhan Kariman"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات / نرم افزار و سخت افزار"

##### موقعیت مکانی شرکت
city: "کرمان"

##### تعداد نفرات شرکت
size: "201 تا 500 نفر"

##### آدرس سایت شرکت
site: "https://avapardaz.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه فناوری آواپرداز (مبیت ، زودکس ، پی بای ، حسابرو ، راهکارصنعت ، آوینوکس ، عصرارتباط ) آواپرداز اکنون دارای اکوسیستمی کامل و متشکل از بخش های مختلف از جمله کسب وکارهای آنلاین و حضوری، زیرساخت های فنی بروز، اداری، لجستیک، مارکتینگ و رسانه است که بیش از 300 نیروی انسانی متخصص را در خود جای داده است. رسالت گروه فناوری آواپرداز فراهم آوری زمینه ای برای رشد افراد و استفاده از دانش و تخصصی است که کسب کرده اند؛ ما در تلاشیم تا فضایی بسازیم که همه افراد در آن فرصت پیشرفت یکسانی دارند و تنها یک اصل آن ها را نسبت به دیگری برتری می بخشد و آن شایستگی است. آواپرداز با تکیه بر ارزش های اخلاقی و انسانی، آموزش های مستمر و ایجاد محیط رقابتی سالم و پویا به شما فرصتی برای توسعه فردی و احقاق حس مفید و تاثیرگذار بودن را ارائه می دهد. کسب وکارهای زیر مجموعه گروه فناوری آواپرداز: فروشگاه اینترنتی مبیت و فروشگاه های زنجیره ای حضوری مبیت استور (عصر ارتباط) پلتفرم دلیوری زودکس پلتفرم خرید و فروش اعتباری پی بای سامانه مدیریت امور کسب وکار حسابرو مرکز نوآوری آوینوکس، مسئولیت اجتماعی گروه فناوری آواپرداز و برگزار کننده همایش ها و رویدادهای اجتماعی"

**Comment by GHAVAMIISBAD** [comment]
![AVAPARDAZ](https://github.com/tajrobe/tajrobe.github.io/assets/108418164/716cb5d4-571f-4ddf-a2a5-eb014f950c78)
![avapardaz-logo 56c88f3](https://github.com/tajrobe/tajrobe.github.io/assets/108418164/c0ccef19-70a8-46c4-a2e6-d1f9b5f73df3)

**Comment by tajrobe** [comment]
[tajrobe.github.io/آواپرداز/](https://tajrobe.github.io/%D8%A2%D9%88%D8%A7%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2/)
