### ISSUE TITLE
بیت 24

### ISSUE THREAD

**Issue by AMD65** [tajrobe/tajrobe.github.io#319]
##### نام شرکت
title: "بیت 24"

##### نام انگلیسی شرکت
name_en: "Bit24"

##### دسته‌ی فعالیت شرکت
industry: "ارزهای دیجیتال و تکنولوژی بلاکچین"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۱ تا ۲۰۰ نفر"

##### آدرس سایت شرکت
site: "http://bit24.cash"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه دانش بنیان بیت 24، یکی از بزرگترین شرکت‌های فینتک که به‌طور تخصصی در زمینه ارزهای دیجیتال و تکنولوژی بلاکچین فعالیت می‌کند.
مجموعه بیت24 متشکل از متخصصین نخبه کشور با هدف حذف واسطه‌ها و در راستای رفع نیاز کاربران ایرانی برای مبادله و خرید و فروش ارزهای دیجیتال، پلتفرم امن و آسان بیت24 را طراحی و راه‌اندازی کرده‌اند. با گذشت زمان و رشد و توسعه پلتفرم بیت24 مفتخریم با رضایت بیش از 95 درصدی کاربران خود، پیشرو در بازار معاملات ارزهای دیجیتال باشیم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیت-24/](https://tajrobe.github.io/%D8%A8%DB%8C%D8%AA-24/)
