### ISSUE TITLE
پابلیکا

### ISSUE THREAD

**Issue by rivassh** [tajrobe/tajrobe.github.io#32]
##### نام شرکت
title: "پابلیکا"

##### نام انگلیسی شرکت
name_en: "publica"

##### دسته‌ی فعالیت شرکت
industry: "تبلیغات و ریپورتاژ"

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://publica.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ما در پابلیکا می‌دانیم چه متنی برای چه رسـانه‌ای مـناسب‌تر است.رسالت ما این
است کـه به شــما کمک کنیم تا اخبار و رپـورتاژ آگــــهی خود را در سـریع‌ترین زمـــان
ممکن و به صورت هدفــمند مـــنتشر کــنید.مــا در کــنار شـــما هــسـتـیم تــا بتــوانند
بــیشترین بــرداشـت را از یـک موقعیت خبری داشته باشید. "

**Comment by rivassh** [comment]
الان من با اکانت حقیقیم ثبت کردم بعدا مشکل می‌شه پیدا نشه برام؟ @tajrobe 
البته پابلیکا رو می‌خوام تعریفش رو بکنم

**Comment by tajrobe** [comment]
شرکت افزوده شد

[https://tajrobe.github.io/پابلیکا](https://tajrobe.github.io/%D9%BE%D8%A7%D8%A8%D9%84%DB%8C%DA%A9%D8%A7/)

همانطور که در صفحه‌ی [درباره ما](https://tajrobe.github.io/about/) ذکر کرده‌ایم، این پروژه هدف تجاری ندارد و اطلاعات مشارکت‌گنندگان در اختیار هیچکس قرار نمی‌گیرد و نخواهد گرفت. اگر نگران ردپای خود در اینترنت هستید، می‌توانید این issue را پاک کنید.

**Comment by rivassh** [comment]
چه جوری می‌شه پاک کرد @tajrobe
