### ISSUE TITLE
بانی‌نو

### ISSUE THREAD

**Issue by BaniRayanPrdazNo** [tajrobe/tajrobe.github.io#320]
##### نام شرکت
title: "بانی‌نو"

##### نام انگلیسی شرکت
name_en: "Banino"

##### دسته‌ی فعالیت شرکت
industry: "محصولات آی‌تی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "+50"

##### آدرس سایت شرکت
site: "Baninopc.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت بانی نو در سال 1377 فعالیت خود را با فروش سیستمهای خانگی و با دارا بودن چهار پرسنل شروع کرد. بانی نو با حرکتی رو به جلو و تلاش مداوم و بی وقفه از سال 1385 مبادرت به واردات انواع قطعات کامپیوتری نمود و طی این سالها با استفاده از تیمی متخصص، کار آمد و تحصیل کرده، در حوزه تجارت و فروش, اقدام به توزیع کالاهای اساسی رایانه ای مانند انواع نوت بوک، تبلت و قطعات اصلی رایانه ای و همچنین ارائه خدمات پس از فروش (گارانتی ) به مشتریان فعالیت مستمر خود را ادامه داده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بانی-نو/](https://tajrobe.github.io/%D8%A8%D8%A7%D9%86%DB%8C-%D9%86%D9%88/)
