### ISSUE TITLE
نورد لوله نیزار 

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#321]
نام شرکت
title: " شرکت نورد لوله و پوشش نیزار "

نام انگلیسی شرکت
name_en: "qnpcc.co"

دسته‌ی فعالیت شرکت
industry: " نورد لوله و پوشش "

موقعیت مکانی شرکت
city: "قم-نیزار"

تعداد نفرات شرکت
size: "100-150 نفر "

آدرس سایت شرکت
site: " https://qnpcc.co/"

توضیحی درباره شرکت و فعالیت‌هایش
content: "  این کارخانه به مساحت ۳۷ هکتار در سال ۱۳۹۴ تأسیس گردید. هدف این کارخانه طراحی و ساخت لوله­ های فولادی می باشد که با تحقق این امر موجبات اشتغال زایی حدود ۲۰۰ نفر به طور مسقیم و ۶۰۰ نفر غیر مستقیم را فراهم می­ نماید.
 "

**Comment by ghost** [comment]
نام شرکت
title: " شرکت نورد لوله و پوشش نیزار "

نام انگلیسی شرکت
name_en: "qnpcc.co"

دسته‌ی فعالیت شرکت
industry: " نورد لوله و پوشش "

موقعیت مکانی شرکت
city: "قم-نیزار"

تعداد نفرات شرکت
size: "100-150 نفر "

آدرس سایت شرکت
site: " https://qnpcc.co/"

توضیحی درباره شرکت و فعالیت‌هایش
content: "  این کارخانه به مساحت ۳۷ هکتار در سال ۱۳۹۴ تأسیس گردید. هدف این کارخانه طراحی و ساخت لوله­ های فولادی می باشد که با تحقق این امر موجبات اشتغال زایی حدود ۲۰۰ نفر به طور مسقیم و ۶۰۰ نفر غیر مستقیم را فراهم می­ نماید.
 "

**Comment by tajrobe** [comment]
[tajrobe.github.io/نورد-لوله-نیزار/](https://tajrobe.github.io/%D9%86%D9%88%D8%B1%D8%AF-%D9%84%D9%88%D9%84%D9%87-%D9%86%DB%8C%D8%B2%D8%A7%D8%B1/)
