### ISSUE TITLE
الماس فناوری ابری پاسارگاد (آلفا)

### ISSUE THREAD

**Issue by MohsenEskandari** [tajrobe/tajrobe.github.io#322]
##### نام شرکت
title: "الماس فناوری ابری پاسارگاد (آلفا)"

##### نام انگلیسی شرکت
name_en: "Alpha cloud"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://www.alphaco.cloud/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت دانش بنیان آلفا شرکتی است که تا قبل از سال 1401 تحت عنوان پلی پاد مشغول فعالیت بود و از ابتدای سال 1401 به صورت مستقل تحت عنوان شرکت الماس فناوری ابری پاسارگاد به فعالیت خود ادامه می دهد. حوزه فعالیت شرکت آلفا، توسعه زیر ساخت کلادگیمینگ میباشد. پلی پاد، اولین کنسول بازی ابری در خاورمیانه، اولین محصول شرکت آلفا است. کاربران در کنسول بازی پلی پاد میتوانند تمامی بازی های کنسولی روز دنیا را بدون نیاز به سخت افزار بازی تنها با استفاده از اینترنت و دستگاه هوشمند خود تجربه کنند. از دیگر فعالیت های های شرکت آلفا می توان به سرویس دهی گرافیکی ابری، ساخت بازی های رایانه ای، توسعه شبیه ساز های گرافیکی و سرویس های XR اشاره کرد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/الماس-فناوری-ابری-پاسارگاد/](https://tajrobe.github.io/%D8%A7%D9%84%D9%85%D8%A7%D8%B3-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%A7%D8%A8%D8%B1%DB%8C-%D9%BE%D8%A7%D8%B3%D8%A7%D8%B1%DA%AF%D8%A7%D8%AF/)
