### ISSUE TITLE
معرفی شرکت

### ISSUE THREAD

**Issue by ahmadgholamnia** [tajrobe/tajrobe.github.io#323]
##### نام شرکت
title: "فوژان اکسوم"

##### نام انگلیسی شرکت
name_en: "fojhun exom"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://www.fojhun.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه شرکتهای فوژان اکسوم با بیش از ربع قرن تجربه تولید و عرضه در زمینه محصولات High-Tech در مساحتی بالغ بر یک هکتار واقع در شهرک صنعتی اشتهارد موفق به تولید محصولات متنوع با برندهای اکسوم و داکس گردیده است.
محصولات تولیدی این شرکت شامل انواع اسکنرهای اسناد، دوربین های مدار بسته حفاظتی و نظارتی، دستگاههای ضبط تصاویر، انواع سوییچ های POE و صنعتی، انواع صندوق های فروشگاهی، بارکد خوان و سیستم های هوشمند سازی ساختمان میباشد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فوژان-اکسوم/](https://tajrobe.github.io/%D9%81%D9%88%DA%98%D8%A7%D9%86-%D8%A7%DA%A9%D8%B3%D9%88%D9%85/)
