### ISSUE TITLE
تامین اندیش پارس

### ISSUE THREAD

**Issue by Hossein-azimi** [tajrobe/tajrobe.github.io#324]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/تامین-اندیش-پارس/](https://tajrobe.github.io/%D8%AA%D8%A7%D9%85%DB%8C%D9%86-%D8%A7%D9%86%D8%AF%DB%8C%D8%B4-%D9%BE%D8%A7%D8%B1%D8%B3/)
