### ISSUE TITLE
شرکت دیناوین

### ISSUE THREAD

**Issue by amirrezayati** [tajrobe/tajrobe.github.io#325]
##### نام شرکت
title: "دیناوین"

##### نام انگلیسی شرکت
name_en: "Dinawin"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by amirrezayati** [comment]
من رفتم برای مصاحبه و انصافا مدیر فنی خوب و باشخصیتی داشت ولی مدیران ارشد شرکت خیلی بی ادب و گستاخ بودن و حقوق رو هم خیلی پایین میبندن.

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت بنویسید:@amirrezayati

[tajrobe.github.io/دیناوین/](https://tajrobe.github.io/%D8%AF%DB%8C%D9%86%D8%A7%D9%88%DB%8C%D9%86/)
