### ISSUE TITLE
ایده گستر پوریا

### ISSUE THREAD

**Issue by amirrezayati** [tajrobe/tajrobe.github.io#326]
##### نام شرکت
title: "ایده گستر پوریا"

##### نام انگلیسی شرکت
name_en: "7soft"

##### دسته‌ی فعالیت شرکت
industry: "خودرویی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://7soft.biz/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت ايده گستر پوريا در مهر ماه سال 1382 تاسيس و به شماره 209972 در اداره ثبت شرکت‌ها و توسط سهامداران خصوصي به ثبت رسيد و به صورت متمرکز به توسعه و توليد نرم افزارهاي تخصصي با کمک مشاوران و افراد خبره در رشته‌هاي مرتبط و خاص پرداخت.

تا پيش از اين زمان سهامداران و کارشناسان شرکت به صورت غير متمرکز و يا نيمه متمرکز پروژه‌هايي در زمينه‌ی مهندسي نرم افزار و پياده سازي سيستم‌هاي يکپارچه کاربردي به انجام رسانيده بودند که پس از آن در ساختاري سازمان يافته به تکميل و بلوغ آن‌ها پرداختند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایده-گستر-پوریا/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%AF%D9%87-%DA%AF%D8%B3%D8%AA%D8%B1-%D9%BE%D9%88%D8%B1%DB%8C%D8%A7/)
