### ISSUE TITLE
ایران سامانه

### ISSUE THREAD

**Issue by ali-ferdows** [tajrobe/tajrobe.github.io#328]
##### نام شرکت
title: "ایران سامانه"

##### نام انگلیسی شرکت
name_en: "iransamaneh"

##### دسته‌ی فعالیت شرکت
industry: "طراحی سایت"

##### موقعیت مکانی شرکت
city: "تهران - کریمخان"

##### تعداد نفرات شرکت
size: "40-50"

##### آدرس سایت شرکت
site: "https://iransamaneh.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت ایمن سامانه سپهر در سال ۱۳۸۴ تاسیس شد. در طی مدت فعالیت تمرکز شرکت بر توسعه سامانه های تخصصی تحت وب و بطور خاص رسانه های خبری و خبرگزاری بوده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایران-سامانه/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87/)
