### ISSUE TITLE
پالایشگاه تصفیه غلات زر

### ISSUE THREAD

**Issue by Samira2222** [tajrobe/tajrobe.github.io#329]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Samira2222** [comment]
قصد دارم از فرصتی که این پلتفرم در اختیار ما قرار داده استفاده کنم و از تجربه تعجب برانگیز خودم در رابطه با پالایشگاه تصفیه غلات زر (هشتگرد) بگم. فوق العاده رفتار غیرحرفه ای در استخدام و مصاحبه دارند. از من خواستند برای جایگاه شغلی کارشناس مدیریت نوآوری که آگهی کرده بودند، پروپوزال بنویسم (کاملا غیرحرفه ای) و تمام مسیر پیاده سازی سیستم مدیریت نوآوری را بر اساس مدارکی که شرکت مشاورشون در زمینه مدیریت نوآوری بهشون ارائه داده بود را با جزئیات تصریح کنم و وظایف کارشناس را هم شرح بدهم تا در اسرع وقت برایشان پرزنت کنم اما بعد از دو هفته وقتی که بر روی پروپوزال ارسالی گذاشتم دیگر خبری از آنها نشد. حداقل کاری که انتظار میرفت انجام بدن تماس با من و بیان علل عدم استخدامم بود حالا بماند که تایم هم مشخص نکردن برای ارائه.

**Comment by tajrobe** [comment]
[tajrobe.github.io/پالایشگاه-غلات-زر/](https://tajrobe.github.io/%D9%BE%D8%A7%D9%84%D8%A7%DB%8C%D8%B4%DA%AF%D8%A7%D9%87-%D8%BA%D9%84%D8%A7%D8%AA-%D8%B2%D8%B1/)
