### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by kazemim99** [tajrobe/tajrobe.github.io#33]
##### نام شرکت
title: "پرسینا"

##### نام انگلیسی شرکت
name_en: "Persina"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "persina.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی سایت، طراحی فروشگاه اینترنتی و ساخت اپلیکیشن
پرسینا، ارائه دهنده خدمات"

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/پرسینا/](https://tajrobe.github.io/%D9%BE%D8%B1%D8%B3%DB%8C%D9%86%D8%A7/)
