### ISSUE TITLE
پالایشگاه تصفیه غلات زر

### ISSUE THREAD

**Issue by Samira2222** [tajrobe/tajrobe.github.io#330]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### هشتگرد 
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Samira2222** [comment]
شرکت فوق العاده حیله گر و دارای اخلاق غیرحرفه ای هست.
طی تجربه ای که برای استخدام بعنوان کارشناس مدیریت نوآوری در پی آگهیشون داشتم از من بعد از دو مرتبه مصاحبه خواستند که پروپوزالی برایشان تهیه کنم و در اسرع وقت پس از تحویل آن جلسه ای برای ارائه آن با من تنظیم خواهند کرد. اما با توجه به این که پیشنهادشان غیرطبیعی و تعجب برانگیز بود بعلت این که من رو برای مشاوره نمی خواستند قبول کردم که پروپوزال بدم. اما بعد از تحویل آن دیگر خبری از آنها برای تعیین وقت ارائه نشد. حداقل انتظاری که از آنها میرفت این بود که تماس می گرفتند و ضمن بیان دلایل منطقی برای عدم ادامه مسیر استخدام از من تشکر می کردند.

**Comment by Samira2222** [comment]
اصلا پیشنهاد نمی کنم

**Comment by tajrobe** [comment]
[tajrobe.github.io/پالایشگاه-غلات-زر/](https://tajrobe.github.io/%D9%BE%D8%A7%D9%84%D8%A7%DB%8C%D8%B4%DA%AF%D8%A7%D9%87-%D8%BA%D9%84%D8%A7%D8%AA-%D8%B2%D8%B1/)
