### ISSUE TITLE
هلدینگ جهان صادرات

### ISSUE THREAD

**Issue by ali13707985** [tajrobe/tajrobe.github.io#331]
##### نام شرکت
title: "هلدینگ جهان صادرات"

##### نام انگلیسی شرکت
name_en: "jahan saderat"

##### دسته‌ی فعالیت شرکت
industry: "پلیمری - سلولزی - شوینده - قطعات - ماشین سازی"

##### موقعیت مکانی شرکت
city: "شهرستان نطنز و تهران"

##### تعداد نفرات شرکت
size: "500 - 1000"

##### آدرس سایت شرکت
site: "https://jahan-saderat.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/جهان-صادرات/](https://tajrobe.github.io/%D8%AC%D9%87%D8%A7%D9%86-%D8%B5%D8%A7%D8%AF%D8%B1%D8%A7%D8%AA/)
