### ISSUE TITLE
شرکت جهان پیمان کاسپین JPC

### ISSUE THREAD

**Issue by SEBI402** [tajrobe/tajrobe.github.io#332]
##### نام شرکت
title: "جهان پیمان کاسپین"

##### نام انگلیسی شرکت
name_en: "JPC"

##### دسته‌ی فعالیت شرکت
industry: "پیمانکاری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20-50"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پیمانکاری در حوزه نفت و گاز"

**Comment by tajrobe** [comment]
[tajrobe.github.io/جهان-پيمان-كاسپين/](https://tajrobe.github.io/%D8%AC%D9%87%D8%A7%D9%86-%D9%BE%D9%8A%D9%85%D8%A7%D9%86-%D9%83%D8%A7%D8%B3%D9%BE%D9%8A%D9%86/)
