### ISSUE TITLE
مینی کالا

### ISSUE THREAD

**Issue by UnrivaledIr** [tajrobe/tajrobe.github.io#333]
##### نام شرکت
title: "مینی کالا"

##### نام انگلیسی شرکت
name_en: "Minikala"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه اینترنتی، فروشگاه واسطه‌گری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "51-200"

##### آدرس سایت شرکت
site: "https://minikala.net"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اینستاگرام رو فروشگاه کردن "

**Comment by tajrobe** [comment]
[tajrobe.github.io/مینی-کالا/](https://tajrobe.github.io/%D9%85%DB%8C%D9%86%DB%8C-%DA%A9%D8%A7%D9%84%D8%A7/)
