### ISSUE TITLE
توسعه گران سیستمهای جامع نرم افزاری

### ISSUE THREAD

**Issue by MaIzadi** [tajrobe/tajrobe.github.io#334]
##### نام شرکت
title: "توسعه گران سیستمهای جامع نرم افزاری"

##### نام انگلیسی شرکت
name_en: "DTS"

##### دسته‌ی فعالیت شرکت
industry: "تولید و پشتیبانی نرم افزار"

##### موقعیت مکانی شرکت
city: "خیابان ترکمنستان کوچه افرا"

##### تعداد نفرات شرکت
size: "کمتر از 10 نفر"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نرم افزار ذیحسابی اموال و انبار (دارایی ثابت) برای سازمانهای دولتی"

**Comment by MaIzadi** [comment]
سلام 
در این شرکت قرارداد ثبت نمی شه اما زیر بیمه و حقوق شما هم نمی زنن
 خیلی کاری با دیر آمدن زود رفتن شما ندارن 
کار رو خوب انجام بدی می گن مرسی خوب هستی بد انجام بدی هم شلوغش نمی کنن
حقوق رو خیلی کم و دیرتر از سر برج می دن
یه مقدار بین خودشون رقابت و اصطکاک وجود داره و جو گاها می شه گفت حتی سمی می شه
از هیچ تکنولوژی مثل تیکتینگ یا جیرا یا گیت هاب و ... استفاده نمی کنن
من دوست داشتم اونجا کار کردن رو و اگه مسائل مالی انقدر فشار نمیآورد شاید برای ده سال هم می خواستم که بمونم

**Comment by tajrobe** [comment]
@MaIzadi لطفا  در صفحه شرکت تجربه خود را بنویسید:

[tajrobe.github.io/توسعه-گران-سیستمهای-جامع-نرم-افزاری/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%DA%AF%D8%B1%D8%A7%D9%86-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85%D9%87%D8%A7%DB%8C-%D8%AC%D8%A7%D9%85%D8%B9-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1%DB%8C/)
