### ISSUE TITLE
Eghtesadonline

### ISSUE THREAD

**Issue by 1mehdifaraji** [tajrobe/tajrobe.github.io#335]
##### نام شرکت
title: "اقتصاد آنلاین"

##### نام انگلیسی شرکت
name_en: "Eghtesadonline"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "https://www.eghtesadonline.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پایگاه خبری از سال ۸۹ آغاز بکار کرده و هم اکنون پرمخاطب ترین پایگاه خبری در حوزه اقتصاد محسوب می شود. این پایگاه خبری زیر نظر مستقیم هیات عالی نظارت بر مطبوعات قرار دارد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/اقتصاد-آنلاین/](https://tajrobe.github.io/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF-%D8%A2%D9%86%D9%84%D8%A7%DB%8C%D9%86/)
