### ISSUE TITLE
نظرات کاربران راستچین

### ISSUE THREAD

**Issue by talashnet** [tajrobe/tajrobe.github.io#336]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by talashnet** [comment]
کلاه برداری سایت راستچین

**Comment by tajrobe** [comment]
[tajrobe.github.io/راست-چین/](http://tajrobe.github.io/%D8%B1%D8%A7%D8%B3%D8%AA-%DA%86%DB%8C%D9%86)
