### ISSUE TITLE
راستچین

### ISSUE THREAD

**Issue by talashnet** [tajrobe/tajrobe.github.io#337]
![209573b750a6a31517fb4321b3219cc09ef396224856e1](https://github.com/tajrobe/tajrobe.github.io/assets/155485377/914a3a9d-378e-4d9b-95c6-55d050946f38)
راستچین##### نام شرکت
title: "راستچین"

##### نام انگلیسی شرکت
name_en: "rtl-theme"

##### دسته‌ی فعالیت شرکت
industry: "وب سایت"

##### موقعیت مکانی شرکت
city: "ایران"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "تهران"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نظرات کاربران در مورد راستچین"

**Comment by talashnet** [comment]
کلاه برداری سایت راستچین

**Comment by tajrobe** [comment]
[tajrobe.github.io/راست-چین/](http://tajrobe.github.io/%D8%B1%D8%A7%D8%B3%D8%AA-%DA%86%DB%8C%D9%86)
