### ISSUE TITLE
گرایش تازه کیش - GSS

### ISSUE THREAD

**Issue by hadimohagheghi** [tajrobe/tajrobe.github.io#338]
##### نام شرکت
title: "گرایش تازه کیش"

##### نام انگلیسی شرکت
name_en: "GSS"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/گرایش-تازه-کیش/](https://tajrobe.github.io/%DA%AF%D8%B1%D8%A7%DB%8C%D8%B4-%D8%AA%D8%A7%D8%B2%D9%87-%DA%A9%DB%8C%D8%B4/)
