### ISSUE TITLE
thelist

### ISSUE THREAD

**Issue by arash-nykbakht-thelist** [tajrobe/tajrobe.github.io#339]
##### نام شرکت
title: "لیست"

##### نام انگلیسی شرکت
name_en: "thelist"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "remote"

##### تعداد نفرات شرکت
size: "25"

##### آدرس سایت شرکت
site: "https://thelist-app.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت یک شرکت ثبت رزرواسیون میز در رستوران و کلاب به صورت آنلاین میباشد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/لیست/](https://tajrobe.github.io/%D9%84%DB%8C%D8%B3%D8%AA/)
