### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by kazemim99** [tajrobe/tajrobe.github.io#34]
##### نام شرکت
title: "مانی بان"

##### نام انگلیسی شرکت
name_en: "manyban"

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://maniban.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی سایت و ساخت اپلیکیشن بصورت پیمانکاری "

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/مانی-بان/](https://tajrobe.github.io/%D9%85%D8%A7%D9%86%DB%8C-%D8%A8%D8%A7%D9%86/)
