### ISSUE TITLE
کبریت توکلی

### ISSUE THREAD

**Issue by mhmmdzde** [tajrobe/tajrobe.github.io#340]
##### نام شرکت
title: "کبریت توکلی"

##### نام انگلیسی شرکت
name_en: "tavakoli match"

##### دسته‌ی فعالیت شرکت
industry: "تولید نئوپان و کبریت"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/کبریت-توکلی/](https://tajrobe.github.io/%DA%A9%D8%A8%D8%B1%DB%8C%D8%AA-%D8%AA%D9%88%DA%A9%D9%84%DB%8C/)
