### ISSUE TITLE
شرکت مشاورین انفورماتیک نیرو (مانیر)

### ISSUE THREAD

**Issue by mhmmdzde** [tajrobe/tajrobe.github.io#341]
##### نام شرکت
title: "مشاورین انفورماتیک نیرو - مانیر"

##### نام انگلیسی شرکت
name_en: "manir"

##### دسته‌ی فعالیت شرکت
industry: "بیلینگ شرکت برق"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "صورتحساب توانیر"

**Comment by mhmmdzde** [comment]
ثبت شرکت جدید

**Comment by tajrobe** [comment]
[tajrobe.github.io/مشاورین-انفورماتیک-نیرو/](https://tajrobe.github.io/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%DB%8C%D9%86-%D8%A7%D9%86%D9%81%D9%88%D8%B1%D9%85%D8%A7%D8%AA%DB%8C%DA%A9-%D9%86%DB%8C%D8%B1%D9%88/)
