### ISSUE TITLE
تگموند

### ISSUE THREAD

**Issue by tagmond** [tajrobe/tajrobe.github.io#342]
##### نام شرکت
title: "تگموند"

##### نام انگلیسی شرکت
name_en: "Tagmond"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه اینترنتی مد و پوشاک"

##### موقعیت مکانی شرکت
city: "ایران، تهران"

##### تعداد نفرات شرکت
size: "0-50 نفر"

##### آدرس سایت شرکت
site: "https://tagmond.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت گسترش و نوآوری تگین با نام تجاری تگموند، فروشگاهی اینترنتی و فعال در حوزه فروش پوشاک برندهای بین‌المللی و ایرانی معتبر بوده که فعالیت خود را از سال 1395 آغاز نموده و هم ا‌کنون در حال همکاری با بیش از 400 برند می‌باشد و به مشتریان سراسر ایران زمین، امکان انتخاب متنوع ترین کالکشن محصولات، یعنی بیش از 70 هزار مدل محصول را می‌دهد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/تگ-موند/](https://tajrobe.github.io/%D8%AA%DA%AF-%D9%85%D9%88%D9%86%D8%AF/)
