### ISSUE TITLE
فناوری اطلاعات حامی بیمه (فنحاب)

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#343]
##### نام شرکت
title: "فناوری اطلاعات حامی بیمه (فنحاب)"

##### نام انگلیسی شرکت
name_en: "Fanhub"

##### دسته‌ی فعالیت شرکت
industry: "بیمه"

##### موقعیت مکانی شرکت
city: "تهران-پردیس"

##### تعداد نفرات شرکت
size: "100-200"

##### آدرس سایت شرکت
site: "http://www.sanhab.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فنحاب در راستای دستیابی به منظر فناوری در تحول دیجیتال در حوزه تخصصی بیمه، همکاری و مشارکت با شــرکت های تامین کننده نرم افزار یکپــارچه بیمه گری را در برنامه های خود گنجانده است.
مدیران ارشد و برنامه ریزان اصلی این شرکت با تکیه بر خلاقیت و دانش کارکنان خود با یکپارچگی و کار تیمی، توسعه دهندگان تحول دیجیتال حوزه بیمه در کشور هستند که با بهره گیری از تجارب موثر خویش تحقق برنامه های طراحی شده را دنبال می کنند تا بتوانند در حوزه بومی سازی و به کارگیری فناوری روز دنیا کسب اعتبار و جایگاهی منطبق با توانایی نیروهای انسانی خود اخذ نمایند."

**Comment by natanail** [comment]
اسم قبلی شرکت "سامانه نگار حامی بیمه" بوده،اگر میشه لطفا با اون لینکش کنید یا اسم اونو تغییر بدید

**Comment by tajrobe** [comment]
نام جدید به عنوان شرکت اضافه شد

[tajrobe.github.io/سامانه-نگار/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%86%DA%AF%D8%A7%D8%B1/)
