### ISSUE TITLE
[tajrobe.github.io/سامانه-نگار/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%86%DA%AF%D8%A7%D8%B1/)

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#344]
....

**Comment by tajrobe** [comment]
نام جدید به عنوان شرکت اضافه شد

[tajrobe.github.io/سامانه-نگار/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%86%DA%AF%D8%A7%D8%B1/)
