### ISSUE TITLE
داده پردازی معتمد تیس

### ISSUE THREAD

**Issue by yousefemz** [tajrobe/tajrobe.github.io#345]
##### نام شرکت
title: "داده پردازی معتمد تیس"

##### نام انگلیسی شرکت
name_en: "Tiss TSP"

##### دسته‌ی فعالیت شرکت
industry: "Financial services"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۱۰-۵۰ نفر"

##### آدرس سایت شرکت
site: "tisstsp.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت معتمد مالیاتی تیس (داده پردازی معتمد تیس) از ابتدای سال ۱۴۰۱ با سرمایه گذاری شرکت های آسیاتک، سان و داده‌های ابری آسیاتک شکل گرفت. هدف ما از ابتدا فراهم سازی آرامش خاطر، ساده سازی فرآیند ثبت و صدور صورتحساب و پشتیبانی همیشگی مودیان است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/داده-پردازی-معتمد-تیس/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%DB%8C-%D9%85%D8%B9%D8%AA%D9%85%D8%AF-%D8%AA%DB%8C%D8%B3/)
