### ISSUE TITLE
موسسه افق ارتباط بین الملل باران

### ISSUE THREAD

**Issue by Wakemeup12** [tajrobe/tajrobe.github.io#346]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Wakemeup12** [comment]
مشکلات در این شرکت یکی ۲تا نیست
مدیران ناکاربلد و پر مدعا
حقوق ها تقریبا هرماه از ۱۰ تا ۱۵ روز دیرتر واریز میشه
تقریبا هر روز یکی از کارشناسا یا مدرساشون گریه میکنه 
مدیر عامل ایران نیست و شرکت تقریبا رو هواست  
روابط جنسی بین کارکنان کاملا مشهود هست
بحث های غیر کاری و دخالت های نابجا در زندگی و مسائل
سیستم کاری ندارند و همه چی با سلام صلوات پیش میرود
مشتریانشون از طریق روابط با ماهیت نامعلومی به دست می اید
واحد مالیشون اصلا سواد مالی ندارند و بیشتر حکم مراقب پولای مدیرعاملو دارند

**Comment by tajrobe** [comment]
[tajrobe.github.io/افق-ارتباط-بین-المللی-باران/](https://tajrobe.github.io/%D8%A7%D9%81%D9%82-%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7-%D8%A8%DB%8C%D9%86-%D8%A7%D9%84%D9%85%D9%84%D9%84%DB%8C-%D8%A8%D8%A7%D8%B1%D8%A7%D9%86/)
