### ISSUE TITLE
آرمان تجارت آرون (پیوان)

### ISSUE THREAD

**Issue by HRPIVAN** [tajrobe/tajrobe.github.io#348]
##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیوان/](https://tajrobe.github.io/%D9%BE%DB%8C%D9%88%D8%A7%D9%86/)
