### ISSUE TITLE
بی طرفی

### ISSUE THREAD

**Issue by rivassh** [tajrobe/tajrobe.github.io#35]
اگر قرار به بی طرفی باشه چرا باید کامنت‌ها بره سمت یه سرور دیگه و یه نفر تایید کنه؟
مستقیم وارد گیت هابش کنید

**Comment by rivassh** [comment]
البته نه اینکه مستقیم در صفحات درج بشه. به صورت پول رکوئست بیاد تا شفاف و بدون قصد و غرض و احتمالا جانبداری کسی یا جریانی باشه

**Comment by tajrobe** [comment]
سلام.
این پروژه [github-pages](https://pages.github.com/)هست و برای دریافت تجربه‌های کاربری از [staticman](https://staticman.net/) استفاده می‌کند. تجربه‌ها بدون تایید منتشر می‌شوند و استفاده از سرور واسط، فقط برای استقرار staticman استفاده شده است، در این روش حریم خصوصی افراد بهتر حفظ می‌شود و نیاز به داشتن یک اکانت گیتهاب برای ثبت تجربه نیست. اگر به هر دلیلی تمایل به ارسال فرم ندارید، می‌توانید مستقیما از طریق گیتهاب، تجربه‌ی خودتان را در قالب یک PR بفرستید.

**Comment by rivassh** [comment]
دو تا مسئله
مثلا برای شرکت آدیلار دقیقا یادمه چندین نظر دیگه وجود داشت که اونها رو نیاوردید و همین من رو به شک انداخت که نکنه کاسه‌ای زیر نیم کاسه هست یا هیچی از جاب گای نیارید یا همه رو کامل بیارید. اینجوری حقوق ضایع می‌شه و اصلا چه ربطی داره. میتونید از شرکت‌های جاب گای فقط استفاده کنید. شاید جاب گای هم همه نظرات رو تایید نکرده بوده
مسئله ای که پشت بند این قضیه به ذهنم خطور کرد این بود که برای شفاف سازی و اثبات حسن نیت از طریق همون سرورها می‌شه بلافاصله نظرات ثبت شده رو به pull request تبدیل کرد 
@tajrobe

**Comment by tajrobe** [comment]
سلام
دیتای وجود در این ریپازیتوری از دیتای crawl شده‌ی زیر بدست آمده است:
https://github.com/RaminNietzsche/jobguy
این کامل‌ترین دیتایی بود که ما پیدا کردیم، اگر شما دیتای کاملتری دارید آن را در اختیار این پروژه قرار دهید.

در خصوص شفاف‌سازی، تا جایی که ممکن بوده این مورد رعایت شده است و سه روش برای مشارکت در این پروژه ر نظر گرفته شده است، 
- مشارکت مستقیم از طریق PR در ریپوی گیتهاب
- مشارکت از طریق ارسال فرم HTML و Staticman (در خصوص Staticman از [سایت](https://staticman.net/) یا [ریپازیتوری گیتهاب](https://github.com/eduardoboucas/staticman) اطلاعات بیشتری کسب کنید.)
- مشارکت از طریق ارسال ایمیل به tajrobe98 در جیمیل

هر فرد از هر یک از روشهای بالا که تمایل دارد، می‌تواند در این پروژه مشارکت کند و تاکیدی روی هیچ‌کدام از روش‌ها نیست. روش بهتری سراغ دارید؟ دیتا و کد پروژه به صورت متن باز در دسترس شماست، آن را بهبود دهید. 

همانطور که در صفحه درباره ما گفته شده این پروژه نفع مالی ندارد و به صورت non-profit متن‌باز و تحت مجوز  GPL-3.0 منتشر می‌شود.
