### ISSUE TITLE
فروشگاه جهان پاک

### ISSUE THREAD

**Issue by jahanpakcom** [tajrobe/tajrobe.github.io#350]
##### نام شرکت
title: "جهان پاک"

##### نام انگلیسی شرکت
name_en: "jahampak"

##### دسته‌ی فعالیت شرکت
industry: "تجهیزات نظافتی و هتلی"

##### موقعیت مکانی شرکت
city: "karaj"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "www.jahanpak.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه اینترنتی و حضوری تجهیزات رفاهی، نظافتی و هتلی جهان پاک"

**Comment by tajrobe** [comment]
already exists [tajrobe.github.io/جهان-پاک/](https://tajrobe.github.io/%D8%AC%D9%87%D8%A7%D9%86-%D9%BE%D8%A7%DA%A9/)
