### ISSUE TITLE
آرا کاوش پژوه

### ISSUE THREAD

**Issue by mjf11100** [tajrobe/tajrobe.github.io#351]
##### نام شرکت
title: "آرا کاوش پژوه"

##### نام انگلیسی شرکت
name_en: "Ara kavosh Pajouh"

##### دسته‌ی فعالیت شرکت
industry: "طراحی، ساخت و تولید تجهیزات آزمایشگاهی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://arakavosh.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت آرا کاوش پژوه یک شرکت دانش بنیان با محوریت ساخت و تولید تجهیزات آزمایشگاهی و ارائه خدمات فنی و مهندسی مورد نیاز مشتریان و کاربران در حوزه های طیف سنجی کروماتوگرافی و الکتروشیمی و … است."

**Comment by mjf11100** [comment]
شرکتی مزخرف و سرکاری! چندبار مصاحبه حضوری بدون اعلام نتیجه و حتی علت رد شدن

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/آرا-کاوش-پژوه/](https://tajrobe.github.io/%D8%A2%D8%B1%D8%A7-%DA%A9%D8%A7%D9%88%D8%B4-%D9%BE%DA%98%D9%88%D9%87/)
