### ISSUE TITLE
فروشگاه ارس یاب

### ISSUE THREAD

**Issue by arasyab** [tajrobe/tajrobe.github.io#352]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ارس-یاب/](https://tajrobe.github.io/%D8%A7%D8%B1%D8%B3-%DB%8C%D8%A7%D8%A8/)
