### ISSUE TITLE
شرکت سامانه جامع ساعی

### ISSUE THREAD

**Issue by afsafaei** [tajrobe/tajrobe.github.io#353]
##### نام شرکت
title: "شرکت سامانه جامع ساعی"

##### نام انگلیسی شرکت
name_en: "saeigroup"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات و مخابرات"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://www.saeigroup.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت سامانه جامع ساعی در شب یلدای سال ۱۳۸۹ با حضور جمعی از متخصصین حوزه فناوری اطلاعات و مخابرات با هدف ارائه خدمات در حوزه فناوری اطلاعات و مخابرات تاسیس شد. ساعی همواره تلاش داشته است تا با فراهم کردن فناوریهای روز جهان و همچنین به کارگیری متخصصان زبده به عنوان یک شریک استراتژیک در سفر تحول دیجیتال همراه مشتریان باشد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سامانه-جامع-ساعی/](https://tajrobe.github.io/%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D8%AC%D8%A7%D9%85%D8%B9-%D8%B3%D8%A7%D8%B9%DB%8C/)
