### ISSUE TITLE
شرکت توسعه زیرساخت مانا مهام

### ISSUE THREAD

**Issue by afsafaei** [tajrobe/tajrobe.github.io#354]
##### نام شرکت
title: "شرکت توسعه زیرساخت مانا مهام"

##### نام انگلیسی شرکت
name_en: "mmid"

##### دسته‌ی فعالیت شرکت
industry: "جایگاه فناوری اطلاعات و تحقق اهداف کلان دولت الکترونیک"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://mmid.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "در سال 1396 با هدف اعتلای جایگاه فناوری اطلاعات و تحقق اهداف کلان دولت الکترونیک در کشور و شناخت دقیق نیازمندی¬های بنیادین و چالش¬های محوری فناوری اطلاعات در سازمان ها، پا به عرصه وجود نهاد.این شرکت با پشتوانه تجارب متخصصین توانمند خود در شناسایی، تحلیل و طراحی راهکارهای فناوری اطلاعات سازمان ها، به عنوان ارائه دهنده راهکارهاي هوشمند مبتنی بر فناوري اطلاعات و ارتباطات براي سازمان¬هاي مختلف اعم از دولتی و خصوصی فعالیت می¬نمایند."

**Comment by afsafaei** [comment]
تو آگهی کارشون زده بودن مسلط به Lpic1 
ولی هرچی سوال درباره دیتا بیس و dns  و تمام سرویس های lpic2 رو پرسیدند
و اصلا هم مشخص نبود دقیقا چی میخوان

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت بنویسید:

[tajrobe.github.io/مانا-مهام/](https://tajrobe.github.io/%D9%85%D8%A7%D9%86%D8%A7-%D9%85%D9%87%D8%A7%D9%85/)
