### ISSUE TITLE
هواپیمایی ماهان

### ISSUE THREAD

**Issue by afsafaei** [tajrobe/tajrobe.github.io#355]
##### نام شرکت
title: "هواپیمایی ماهان"

##### نام انگلیسی شرکت
name_en: "mahan air"

##### دسته‌ی فعالیت شرکت
industry: "حمل و نقل و ارایه خدمات مسافری و باری ایران "

##### موقعیت مکانی شرکت
city: "تهران-صادقیه"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://www.mahanair.co.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "هواپیمایی ماهان به عنوان اولین شرکت خصوصی در صنعت حمل و نقل و ارایه خدمات مسافری و باری ایران در ســـال 1371 تاسیس و شروع به فعالیت نمود. فعالیت این مجموعه در عرصه ملی با پروازهای تهران – کرمان - تهران آغاز و پس از آن توانست با افزایش امکانات و همچنین توسعه ناوگان هوایی رشد مسیرهای مختلف داخلی و بین المللی را دردستور کار قراردهد.

"

**Comment by tajrobe** [comment]
[tajrobe.github.io/هواپیمایی-ماهان/](https://tajrobe.github.io/%D9%87%D9%88%D8%A7%D9%BE%DB%8C%D9%85%D8%A7%DB%8C%DB%8C-%D9%85%D8%A7%D9%87%D8%A7%D9%86/)
