### ISSUE TITLE
هیدرولیک کاران

### ISSUE THREAD

**Issue by SarahKeshvardoust** [tajrobe/tajrobe.github.io#356]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by SarahKeshvardoust** [comment]
تجربه نسبتا عجیب و نه چندان جالب
اصلا جالب نبود.. هیشکی اینجا قراردادنداره گویا اصلا هم براشون مهم نیست فقط ظاهرا حقوق سر وقت میدن ...چن روز اونجا بودم متوجه بی درو پیکریش شدم اومدم بیرون !

قانون قانونه ولی ظاهرا فقط دنبال توجیه بودن اول تو مصاحبه خانمی که اسمش الهام عابدی بود گفت قرارداد دارید بعد که با یکی از پزسنل حرف زدم گفت اینجا هیشکدوممون قراداد نداریم و انگار خیلی هم عادی بوده براشون !!!!!!!!!!!!!!!!!!!!!!!!!!!

فکر کنم هنوز پرسنل به حقوق اولیه وانسانیشون آشنا نیستن :)))) خیلی وسایل قدیمی و عهد عتیق و سیستم های کند و ناجور و هنگی هم داشت !

**Comment by tajrobe** [comment]
لطفا تجربه خود را بدون نام بردن از اشخاص حقیقی در صفحه زیر بنویسید:

[tajrobe.github.io/هیدرولیک-کاران/](https://tajrobe.github.io/%D9%87%DB%8C%D8%AF%D8%B1%D9%88%D9%84%DB%8C%DA%A9-%DA%A9%D8%A7%D8%B1%D8%A7%D9%86/)
