### ISSUE TITLE
شرکت بیژن

### ISSUE THREAD

**Issue by SarahKeshvardoust** [tajrobe/tajrobe.github.io#357]
##### نام شرکت    
title: "" صنایع غذایی بیزن

##### نام انگلیسی شرکت   bizhan
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "" صنایع غذایی

##### موقعیت مکانی شرکت
city: "" وزرا

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/صنایع-غذایی-بیژن/](https://tajrobe.github.io/%D8%B5%D9%86%D8%A7%DB%8C%D8%B9-%D8%BA%D8%B0%D8%A7%DB%8C%DB%8C-%D8%A8%DB%8C%DA%98%D9%86/)
