### ISSUE TITLE
دانادل

### ISSUE THREAD

**Issue by elliotWoas** [tajrobe/tajrobe.github.io#358]
##### نام شرکت
title: "دانادل"

##### نام انگلیسی شرکت
name_en: "danadel"

##### دسته‌ی فعالیت شرکت
industry: "مجموعه فرهنگی بازی و تفریحی با خونواده "

##### موقعیت مکانی شرکت
city: "تهران. خیابان شریعتی مجموعه چمران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "http://www.danadelshahr.ir/", "danadelstudio.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "دانادل، خانه ایست برای ایده های بلندپروازانه ای که آینده فرزندان ایران زمین را خواهد ساخت"

**Comment by tajrobe** [comment]
[tajrobe.github.io/دانادل/](https://tajrobe.github.io/%D8%AF%D8%A7%D9%86%D8%A7%D8%AF%D9%84/)
