### ISSUE TITLE
شرکت نرم افزاری آرپا

### ISSUE THREAD

**Issue by MaghsoodSalimi** [tajrobe/tajrobe.github.io#36]
##### نام شرکت
title: "آرپا"

##### نام انگلیسی شرکت
name_en: "Arpa"

##### دسته‌ی فعالیت شرکت
industry: "تولید نرم افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۰"

##### آدرس سایت شرکت
site: "www.arpaco.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/آرپا](https://tajrobe.github.io/%D8%A2%D8%B1%D9%BE%D8%A7/)
