### ISSUE TITLE
ثبت

### ISSUE THREAD

**Issue by sharrpas** [tajrobe/tajrobe.github.io#360]
##### نام شرکت
title: "سهدا"

##### نام انگلیسی شرکت
name_en: "sahda"

##### دسته‌ی فعالیت شرکت
industry: "درمان"

##### موقعیت مکانی شرکت
city: "واحد فناوری دانشگاه علوم تحقیقات"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://sahda.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "درمان انلاین"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ماندگار-درمان-ایرانیان/](https://tajrobe.github.io/%D9%85%D8%A7%D9%86%D8%AF%DA%AF%D8%A7%D8%B1-%D8%AF%D8%B1%D9%85%D8%A7%D9%86-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%DB%8C%D8%A7%D9%86/)
