### ISSUE TITLE
شرکت جدید

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#361]
##### نام شرکت
title: "نویان نگین پارسیان"

##### نام انگلیسی شرکت
name_en: "nouyan negin parsian"

##### دسته‌ی فعالیت شرکت
industry: "کیت های پزشکی درمانی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "150"

##### آدرس سایت شرکت
site: "https://nouyan-co.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ویان‌نگین‌پارسیان تولیدکننده و واردکننده کیت‌ها و دستگاه‌های سنجش ایمونواسی است. شرکت نویان‌نگین‌پارسیان "تامین مناسب" و "کیفیت بالا" بهمراه ارائه "خدمات پس از فروش" در کوتاه‌ترین زمان ممکن را هدف خود قرار داده است،تا بتواند بازویی برای ارتقای صنعت آزمایشگاهی باشد"

**Comment by pooriaashkevarvakili** [comment]
این شرکت جدید درسایت تجربه اضافه کنید

**Comment by tajrobe** [comment]
[tajrobe.github.io/نویان-نگین-پارسیان/](https://tajrobe.github.io/%D9%86%D9%88%DB%8C%D8%A7%D9%86-%D9%86%DA%AF%DB%8C%D9%86-%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%A7%D9%86/)
