### ISSUE TITLE
مکانیک آب

### ISSUE THREAD

**Issue by Ahmadsukar** [tajrobe/tajrobe.github.io#362]
##### نام شرکت
title: "**مکانیک آب**"

##### نام انگلیسی شرکت
name_en: "Mechanic AB"

##### دسته‌ی فعالیت شرکت
industry: "تولید شیرالات صنعتی"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "WWW.mechanicab.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Ahmadsukar** [comment]
متأسفانه واحد فنی این شرکت محیط کاری به شدت سمی داره و هر لحظه باید مراقب همکارها و مدیرتون باشین که شما رو وسط بازی ها و تسویه حساب های خودشون نندازن. بیشتر به جای کار کردن باید بازیگر خوبی باشین.برگ قرارداد کاری رو هم به خودتون نمیدن تا دستتون جایی بند نباشه.برای نیروی کار جدید هم ارزشی قائل نیستن و به روش های مختلف مانع پا گیری نیروی جدید میشن و سعی میکنند که طرف رو ناامید و دلسرد کنند.

یادتون باشه نه به مدیر و نه به همکاراتون اعتماد نکنید.در مورد کارگران هم حق بیمه سختی زیان آوری رو پرداخت نمی کنن و هر کس هم اعتراض کنه تهدید و ارعاب میشه.مدیریت خیلی ضعیف و ناکارآمدی داره و فاقد ضابطه و قانون هست و کارها بر اساس ریش سفیدی و باندبازی جلو میره.این شرکت فاقد مدیر منابع انسانی هست دیگه خودتون حسابتون رو بکنید.برای خانم های آبرومند اصلا محیط مناسبی نداره

**Comment by Ahmadsukar** [comment]
متأسفانه واحد فنی این شرکت محیط کاری به شدت سمی داره و هر لحظه باید مراقب همکارها و مدیرتون باشین که شما رو وسط بازی ها و تسویه حساب های خودشون نندازن. بیشتر به جای کار کردن باید بازیگر خوبی باشین.برگ قرارداد کاری رو هم به خودتون نمیدن تا دستتون جایی بند نباشه.برای نیروی کار جدید هم ارزشی قائل نیستن و به روش های مختلف مانع پا گیری نیروی جدید میشن و سعی میکنند که طرف رو ناامید و دلسرد کنند.

یادتون باشه نه به مدیر و نه به همکاراتون اعتماد نکنید.در مورد کارگران هم حق بیمه سختی زیان آوری رو پرداخت نمی کنن و هر کس هم اعتراض کنه تهدید و ارعاب میشه.مدیریت خیلی ضعیف و ناکارآمدی داره و فاقد ضابطه و قانون هست و کارها بر اساس ریش سفیدی و باندبازی جلو میره.این شرکت فاقد مدیر منابع انسانی هست دیگه خودتون حسابتون رو بکنید.برای خانم های آبرومند اصلا محیط مناسبی نداره

@mechanicab.com

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مورد نظر بنویسید: @Ahmadsukar 
[tajrobe.github.io/مکانیک-آب/](https://tajrobe.github.io/%D9%85%DA%A9%D8%A7%D9%86%DB%8C%DA%A9-%D8%A2%D8%A8/)

**Comment by Ahmadsukar** [comment]
با سلام
درخواست حذف تجربه ثبت شده را دارم/.
