### ISSUE TITLE
داده پردازی آموت

### ISSUE THREAD

**Issue by sepehr-safaeian** [tajrobe/tajrobe.github.io#363]
##### نام شرکت
title: "داده پردازی آموت"

##### نام انگلیسی شرکت
name_en: "AmootSoft"

##### دسته‌ی فعالیت شرکت
industry: "خدمات نرم افزاری"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "۲۵-۵۰"

##### آدرس سایت شرکت
site: "amootsoft.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نرم افزار مدیریت مشتریان، سیستم پیامک انبوه، پیام صوتی تبلیغاتی"

**Comment by sepehr-safaeian** [comment]
بشدت مدیریت سواستفاده‌گر، از لحاظ مختلف، تابع قوانین اداره کار نیستند به طوریکه که بجای ۲.۵ روز مرخصی فقط یک روز مرخصی میدن، بیمه ها بشدت ناقص رد میشه، در یک سال همکاری هیچ وعده افزایش حقوق به هیچکدام از همکاران صورت نگرفت، در نهایت هم قبل از تسویه حساب فیش رو نشون میدن میگن امضا کنید که درسته تا اقدام به واریز بشه، بعد از امضا هیچی واریز نکردند و مدیریت مجموعه فرمودند مدرکی دارید برید ثابت کنید، چند روز بعد منابع انسانی پیام دادند که مدیرعامل گفتن بیاین یه پروژه رو انجام بدید برامون با هم با واریز باقی حقوق موافقت میکنیم...

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مورد نظر بنویسید: @sepehr-safaeian 

[tajrobe.github.io/داده-پردازی-آموت/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%DB%8C-%D8%A2%D9%85%D9%88%D8%AA/)
