### ISSUE TITLE
شرکت ایلیا استیل

### ISSUE THREAD

**Issue by momi23899** [tajrobe/tajrobe.github.io#365]
##### نام شرکت ایلیا استیل
title: ""

##### نام انگلیسی شرکت Iliasteel
name_en: ""

##### دسته‌ی فعالیت شرکت هود و سینک و گاز رومیزی
industry: ""

##### موقعیت مکانی شرکت تهران شریعتی
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت تهران شریعتی
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by momi23899** [comment]
شرکت ایلیا استیل بسیار ضعیف در قسمت مدیریت عامل و منابع انسانی ، حجم کار به شدت بالا نسبت به حقوق دریافتی ، هیچ چیز جدیدی یاد نمیگیرید ، رفتار مدیریت عامل بسیار زشت و زننده ، نیرو های جدید پس از 6 ماه حضور در شرکت استعفا میدهند ، اقدام حقوقی وکیل شرکت برروی چک و سفته پرسنل

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مورد نظر بنویسید: @momi23899 
[tajrobe.github.io/ایلیا-استیل/](https://tajrobe.github.io/%D8%A7%DB%8C%D9%84%DB%8C%D8%A7-%D8%A7%D8%B3%D8%AA%DB%8C%D9%84/)
