### ISSUE TITLE
شرکت 

### ISSUE THREAD

**Issue by navid20015** [tajrobe/tajrobe.github.io#366]
نام شرکت

**Comment by tajrobe** [comment]
[tajrobe.github.io/راهکار-اندیشان-سپاروک/](https://tajrobe.github.io/%D8%B1%D8%A7%D9%87%DA%A9%D8%A7%D8%B1-%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%D8%A7%D9%86-%D8%B3%D9%BE%D8%A7%D8%B1%D9%88%DA%A9/)
