### ISSUE TITLE
add intsoft company

### ISSUE THREAD

**Issue by citayesh** [tajrobe/tajrobe.github.io#367]
##### نام شرکت
title: "اینت سافت"

##### نام انگلیسی شرکت
name_en: "intsoft"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "netherlands"

##### تعداد نفرات شرکت
size: "2-10"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "Our company in the Netherlands has developed an innovative mobile app using state-of-the-art technologies and with great potential for scaling. If you're an ambitious, open-minded person willing to engage in startup adventures, this is the right place for you.
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/اینت-سافت/](https://tajrobe.github.io/%D8%A7%DB%8C%D9%86%D8%AA-%D8%B3%D8%A7%D9%81%D8%AA/)
