### ISSUE TITLE
(جاده) ابتکار آفرینان افق اندیشه

### ISSUE THREAD

**Issue by haedarfarhani** [tajrobe/tajrobe.github.io#368]

**Comment by tajrobe** [comment]
[tajrobe.github.io/ابتکار-آفرینان-افق-اندیشه/](https://tajrobe.github.io/%D8%A7%D8%A8%D8%AA%DA%A9%D8%A7%D8%B1-%D8%A2%D9%81%D8%B1%DB%8C%D9%86%D8%A7%D9%86-%D8%A7%D9%81%D9%82-%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%D9%87/)
