### ISSUE TITLE
فرصت گستر فردا

### ISSUE THREAD

**Issue by rajausercompany** [tajrobe/tajrobe.github.io#370]
##### نام شرکت
title: "فرصت گستر فردا"

##### نام انگلیسی شرکت
name_en: "forsatgostar"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات / نرم افزار و سخت افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "forsatgostar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مشاوران فرصت گستر ، مجموعه ای چابک برای توسعه نیازمندی های فرایندی کسب و کارها در حوزه فناوری اطلاعات و ارتباطات و تکنولوژی های نوین با پنج سال سابقه فعالیت و دامنه مشتریان متنوع است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فرصت-گستر-فردا/](https://tajrobe.github.io/%D9%81%D8%B1%D8%B5%D8%AA-%DA%AF%D8%B3%D8%AA%D8%B1-%D9%81%D8%B1%D8%AF%D8%A7/)
