### ISSUE TITLE
فرصت گستر فردا

### ISSUE THREAD

**Issue by truthonraja** [tajrobe/tajrobe.github.io#371]
description: 'این شرکت فرصت گستر فردا همان شرکته فناوری اطلاعات رجاء است که توسط محمد شفیعی نیا اداره می شود و برای گرفتن کارمندان جدید به دلیل بدنامی شرکت قبلی،اخیرا به نام این شرکتی که تازه ثبت کرده آگهی میگزاره .
پس برای اطلاعات بیشتر به شرکت فناوری اطلاعات رجاء مراجعه کنید.
  '

state: کارآموز

job_name: ''

company_slug: 'فرصت گستر فردا'

pros: ''

cons: ''

rate:  1.0

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مربوطه بنویسید @truthonraja 

[tajrobe.github.io/فرصت-گستر-فردا/](https://tajrobe.github.io/%D9%81%D8%B1%D8%B5%D8%AA-%DA%AF%D8%B3%D8%AA%D8%B1-%D9%81%D8%B1%D8%AF%D8%A7/)
