### ISSUE TITLE
شرکت توسعه خدمات شبکه پیام سامان

### ISSUE THREAD

**Issue by mohsenshahrii** [tajrobe/tajrobe.github.io#372]

**Comment by tajrobe** [comment]
[tajrobe.github.io/توسعه-خدمات-شبکه-پیام-سامان/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D8%B4%D8%A8%DA%A9%D9%87-%D9%BE%DB%8C%D8%A7%D9%85-%D8%B3%D8%A7%D9%85%D8%A7%D9%86/)
