### ISSUE TITLE
توسعه فن آوری خوارزمی

### ISSUE THREAD

**Issue by asadi12658** [tajrobe/tajrobe.github.io#373]
##### نام شرکت توسعه فن آوری خوارزمی
title: ""

##### نام انگلیسی شرکت kharazmi
name_en: ""

##### دسته‌ی فعالیت شرکت ای تی
industry: ""

##### موقعیت مکانی شرکت خیابان مطهری
city: ""

##### تعداد نفرات شرکت 500
size: ""

##### آدرس سایت شرکت https://kharazmico.com/
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش درحوزه پشتیبانی بانکی فعالیت دارد 
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/توسعه-فناوری-اطلاعات-خوارزمی/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA-%D8%AE%D9%88%D8%A7%D8%B1%D8%B2%D9%85%DB%8C/)
