### ISSUE TITLE
پارس حیان

### ISSUE THREAD

**Issue by alimokhtarifar** [tajrobe/tajrobe.github.io#374]
##### نام شرکت
title: "پارس حیان"

##### نام انگلیسی شرکت
name_en: "pars hayan"

##### دسته‌ی فعالیت شرکت
industry: "دارویی و آرایشی بهداشتی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "1000-2000"

##### آدرس سایت شرکت
site: "parshayan.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "
شرکت داروسازی پارس‌حیان یک گروه دارویی-بهداشتی با بیش از ۴۰ سال قدمت است که توسط دو تن از دانشمندان سرشناس، محقق و اساتید دانشگاه‌های فرانسه و ایران، سرکار خانم‌ها دکتر رقیه گلوبندی و دکتر زهرا گلوبندی در سال ۱۳۶۱ تأسیس گردیده است و به نوآوری، کیفیت، کارآفرینی و مسئولیت اجتماعی شهرت دارد. این شرکت بیش از ۱۰۰۰ محصول را در قالب ۱۴ برند و ساب‌برند به مصرف‌کنندگان ایرانی و همچنین کشورهای روسیه، عراق، کویت، افغانستان، تاجیکستان، آذربایجان، لبنان، عمان و ارمنستان عرضه می‌کنند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پارس-حیان/](https://tajrobe.github.io/%D9%BE%D8%A7%D8%B1%D8%B3-%D8%AD%DB%8C%D8%A7%D9%86/)
