### ISSUE TITLE
ماورانت

### ISSUE THREAD

**Issue by alirezakhani** [tajrobe/tajrobe.github.io#375]
##### نام شرکت
title: "ماورانت"

##### نام انگلیسی شرکت
name_en: "Mavaranet"

##### دسته‌ی فعالیت شرکت
industry: "برندینگ پزشکی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "160"

##### آدرس سایت شرکت
site: "mavaranet.net"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ماورانت اولین و بزرگترین آژانس برندینگ با تمرکز بر متخصصین درمانی در خاورامیانه"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ماورانت/](https://tajrobe.github.io/%D9%85%D8%A7%D9%88%D8%B1%D8%A7%D9%86%D8%AA/)
