### ISSUE TITLE
پایشگران مدیریت طرح (پایشگران MT)

### ISSUE THREAD

**Issue by paria-msv** [tajrobe/tajrobe.github.io#376]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پایشگران-مديريت-طرح/](https://tajrobe.github.io/%D9%BE%D8%A7%DB%8C%D8%B4%DA%AF%D8%B1%D8%A7%D9%86-%D9%85%D8%AF%D9%8A%D8%B1%D9%8A%D8%AA-%D8%B7%D8%B1%D8%AD/)
