### ISSUE TITLE
پایشگران مدیریت طرح

### ISSUE THREAD

**Issue by paria-msv** [tajrobe/tajrobe.github.io#377]
description: 'شرح تجربه‌ی شما'

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'نام شرکت'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by paria-msv** [comment]
**تجربه بسیار بد از همکاری**
من حدود 6 ماه در این شرکت به عنوان نیروی تست کار کردم.
 به شدت این پوزیشن شغلی براشون بی ارزشه و بیگاری شدید میکشن از نیرو و به هیچ عنوان اجازه اظهار نظر برای تعیین زمان تست و موارد دیگه ندارید و همه این موارد از سمت مدیرعامل نعیین میشه و یا یک سری از دولوپرهای بی سواد قدیمی. و در واقع همه اجازه دخالت در روند تست دارن و حتی توهین دارن ولی نیروی تست فقط باید سکوت کنه و بیگاری بکشه. و بزگترین معظل اینه که نیروی قدیمی اونجا که به عنوان سرپرست تست هست به شدت دورو هست و به هیچ عنوان از نیروی تست حمایت نمیکنه از ترس به خطر افتادن موقعیت خودش و زمانی که باهاش صحبت میکنی تایید میکنه ولی در مواقعی که باید در جلسه حضور پیدا کنه و صحبت کنه کاملا رک عنوان میکنه که به من ربطی نداره و خودت باید مشکلت رو رفع کنی و من هیج حرفی نمیزنم و در جلسه حضور پیدا نمیکنم!!!!! 
در مورد خود شرکت هم که بخوام بگم : 
- مدیرعامل بسیار بی منطق و بیسواد هست و همیشه باید با نظر اشتباه اون پیش رفت و اگر مخالفت کنی سریع بهت توهین میکنه وتعادل در رفتار نداره به طوری که یک روز خوب رفتار میکنه یک روز بد، نیرویی اونجا ارزش داره که مدام پاچه خواری مدیرعامل رو کنه و بی دلیل ازش تعریف کنه و بله قربان گو باشه.
- از تکنولوژی های بسیار قدیمی و منسوخ شده استفاده میکنن.
- لول برنامه نویس ها به شدت پایینه و سطح کدی که نوشته میشه در حد ریویو هست.
- **قرارداد دو برگه ای هست و فقط قرارداد وزارت کار رو تحویل میدن.**
- برای پرداخت اضافه کار و کسر کار خارج از عرف وزارت کار رفتار میکنن.
- پرداخت عیدی و سنوات براساس پاییه حقوق پرداخت میشه که همون هم حداقل ترین حالت در نظر گرفته میشه!!!
- تجهیزات بسیار قدیمی و از کار افتاده در اختیارت قرارد میدن و در صورت درخواست نیز هیچ اقدامی صورت نمیگیره.
- صبحانه ای که شرکت میده اصلا قابل خوردن نیست و مجور هستی وسایل صبحانه تهیه کنی و صبحانه ای که در اختیار پرسنل قرار میدن با صبحانه مدیرعامل کاملا متفاوته.
- مدیرعامل برای تولدها تبعیض قائل میشه و هزینه تهیه کیک فقط برای 3،4 تا نیروی سوگلی پرداخت میشه و برای باقی نیرو ها حتی تبریک هم گفته نمیشه.
- برای زمان و زحمت نیرو ارزش قائل نیستن.
- به هیچ عنوان وارد تیم عمر ایران نشید که زمان کوتاهی دوام میارید چندین سال هست که فقط 3 تا نیروی ثابت رو داره که ساعتی هستن.. بخاطر در رابطه بودن مدیرپروژه با سرپرست تست هرکسی نمیتونه اونجا دوام بیاره چون باید طوری رفتار کنی که همیشه خانم تست ازت راضی باشه و حالش با تو خوب باشه وگرنه مدیر پروژه سریع وارد کار میشه و موقع رفتنت فرا میرسه!!!! 
- موقع مصاحبه وعده های زیاده داده میشه که هیچ یک عملی نمیشه!!

**Comment by tajrobe** [comment]
[tajrobe.github.io/پایشگران-مديريت-طرح/](https://tajrobe.github.io/%D9%BE%D8%A7%DB%8C%D8%B4%DA%AF%D8%B1%D8%A7%D9%86-%D9%85%D8%AF%D9%8A%D8%B1%D9%8A%D8%AA-%D8%B7%D8%B1%D8%AD/)
