### ISSUE TITLE
توربین های گازی صنعتی خاورمیانه 

### ISSUE THREAD

**Issue by mohrezakiaan** [tajrobe/tajrobe.github.io#378]
##### نام شرکت توربین های گازی صنعتی خاورمیانه 
title: ""

##### نام انگلیسی شرکت MIGT
name_en: ""

##### دسته‌ی فعالیت شرکت ساخت توربین های گازی
industry: ""

##### موقعیت مکانی شرکت شهرک صنعتی شمس آباد
city: ""

##### تعداد نفرات شرکت 500نفر
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش ساخت توربین های گازی جهت تولید برق و انتقال گاز
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/توربین-های-گازی-صنعتی-خاورمیانه/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B1%D8%A8%DB%8C%D9%86-%D9%87%D8%A7%DB%8C-%DA%AF%D8%A7%D8%B2%DB%8C-%D8%B5%D9%86%D8%B9%D8%AA%DB%8C-%D8%AE%D8%A7%D9%88%D8%B1%D9%85%DB%8C%D8%A7%D9%86%D9%87/)
