### ISSUE TITLE
توربین های گازی صنعتی خاورمیانه 

### ISSUE THREAD

**Issue by mohrezakiaan** [tajrobe/tajrobe.github.io#379]
description: 'من تحت عنوان حسابدار توو مجموع حدود 5 سال 
خالصانه فعالیت داشتم و خدایی از جونو دل مایه میذاشتم برا شرکت اما متاسفانه یک شبه عذر منو خواستن بدون هیچ دلیل خاصی.. متاسفانه اونجا نیرو انسانی براشون اهمیت زیادی نداره و فوق العاده شدید باندبازی هستش'

state: تمام وقت

job_name: 'کارشناس مالی'

company_slug: 'شرکت توربین های گازی صنعتی خاورمیانه'

pros: 'حقوق به موقع,کارانه'

cons: 'محیط فوق العاده بد,باند بازی,بی ارزش بودن نیرو انسانی'

rate: 2.5

**Comment by tajrobe** [comment]
[tajrobe.github.io/توربین-های-گازی-صنعتی-خاورمیانه/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B1%D8%A8%DB%8C%D9%86-%D9%87%D8%A7%DB%8C-%DA%AF%D8%A7%D8%B2%DB%8C-%D8%B5%D9%86%D8%B9%D8%AA%DB%8C-%D8%AE%D8%A7%D9%88%D8%B1%D9%85%DB%8C%D8%A7%D9%86%D9%87/)
