### ISSUE TITLE
شرکت مهندسی نصب و راه اندازی نفت ایرانیان

### ISSUE THREAD

**Issue by amirdoulat** [tajrobe/tajrobe.github.io#38]
##### نام شرکت
title: "شرکت مهندسی نصب و راه اندازی نفت ایرانیان"

##### نام انگلیسی شرکت
name_en: "saffron"

##### دسته‌ی فعالیت شرکت
industry: "پتروشیمی"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://ioecc.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ایجاد بستر یکپارچه برای مدیریت و نظارت صنایع پتروشیمی"

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/شرکت-مهندسی-نصب-راه-اندازی-نفت-ایرانیان/](https://tajrobe.github.io/%D8%B4%D8%B1%DA%A9%D8%AA-%D9%85%D9%87%D9%86%D8%AF%D8%B3%DB%8C-%D9%86%D8%B5%D8%A8-%D8%B1%D8%A7%D9%87-%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-%D9%86%D9%81%D8%AA-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%DB%8C%D8%A7%D9%86/)
