### ISSUE TITLE
مبل الدورادو

### ISSUE THREAD

**Issue by Eldoradu** [tajrobe/tajrobe.github.io#380]
##### نام شرکت
title: "مبل الدورادو"

##### نام انگلیسی شرکت
name_en: "eldoradosofagroup"

##### دسته‌ی فعالیت شرکت
industry: "تولید مبلمان"

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Eldoradu** [comment]
با تشابه اسمی به برند قدیمی الدورادو با مدیریت جدید و خاله زنک بازی
بدترین شرایط کاری با ادعای زیاد
درگیری سر هر چیزی و خاله زنک بازی که مدیر عامل آن به وجود آورده

**Comment by tajrobe** [comment]
لطفا تجربه خود را در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/مبلمان-الدورادو/](https://tajrobe.github.io/%D9%85%D8%A8%D9%84%D9%85%D8%A7%D9%86-%D8%A7%D9%84%D8%AF%D9%88%D8%B1%D8%A7%D8%AF%D9%88/)
