### ISSUE TITLE
Useful 

### ISSUE THREAD

**Issue by Ahmadmsv** [tajrobe/tajrobe.github.io#381]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
با سلام
مشخصات شرکتی با این نام پیدا نشد؛ لطفا اطلاعات بیشتری درباره شرکت مورد نظر وارد کنید.
