### ISSUE TITLE
تولیدی صنعتی پکاشیمی

### ISSUE THREAD

**Issue by aa001010** [tajrobe/tajrobe.github.io#384]
##### نام شرکت
title: ""
تولیدی صنعتی پکاشیمی
##### نام انگلیسی شرکت
name_en: ""Pekachemie

##### دسته‌ی فعالیت شرکت
industry: ""تولید رنگ پودری

##### موقعیت مکانی شرکت
city: ""دفتر مرکزی: سعادت آباد   کارخانه: شهرک صنعتی شمس آباد

##### تعداد نفرات شرکت
size: ""260

##### آدرس سایت شرکت
site: ""https://pekachemie.com/fa

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
شرکت تولیدی صنعتی پکاشیمی با هدف تولید انواع پوشش های صنعتی و رنگ پودری در اسفند سال 1374 تأسیس گردید وکار مطالعه و طراحی تولید رنگ های پودری الکترواستاتیک را در سالهای 1375 و1376 به انجام رسانید.این شرکت مراحل تهیه ونصب ماشین آلات و تجهیزات خط تولید را در سال 1377 پشت سر گذاشته در سال 1378 موفق به تولید آزمایشی این رنگ ها گردید و نهایتا از اوایل سال 1379 تولید انبوه انواع [رنگ های پودری] را آغاز نمود.این شرکت با برنامه ریزی و مدیریت و اجرای طرحهای توسعه در مراحل مختلف هم اکنون با برخوداری از خطوط تولید متعدد و بهره گیری از آخرین تکنولوژی های تولید رنگ های پودری در زمره بزرگترین تولید کنندگان این محصولات در منطقه به شمار می رود.

**Comment by tajrobe** [comment]
[tajrobe.github.io/پکاشیمی/](https://tajrobe.github.io/%D9%BE%DA%A9%D8%A7%D8%B4%DB%8C%D9%85%DB%8C/)
