### ISSUE TITLE
KianTC

### ISSUE THREAD

**Issue by ahmadmhm** [tajrobe/tajrobe.github.io#385]
##### نام شرکت
title: "کیان تجارت شریف"

##### نام انگلیسی شرکت
name_en: "kian tc"

##### دسته‌ی فعالیت شرکت
industry: "software development"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "10-20"

##### آدرس سایت شرکت
site: "https://www.kiantc.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "در حوزه توسعه اپلیکیشن های موبایل و وب"

**Comment by tajrobe** [comment]
[tajrobe.github.io/کیان-تجارت/](https://tajrobe.github.io/%DA%A9%DB%8C%D8%A7%D9%86-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA/)
