### ISSUE TITLE
فناوری اطلاعات نام آوران عصرنوین (فنحاب زیر ساخت)

### ISSUE THREAD

**Issue by natanailmaybe** [tajrobe/tajrobe.github.io#386]
##### نام شرکت
title: "فناوری اطلاعات نام آوران عصرنوین (فنحاب زیر ساخت)"

##### نام انگلیسی شرکت
name_en: "Fannavari Etelaat Namavaran AsreNovin (Fanhab Zirsakht) "

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات و زیرساخت"

##### موقعیت مکانی شرکت
city: "پارک فناوری پردیس-تهران"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://fanhab.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فنحاب نظر به راهبرد و سیاست بیمه مرکزی جمهوری اسلامی ایران در راستای پیاده‌سازی اهداف ارائه خدمات از طریق دولت الکترونیک، استقرار حاکمیت فناوری اطلاعات و ایجاد مرکز داده مستقل و پشتیبان برای خود نسبت به تأمین شبکه و زیرساخت مرکز داده اقدام گردیده که محل استقرار آن، پارک فناوری پردیس است ."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فناپ-زیرساخت/](https://tajrobe.github.io/%D9%81%D9%86%D8%A7%D9%BE-%D8%B2%DB%8C%D8%B1%D8%B3%D8%A7%D8%AE%D8%AA/)
