### ISSUE TITLE
آریان گلاره

### ISSUE THREAD

**Issue by Tuolumne1** [tajrobe/tajrobe.github.io#387]
آریان گلاره نام شرکت
title: ""

Ariyan gelare نام انگلیسی شرکت
name_en: ""
صنایع غذایی دسته‌ی فعالیت شرکت
industry: ""

نظرآباد موقعیت مکانی شرکت
city: ""

۲۰۰ تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/آریان-گلاره-(رزا)/](https://tajrobe.github.io/%D8%A2%D8%B1%DB%8C%D8%A7%D9%86-%DA%AF%D9%84%D8%A7%D8%B1%D9%87-(%D8%B1%D8%B2%D8%A7)/)
