### ISSUE TITLE
صدگان سامانه هوشمند

### ISSUE THREAD

**Issue by SK19002N3** [tajrobe/tajrobe.github.io#388]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/صدگان-سامانه-هوشمند/](https://tajrobe.github.io/%D8%B5%D8%AF%DA%AF%D8%A7%D9%86-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF/)
