### ISSUE TITLE
تجربه کار با شرکت

### ISSUE THREAD

**Issue by SK19002N3** [tajrobe/tajrobe.github.io#389]
description: 'من نزدیک 2 سال با این شرکت کار میکردم. یکی از بی نظم ترین شرکتهایی بود که باهاشون کار کردم. مدیریت نادرست و بی نظمی در شرکت بی داد می کنه.'

state: تمام وقت

job_name: 'برنامه نویس'

company_slug: 'صدگان'

pros: 'حقوق بالا و به موقع'
 

rate: 1

**Comment by tajrobe** [comment]
[tajrobe.github.io/صدگان-سامانه-هوشمند/](https://tajrobe.github.io/%D8%B5%D8%AF%DA%AF%D8%A7%D9%86-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF/)
