### ISSUE TITLE
شرکت مشاور مدیریت و خدمات ماشینی تامین

### ISSUE THREAD

**Issue by khasragh** [tajrobe/tajrobe.github.io#39]
##### نام شرکت
title: "شرکت مشاور مدیریت و خدمات ماشینی تامین"

##### نام انگلیسی شرکت
name_en: "Tamin (ICT & Management Consultancy)"

##### دسته‌ی فعالیت شرکت
industry: " نرم افزار و خدمات سخت افزار و شبکه و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "+600"

##### آدرس سایت شرکت
site: "www.taminn.org"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مشاور مدیریت و خدمات ماشینی تامین وارد چهارمین دهه از فعالیت خود می شود، در سالهای اخیر خدماتی ارزنده در قالب پروژه های ملی توسط شرکت به انجام رسیده که از آن جمله می توان به پروژه بانک جامع اطلاعات ایرانیان ، پروژه ملی ۳۰۷۰، پروژه ملی نسخه الکترونیک و ... اشاره نمود. 
![aaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/58873008/149757908-9f887011-334f-43d3-9109-42edc593e3f9.jpg)

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/خدمات-ماشینی-تامین/](https://tajrobe.github.io/%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D9%85%D8%A7%D8%B4%DB%8C%D9%86%DB%8C-%D8%AA%D8%A7%D9%85%DB%8C%D9%86/)
