### ISSUE TITLE
 آپتاسیس آپادانا تابناک سیستم 

### ISSUE THREAD

**Issue by ArashNazariGH** [tajrobe/tajrobe.github.io#391]
##### نام شرکت
title: "" آپتاسیس 

##### نام انگلیسی شرکت
name_en: "" aptasys 

##### دسته‌ی فعالیت شرکت
industry: "" تجهیزات آزمایشگاهی 

##### موقعیت مکانی شرکت
city: "" شهرک گلستان 

##### تعداد نفرات شرکت
size: "" ۱۰۰

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "" واردات دستگاه های آزمایشگاهی و تولید کیت های آزمایشگاهی

**Comment by tajrobe** [comment]
[tajrobe.github.io/آپتاسیس/](https://tajrobe.github.io/%D8%A2%D9%BE%D8%AA%D8%A7%D8%B3%DB%8C%D8%B3/)
