### ISSUE TITLE
شرکت طراحی نگاراندیشگان

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#392]
##### نام شرکت
title: "شرکت طراحی نگاراندیشگان"

##### نام انگلیسی شرکت
name_en: "Negar andishgan"

##### دسته‌ی فعالیت شرکت
industry: "تجهیزات پزشکی"

##### موقعیت مکانی شرکت
city: "پردیس"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://negand.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت دانش بنیان طراحی نگاراندیشگان تولیدکننده دستگاه های EEG و EMG، با کاربردهای تحقیقاتی و کلینیکی، در ایران می باشد. این شرکت با داشتن 25 سال سابقه‌، تحت نظارت یک تیم مجرب دستگاه های EEG ،EMG ،LTM و لوازم جانبی آن ها را مطابق با فناوری روز تولید می کند. در حال حاضر محل اصلی فعالیت شرکت پارک فناوری پردیس می‌باشد."

**Comment by ghost** [comment]
مراحل مصاحبه خوب و محترمانه طی می‌شه. حقوق‌های خیلی پایین داده می‌شه و در مراحل استخدام صحبتی از حقوق نمی کنند تا در مقابل عمل انجام شده قرار بگیرید. مدیرای اصلی شرکت ساکن ایران نیستند و مدیرایی که ایران هستند شرکت رو به صورت هیئتی اداره می کنند. مدیر تولید شخص بی سواد و بی شخصیتی هست که سابقه ی حرکات شنیع، دور از اخلاق و زننده‌ی بسیاری داشته و داره توی شرکت. بیمه‌ی تکمیلی یکسال بعد از حضور براتون ممکن میشه که یه بخشی از هزینش از حقوقتون کم میشه. بابت امریه‌ی سربازی و سایر امتیازها هم وعده داده می‌شه ولی معمولا عملی نمی‌شه. اساس کار شرکت و تشویقی‌های شرکت غیر حرفه‌ای هستش و غالبا نیروها رو تشویق به زدن زیرآب همدیگه می‌کنند.

**Comment by tajrobe** [comment]
[tajrobe.github.io/طراحی-نگاراندیشگان/](https://tajrobe.github.io/%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C-%D9%86%DA%AF%D8%A7%D8%B1%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%DA%AF%D8%A7%D9%86/)
