### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Amir-yazdanmanesh** [tajrobe/tajrobe.github.io#393]
##### نام شرکت
title: "دیجیتون"

##### نام انگلیسی شرکت
name_en: "digitoon"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/دیجیتون/](https://tajrobe.github.io/%D8%AF%DB%8C%D8%AC%DB%8C%D8%AA%D9%88%D9%86/)
