### ISSUE TITLE
کتابخانه عمومی

### ISSUE THREAD

**Issue by bahararia** [tajrobe/tajrobe.github.io#394]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/کتابخانه-عمومی-کشور/](https://tajrobe.github.io/%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87-%D8%B9%D9%85%D9%88%D9%85%DB%8C-%DA%A9%D8%B4%D9%88%D8%B1/)
