### ISSUE TITLE
راهکار اندیشان ویرا سیستم

### ISSUE THREAD

**Issue by shaahinmail** [tajrobe/tajrobe.github.io#395]
##### نام شرکت
title: "راهکار اندیشان ویرا سیستم"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "نرم افزار، فروش و استقرار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "25"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by shaahinmail** [comment]
شرکت راهکار اندیشان ویرا سیستم، تحت لیسانس همکاران سیستم، در سال 1398 با مسئولیت فروش، استقرار و آموزش نرم‌افزارهای همکاران سیستم تأسیس شد. طی این مدت زمان، برای بیش از 100 شرکت بزرگ و متوسط در صنایع مختلف، نرم‌افزارهای راهکاران و راهکاران ابری همکاران سیستم را با موفقیت پیاده سازی کرده است. این شرکت در حوزه محصولات مالی، سرمایه‌انسانی،تدارکات و لجستیک، فروش‌، تولید، حسابداری مدیریت و مدیریت فرآیند کسب و کار متخصص است.

شرکت راهکار اندیشان ویرا سیستم، بعنوان شریک توسعه دهنده محصول (Build partner) نیز در حال فعالیت است

**Comment by tajrobe** [comment]
[tajrobe.github.io/راهکار-اندیشان-ویرا-سیستم/](https://tajrobe.github.io/%D8%B1%D8%A7%D9%87%DA%A9%D8%A7%D8%B1-%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%D8%A7%D9%86-%D9%88%DB%8C%D8%B1%D8%A7-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85/)
