### ISSUE TITLE
توسعه گران نرم افزار آذربایجان 

### ISSUE THREAD

**Issue by asdcoasdco** [tajrobe/tajrobe.github.io#396]
##### نام شرکت
title: "توسعه گران نرم افزار آذربایجان"

##### نام انگلیسی شرکت
name_en: "ASDCO"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات"

##### موقعیت مکانی شرکت
city: "تبریز"

##### تعداد نفرات شرکت
size: "50-100"

##### آدرس سایت شرکت
site: "WWW.ASD.IR"

##### توضیحی درباره شرکت و فعالیت‌هایش
content"شرکت دانش بنیان توسعه گران نرم افزار آذربایجان  "

**Comment by tajrobe** [comment]
[tajrobe.github.io/توسعه-گران-نرم-افزار-آذربایجان/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D8%B9%D9%87-%DA%AF%D8%B1%D8%A7%D9%86-%D9%86%D8%B1%D9%85-%D8%A7%D9%81%D8%B2%D8%A7%D8%B1-%D8%A2%D8%B0%D8%B1%D8%A8%D8%A7%DB%8C%D8%AC%D8%A7%D9%86/)
