### ISSUE TITLE
آنی‌جا | Anyja

### ISSUE THREAD

**Issue by Mahit01** [tajrobe/tajrobe.github.io#397]
##### نام شرکت
title: ""آنی‌جا

##### نام انگلیسی شرکت
name_en: ""Anyja

##### دسته‌ی فعالیت شرکت
industry: "" رزرو اقامتگاه

##### موقعیت مکانی شرکت
city: "" تهران

##### تعداد نفرات شرکت
size: "" 35

##### آدرس سایت شرکت
site: ""https://anyja.ir

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
رزرو آنلاین اقامتگاه

**Comment by Mahit01** [comment]
از وقتی آنیجا کلا 3 نفر بودن بهشون اضافه شدم. و الان 35 نفر هستیم. آنیجا بدون سرمایه گذاری بیرونی و به صورت بوت استرپ رشد کرده و همین الان داریم با قدیمی های این حوزه رقابت میکنیم.
از روز اول کار، چیزی که برام جالب بود، محیط دوستانه و صمیمی شرکت بود. مدیر و بنیان گذار آنیجا زودتر از همه سرکار میاد و نفر آخر میره بیرون. تقریبا در همه این سالها به همین صورت بوده. و تا جایی که بتونه برای حل مسائل کنار پرسنل شرکت هست.
از اینکه عضوی از بدنه شرکت آنی‌جا هستم احساس خوبی دارم.
نقش من توی شرکت آنیجا، تحقیق و بررسی برای طراحی امکانات جدید توی اپلیکیشن هست. با توجه به اینکه فعالیت ما رزرو اقامتگاهه، روزانه صدها بازخورد میگیریم و من وظیفه دارم بر اساس نیاز بازار و مخاطبان، راه حل هایی برای بهبود کسب و کارمون ارائه بدم.

**Comment by tajrobe** [comment]
[tajrobe.github.io/آنی-جا/](https://tajrobe.github.io/%D8%A2%D9%86%DB%8C-%D8%AC%D8%A7/)
