### ISSUE TITLE
پارس آدرخش

### ISSUE THREAD

**Issue by parsazarakhsh** [tajrobe/tajrobe.github.io#399]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پارس-آذرخش/](https://tajrobe.github.io/%D9%BE%D8%A7%D8%B1%D8%B3-%D8%A2%D8%B0%D8%B1%D8%AE%D8%B4/)
