### ISSUE TITLE
جهان ارقام پارس(جامپ

### ISSUE THREAD

**Issue by Negar1985** [tajrobe/tajrobe.github.io#40]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Negar1985** [comment]
من حدود دو سال در اين شركت كار كردم.به شدت به لحاظ مديريتي و نيز منابع انساني ضعيف مي باشد. به نظرم براي افراد جونيور كه استاندارد خاصي براي محيط كار در ذهن نداشته باشند مناسب خواهد بود ولي نيروهاي سينيور صرفا سرخورده شده و چالش هاي بيهوده خواهند داشت.

**Comment by tajrobe** [comment]
new company added: [https://tajrobe.github.io/جهان-ارقام-پارس/](https://tajrobe.github.io/%D8%AC%D9%87%D8%A7%D9%86-%D8%A7%D8%B1%D9%82%D8%A7%D9%85-%D9%BE%D8%A7%D8%B1%D8%B3/)

@Negar1985 خواهشمند است تجربه خود را در [این صفحه](https://tajrobe.github.io/review/?slug=jahan-argham-pars&name=%D8%AC%D9%87%D8%A7%D9%86-%D8%A7%D8%B1%D9%82%D8%A7%D9%85-%D9%BE%D8%A7%D8%B1%D8%B3) ثبت کنید.
