### ISSUE TITLE
شرکت کهکشان نور 

### ISSUE THREAD

**Issue by smrt98** [tajrobe/tajrobe.github.io#402]
##### نام شرکت
title: "کهکشان نور"

##### نام انگلیسی شرکت
name_en: "kahkeshan noor"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "50 تا 100"

##### آدرس سایت شرکت
site: "www.kahkeshan.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "کهکشان نور، عضوی از یک خانواده بزرگ است! خانواده‌ای از جنس کهکشان با تمرکز بر ارایه خدمات تخصصی حوزه فناوری اطلاعات. با تخصصی‌تر شدن حوزه فناوری اطلاعات و خاص شدن نیاز سازمان‌ها، موسسه کهکشان اقدام به تاسیس شرکت‌های دیگری از جمله کهکشان مشاور ایمن و فن‌آور کهکشان دانا کرد که در زیر مجموعه گروه شرکت‌های کهکشان به ارایه خدمات تخصصی فناوری اطلاعات می‌پردازند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/کهکشان-نور/](https://tajrobe.github.io/%DA%A9%D9%87%DA%A9%D8%B4%D8%A7%D9%86-%D9%86%D9%88%D8%B1/)
