### ISSUE TITLE
تک باغ

### ISSUE THREAD

**Issue by villadoost** [tajrobe/tajrobe.github.io#403]
##### نام شرکت
title: "تک باغ"

##### نام انگلیسی شرکت
name_en: "takbagh"

##### دسته‌ی فعالیت شرکت
industry: "معماری منظر"

##### موقعیت مکانی شرکت
city: "ایران،تهران"

##### تعداد نفرات شرکت
size: "15"

##### آدرس سایت شرکت
site: "https://takbagh.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "خدمات ارائه شده توسط تک باغ: ۱. طراحی و اجرای محوطه‌سازی ویلاها و باغ‌ها با توجه به نیازها و سلیقه‌های مشتریان. ۲. ایجاد فضاهای استراحتی و تفریحی زیبا و دلپذیر. ۳. ارائه خدمات نگهداری و مراقبت از فضاهای سبز به منظور حفظ زیبایی و دوام آن‌ها. ۴. انجام پروژه‌های نورپردازی منحصر به فرد برای افزایش جذابیت شبانه فضاهای سبز."

**Comment by villadoost** [comment]
مزایای استفاده از برند تک باغ: ۱. طراحی منحصر به فرد: تیم تخصصی ما با درک عمیق از ذائقه‌ها و نیازهای مشتریان، به طراحی فضاهای سبز منحصر به فردی می‌پردازد که جذابیت و زیبایی ویلا را افزایش می‌دهد. ۲. استفاده از مواد با کیفیت: در تمامی مراحل ساخت و طراحی، از مواد با کیفیت و متناسب با استانداردهای بین‌المللی استفاده می‌شود تا اطمینان از دوام و کیفیت بالای اجرا به دست آید. ۳. توجه به جزئیات: هر جزئی از محوطه‌سازی، از جمله انتخاب گیاهان، نورپردازی، امکانات آبیاری و... با دقت بالا و به روشی حرفه‌ای طراحی و اجرا می‌شود تا به بهترین نتیجه ممکن دست یابیم. ۴. پشتیبانی و خدمات پس از فروش: برند تک باغ تا آخرین لحظه در کنار مشتریان خود است و از طریق ارائه خدمات پس از فروش، اطمینان از رضایت و خوشحالی مشتریان را فراهم می‌کند.

**Comment by tajrobe** [comment]
[tajrobe.github.io/معماری-منظر-تک-باغ/](https://tajrobe.github.io/%D9%85%D8%B9%D9%85%D8%A7%D8%B1%DB%8C-%D9%85%D9%86%D8%B8%D8%B1-%D8%AA%DA%A9-%D8%A8%D8%A7%D8%BA/)
