### ISSUE TITLE
پاکدون

### ISSUE THREAD

**Issue by villadoost** [tajrobe/tajrobe.github.io#404]
##### نام شرکت
title: "پاکدون"

##### نام انگلیسی شرکت
name_en: "pakdoon"

##### دسته‌ی فعالیت شرکت
industry: "هلدینگ صنعتی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "60"

##### آدرس سایت شرکت
site: "https://pakdoon.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پاکدون مدت هاست که از شرکت های برتر نظافت،سمپاشی ، تولیدکنندگان محصولات بهداشتی ، تولیدکننده ابزار بهداشتی و نظافت و فروشگا های زنجیره ای در ایران است.."

**Comment by villadoost** [comment]
گروه [پاکدون](https://pakdoon.com/) یک [هلدینگ](https://pakdoon.com/) خدماتی و صنعتی است. ما از سال 1389 این کار را انجام می دهیم. ما تاکنون در زمینه خدمات بهداشتی تعداد 3500 خدمات [نظافت](https://pakdoon.com/Cleaning-service-company) و 2200 خدمات [سمپاشی](https://pakdoon.com/pest-control-company) و مبارزه با آفات ارائه داده ایم.و بیش از 25000 قطعه ابزار بهداشتی و [نظافت](https://pakdoon.com/Cleaning-service-company) را تولید و توزیع نموده. ما تقریبا تمام خدمات بهداشتی و ابزار های بهداشتی را در فروشگا های زنجیره ای و فروشگاه های بزرگ عرضه می کنیم.مثل تولید ترولی نظافت ، انواع تی ،جارو،سطل های زباله و…و خدمات نظافت ،شیشه پاک کنی،اسباب کشی،سمپاشی و…. تولید انواع شوینده های بهداشتی مثل مایع دستشویی،ظرفشویی،لباس شویی،شیشه پاک کنی …

**Comment by tajrobe** [comment]
[tajrobe.github.io/پاکدون/](https://tajrobe.github.io/%D9%BE%D8%A7%DA%A9%D8%AF%D9%88%D9%86/)
