### ISSUE TITLE
پیمنتر | پرداخت ارزی

### ISSUE THREAD

**Issue by Tx7info** [tajrobe/tajrobe.github.io#405]
##### نام شرکت
title: "پیمنتر"

##### نام انگلیسی شرکت
name_en: "paymenter"

##### دسته‌ی فعالیت شرکت
industry: "پرداخت ارزی"

##### موقعیت مکانی شرکت
city: "مازندران"

##### تعداد نفرات شرکت
size: "18"

##### آدرس سایت شرکت
site: "http://paymenter.store/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پیمنتر سامانه خرید اشتراک پریمیوم اپلیکیشن های اندروید و ios است. با پیمنتر به راحتی کارت اعتباری یا گیفت کارت های هر فروشگاه معتبری از جمله : آیتونز، گوگل پلی، پلی استیشن، ایکس باکس، اسپاتیفای، استیم، آمازون و … که نیاز دارید را خریداری کنید.

"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیمنتر/](https://tajrobe.github.io/%D9%BE%DB%8C%D9%85%D9%86%D8%AA%D8%B1/)
