### ISSUE TITLE
صندوق شکوفایی و نوآوری ریاست جمهوری

### ISSUE THREAD

**Issue by shayanam1** [tajrobe/tajrobe.github.io#406]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by shayanam1** [comment]
توی طرح پایش سلامت کارکنان انقد چندلیتر ازت خون میگیرن انگار میخوان بفروشن.هر سال هم تکرار میشه.
حقوق کمش به کنار تازه تحقیقات محلی حین کار هم دارن!!!!!!

**Comment by tajrobe** [comment]
@shayanam1 
لطفا تجربه خود را به صورت مشروح در صفحه زیر بنویسید:

[tajrobe.github.io/صندوق-شکوفایی-ریاست-جمهوری/](https://tajrobe.github.io/%D8%B5%D9%86%D8%AF%D9%88%D9%82-%D8%B4%DA%A9%D9%88%D9%81%D8%A7%DB%8C%DB%8C-%D8%B1%DB%8C%D8%A7%D8%B3%D8%AA-%D8%AC%D9%85%D9%87%D9%88%D8%B1%DB%8C/)
