### ISSUE TITLE
فانی موبایل گیمز

### ISSUE THREAD

**Issue by parastooh79** [tajrobe/tajrobe.github.io#407]
##### نام شرکت
title: "فانی موبایل گیمز"

##### نام انگلیسی شرکت
name_en: "FunnyMobileGames"

##### دسته‌ی فعالیت شرکت
industry: "تکنولوژ‌ی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10 - 50"

##### آدرس سایت شرکت
site: "http://funnymobilegames.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "To start realising our big dreams, we chose mobile gaming as our first and main area of focus. Playing games is one of the few truly universal activities that transcends age, gender or nationality and we believe with the right product, we could reach billions of people worldwide."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فانی-موبایل-گیم/](https://tajrobe.github.io/%D9%81%D8%A7%D9%86%DB%8C-%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84-%DA%AF%DB%8C%D9%85/)
