### ISSUE TITLE
پذیرا نوش شیرین (بانیان)

### ISSUE THREAD

**Issue by faezehfathi1403** [tajrobe/tajrobe.github.io#408]
##### نام شرکت
title: " پذیرا نوش شیرین"

##### نام انگلیسی شرکت
name_en: "Pazira Noosh Shirin"

##### دسته‌ی فعالیت شرکت
industry: "صنایع غذایی"

##### موقعیت مکانی شرکت
city: "قرچک/تهران"

##### تعداد نفرات شرکت
size: "30-60"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تولید انواع کنسرو غیر گوشتی به ویژه محصولات پایه زیتون"

**Comment by tajrobe** [comment]
[tajrobe.github.io/پذیرا-نوش-شیرین/](https://tajrobe.github.io/%D9%BE%D8%B0%DB%8C%D8%B1%D8%A7-%D9%86%D9%88%D8%B4-%D8%B4%DB%8C%D8%B1%DB%8C%D9%86/)
