### ISSUE TITLE
یادگار درخشان آریا

### ISSUE THREAD

**Issue by Shamshirgar** [tajrobe/tajrobe.github.io#409]
##### یادگار درخشان آریا
title: "یادگار درخشان آریا"

##### نام انگلیسی شرکت
name_en: "Yadegar Derakhshan Aria"

##### دسته‌ی فعالیت شرکت
industry: "Web Designing"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://yadegar.net"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی وب سایت، سئو سایت و خدمات آموزشی"

**Comment by tajrobe** [comment]
[tajrobe.github.io/یادگار-درخشان-آریا/](https://tajrobe.github.io/%DB%8C%D8%A7%D8%AF%DA%AF%D8%A7%D8%B1-%D8%AF%D8%B1%D8%AE%D8%B4%D8%A7%D9%86-%D8%A2%D8%B1%DB%8C%D8%A7/)
