### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by omidjaberi79** [tajrobe/tajrobe.github.io#41]
##### نام شرکت
title: "نونگار پردازش"

##### نام انگلیسی شرکت
name_en: "npco"

##### دسته‌ی فعالیت شرکت
industry: "طراحی سایت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "npco.net"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی سایت"

**Comment by omidjaberi79** [comment]
New Com

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/نونگار-پردازش](https://tajrobe.github.io/%D9%86%D9%88%D9%86%DA%AF%D8%A7%D8%B1-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%D8%B4/)
