### ISSUE TITLE
پلتفرم جامع خدمات کشاورزی اگرویار

### ISSUE THREAD

**Issue by Ardex-0** [tajrobe/tajrobe.github.io#410]
##### نام شرکت
title: "اگرویار"

##### نام انگلیسی شرکت
name_en: "Agroyaar"

##### دسته‌ی فعالیت شرکت
industry: "IT , ICT , Agriculture , Smart agriculture"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "+50"

##### آدرس سایت شرکت
site: "www.agroyaar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه شرکت های خوشه پروران در سال 1393 با هدف تولید کودهای زیستی و شیمیایی و تامین نهاده های بخش کشاورزی شروع به فعالیت کرد ولی همواره به خوبی می‌دانستیم استفاده از بهترین کودها هم به تنهایی برای افزایش عملکرد و بهبود شرایط مزارع کافی نیستند. به دنبال حلقه گمشده این بخش و با توجه به بازخوردها و نظرات کشاورزان و همراهان عزیزمان، سرانجام در سال 1399 پا به عرصه خدمات کشاورزی گذاشتیم و این چنین بود که پس از 6 سال نیازسنجی در این حوزه پلتفرم جامع خدمات کشاورزی اگرویار متولد شد.
<img width="334" alt="Intro-1" src="https://github.com/tajrobe/tajrobe.github.io/assets/77410385/be28b5f9-957c-4522-874c-6fbd0e350c7c">
"

**Comment by tajrobe** [comment]
[tajrobe.github.io/خوشه-پروران-اگرویار/](https://tajrobe.github.io/%D8%AE%D9%88%D8%B4%D9%87-%D9%BE%D8%B1%D9%88%D8%B1%D8%A7%D9%86-%D8%A7%DA%AF%D8%B1%D9%88%DB%8C%D8%A7%D8%B1/)
