### ISSUE TITLE
سیسنو

### ISSUE THREAD

**Issue by aligarmroodi1365** [tajrobe/tajrobe.github.io#411]
##### نام شرکت
title: "سیسنو"

##### نام انگلیسی شرکت
name_en: "sisno"

##### دسته‌ی فعالیت شرکت
industry: "crm"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "sisno.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "سیستم نوبت دهی crm , hr Portal"

**Comment by tajrobe** [comment]
[tajrobe.github.io/سیسنو/](https://tajrobe.github.io/%D8%B3%DB%8C%D8%B3%D9%86%D9%88/)
