### ISSUE TITLE
سعادت رنت

### ISSUE THREAD

**Issue by saadatrentsr** [tajrobe/tajrobe.github.io#412]
نام شرکت:  شرکت بین المللی اجاره خودرو سعادت رنت (SaadatRent Car Rental Company)
https://www.saadatrent.com/
سعادت رنت با داشتن بیش از 100 نفر کارمند در شعبه های مختلف، خدماتی از قبیل:
اجاره خودرو بدون راننده
کرایه خودرو با راننده
اجاره ون و اتوبوس
اجاره ماشین عروس 
و با بیش از 98% رضایت مشتریان و گردشگران خارجی به عنوان بهترین شرکت رنت خودرو بین المللی ایرانی شناخته شده است.
تمام خودروهای اجاره ای مدل 2023 و 2024 است و با تنوع خودروهای لوکس و لاکچری، نیمه اقتصادی و اقتصادی، ناوگان سعادت رنت دارای تمامی برندهای خودرو ها می باشد. 
شعبه مرکزی: 
آدرس: تهران، شهرزیبا، بلوار تعاون، خیابان فرساد، خیابان سرو، کوچه نیلوفر ۳، پلاک ۳
شماره تماس: 02191013399
اینستاگرام: https://www.instagram.com/saadatrent/
تلگرام: https://t.me/Saadat_Rent
ساعت کاری: شنبه تا چهارشنبه از ساعت 9 الی 18 – پنج‌شنبه از ساعت 9 الی 14

**Comment by tajrobe** [comment]
[tajrobe.github.io/کارن-آوران-سعادت-آتیه/](https://tajrobe.github.io/%DA%A9%D8%A7%D8%B1%D9%86-%D8%A2%D9%88%D8%B1%D8%A7%D9%86-%D8%B3%D8%B9%D8%A7%D8%AF%D8%AA-%D8%A2%D8%AA%DB%8C%D9%87/)
