### ISSUE TITLE
Complaint 

### ISSUE THREAD

**Issue by reyazat** [tajrobe/tajrobe.github.io#414]
با سلام‌
من چندین ایمیل برای شما نوشتم که بدون پاسخ مانده ؛ اینجانب فرهاد ریاضت هیچ گونه ارتباط حقوقی رسمی و غیر رسمی با این شرکت توسعه میهن که شما نام بردید ندارم ؛  ضمنا چرا بجای وب سایت شرکت توسعه میهن وبسایت یک شرکت دیگه را نام بردید لطفاً اگر شما مدرکی برای این ارتباط داری تا ۳ روز کاری دیگر برای من بفرستید و در غیر این صورت اطلاعات مربوط به فرهاد ریاضت که کاملا غلط هست را پاک بفرمایید. بدیهی است که موارد بالا قابل پیگیری حقوقی در خارج از ایران می‌باشد
با احترام
فرهاد ریاضت

**Comment by tajrobe** [comment]
done
