### ISSUE TITLE
تجربه‌ها با ایمیل تکراری

### ISSUE THREAD

**Issue by tajrobe** [tajrobe/tajrobe.github.io#415]
@pooooriya @Aisa-Asghari @hnaderi @thejimbow

اخیرا شرکتی از طریق ایمیل با ما مکاتبه کرده و مدعی است که چندین مورد از تجربه‌های ثبت شده  در مورد آن شرکت، با یک ایمیل ثبت شده است و درخواست حذف تمامی این تجربه‌ها را دارد. مورد ادعا شده درست است و  Hash ایمیل  تمام تجربه‌های ذکر شده یکسان هستند. به نظر شما در این حالت راه‌کار بهتر کدام است:

1. تجربه‌ها دست‌نخورده باقی بمانند (چون در قوانین ثبت تجربه اشاره‌ای به ثبت تجربه با ایمیل تکراری نشده)
2. تمامی تجربه‌ها در یک مورد تجمیع شوند.
3. تمامی تجربه‌ها به جز یک مورد حذف شوند.
4. تمامی تجربه‌ها با ایمیل یکسان حذف شود.

با کدام مورد موافق هستید؟ یا راه بهتری سراغ دارید؟

**Comment by NargesArabani** [comment]
در خصوص گزینه های مطرح شده
1- از آنجایی که به جز یک مورد از تجربه ها که در آن ذکر شده در ادامه تجربه قبلی است، در بقیه موارد تجربه ها از زبان های مختلف نوشته شده است و در اصل رسایی ندارد، این گزینه به نظر میرسد گزینه خوبی نباشد. هر کسی میتواند با سو نیت تجربه های مختلف ثبت کند.
2- گزینه دوم هم چون نظرات از زبان های مختلف نوشته شده، نظر تجمیع شده، پراکنده خواهدبود.
3و 4- به نظر یکی از این گزینه ها راهکار مناسبی هستند. و همچنین تمهیدی شود تا با یک آدرس ایمیل بتوان فقط یک تجربه کاری و یک تجربه مصاحبه ثبت شود.
