### ISSUE TITLE
دیزل پارسیا

### ISSUE THREAD

**Issue by parsia20** [tajrobe/tajrobe.github.io#417]
##### نام شرکت
title: "دیزل پارسیا"

##### نام انگلیسی شرکت
name_en: "Diesel Parsia"

##### دسته‌ی فعالیت شرکت
industry: "انرژی"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size:  "25-35"

##### آدرس سایت شرکت
site: "https://dieselparsia.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "دیزل پارسیا یک شرکت خصوصی در بخش انرژی و برق است که یکی از بزرگ ترین مراکز فروش و اجاره ژنراتور در سراسر ایران می باشد. تعمیرات و اورهال دیزل ژنراتور  از جمله فعالیت های این می‌باشد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/دیزل-پارسیا/](https://tajrobe.github.io/%D8%AF%DB%8C%D8%B2%D9%84-%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%A7/)
