### ISSUE TITLE
نوآوران داده پرداز فراز

### ISSUE THREAD

**Issue by SheydaSafiallah** [tajrobe/tajrobe.github.io#418]
##### نام شرکت
title: "نوآوران داده پرداز فراز"

##### نام انگلیسی شرکت
name_en: "Faraz Data Processing Innovators"

##### دسته‌ی فعالیت شرکت
industry: "ارائه‌دهنده‌ی نمودارهای آنلاین بازار داخلی و جهانی"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "15-30"

##### آدرس سایت شرکت
site: "https://faraz.io/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فراز، وب‌سایتی پیشگام برای ارائه چارت‌ از بازارهای مالی داخلی و جهانی است. شرکت فراز از سال ۱۳۹۹ شروع به کار کرده و تا کنون بالغ بر ۱۰۰,۰۰۰ کاربر فعال با بالاترین درصد رضایت دارد. هدف ما ارائه آمار دقیق و لحظه‌ای به همراه ابزارهای حرفه‌ای تحلیل تکنیکال است تا تحلیل‌گران بتوانند با شفافیت کامل بازارها را بررسی کنند."

**Comment by tajrobe** [comment]
[ajrobe.github.io/داده-پرداز-فراز/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2-%D9%81%D8%B1%D8%A7%D8%B2/)
