### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by omidjaberi79** [tajrobe/tajrobe.github.io#42]
##### نام شرکت
title: "تین تجارت نیک"

##### نام انگلیسی شرکت
name_en: "tin tejarat nic"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه اینترنتی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "5"

##### آدرس سایت شرکت
site: "tinic.co"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "

ما یک شرکت در زمینه واردات و فروش کاغذ A4 برند هایتری هستیم. سعی داریم با جذب نیرو های فعال و متخصص شرکت رو به اهدافش نزدیک تر کنیم. این جا هم ما به افزایش مهارت های شما و هم شما به بهبود عملکرد شرکتمون کمک میکنید.
"

**Comment by tajrobe** [comment]
[https://tajrobe.github.io/تین-تجارت-نیک/](https://tajrobe.github.io/%D8%AA%DB%8C%D9%86-%D8%AA%D8%AC%D8%A7%D8%B1%D8%AA-%D9%86%DB%8C%DA%A9/)
