### ISSUE TITLE
فرش الماس کویر

### ISSUE THREAD

**Issue by GHAVAMIISBAD** [tajrobe/tajrobe.github.io#428]
##### نام شرکت
title: "فرش الماس کویر"

##### نام انگلیسی شرکت
name_en: "Almas Kavir Kerman Carpet Company"

##### دسته‌ی فعالیت شرکت
industry: "تولید و فروش فرش صنعتی"

##### موقعیت مکانی شرکت
city: "کرمان"

##### تعداد نفرات شرکت
size: "
201 تا 500 نفر"

##### آدرس سایت شرکت
site: "https://almascarpet.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "قالی کرمان و هویت ناب آن همچون الماسی در دل کویر می‌درخشد. این گنجینه فرهنگی ما را بر آن داشت تا برای حفظ و ماندگاری قالی کرمان و احیای این هنر اصیل، و ایجاد اشتغال پای به عرصه تولید گذاشته و شرکت فرش الماس کویر در سال 1385 از دل آن خلق شد و اولین تولیدات مجموعه یک سال بعد به بازار عرضه گشت. فرش الماس کویر در حال حاضر با بیش از 350 نفر پرسنل در حال فعالیت و با بیش از 10 کلکسیون در طرح‌ها و نقش‌های مختلف و متناسب با سلیقه مخاطبان و ترندهای روز، یکی از برترین تولیدکنندگان فرش در کشور ایران است و توانسته 16 فروشگاه منحصربه فرد در سرتاسر ایران داشته باشد و در کنار آن با صادرات به بیش از 32 کشور جهان، حضوری فعال در بازار جهانی فرش داشته باشد. الماس کویر به لطف خدا و همت سرمایه‌های انسانی ارزشمندش اکنون در حال تبدیل شدن به هلدینگی بزرگ است که زنجیره ارزشی از بخش‌های مختلف همچون کارخانجات تولیدی فرش، فروشگاه‌ها و شعب فرش الماس کویر، آکادمی الماس که بازوی آموزشی ست، باشگاه فرهنگی ورزشی الماس، رستوران الماس و اخیرا نیز با اضافه شدن واحد معدن الماس، در حال گسترش هرچه بیشتر این زنجیره ارزش است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/فرش-الماس-کویر/](https://tajrobe.github.io/%D9%81%D8%B1%D8%B4-%D8%A7%D9%84%D9%85%D8%A7%D8%B3-%DA%A9%D9%88%DB%8C%D8%B1/)
