### ISSUE TITLE
ماهان ارتباط ویرا

### ISSUE THREAD

**Issue by artemismahjoub** [tajrobe/tajrobe.github.io#429]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ماهان-ارتباط-ویرا/](https://tajrobe.github.io/%D9%85%D8%A7%D9%87%D8%A7%D9%86-%D8%A7%D8%B1%D8%AA%D8%A8%D8%A7%D8%B7-%D9%88%DB%8C%D8%B1%D8%A7/)
