### ISSUE TITLE
عدل افرینان ماندگار 

### ISSUE THREAD

**Issue by mrrezakarimi99** [tajrobe/tajrobe.github.io#43]
##### نام شرکت
title: "عدل افرینان ماندگار (ادوتل) "

##### نام انگلیسی شرکت
name_en: "adl afarinan mandegar (adotel) "

##### دسته‌ی فعالیت شرکت
industry: "'گردشگری و هتل داری "

##### موقعیت مکانی شرکت
city: "تهران - پارک وی"

##### تعداد نفرات شرکت
size: "8 - 12"

##### آدرس سایت شرکت
site: "adl-co.ir / adotel.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "به اسم خانواده نیرو میگیرن باهاش قرار  داد سخت میبندن که  از طرف موقع رفتن پول بگیرن و یا اینکه باقی مانده پولشو پرداخت نکنن با منت "

**Comment by tajrobe** [comment]
[tajrobe.github.io/عدل-آفرینان-ماندگار/](https://tajrobe.github.io/%D8%B9%D8%AF%D9%84-%D8%A2%D9%81%D8%B1%DB%8C%D9%86%D8%A7%D9%86-%D9%85%D8%A7%D9%86%D8%AF%DA%AF%D8%A7%D8%B1/)
