### ISSUE TITLE
هلدینگ فناوری بنتک

### ISSUE THREAD

**Issue by elahe11** [tajrobe/tajrobe.github.io#430]
##### نام شرکت
title: "هلدینگ فناوری بنتک"

##### نام انگلیسی شرکت
name_en: "bontech"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://bontech.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by elahe11** [comment]
شرکت اولیه پیک آسا بوده.

**Comment by tajrobe** [comment]
[tajrobe.github.io/هلدینگ-بنتک/](https://tajrobe.github.io/%D9%87%D9%84%D8%AF%DB%8C%D9%86%DA%AF-%D8%A8%D9%86%D8%AA%DA%A9/)
