### ISSUE TITLE
 تحلیلگران هوشمند فناوری اطلاعات امید (امید تِک)

### ISSUE THREAD

**Issue by elahe11** [tajrobe/tajrobe.github.io#431]
##### نام شرکت
title: " تحلیلگران هوشمند فناوری اطلاعات امید (امید تِک)"

##### نام انگلیسی شرکت
name_en: "omidtech"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://www.omidtech.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by elahe11** [comment]
یکی از شرکت های زیر مجموعه هلدینگ امید شرکت It بانک سپه

**Comment by tajrobe** [comment]
[tajrobe.github.io/امید-تک/](https://tajrobe.github.io/%D8%A7%D9%85%DB%8C%D8%AF-%D8%AA%DA%A9/)
