### ISSUE TITLE
چهارده دلیل برای اینکه نباید در شرکت سامانه پردازان همگام رادین کار کنید

### ISSUE THREAD

**Issue by karshenas1** [tajrobe/tajrobe.github.io#432]
description: 'چهارده دلیل برای اینکه نباید در شرکت سامانه پرداز همگام رادین کار کنید
دلیل اول: قرارداد کاری با شما بر خلاف تمام ضوابط و قوانین وزارت کار منعقد می شود و هرگز نسخه ایی صحیح از قرارداد را به شما نمی دهند
دلیل دوم: دو قرارداد جداگانه با شما منعقد می شود  با حداقل حقوق و مزایا که کاملاً صوری است و در واقع خواسته اند امکان اعتراض و شکایت نداشته باشید. 
دلیل سوم: چند صد میلیون سفته بابت ضمانت از شما می گیرند که حتی امکان استعفا را هم از شما می گیرند. در واقع اسیر و برده می شوید. 
دلیل چهارم: برای اینکه قوانین اداره مالیات و اداره تامین اجتماعی را دور بزنند حقوق شما را در چند مرحله و به شماره حسابهای مختلف واریز می کنند و حداقل مزایا را در نظر می گیرند. 
دلیل پنجم: در انتهای ماه به بهانه های مختلف مبالغی از حقوق شما کسر می شود. و انتهای ماه نمی فهمید شما طلبکار هستید یا آنها 
دلیل ششم : همسر معاون فنی شرکت در تمام امور دخالت می کند و رفتار زشت و زننده ایی دارد. باید گوشه کنایه ها و بی ادبی های او را هم تحمل کنید. 
دلیل هفتم: مدیر عامل شرکت هیچ نقش موثری ندارد و معاون فنی شرکت و همسرش همه کاره هستند. بنابراین هیچ جایگاهی برای اعتراض ندارید. 
دلیل هشتم: یک انسان بی نزاکت وبی سوادی به عنوان مدیر منابع انسانی در شرکت هست که در واقع حافظ منافع معاون فنی شرکت است. تحت هر حالتی شما محکوم هستید و هیچ حقی ندارید. 
دلیل نهم: از بدو ورود تا خروج توسط بیش از 90 دوربین کنترل می شوید. تمام اعمال و رفتار شما کنترل می شود . تمام دوربین ها مهجز به سیستم های استراق سمع هستند. هیچ جایی برای حرف زدن امن نیست. حتی اگر بخواهید با موبایل صحبت کنید باید به فاصله ی صد متر از شرکت دور شوید. (البته برای این کار باید مرخصی ثبت کنید) 
دلیل دهم: فرهنگ جاسوسی و زیرآب زنی در شرکت به قدری زیاد است که حتی به خودتان هم شک می کنید. 
دلیل یازدهم: ایام کاری بنا به دلخواه معاون فنی تعریف می شود. تعطیلات اضطراری و خاص را قبول ندارند حتی در ایام کرونا حاضر نبودند مرخصی فرد مبتلا را تایید کنند. 
دلیل دوازدهم: حق ماموریت، کار در ایام تعطیل، اضافه کاری و ... به دلخواه معاون فنی است. 
دلیل سیزدهم: تمام مواردی که دوستان و همکاران من در کامنتهای قبلی نوشتند درست است. 
دلیل چهاردهم: این شرکت حتی در مقابل کارفرمای دولتی اش هم حقه باز و متقلب است و از شما هم انتظار دارد این گونه رفتار کنید
به زودی بقیه همکاران دلایل بیشتری به این موارد اضافه خواهند کرد ... 
'

state: |تمام وقت

job_name: 'کارشناس ارشد'

company_slug: 'همگام رادین'

pros: 'مزایا تحقیر توهین مرگ زودرس '

cons: ''

rate: 1

**Comment by tajrobe** [comment]
@karshenas1  
این متن از قبل در این صفحه وجود دارد: 
[tajrobe.github.io/همگام-رادین/](https://tajrobe.github.io/%D9%87%D9%85%DA%AF%D8%A7%D9%85-%D8%B1%D8%A7%D8%AF%DB%8C%D9%86/)
