### ISSUE TITLE
هایپر فامیلی

### ISSUE THREAD

**Issue by Morteza70407** [tajrobe/tajrobe.github.io#433]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Morteza70407** [comment]
هایپر فامیلی

شرکت فامیلی مدرن، زیر مجموعه گروه صنعتی گلرنگ،فعالیت خود را در عرصه خرده فروشی کشور در سطح فروشگاه‌های هایپر در وسعت بالای 1000متر مربع آغاز نموده است.در حال حاضر تعداد 1000 نفر پرسنل در این مجموعه موفق مشغول به کار هستند که با تصمیمات رو به رشد شرکت این تعداد رو به افزایش است.این شرکت با اتکا به پتانسیل بـالای گروه صنعتی گلرنگ، توان و تخصص مدیران جوان و تلاش و تعهد همه همکاران خود تصمیم دارد فروشگاهی کامل و محبوب بـــرای تامین نیازهای مردم عزیز باشد. فروشگاه های فامیلی در حال حاضر در اکثر استا‌ن‌ها و شهرهای ایران دارای شعب متعددی است.


https://hyperfamili.com/

**Comment by tajrobe** [comment]
[tajrobe.github.io/هایپر-فامیلی/](https://tajrobe.github.io/%D9%87%D8%A7%DB%8C%D9%BE%D8%B1-%D9%81%D8%A7%D9%85%DB%8C%D9%84%DB%8C/)
