### ISSUE TITLE
دانش 

### ISSUE THREAD

**Issue by Morteza70407** [tajrobe/tajrobe.github.io#434]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
@Morteza70407  لطفا اطلاعات بیشتری از شرکت مورد نظر (آدرس سایت، نام کامل و...) ارائه کنید.
