### ISSUE TITLE
دماتجهیز

### ISSUE THREAD

**Issue by parichehresmaeilian** [tajrobe/tajrobe.github.io#435]
##### نام شرکت
title: "دماتجهیز"

##### نام انگلیسی شرکت
name_en: "DamaTajhiz"

##### دسته‌ی فعالیت شرکت
industry: " تجهیزات تهویه مطبوع، تأسیسات گرمایشی "

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://damatajhiz.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه مهندسی دمـاتجهیــز با نگاهی به آینده، مسیر موفقیت برند خود را ابتدا به عنوان اولین استارتاپ عرضه و فروش تجهیزات تأسیسات ساختمان با راه‌اندازی جامع‌ترین وب سایت فروش تجهیزات تهویه مطبوع (HVAC)، تجهیزات گرمایشی و موتورخانه، تجهیزات استخر، سونا و جکوزی، تجهیزات کنترل و ایمنی در 6 بخش و 80 گروه ترسیم نموده است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/دماتجهیز/](https://tajrobe.github.io/%D8%AF%D9%85%D8%A7%D8%AA%D8%AC%D9%87%DB%8C%D8%B2/)
