### ISSUE TITLE
الکترونیک برتر

### ISSUE THREAD

**Issue by zeinaberfani** [tajrobe/tajrobe.github.io#437]
##### نام شرکت
title: ""الکترونیک برتر

##### نام انگلیسی شرکت
name_en: ""PEC

##### دسته‌ی فعالیت شرکت
industry: ""تجهیزات پزشکی

##### موقعیت مکانی شرکت
city: ""پارک فناوری پردیس

##### تعداد نفرات شرکت
size: ""20

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/الکترونیک-برتر/](https://tajrobe.github.io/%D8%A7%D9%84%DA%A9%D8%AA%D8%B1%D9%88%D9%86%DB%8C%DA%A9-%D8%A8%D8%B1%D8%AA%D8%B1/)
