### ISSUE TITLE
مدیران 21

### ISSUE THREAD

**Issue by mm831217** [tajrobe/tajrobe.github.io#438]
##### نام شرکت
title: "مدیران 21"

##### نام انگلیسی شرکت
name_en: "Modiran 21"

##### دسته‌ی فعالیت شرکت
industry: "مشاوره"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "1-20"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مشاوره مدیریت"

**Comment by mm831217** [comment]
شرکت مشاور مدیریت مدیران ۲۱ در سال ۱۳۷۹ توسط آقای سیدرضا خلیلی، با هدف ارائه خدمات مشاوره مدیریت عملیاتی به شرکت‌های کوچک و متوسط خصوصی ایرانی، تأسیس شد. هدف و مأموریت این شرکت مشاور مدیریت را می‌توان به طور خلاصه بومی سازی و کاربردی کردن مدیریت علمی در شرکت‌های کوچک و متوسط ایرانی دانست.
در شرکت مدیران 21، آخرین یافته‌های علمی روز از طریق افراد دانشگاهی تیم مشاوره مدیریت مدیران ۲۱ در جلسات تخصصی با افراد باسابقه و عملیاتی مطرح شده و با در نظر گرفتن، شرایط محیط کسب‌کار ایران و متناسب با نیازهای سازمان‌های ایرانی بومی‌سازی می‌شود.

**Comment by tajrobe** [comment]
[tajrobe.github.io/مدیران-21/](https://tajrobe.github.io/%D9%85%D8%AF%DB%8C%D8%B1%D8%A7%D9%86-21/)
