### ISSUE TITLE
توسن تکنو

### ISSUE THREAD

**Issue by Morteza70407** [tajrobe/tajrobe.github.io#439]
##### نام شرکت
title: "توسن تکنو"

##### نام انگلیسی شرکت
name_en: "Tosan Techno"

##### دسته‌ی فعالیت شرکت
industry: "خدمات و پرداخت الکترونیک"

##### موقعیت مکانی شرکت
city: "سعادت آباد"

##### تعداد نفرات شرکت
size: "بیش از 500"

##### آدرس سایت شرکت
site: "https://www.tosantechno.com/fa/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "خدمات و پرداخت الکترونیک"

**Comment by Morteza70407** [comment]
من دو مرحله  برای شغل کارشناس پشتیبانی نرم افزار مصاحبه رفتم 
تو جلسه اول مصاحبه با مدیر واحد بود که یه خانم بود. از لحظه ای که مصاحبه شروع شد تا پایانش بجای اینکه روال عادی مصاحبه طی بشه دایم از مدیرش و جو بد اونجا گفت... من نمیدونم اگه قراره استخدام کنید این چه حرکتیه که مدیر یه واحد تو جلسه مصاحبه درده دل میکنه و از مدیر IT  بد میگه... تو همون جلسه انگاری واسه اینکه خودش رو خالی کنه تمام سوالاتی که تو جلسه مصاحبه دوم قرار بود ازم پرسیده بشه رو با یه حرص خاصی داشت بهم میگفت....

تو جلسه دوم با 4 نفر مصاحبه کردم... یکی از یکی گاوتر و بیشعور تر. همون خانمی که باهاش تو جلسه اول مصاحبه کردم دایم سرش تو لپ تاپ بود و میخندید یه خانم دیگه هم از منابع انسانی که یه سری سوالای بی سر و ته میپرسید ، یه بنده خدایی که یه یخورده نرمال تر بود سوالای فنی میپرسید و مدیر IT  که از همه گاو تر بود. وسط جلسه مصاحبه سرش تو گوشی و اینستاگرام بود و چند بار صدایی کلیپ هایی که داشت میدید یهو از گوشیش در میومد یهو پا میشد میرفت بیرون بر میگشت و وسط راه یهو سوال میپرسید اصلا یه وضعی
دایم با سوالاش قصد بهم زدن ارامشم رو داشت، یه استدلال های براتون میارن که اگه به خودتون شک میکنید که چرا اومدید اینجا واسه کار

اخرش هم گفتم که تو یه ایمیل برات نتیجه مصاحبه رو اعلام میکنیم
کلا هم به وقت و زمان اعتقادی ندارن تو هر دو تا مصاحبه سر ساعت رفتم ولی نیم ساعت داشتم در و دیوار رو نگاه میکردم

**Comment by tajrobe** [comment]
[tajrobe.github.io/توسن-تکنو/](https://tajrobe.github.io/%D8%AA%D9%88%D8%B3%D9%86-%D8%AA%DA%A9%D9%86%D9%88/)
