### ISSUE TITLE
دانش رفاه پردیس

### ISSUE THREAD

**Issue by Morteza70407** [tajrobe/tajrobe.github.io#440]
##### نام شرکت
title: "دانش رفاه پردیس"

##### نام انگلیسی شرکت
name_en: "ِDanesh Refah Pardis"

##### دسته‌ی فعالیت شرکت
industry: "Software"

##### موقعیت مکانی شرکت
city: "خیابان طالقانی"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "https://daneshrefah.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فعالیت در حوزه بانکداری و نرم افزار های بانکی"

**Comment by tajrobe** [comment]
[tajrobe.github.io/دانش-رفاه-پردیس/](https://tajrobe.github.io/%D8%AF%D8%A7%D9%86%D8%B4-%D8%B1%D9%81%D8%A7%D9%87-%D9%BE%D8%B1%D8%AF%DB%8C%D8%B3/)
