### ISSUE TITLE
ماتریس

### ISSUE THREAD

**Issue by Alishariat73** [tajrobe/tajrobe.github.io#441]
##### نام شرکت
title: ""ماتریس

##### نام انگلیسی شرکت
name_en: ""matris

##### دسته‌ی فعالیت شرکت
industry: ""کامپیوتر و فناوری اطلاعات

##### موقعیت مکانی شرکت
city: ""تهران - خیابان بخارست

##### تعداد نفرات شرکت
size: ""۵۰۰

##### آدرس سایت شرکت
site: ""matris.co.ir

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""مجتمع تولیـدی ماتریس صادر کننـده نمونه استان تهران و عضو اتحادیه صادرکنندگان کالا و خدمات است. این مجموعه از سال 1376 در زمینه تولید، صادرات و واردات و خرید و فروش کلیه تجهیزات و سخت افزار رایانه فعالیت می نماید و نماینده انحصاری تولید و پخش بسیاری از برندهای معتبر از جمله MSI بوده و دارای 500 فروشگاه و مرکز خدمات پس از فروش و نماینده در کلیه شهرهای ایران می باشد. این مجموعه دارای بخش های متفاوتی برای حفظ استاندارد بالا می باشد: بخش های روابط بین الملل، کاوش و تحقیق بازار جهانی، خرید، فروش، امور شهرسـتانها، فروش دولتی، تحقیق و توسـعه، بخش تولیـد و کارآفرینی، تضمین و ارزیابی کیفی، خدمات پس از فروش، بازرسی و امور مشتریان، روابط عمومی، تبلیغات و طراحی، معماری، فناوری اطلاعات و ... تلاش اعضای این مجموعه با یکدلی و یکرنگی بر اساس خط مشی اصلی مدیریت شـرکت، ایجاد مرکـزی پیشرو و حـامی مصرف کننده و همواره در جهت ارائه آخرین فن آوری های جهان در زمینه رایانه با بهترین پوشش خدماتی بوده و می باشد. هم اکنون شرکت ماتریس نمایندگی انحصاری فروش و ارائه خدمات پس از فروش محصولات بسیار معتبری است که از آن جمله می توان به برندهای بسیار مشهور زیراشاره کرد: MSI, MAYA, AMD, ASUS, TOSHIBA, KIOXIA

**Comment by tajrobe** [comment]
[tajrobe.github.io/ماتریس/](https://tajrobe.github.io/%D9%85%D8%A7%D8%AA%D8%B1%DB%8C%D8%B3/)
