### ISSUE TITLE
گروه مالی فیروزه

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#442]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/گروه-مالی-فیروزه/](https://tajrobe.github.io/%DA%AF%D8%B1%D9%88%D9%87-%D9%85%D8%A7%D9%84%DB%8C-%D9%81%DB%8C%D8%B1%D9%88%D8%B2%D9%87/)
