### ISSUE TITLE
سفروایرانیان

### ISSUE THREAD

**Issue by mreza-mz** [tajrobe/tajrobe.github.io#443]
##### نام شرکت
title: "سفروایرانیان"

##### نام انگلیسی شرکت
name_en: "safaroiranian"

##### دسته‌ی فعالیت شرکت
industry: "آژانس هواپیمایی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "70"

##### آدرس سایت شرکت
site: "safaroiranian.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "درزمینه فروش تور فعالیت دارد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/سفر-رو-ایرانیان/](https://tajrobe.github.io/%D8%B3%D9%81%D8%B1-%D8%B1%D9%88-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%DB%8C%D8%A7%D9%86/)
