### ISSUE TITLE
نسیم تلکام

### ISSUE THREAD

**Issue by aghta** [tajrobe/tajrobe.github.io#444]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "سعادت آباد"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: "https://nasimtel.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "درخصوص سیستم تلفنی voip فعالیت دارد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/نسیم-تلکام/](https://tajrobe.github.io/%D9%86%D8%B3%DB%8C%D9%85-%D8%AA%D9%84%DA%A9%D8%A7%D9%85/)
