### ISSUE TITLE
صنعت رایان پارس 

### ISSUE THREAD

**Issue by frauhadis** [tajrobe/tajrobe.github.io#445]
##### نام شرکت
title: "صنعت رایان پارس"

##### نام انگلیسی شرکت
name_en: "sanat rayan pars"

##### دسته‌ی فعالیت شرکت
industry: "تولید باتری های سرب اسید ساکن"

##### موقعیت مکانی شرکت
city: "البرز، اشتهارد"

##### تعداد نفرات شرکت
size: "۳۰۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/صنعت-رایان-پارس/](https://tajrobe.github.io/%D8%B5%D9%86%D8%B9%D8%AA-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86-%D9%BE%D8%A7%D8%B1%D8%B3/)
