### ISSUE TITLE
 دارو بهداشت آسیا

### ISSUE THREAD

**Issue by ahz1990** [tajrobe/tajrobe.github.io#446]
دارو بهداشت آسیا ##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""پخش و توزیع دارو

####را# موقعیت مکانی شرکت
city: ""اصفهان

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""پخش و توزیع دارو برای داروخانه ها و بیمارستانهای استان اصفهان

**Comment by ahz1990** [comment]
شرکتی بسیار مزخرف با حقوق و مزایای پایین و مدیریت فاقد دانش مدیریتی  و آماتور

**Comment by tajrobe** [comment]
@ahz1990 
لطفا تجربه خود را به صورت کامل در صفحه شرکت بنویسید:
[tajrobe.github.io/دارو-بهداشت-آسیا/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%B1%D9%88-%D8%A8%D9%87%D8%AF%D8%A7%D8%B4%D8%AA-%D8%A2%D8%B3%DB%8C%D8%A7/)
