### ISSUE TITLE
ساریاک

### ISSUE THREAD

**Issue by mboroomand1359** [tajrobe/tajrobe.github.io#449]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ساریاک/](https://tajrobe.github.io/%D8%B3%D8%A7%D8%B1%DB%8C%D8%A7%DA%A9/)
