### ISSUE TITLE
شرکت پروشات هانا

### ISSUE THREAD

**Issue by Parnianamini** [tajrobe/tajrobe.github.io#450]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Parnianamini** [comment]
تجربه کاری تو این شرکت فقط باعث میشه اعصاب و روانتون و از دست بدید. این شرکت حقوق ها رو به زور و تیکه تیکه پرداخت میکنه. عملا دو سه نفر تو این شرکت بیمه هستن. برای واریزی حقوق باید التماس کنی. اگر بخوای ازشون جداشی با سفته یا تضامین داخل قرارداد تهدیدتون میکنن و اخرین حقوقتون یا نمیدن یا باید با دعوا بگیرید.
بابت حقتون تحقیرتون می‌کنند و باهاتون درگیر میشن. مدیر این شرکت پرونده شکایت های بسیار زیادی توی اداره کار داره.
از نظر سطح کاری هم بیشتر کارهای اضافه و اذیت کننده دارید و کمکی به رشدتون نمیشه. 
عمرتون و با رفتن توی این شرکت اصلا هدر ندید.

**Comment by tajrobe** [comment]
[tajrobe.github.io/پروشات-هانا/](https://tajrobe.github.io/%D9%BE%D8%B1%D9%88%D8%B4%D8%A7%D8%AA-%D9%87%D8%A7%D9%86%D8%A7/)
