### ISSUE TITLE
همیار گشت سفر بازی

### ISSUE THREAD

**Issue by Hadiam1373** [tajrobe/tajrobe.github.io#451]
##### نام شرکت
title: "همیار گشت سفر بازی"

##### نام انگلیسی شرکت
name_en: "hamyar gasht safar bazi"

##### دسته‌ی فعالیت شرکت
industry: "گردشگری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "https://www.safarbazi.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Hadiam1373** [comment]
تجربه مصابه من با شرکت سفر بازی به این صورت بود که ابتدا تماس گرفتن و یک تایم مصاحبه آنلاین با من ست کردن بعد از حضور در جلسه و گذشت یک ربع هیچ کس در جلسه حاضر نشد و با تلفنی که در ایمیل گذاشته بودن تماس گرفتم ولی کسی پاسخگو نبود . بعد از گذشت دو ساعت با من تماس گرفتن که در یک جلسه بودیم و امکان حضور نداشتیم و یک تایم دیگه برای ساعت 9 شب همون روز با من ست کردن ، برای دفعه دوم در مصاحبه شرکت کردم و یک ساعت و ربع از من سوال کردن و آخر مصاحبه کننده گفت خیلی تحت تاثیر قرار گرفتم از دانش تون و یک تسک رو ارسال میکنم براتون ، تسک رو فرستاد و من فایل فیگما رو که باز کردم متوجه شدم که یک بخش از پروژه ه ی پنل ادمین خود شرکت است ، با این حال دو روز زمان گذاشتم و تسک رو انجام دادم و ارسال کردم بعد از گذشت هشت روز پیگیری کردم که نتیجه رو به من اطلاع بدین چون میخوام تصمیم گیری کنم ، یک متن برای من ارسال کردن که همه ما تحت تاثیر مهارت شما قرار گرفتیم ولی در حال حاضر امکان همکاری نداریم . بدون اینکه یک فیدبک به من بدن که چرا ؟ لطفا هر تسکی رو اجام ندین بچه ها خیلی از این شرکتا اینجوری پروژّه شونو جمع میکنن !

**Comment by tajrobe** [comment]
[tajrobe.github.io/همیار-گشت-سفربازی/](https://tajrobe.github.io/همیار-گشت-سفربازی/)
