### ISSUE TITLE
تولیمرغ

### ISSUE THREAD

**Issue by Eshi1981** [tajrobe/tajrobe.github.io#452]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/تولیمرغ/](https://tajrobe.github.io/%D8%AA%D9%88%D9%84%DB%8C%D9%85%D8%B1%D8%BA/)
