### ISSUE TITLE
بیسکویت گرجی

### ISSUE THREAD

**Issue by Lili-mnp** [tajrobe/tajrobe.github.io#453]
##### نام شرکت
title: "بیسکویت گرجی"

##### نام انگلیسی شرکت 
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "تولید بیسکویت"

##### موقعیت مکانی شرکت
city: "تهران ایرانشهر"

##### تعداد نفرات شرکت
size: "۵۰۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Lili-mnp** [comment]
شرکتی که فقط با باند بازی داره میچرخه
کلی دزدی توشه و مدیرای شرکت خودشون توش دخیلن
ادمایی اونجا کار میکنن که هیچ مهارت و تخصصی ندارن و فقط از طریق دوست و فامیل اونجا وارد شدن و با زیراب زدن تونستن بمونن و دزدی کنن
حق و حقوق پرسنل شرکتو نمیدن،ولی خودشون از ۱۰۰ جا دارن میخورن
هر روز بازیتون میدن،فقط این پشت اون دروغ میگه و زیراب میزنه و مدیران شرکت فقط کسایی رو دوست دارن که تو دزدیشون شریک باشه و بهشون خبر بده
شرکت مزخرفیه،حقوق خوبی نداره،همیشه ام حقوق معوقه داره
بیشتر شبیه سریالای جم تی وی عه این شرکت
همه با هم رابطه دارن و هیچ کس گردن نمیگیره

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیسکویت-گرجی/](https://tajrobe.github.io/%D8%A8%DB%8C%D8%B3%DA%A9%D9%88%DB%8C%D8%AA-%DA%AF%D8%B1%D8%AC%DB%8C/)
