### ISSUE TITLE
پژوهشگران صنعت آرتا

### ISSUE THREAD

**Issue by Serve523** [tajrobe/tajrobe.github.io#454]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پژوهشگران-صنعت-آرتا/](https://tajrobe.github.io/%D9%BE%DA%98%D9%88%D9%87%D8%B4%DA%AF%D8%B1%D8%A7%D9%86-%D8%B5%D9%86%D8%B9%D8%AA-%D8%A2%D8%B1%D8%AA%D8%A7/)
