### ISSUE TITLE
Fix Sorting Of New Post

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#455]
پست های جدید اول صفحه شرکت نمیان و میرن انتها که باید اسکرول کنه کاربر 
یه تغییری لازمه بیان بالا و اول باشن بر طبق زمان اوناییم که زمانشون مشخص نیست بره ته

**Comment by pooooriya** [comment]
#456 456

یه نگاهی بنداز به این ببین چطوریه روش حلش

**Comment by tajrobe** [comment]
سلام به آقا پوریای عزیز
چندین بار برای حل این مشکل تلاش شده ولی نتیجه‌بخش نبوده:[+](https://github.com/tajrobe/tajrobe.github.io/commit/a468d3241539023265dcebc44ba2bff24addb3bf)، [+](https://github.com/tajrobe/tajrobe.github.io/commit/e11fbfa403287f9faa0eb57d89360e23a9fc95bf)، [+](https://github.com/tajrobe/tajrobe.github.io/commit/2ac98ea1fe85ae5d6b10f504d536b1fa055a90a2)، [+](https://github.com/tajrobe/tajrobe.github.io/commit/a1c2b59b962e378fb47bf287eecf5396fdf937d4)، [+](https://github.com/tajrobe/tajrobe.github.io/commit/17174ed01235859f1c04462df0c12c599bb21bd0)

حتی روی سرور لوکال هم این سورت جواب نمیده، احتمالا با یه راه‌حل جاوااسکریپت انجام بدیم که در سمت فرانت امکان` مرتب‌سازی پیش‌فرض` و `مرتب‌سازی بر حسب جدیدترین` رو در قالب یه کمبوباکس داشته باشیم.

**Comment by tajrobe** [comment]
فعلا به نظر میرسه با js مشکل حل شده باشه
