### ISSUE TITLE
اعتبار تجربه ها 

### ISSUE THREAD

**Issue by MirS0bhan** [tajrobe/tajrobe.github.io#457]
درود. همونطور که شفافیت مهمه ولی اعتبار تجربه هم مهمه تا توسط یه سری افراد چه مخالف شرکت و چه موافق اسپم نشه این صفحات. اگه راهکاری مد نظر دارید که بشه هم ناشناس بودن افراد حفظ بشه و هم معتبر باشند تجربه ها حتما بفرمایید

**Comment by tajrobe** [comment]
سلام 
اینکه یه چیز رو  آزاد کنیم و تا حدامکان حد و حصرش رو برداریم، احتمالا آفت‌هایی هم داره که شما بهش اشاره کردید، ولی درمجموع نسبت فایده به ضررش می‌صرفه. در خصوص اعتبار تجربه‌ها GitHub-pages امکانات زیادی نداره و ما تا حد زیادی روی هوش کسی که تجربیات رو میخونه حساب کردیم، به نظر ما، مخاطب‌مون باهوشه (مثل شما) و تا حد زیادی امکان تشخیص موارد نادرست از درست و داره.
البته اینا به این معنا نیست که برای بهتر شدن این پروژه تلاش نکنیم، راهکار مفیدتری فعلا به ذهنمون نرسیده، اگه شما ایده‌ی خوبی (با توجه به محدودیت‌های GitHub-pages) دارید، خوشحال میشیم که با ما به اشتراک بگذارید.
