### ISSUE TITLE
شرکت مهندسین مهساب شرق

### ISSUE THREAD

**Issue by mehdi-sharif1** [tajrobe/tajrobe.github.io#458]
##### نام شرکت
title: ""مهندسین مشاور مهساب شرق

##### نام انگلیسی شرکت
name_en: ""Mahsab Sharq consulting Engineering

##### دسته‌ی فعالیت شرکت
industry: ""مهندسی آب و محیط زیست

##### موقعیت مکانی شرکت
city: ""تهران

##### تعداد نفرات شرکت
size: ""۱۵
##### آدرس سایت شرکت
site: ""https://mahsab.com/

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/مهساب-شرق/](https://tajrobe.github.io/%D9%85%D9%87%D8%B3%D8%A7%D8%A8-%D8%B4%D8%B1%D9%82/)
