### ISSUE TITLE
تجربه کاری ناموفق در ماهکس

### ISSUE THREAD

**Issue by Moonlight719-wq** [tajrobe/tajrobe.github.io#460]
ماهکس(سریع ترابر ماهان)
Mahex

**Comment by Moonlight719-wq** [comment]
این شرکت حقوق رو خیلی پایین میبنده و زمان استعفا به مدت ۶ ماه الی ۱ سال پرداخت آخرین حقوقتون رو به تعویق میندازه و در بدو ورود ازتون سفته میگیره با ضامن که اون رو هم به مدت حدود یک سال نگه میداره .به مزایایی هم که داخل آگهی های استخدام مینویسن خیلی توجه نکنید کوهنوردی چندسال یکبار به تعداد محدوده مافیا هم که نوشته جزو مزایا بعد از تایم کاری جمع میشن تو سالن غذاخوری بازی میکنن😅دوچرخه سواری و ایناهم که دروغه ، وامی که نوشته بعد از چندسال سابقه کار ۱۵ تومن بهتون میدن با ضامن ، بیمه تکمیلی هم بعد از ۶ ماه بهتون تعلق میگیره. آمار استعفای نیروهاشونم به شدت بالاس .

**Comment by tajrobe** [comment]
[tajrobe.github.io/ماهکس/](https://tajrobe.github.io/%D9%85%D8%A7%D9%87%DA%A9%D8%B3/)
