### ISSUE TITLE
آراهنر ( طراحان هدیه خلاق)

### ISSUE THREAD

**Issue by Sohrab67m** [tajrobe/tajrobe.github.io#461]
##### نام شرکت
title: "" آراهنر

##### نام انگلیسی شرکت
name_en: "" arahonar

##### دسته‌ی فعالیت شرکت
industry: "" هدایای سازمانی

##### موقعیت مکانی شرکت
city: "" تهران پاسداران

##### تعداد نفرات شرکت
size: ""
۵۰ 
##### آدرس سایت شرکت
site: "" arahonar.com

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "" فروش هدایای سازمانی

**Comment by Sohrab67m** [comment]
میخوام براتون از تجربه کاری به شدت افتضاح چند سال کار تو این مجموعه بگم و پشیمونی بابت اینکه ۳ سال از وقت و تجربه م رو  برای بهبود شرایط هدر دادم ولی زهی خیال باطل. وقتی وارد مجموعه می‌شید همه چی قشنگ و جذاب اما بعد گذشت چند وقت به اشتباه بزرگ خودتون پی می‌برید و می‌فهمید که با چه افراد سمی و مخربی همکار شدید . 
۳ مدیر اصلی مجموعه که به شدت آدم های دهن بین و متأسفانه بی تجربه هستند با این که همیشه تو حرف خودشون رو عمل گرا و انتقاد پذیر نشون میدن اما خلافش ثابت میشه بهتون . فقط حرف و حرف سعی میکنن همه چی رو قشنگ نشون بدن و تو حرف همه فرآیند ها رو اصولی جلوه بدن اما هیچ وقت بهشون اعتماد نکنید. 
به این هم دقت کنید که خروج و جذب این مجموعه چقدر زیاده و خیلی افراد با تجربه و متخصص رو می‌دیدم که بعد یک الی دوسال یا حتی چند ماه که شرایط رو دیدن بیخیال شدن و رفتند یا حتی افرادی که دووم آوردند برای بهبود شرایط رو خودشون بعد استفاده هایی که کردند با رفتار بد انداختن بیرون .
سرپرست ها و مدیران واحد همه شون الآن از افراد نزدیک و رفیق های صمیمی مدیران مجموعه هستند که فقط یاد گرفتند که خبرچین و چاپلوس باشند و به اصطلاح زیرآب بقیه رو بزنند.
متأسفانه این مجموعه با پارتی بازی و رانت های مختلف هستش که هنوز داره به کارش ادامه میده و اگه میخواهید که به حریم شخصی تون تجاوز بشه ( این قسمت برای خانم ها البته بگم که همون آقایون نزدیک به مدیران ممکنه حتی بهتون تعرض هم بکنند که قبلاً  بسیار اتفاق افتاده ) باید با مواردی که گفتم بسازید.
 واقعا اگه دوست دارید تو مجموعه ای کار کنید که فقط پشت سر هم دیگه حرف میزنند و با کثافت کاری های مختلف سر و کار داشته باشید بهتون آراهنر رو پیشنهاد میکنم .
البته از مجموعه کوچیک با مدیران افتضاح بیشتر از این انتظار نمیره .
هرچی بگم از این آراهنر متأسفانه کم گفتم تا حالا نه همچین مجموعه ای دیدم و نه شنیدم ؛ برا خودتون ارزش قائل بشید و اصلا وارد این مجموعه نشید

**Comment by tajrobe** [comment]
[tajrobe.github.io/آرا-هنر/](https://tajrobe.github.io/%D8%A2%D8%B1%D8%A7-%D9%87%D9%86%D8%B1/)
