### ISSUE TITLE
دی کامپیوتر

### ISSUE THREAD

**Issue by baharda** [tajrobe/tajrobe.github.io#462]
##### نام شرکت دی کامپیوتر
title: ""

##### نام انگلیسی شرکت day computer
name_en: ""

##### دسته‌ی فعالیت شرکت نرم افزار
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت 70
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by baharda** [comment]
این شرکت همان شرکت تایگر هست که به خاطر نظرات منفی زیاد اسمشونو تغییر دادند و تمام تجربه های منفی راجب شرکت تایگر درست هست و اصلا با این شرکت قرارداد نبندید که هر روز کارکردن اونجا از جهنم بدتره . احتمالا این راهکار تغییر اسم شرکتم وکیل بی تربیت شرکت یادشون داده ولی تنها راه تغییر اون شرکت تغییر مدیر عاملشه. 
اگر به فکر استخدام توی این شرکت هستید تجربه های شرکت تایگر را بخونید.

**Comment by tajrobe** [comment]
[tajrobe.github.io/دی-کامپیوتر/](https://tajrobe.github.io/%D8%AF%DB%8C-%DA%A9%D8%A7%D9%85%D9%BE%DB%8C%D9%88%D8%AA%D8%B1/)
