### ISSUE TITLE
پیتزا سیب 360

### ISSUE THREAD

**Issue by Negin3055** [tajrobe/tajrobe.github.io#463]
##### نام شرکت
title: "پیتزا سیب 360"

##### نام انگلیسی شرکت
name_en: "Pitza Sib 360"

##### دسته‌ی فعالیت شرکت
industry: "هلدینگ رستورانی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "کمتر از 80"

##### آدرس سایت شرکت
site: "https://sib360.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه رستورانهای سیب 360 و راسپر از جمله برندهای تحت پوشش هلدینگ SYBT میباشد"

**Comment by Negin3055** [comment]
این شرکت تحت عنوان هلدینگ SYBT کار میکنه و برندهای سیب 360 و راسپر تا الان جز زیر محموعه این هلدینگ هست 
شرکت بسیار بی برنامه و بی ثبات هست در طول شش ماه 3 تا مدیر عامل عوض میکنه ، 
برای کار بیش از 6 ماه تو این شرکت دل نبندید 
امنیت شغلی صفر هست  چون تصمیم ها بی ثبات هست 
مشکل اصلی هم مالک اصلی شرکت یامدیر عامل اصلی شرکت هست  هیچ برنامه ای برای نگهداشت نیروها ِ نگهداشت شعبه ها، یا توسعه انها نداره

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیتزا-سیب-360/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%AA%D8%B2%D8%A7-%D8%B3%DB%8C%D8%A8-360/)
