### ISSUE TITLE
تامین خدمات سیستم‌های کاربردی کاسپین

### ISSUE THREAD

**Issue by bansheess** [tajrobe/tajrobe.github.io#464]
##### نام شرکت
title: "تامین خدمات سیستم‌های کاربردی کاسپین"

##### نام انگلیسی شرکت
name_en: "caspian"

##### دسته‌ی فعالیت شرکت
industry: "زیرساخت بانکی بانک پارسیان"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "250"

##### آدرس سایت شرکت
site: "https://www.caspco.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تامین و نگهداری زیرساخت های بانک پارسیان"

**Comment by tajrobe** [comment]
[tajrobe.github.io/تامین-خدمات-کاسپین/](https://tajrobe.github.io/%D8%AA%D8%A7%D9%85%DB%8C%D9%86-%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%DA%A9%D8%A7%D8%B3%D9%BE%DB%8C%D9%86/)
