### ISSUE TITLE
افزودن شرکت

### ISSUE THREAD

**Issue by hn20m** [tajrobe/tajrobe.github.io#465]
##### نام شرکت
title: "موسسه فرهنگی تبلیغاتی بهمن سبز"

##### نام انگلیسی شرکت
name_en: "bahmansabz"

##### دسته‌ی فعالیت شرکت
industry: "هنری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۰۰"

##### آدرس سایت شرکت
site: "bahmansabz.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکتی فعال در حوزه تولید فیلم، ساخت سینما، مدیریت سینما و فروش بلیط"

**Comment by tajrobe** [comment]
[tajrobe.github.io/بهمن-سبز/](https://tajrobe.github.io/%D8%A8%D9%87%D9%85%D9%86-%D8%B3%D8%A8%D8%B2/)
