### ISSUE TITLE
سرورستاپ

### ISSUE THREAD

**Issue by mehdi-amz** [tajrobe/tajrobe.github.io#467]
##### نام شرکت
title: "سرورستاپ"

##### نام انگلیسی شرکت
name_en: "Serversetup"

##### دسته‌ی فعالیت شرکت
industry: "هاستینگ"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://serversetup.co/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "​سرورستاپ از سال ۱۳۹۲ خدمات خود شامل ارائه سرور‌های اختصاصی و مجازی،‌هاست، ثبت دامنه، امنیت و … را در زمینه هاستینگ آغاز کرده است. کیفیت بالای سرویس‌ها با زیر ساخت و خدماتی متفاوت با استفاده از تکنولوژی‌های روز دنیا بخشی از ویژگی‌های سرورستاپ می باشد. رضایت مندی مشتری جزء اولین اصول سرورستاپ بوه است و به همین دلیل همواره تمامی تلاش خود را برای ارائه بهترین سرویس و ارتقا کیفی سرویس‌ها بکار می‌گیرد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرورستاپ/](https://tajrobe.github.io/%D8%B3%D8%B1%D9%88%D8%B1%D8%B3%D8%AA%D8%A7%D9%BE/)
