### ISSUE TITLE
رویین پولاد ایرانیان

### ISSUE THREAD

**Issue by mhacc1980** [tajrobe/tajrobe.github.io#468]
##### نام شرکت
title: ""
رویین پولاد ایرانیان
##### نام انگلیسی شرکت
name_en: ""
Rooeenpoolad Iranian

##### دسته‌ی فعالیت شرکت
industry: ""
بازرگانی - واردات دستگاه لیزر

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by mhacc1980** [comment]
یه شرکت جمع وجور که در ابتدا خوب به نظر میاد ولی محیطی  بسیار غیرحرفه ای داره.مدیرعامل بی قابلیت که توان مدیریت ۷ تا نیرو نداره. در کمتر از یکسال چندین جابجایی نیرو در بخشهای مختلف و تمامی اینها بک روز قبل میگن از فردا نیا اونم با دلایل موهوم و مسخره که خودشون هم باور ندارن و فقط بخاطر خاله زنک بازی این اخراجها انجام میشه. شعار شون اینه که ما یک خانواده هستیم که این دقیقا نقطه شروع رفتارهای سبک سرانه، سطح پایین و دور از شان یک سازمان هست. اینها یه نیرو خدماتی ندارن، میزها و کف ساختمون ماهی یکبار نظافت میشه،خودت باید چایی درست کنی،چایی بریزی،ظرفت بشوری. اتاقهای خفه ، لابی مثل انباری حتی یه صندلی برا بازرس بیمه ندارن. از همه بدتر ناکارآمدی یک نفر و تبعیض قائل شدن مدیریت برای اون نسبت به سایرین.در مجموع بیخودترین و سطح پایین ترین تجربه کاری من بود.

**Comment by tajrobe** [comment]
[tajrobe.github.io/رویین-پولاد/](https://tajrobe.github.io/%D8%B1%D9%88%DB%8C%DB%8C%D9%86-%D9%BE%D9%88%D9%84%D8%A7%D8%AF/)
