### ISSUE TITLE
نکس‌تاک

### ISSUE THREAD

**Issue by Mohireza1** [tajrobe/tajrobe.github.io#469]
##### نام شرکت
title: "نکس‌تاک"

##### نام انگلیسی شرکت
name_en: "NexTalk"

##### دسته‌ی فعالیت شرکت
industry: "آموزش"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵"

##### آدرس سایت شرکت
site: "nextalk.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "اولین موسسه آموزش زبان به روش فری دیسکاشن و به طور کاملا آنلاین در کشور"

**Comment by tajrobe** [comment]
[tajrobe.github.io/نکس-تاک/](https://tajrobe.github.io/%D9%86%DA%A9%D8%B3-%D8%AA%D8%A7%DA%A9/)
