### ISSUE TITLE
دانش پارسیان

### ISSUE THREAD

**Issue by worldmohammad** [tajrobe/tajrobe.github.io#47]
##### دانش پارسیان
title: ""

##### danesh parsian
name_en: ""

##### computer
industry: ""

##### tehran
city: ""

##### 100
size: ""

##### dapa.ir
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/دانش-پارسیان/](https://tajrobe.github.io/%D8%AF%D8%A7%D9%86%D8%B4-%D9%BE%D8%A7%D8%B1%D8%B3%DB%8C%D8%A7%D9%86/)
