### ISSUE TITLE
یاکس | آشپزخانه پرستیژ

### ISSUE THREAD

**Issue by aquariusintelligent** [tajrobe/tajrobe.github.io#470]
##### نام شرکت
title: " یاکس" 

##### نام انگلیسی شرکت
name_en: "YAKS"

##### دسته‌ی فعالیت شرکت
industry: "کابینت آشپرخانه"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "+20"

##### آدرس سایت شرکت
site: ایران ، تهران ، پارک‌وی، ابتدای بزرگراه چمران، شوروم یاکس""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: تفکر یاکس ارائه تجربه‌ای از فضای آشپزخانه برای مشتریان خود، فراتر از فضای آشپزی است. یاکس می‌خواهد مصرف‌کنندگان را در تمام فرآیندهای رویارویی با برند، تا زمان استفاده از محصول همراهی کند. ما به دنبال ثبت خاطرات ماندگار در ذهن مخاطبان خود هستیم. ما می‌خواهیم مشتریان تجربه خوشایند برقراری ارتباط با ما را به خاطر بسپارند، حتی اگر مشتری ما نباشند.""

**Comment by aquariusintelligent** [comment]
متاسفانه در هنگام مصاحبه کاری بی احترامی به فرد و افرادی کاملا غیر حرفه ایی دراین شرکت نظر شما رو جلب می کند متاسفانه فرهنگ سازمانی دراین شرکت هیچگونه جایگاهی ندارد بی احترامی در خصوصی ترین حالت فرد یک امری طبیعی دراین مجموعه هست باتوجه به تایم کوتاه دراین مجموعه اصلا به هیچ عنوان به فرد فردی که دارای صبری زیاد و احترام متقابل رو به افراد رویه خودم میدانم توصیه نمی کنم ابته ازجا که مجموعه دفتر شرکت در شمالی ترین نقطه تهران هست و این فکر درفرد جویای کار  حس میشود درایک مجموعه بسیار باکلاس کاری وسازمانی استخدام خواهد شد ولی کاملا مبرهن هست که دریک مجموعه بامشکلات فراوان و تصمیمات شتبازده و بی ثبات کاری روبه رو هست

**Comment by tajrobe** [comment]
[tajrobe.github.io/یاکس/](https://tajrobe.github.io/%DB%8C%D8%A7%DA%A9%D8%B3/)
