### ISSUE TITLE
شرکت داده پردازی ایران

### ISSUE THREAD

**Issue by rezaei67** [tajrobe/tajrobe.github.io#471]
##### نام شرکت
title: " داده پردازی ایران"

##### نام انگلیسی شرکت
name_en: "DPI"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "300"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "EX IBM"

**Comment by tajrobe** [comment]
[tajrobe.github.io/داده-پردازی-ایران/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%DB%8C-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86/)
