### ISSUE TITLE
شرکت ادمان فناوری پنگان (ادمان تک)

### ISSUE THREAD

**Issue by Experiencefrom2016** [tajrobe/tajrobe.github.io#472]
##### نام شرکت
title: "ادمان فناوری پنگان"

##### نام انگلیسی شرکت
name_en: "Edman Fanavari Pangan"

##### دسته‌ی فعالیت شرکت
industry: "تجهیزات داروسازی و آزمایشگاهی" 

##### موقعیت مکانی شرکت
city: "کرج"

##### تعداد نفرات شرکت
size: "۱۰-۲۰"

##### آدرس سایت شرکت
site: "www.edmantech.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: دفتر این شرکت خصوصی در مجموعه سرم سازی رازی واقع شده و عمده فعالیت هایش تعمیر و نگهداری فرمانتورها و فریزرهای این مجموعه می باشد. همچنین محصولاتی را نیز برای شرکت های حوزه داروسازی تولید می کند.

**Comment by Experiencefrom2016** [comment]
شرکتی که بی نظم و بی مسئولیتی در آن موج می زند‌.

**Comment by tajrobe** [comment]
لطفا تجربه خود را به صورت مبسوط در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/ادمان-فناوری-پنگان/](https://tajrobe.github.io/%D8%A7%D8%AF%D9%85%D8%A7%D9%86-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D9%BE%D9%86%DA%AF%D8%A7%D9%86/)
