### ISSUE TITLE
شرکتی بی نظم و بی مسئولیت 

### ISSUE THREAD

**Issue by Experiencefrom2016** [tajrobe/tajrobe.github.io#473]
description: 'شرح تجربه‌ی شما'

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'ادمان فناوری پنگان'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by tajrobe** [comment]
لطفا تجربه خود را به صورت مبسوط در صفحه شرکت مربوطه بنویسید:

[tajrobe.github.io/ادمان-فناوری-پنگان/](https://tajrobe.github.io/%D8%A7%D8%AF%D9%85%D8%A7%D9%86-%D9%81%D9%86%D8%A7%D9%88%D8%B1%DB%8C-%D9%BE%D9%86%DA%AF%D8%A7%D9%86/)
