### ISSUE TITLE
پگاه سیستم

### ISSUE THREAD

**Issue by ImanGhorbani121** [tajrobe/tajrobe.github.io#474]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پگاه-سیستم/](https://tajrobe.github.io/%D9%BE%DA%AF%D8%A7%D9%87-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85/)
