### ISSUE TITLE
مکتب خونه

### ISSUE THREAD

**Issue by mehdi-amz** [tajrobe/tajrobe.github.io#475]
##### نام شرکت
title: "مکتب خونه"

##### نام انگلیسی شرکت
name_en: "maktabkhooneh"

##### دسته‌ی فعالیت شرکت
industry: "Education center"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "100-200"

##### آدرس سایت شرکت
site: "https://maktabkhooneh.org/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مکتب‌خونه بزرگ‌ترین رسانه دیجیتال آموزش مجازی در ایران است که از سال 1390 فعالیت خود را آغاز کرده است. هدف مکتب‌خونه در دسترس قرار دادن آموزش با کیفیت بالا برای همه‌ی فارسي‌زبانان است. ما اعتقاد داریم که هیچ کس نباید به خاطر هیچ چیز از لذت یاد گرفتن محروم شود. نباید سن و سال، مکان، موقعیت یا امکانات مالی فرد، وی را از یادگیری و موفقیت باز دارد.

"

**Comment by tajrobe** [comment]
already exists: [tajrobe.github.io/مکتب-خونه/](https://tajrobe.github.io/%D9%85%DA%A9%D8%AA%D8%A8-%D8%AE%D9%88%D9%86%D9%87/)
