### ISSUE TITLE
جاب ویژن

### ISSUE THREAD

**Issue by mehdi-amz** [tajrobe/tajrobe.github.io#476]
##### نام شرکت
title: "جاب ویژن"

##### نام انگلیسی شرکت
name_en: "Jobvision"

##### دسته‌ی فعالیت شرکت
industry: "Employment consultant "

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "200-500"

##### آدرس سایت شرکت
site: "https://jobvision.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "جاب ویژن (Job Vision)، معتبرترین سایت‌ استخدام و کاریابی در کشور است که تا به امروز بیش از 66 هزار سازمان از جمله اسنپ، ایرانسل، دیجی‌کالا، کاله، یونیلیور، هایپراستار، بانک خاورمیانه، شرکت سفرهای علی بابا، تپسی و... آگهی‌های استخدامی خود را در این پلتفرم منتشر کرده و بیش از دو و نیم میلیون کارجو از خدمات این سایت در حوزه کاریابی و استخدام بهره برده‌اند. برآوردها نشان میدهد صرفا در سال 1400 بیش از 20 هزار نفر از طریق جاب ویژن استخدام شده‌اند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/جاب-ویژن/](https://tajrobe.github.io/%D8%AC%D8%A7%D8%A8-%D9%88%DB%8C%DA%98%D9%86/)
