### ISSUE TITLE
خبرگزاری درلحظه

### ISSUE THREAD

**Issue by mehdi-amz** [tajrobe/tajrobe.github.io#477]
##### نام شرکت
title: "خبرگزاری درلحظه"

##### نام انگلیسی شرکت
name_en: "Darlahzeh news"

##### دسته‌ی فعالیت شرکت
industry: "News Agency"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://darlahzeh.news/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "سایت خبری درلحظه با هدف پوشش اخبار مهم ایران از سال ۱۴۰۳ شروع به کار کرده است"

**Comment by tajrobe** [comment]
[tajrobe.github.io/خبرگزاری-در-لحظه/](https://tajrobe.github.io/%D8%AE%D8%A8%D8%B1%DA%AF%D8%B2%D8%A7%D8%B1%DB%8C-%D8%AF%D8%B1-%D9%84%D8%AD%D8%B8%D9%87/)
