### ISSUE TITLE
بیمه سامان 

### ISSUE THREAD

**Issue by MS-EF** [tajrobe/tajrobe.github.io#478]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/بیمه-سامان/](https://tajrobe.github.io/%D8%A8%DB%8C%D9%85%D9%87-%D8%B3%D8%A7%D9%85%D8%A7%D9%86/)
