### ISSUE TITLE
ازکی و بیمتو (نوین نار)

### ISSUE THREAD

**Issue by Kahookahoo** [tajrobe/tajrobe.github.io#479]
##### نام شرکت
title: ""ازکی دات کام . بیمتو . تجارت الکترونیک نوین نار 

##### نام انگلیسی شرکت
name_en: ""azki.com bimito novin nar

##### دسته‌ی فعالیت شرکت
industry:""بیمه . درمان . خدمات ماشین 

##### موقعیت مکانی شرکت
city: ""تهران . پارک ساعی . پارک وی . صادقیه

##### تعداد نفرات شرکت
size: ""500-1000

##### آدرس سایت شرکت
site: ""azki.com

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
شرکت تجارت الکترونیک نوین نار (erp) به عنوان سر لیدر شرکت های ادغامی برند ازکی و بیمتو  و شرکت های زیر مجموعه هلدینگ ماموت  و max فعالیت میکند . از جمله فعالیت های شبکه ای در خودرو 45 و ثبت  خلافی انلاین و دیگر موسساتی که توسط

**Comment by Kahookahoo** [comment]
اگه در مورد شرکت میخواید بدونید ... اسم شرکت نوین نار هستش و رییس  شرکت نوین نار (erp )و ازکی و بیمیتو توش ترکیب شدن و زیر مجموعه هلدینگ ماموت هستن . بیمیتو و ازکی صرفا سایت هستن   شرکت hr بسیار حروم خوری داره و اون خوشگلی ها حتی موقع مصاحبه و معرفی هم بهتون دروغ میگن و کلا دیدین با شما خوب رفتار میکنن بدونید دروغی بیش نیست  .

 وقت شما رو به هنگام اموزش هدر میدن  طوری که ذهنتون رو خسته میکنن که نتونید چیزی یاد بگیرید . سعی کنید کال سنتر نیوفتید و بیوفتید پییگیری که برید  یا cx یا فروش از بقیه کارش راحت تره و خیلی از واقعیات رو نمیفهمیدد 

 ...  اموزش بشدت افتضاحی داره .بشدت شرکت زیراب زنی زیاد داره . Qc اصلا به ارور های کلیدی شما کاری نداره وتو  اموزش با پنل  مدیریت تماس افتضاحه.. .. ‌سیگار کشیدن و مثل بقیه بودن اصله اونجا وگرنه تک میفتین ... صداتون رو داخل جلسات فیدبک ضبط میکنن و داخل اتاق ها هم همینطوره ....پس بیخود اعتماد نکنید  

 بدونید سرپرست ها علاقه ای به پاسخ دادن ندارند و کار تیمی دروغی بیش نیست . با این که وظیفشونه   حتما باید سر تایمتون ناهار برید وگرنه میپره اخر وقت تماس بهتون میخوره و اجازه ثبتش رو تو پنل ساعت کارکنان ندارید . دم در گیت ورود و خروج براتون گذاشتن. تماس بالای ۱ دقه باگه و احترام به صحبت مشتری براشون مهم نیست و با افزایش تایم تماس باگ شما میشه .

 درکل اونجا برای این موارد کسی عیبتون رو نمیگه . اموزش مجدد نداره و عیبتون رو خودتون باید بفهمید و انجامش ندید برای همینم میگم برید بخش های دیگه .  اونجا باید از قراداد ها و مسئولیت بشدت بترسید !!! بدترین hr ممکن رو داره ....و چون بخش عملیات(پیگیری و کال و cx و b2b)  رو جدا کردن  و ساختمانش  پارک وی هست  هر غلطی دلشون خواست میخوردن .  

ساختمان مرکزی بالای پارک ساعی و واحد پخشش و ارسالش  هم داخل صادقیس  امنیت شغلی نداره و قرارداد ها سه ماهس .حقوقتون رو بی برنامه میدن . از بیمه تکمیلی رایگان اصلا استفاده نکنید وگرنه دچار کسری حقوق موقع عزل قراداد میشید ....بماند که تمام موارد دریافت خسارت رو مجبور هستین از خود شرکت پیگیر بشین ... پس اگه بیمه حتی به رایگان خواستین حضوری خودتون دریافت کنید !!!! اصلا از شرکت قبولش نکنید !!! و مهر و امضا رو مجبورشون کنید بگیرند  دقت کنید مجبورشون کنید  بابت تحویل وسایل و غیره مهر و امضا بگیرید و تونستید موقع قرارداد هرگونه استفاده شرکت از کد ملی و اطلاعات شخصی شما رو ازشون بخواید تو قرارداد ذکر کنن که محدود شن و حق استفاده نداشته باشن.... 


تا دوسال هم حق ندارید  تو شرکت های مشابه کار کنید و تا ۱۰۰ میلیون میتونن از شما خسارت بگیرن . شرکتی که پول مردم رو نگه میداره و با تاخیر پول شرکت های بیمه رو میده و باید کال سنتر و پیگیریش فحشش رو بخورن و مفاد قراردادش به هنگام خرید مشخص نیست  .....و مثل شرکتای بیمه ای که باهاش کار میکنه از دست و پای مورچه کره میگیره    تو قرارداد قید شده که باید کارفرما و کارمند از یکماه زودتر خبر بدن به بهم واسه استعفا یا اخراج .... اما دیدین یهو اکثر بچه ها رو انداختن بیرون !!!! و اتو به اندازه کافی ازتون میگیرن که کاری به جایی نبرین ....

  این همه عیب گفتم . مزایا . بیمه وحقوقتون رو میدن . چایی تا دلتون خواست داره ...اندازه حدودی که براتون تعیین کردن ازادی دارید ...مستخدم های خوبی استخدام میکنن و شغل مستخدمی شرف داره به پیگیری و کال سنتری و حقوقشم دوبرابره ....کاری به روسریتون و حجابتون ندارند. ولی گفتم باید مثل بقیه باشین .   حقوق کال از بقیه کمتره و پیگیری ۲۰ درصد بیشتر و شکایت یک و نیم برابر ... Qc هم که ۳۰ درصد بیشتر از پیگیریه....b2b راحت تره و شیفتت رو شیفت اداری عادی تنظیم میشه و حقوقت هم خیلی بیشتره !!!  سعی کنید کاری برید که اصلا زیر ذره بین این جماعت نباشید ... 

 کارشناس ای تی ... هر موقع دلش بخواد میره و میاد . این وسط خرابی سیستمت بر گردن خودته و اسم کارمندایی که قصد خروج از شرکت دارند  رو دستمال کاغذی مینویسن !! و موقع تعدیل وسط کار یهو میگن وسایلت رو بذار و خوش اومدی فلان روز بیا   شرکتی که به جای دیدن مدیر منابع انسانی و هیئت خروج ... چنتا الاغ که باهاشون سر و کار داشتی رو دائم میبینی و جایی نیست که عیبشون رو بهشون بگی ... مجبوری بیای اینجا بگی تا بفهمن عیبشون چیه ..

.   بدتر از اینکه عیب و ایراد و موجه نبودن کارشناس گردن سرپرستشه و سرپرست به وقت زیرابتو میزنه ....چرا چون پاسخ درست ندادی و میری میپرسی و اون سرپرست بدش میاد جواب بده !!!  بهترین شغل پیک موتوری شدن و کارشناس ارزیابی خسارت بودنه .. چرا چون نمیری انجام بدی و کسی هم چیزی بهت نمیگه و فحشش رو یکی دیگه میخوره!!!  بدترین تجربه شغلیم بود و برای اون مبلغ ارزششو اصلا نداشت واقعا بهتون میگم که تو هیچ کدوم از شرکت های بیمه کار نکنید چه اینترنتی و چه غیر اینترنتی

**Comment by Kahookahoo** [comment]
اگه در مورد شرکت میخواید بدونید ... اسم شرکت نوین نار هستش و رییس  شرکت نوین نار (erp )و ازکی و بیمیتو توش ترکیب شدن و زیر مجموعه هلدینگ ماموت هستن . بیمیتو و ازکی صرفا سایت هستن   شرکت hr بسیار حروم خوری داره و اون خوشگلی ها حتی موقع مصاحبه و معرفی هم بهتون دروغ میگن و کلا دیدین با شما خوب رفتار میکنن بدونید دروغی بیش نیست  .

 وقت شما رو به هنگام اموزش هدر میدن  طوری که ذهنتون رو خسته میکنن که نتونید چیزی یاد بگیرید . سعی کنید کال سنتر نیوفتید و بیوفتید پییگیری که برید  یا cx یا فروش از بقیه کارش راحت تره و خیلی از واقعیات رو نمیفهمیدد 

 ...  اموزش بشدت افتضاحی داره .بشدت شرکت زیراب زنی زیاد داره . Qc اصلا به ارور های کلیدی شما کاری نداره وتو  اموزش با پنل  مدیریت تماس افتضاحه.. .. ‌سیگار کشیدن و مثل بقیه بودن اصله اونجا وگرنه تک میفتین ... صداتون رو داخل جلسات فیدبک ضبط میکنن و داخل اتاق ها هم همینطوره ....پس بیخود اعتماد نکنید  

 بدونید سرپرست ها علاقه ای به پاسخ دادن ندارند و کار تیمی دروغی بیش نیست . با این که وظیفشونه   حتما باید سر تایمتون ناهار برید وگرنه میپره اخر وقت تماس بهتون میخوره و اجازه ثبتش رو تو پنل ساعت کارکنان ندارید . دم در گیت ورود و خروج براتون گذاشتن. تماس بالای ۱ دقه باگه و احترام به صحبت مشتری براشون مهم نیست و با افزایش تایم تماس باگ شما میشه .

 درکل اونجا برای این موارد کسی عیبتون رو نمیگه . اموزش مجدد نداره و عیبتون رو خودتون باید بفهمید و انجامش ندید برای همینم میگم برید بخش های دیگه .  اونجا باید از قراداد ها و مسئولیت بشدت بترسید !!! بدترین hr ممکن رو داره ....و چون بخش عملیات(پیگیری و کال و cx و b2b)  رو جدا کردن  و ساختمانش  پارک وی هست  هر غلطی دلشون خواست میخوردن .  

ساختمان مرکزی بالای پارک ساعی و واحد پخشش و ارسالش  هم داخل صادقیس  امنیت شغلی نداره و قرارداد ها سه ماهس .حقوقتون رو بی برنامه میدن . از بیمه تکمیلی رایگان اصلا استفاده نکنید وگرنه دچار کسری حقوق موقع عزل قراداد میشید ....بماند که تمام موارد دریافت خسارت رو مجبور هستین از خود شرکت پیگیر بشین ... پس اگه بیمه حتی به رایگان خواستین حضوری خودتون دریافت کنید !!!! اصلا از شرکت قبولش نکنید !!! و مهر و امضا رو مجبورشون کنید بگیرند  دقت کنید مجبورشون کنید  بابت تحویل وسایل و غیره مهر و امضا بگیرید و تونستید موقع قرارداد هرگونه استفاده شرکت از کد ملی و اطلاعات شخصی شما رو ازشون بخواید تو قرارداد ذکر کنن که محدود شن و حق استفاده نداشته باشن.... 


تا دوسال هم حق ندارید  تو شرکت های مشابه کار کنید و تا ۱۰۰ میلیون میتونن از شما خسارت بگیرن . شرکتی که پول مردم رو نگه میداره و با تاخیر پول شرکت های بیمه رو میده و باید کال سنتر و پیگیریش فحشش رو بخورن و مفاد قراردادش به هنگام خرید مشخص نیست  .....و مثل شرکتای بیمه ای که باهاش کار میکنه از دست و پای مورچه کره میگیره    تو قرارداد قید شده که باید کارفرما و کارمند از یکماه زودتر خبر بدن به بهم واسه استعفا یا اخراج .... اما دیدین یهو اکثر بچه ها رو انداختن بیرون !!!! و اتو به اندازه کافی ازتون میگیرن که کاری به جایی نبرین ....

  این همه عیب گفتم . مزایا . بیمه وحقوقتون رو میدن . چایی تا دلتون خواست داره ...اندازه حدودی که براتون تعیین کردن ازادی دارید ...مستخدم های خوبی استخدام میکنن و شغل مستخدمی شرف داره به پیگیری و کال سنتری و حقوقشم دوبرابره ....کاری به روسریتون و حجابتون ندارند. ولی گفتم باید مثل بقیه باشین .   حقوق کال از بقیه کمتره و پیگیری ۲۰ درصد بیشتر و شکایت یک و نیم برابر ... Qc هم که ۳۰ درصد بیشتر از پیگیریه....b2b راحت تره و شیفتت رو شیفت اداری عادی تنظیم میشه و حقوقت هم خیلی بیشتره !!!  سعی کنید کاری برید که اصلا زیر ذره بین این جماعت نباشید ... 

 کارشناس ای تی ... هر موقع دلش بخواد میره و میاد . این وسط خرابی سیستمت بر گردن خودته و اسم کارمندایی که قصد خروج از شرکت دارند  رو دستمال کاغذی مینویسن !! و موقع تعدیل وسط کار یهو میگن وسایلت رو بذار و خوش اومدی فلان روز بیا   شرکتی که به جای دیدن مدیر منابع انسانی و هیئت خروج ... چنتا الاغ که باهاشون سر و کار داشتی رو دائم میبینی و جایی نیست که عیبشون رو بهشون بگی ... مجبوری بیای اینجا بگی تا بفهمن عیبشون چیه ..

.   بدتر از اینکه عیب و ایراد و موجه نبودن کارشناس گردن سرپرستشه و سرپرست به وقت زیرابتو میزنه ....چرا چون پاسخ درست ندادی و میری میپرسی و اون سرپرست بدش میاد جواب بده !!!  بهترین شغل پیک موتوری شدن و کارشناس ارزیابی خسارت بودنه .. چرا چون نمیری انجام بدی و کسی هم چیزی بهت نمیگه و فحشش رو یکی دیگه میخوره!!!  بدترین تجربه شغلیم بود و برای اون مبلغ ارزششو اصلا نداشت واقعا بهتون میگم که تو هیچ کدوم از شرکت های بیمه کار نکنید چه اینترنتی و چه غیر اینترنتی

**Comment by tajrobe** [comment]
[tajrobe.github.io/ازکی/](https://tajrobe.github.io/%D8%A7%D8%B2%DA%A9%DB%8C/)
