### ISSUE TITLE
آیدی پی

### ISSUE THREAD

**Issue by xfiveit** [tajrobe/tajrobe.github.io#48]
##### نام شرکت
title: "آیدی پی"

##### نام انگلیسی شرکت
name_en: "IDPay"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران, تهران"

##### تعداد نفرات شرکت
size: "100-200 نفر"

##### آدرس سایت شرکت
site: "https://idpay.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "آیدی پی متعلق به شرکت وب کاران ایمن است. شرکتی خلاق در زمینه خدمات پرداخت که از شهریور ماه 1387 آغاز به کار کرده است.

آیدی پی که با مجوز رسمی شاپرک بانک مرکزی فعالیت می کند، می کوشد با ارائه راهکارهای جدید پرداخت در حوزه آنلاین خدمات با کیفیت بالا را به مشتریان خود ارائه بدهد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/آیدی-پی/](https://tajrobe.github.io/%D8%A2%DB%8C%D8%AF%DB%8C-%D9%BE%DB%8C/)
