### ISSUE TITLE
تجربه کاربری با گیل مد

### ISSUE THREAD

**Issue by Rangingnocom** [tajrobe/tajrobe.github.io#480]
##### نام شرکت
title: ""گیل مد 

##### نام انگلیسی شرکت
name_en: ""gil mode

##### دسته‌ی فعالیت شرکت
industry: ""مد و فشن

##### موقعیت مکانی شرکت
city: ""ایران،رشت
![Screenshot_۲۰۲۴-۰۸-۳۰-۱۳-۱۰-۲۴-۸۶۸_com android chrome](https://github.com/user-attachments/assets/30e555fe-b902-4e1c-8560-f0e94d34fbc3)

##### تعداد نفرات شرکت
size: ""7

##### آدرس سایت شرکت
site: ""Www.gilmode.com

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""فروشگاه انلاین در زمینه لباس زنانه

**Comment by Rangingnocom** [comment]
**تجربه خرید انلاین از سایت گیل مد رو داشتم ارسال کمتر از 24 ساعت،بسته بندی خیلی شیک و جذاب و دلبرونه، اشانتیون دلبرانه، کارت تشکر از خرید و خ
![Uploading IMG_20240918_202423_466.jpg…]()
لاصه گیل مد تو بهترین منی**🥰❤️

**Comment by tajrobe** [comment]
[tajrobe.github.io/گیل-مد/](https://tajrobe.github.io/%DA%AF%DB%8C%D9%84-%D9%85%D8%AF/)
