### ISSUE TITLE
نت پرداز دانا 

### ISSUE THREAD

**Issue by moh-hosseini98** [tajrobe/tajrobe.github.io#482]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/نت-پرداز-دانا/](https://tajrobe.github.io/%D9%86%D8%AA-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2-%D8%AF%D8%A7%D9%86%D8%A7/)
