### ISSUE TITLE
مهندسین مشاور کوتوال

### ISSUE THREAD

**Issue by yasamanhashemi** [tajrobe/tajrobe.github.io#483]
##### نام انگلیسی شرکت
name_en: "kootwall Consulting Engineers" 

##### دسته‌ی فعالیت شرکت
industry: "ساختمان، معماری و شهرسازی" 

##### موقعیت مکانی شرکت
city: "تهران" 

##### تعداد نفرات شرکت
size: "10-50"

##### آدرس سایت شرکت
site: "http://kootwall.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by yasamanhashemi** [comment]
این شرکت به لحاظ اخلاق حرفه ای بسیار ضعیفه. من این شرکت مصاحبه رفتم. پرسیدن از کی میتونی شروع به کار کنی گفتم چون شاغل هستم از 2 هفته ی دیگه میتونم. فرداش تماس گرفتن گفتن میتونید برای همکاری بیاید. من هم گفتم از همون تاریخی که گفتم میتونم شروع کنم. قرار شد تماس بگیرن برای هماهنگی. خبری نشد. من به رئیس شرکت قبلیم گفتم نمیام. باهاشون تماس گرفتم گفتم از شنبه میام. گفتن ما عجله داشتیم یک نفر دیگه رو استخدام کردیم. لزومی هم ندیده بودن به من اطلاع بدن! گفتم چرا خبر ندادید من روی حرف شما حساب کردم خیلی راحت گفتن نمیدونم!

**Comment by tajrobe** [comment]
[tajrobe.github.io/کوتوال/](https://tajrobe.github.io/%DA%A9%D9%88%D8%AA%D9%88%D8%A7%D9%84/)
