### ISSUE TITLE
پرگاسیران

### ISSUE THREAD

**Issue by pargasiran** [tajrobe/tajrobe.github.io#484]
##### نام شرکت: پرگاسیران
title: ""

##### نام انگلیسی شرکت: Pargasiran

1. name_en: ""

##### دسته‌ی فعالیت شرکت: نفت، گاز و پتروشیمی
industry: ""

##### موقعیت مکانی شرکت: قیطریه
city: ""

##### تعداد نفرات شرکت: حدود 300
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
شرکت پرگاسیران یک شرکت خصوصی در حوزه نفت، گاز و پتروشیمی است. این شرکت در سال 1360 تاسیس شد. شروع فعالیت جدی شرکت با ساخت شناور های دریایی بود. از اواخر دهه 90 شمسی وارد فعالیت در حوزه ساخت مخازن تحت فشار شد. کارخانه شرکت در بابلسر و دفتر مرکزی در تهران واقع است.سال ها دفتر مرکزی در سهروردی بود ولی از اوایل سال 1403 علاوه بر ساختمان سهروردی بسیاری از بخش های اصلی شرکت به ساختمانی در قیطریه منتقل شدند.
content: ""

**Comment by pargasiran** [comment]
یک شرکت خصوصی است که بصورت خانوادگی توسط خانواده انصاری اداره میشود

**Comment by tajrobe** [comment]
@pargasiran لطفا تجربه خود را به صورت مشروح در صفحه شرکت بنویسید:

[tajrobe.github.io/پرگاسیران/](https://tajrobe.github.io/%D9%BE%D8%B1%DA%AF%D8%A7%D8%B3%DB%8C%D8%B1%D8%A7%D9%86/)
