### ISSUE TITLE
تهویه

### ISSUE THREAD

**Issue by Ahmadd990** [tajrobe/tajrobe.github.io#485]
##### نام شرکت
title: "تهویه"

##### نام انگلیسی شرکت
name_en: "TAHVIEH"

##### دسته‌ی فعالیت شرکت
industry: "HVAC"

##### موقعیت مکانی شرکت
city: "QAZVIN"

##### تعداد نفرات شرکت
size: "500"

##### آدرس سایت شرکت
site: "QAZVIN"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تولید کننده سیستم های تهویه مطبوع صنعتی و خانگی"

**Comment by Ahmadd990** [comment]
- در مقایسه ب شرکت های دیگه ی صنعت HVAC ، شرکت تهویه در کل شرکت بزرگ و خوبیه ولی موارد زیر رو هم داره:
 پرداخت حقوقش نه خیلی منظم و سر تایمه و نه خیلی بی نظم
- به دلیل سیستم مدیریت شبه دولتی که داره تصمیمات احمقانه مدیریتی توش زیاد دیده میشه
- مثل شرکت های دیگه تنها چیزی که براشون اهمیت نداره اینه که قدر نیروهای خوبشون رو بدونن و خیلی راحت ادم از دست میدن
- تاثیر باندبازی و روابط غیر کاری و غیرحرفه ای تو بالا رفتن یه نفر و پیشرفت کاریش خیلی موثر تر از پارامترهایی مثل باسوادی و صلاحیت و غیره است. در اصل چیزی که اصلا اهمیتی نداره سواده (چون مدیرانی تصمیم گیرنده هستن که خودشون سواد صنعت تهویه مطبوع رو ندارن)
- باید به دیدن این صحنه که توی این شرکت کلی پیرمرد و بازنشسته (دور از چشم اداره کار) مشغول کارن عادت کنید. بعضی مواقع ادم یاد پارک ملت میفته. 
- در 15 سال اخیر شرکت از تولیدات با کیفیت به سمت اینکه ادعا کنه من همه چی میسازم پیش رفته. کیفیت مدارک فنی و مهندسی و همچنین محصولات فدای تعدد محصولات شده و دست تو هر کاری بردن اونم نه به صورت کامل. بهترین عبارت برای توضیفش ناخنک زدنه. شرکت به هر محصولی یه ناخنک زده فقط و بعدش رفته سراغ محصول بعدی- تیم تحقیق و توسعه اش بیشتر به یه تیم کارچاق کن شباهت داره تا یه تیم اکادمیک!

**Comment by tajrobe** [comment]
[tajrobe.github.io/تهویه/](https://tajrobe.github.io/%D8%AA%D9%87%D9%88%DB%8C%D9%87/)
