### ISSUE TITLE
ساب سنگ الوند

### ISSUE THREAD

**Issue by bobigoal** [tajrobe/tajrobe.github.io#486]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ساب-سنگ-الوند/](https://tajrobe.github.io/%D8%B3%D8%A7%D8%A8-%D8%B3%D9%86%DA%AF-%D8%A7%D9%84%D9%88%D9%86%D8%AF/)
