### ISSUE TITLE
سرور دات آی آر

### ISSUE THREAD

**Issue by amb1779** [tajrobe/tajrobe.github.io#487]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/سرور-دات-آی-آر/](https://tajrobe.github.io/%D8%B3%D8%B1%D9%88%D8%B1-%D8%AF%D8%A7%D8%AA-%D8%A2%DB%8C-%D8%A2%D8%B1/)
