### ISSUE TITLE
توسعه اعتبارسنجی شهر

### ISSUE THREAD

**Issue by tochal09** [tajrobe/tajrobe.github.io#488]
##### نام شرکت
title: ""
توسعه اعتبارسنجی شهر
##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""
بانکداری
##### موقعیت مکانی شرکت
city: ""
خیابان طالقانی
##### تعداد نفرات شرکت
size: ""30

##### آدرس سایت شرکت
site: ""https://etebarsanjishahr.ir/

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
شرکت توسعه اعتبارسنجی شهر به صورت شرکت سهامی خاص با هدف اعتبارسنجی اشخاص حقیقی و حقوقی به منظورمدیریت و اندازه گیری ریسک های اعتباری در چارچوب قوانین و مقررات کشور تأسیس و در تاریخ ۱۳۹۴/۱۱/۰۳ تحت شماره ۴۸۶۰۶۸ نزد اداره ثبت شرکت ها و مالکیت صنعتی تهران به ثبت رسیده است.

در حال جزء شرکت های زیرمجموعه بانک شهر می باشد. نشانی مرکز اصلی شرکت در تهران خیابان طالقانی، تقاطع مفتح، پلاک ۱۲۸، طبقه هفتم، واقع می باشد.

**Comment by tochal09** [comment]
اول اینکه مجموعه ( که البته خانه سالمندان براش اسم بهتریه) کار اعتبارسنجی مشتریان بانک شهر رو انجام میده.
چارچوب اصلی شرکت رو یه سری بازنشسته فسیل که از بانک ملت اومدن تشکیل میدن...
خیلی از نیروهایی که قبلا سی سال تو بانک ملت کار کردن  و رفقای مدیر عامل بودن اومدن در قالب شرکت و این باعث شد تمامی حقوق و مزایاشون که در بانک بودن دوبله و سوبله بشه و در واقع هم از توبره بخورن هم از آخور...
البته حقوقشون از زمانی که نیروی بانک بودن  خیلی بیشتر شد ولی مزایای بانکی ها رو هم  دوبله دارن  از جمله وام های کلان، تسهیلات رفاهی و مسافرتی و هتل در شهرهای مختلف، ساعت کاری و حجم کاری کمتر و . . .
کل تایم کاری پرسنل با چرت زدن و مکالمات غیر کاری با تلفن ثابت شرکت و تخمه خوردن و ساعت کاری پر کردن میگذره...کسی اگه بخواد کار کنه و وجدان کاری داشته باشه تو این سیستم تحقیر میشه...کسی هم حق نداره چیری بهشون بگه چون رفیق مدیر عاملن....
مدیرای شرکت خودشون جاسوسی و زیرآب زنی میکنن و انواع و اقسام توهین های قومیتی و .. رو به پرسنل می کنن....

**Comment by tajrobe** [comment]
[tajrobe.github.io/اعتبارسنجی-شهر/](https://tajrobe.github.io/%D8%A7%D8%B9%D8%AA%D8%A8%D8%A7%D8%B1%D8%B3%D9%86%D8%AC%DB%8C-%D8%B4%D9%87%D8%B1/)
