### ISSUE TITLE
پلتفرم یاراپلاس | yaraplus.org

### ISSUE THREAD

**Issue by mohamad178** [tajrobe/tajrobe.github.io#489]
##### نام شرکت
title: ""یاراپلاس

##### نام انگلیسی شرکت
name_en: ""
yaraplus
##### دسته‌ی فعالیت شرکت
industry: ""social media services + telegram bots

##### موقعیت مکانی شرکت
city: ""mashhad & tehran

##### تعداد نفرات شرکت
size: ""11-20

##### آدرس سایت شرکت
site: ""yaraplus.org

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""پلتفرم یاراپلاس
یک پلتفرم جامع برای خدمات دیجیتال، از تبلیغات و فروش در شبکه‌های اجتماعی تا خرید گیفت کارت، اکانت بازی و شماره مجازی. 

سرویس‌های یاراپلاس سریع، تضمینی و متناسب با نیازهای شما هستند.

**Comment by mohamad178** [comment]
I worked as a backend developer and server admin for YaraPlus for two years. We had an incredibly professional, creative, and ethical team. I left due to a job offer from abroad, but throughout my time with them, I truly enjoyed being a part of such an amazing team.

**Comment by mohamad178** [comment]
This team is currently looking to hire skilled video content creators and professional mentors. If you're interested, feel free to reach out to them!

**Comment by tajrobe** [comment]
@mohamad178 لطفا تجربه خود را در صفحه شرکت بنویسید: 

[tajrobe.github.io/یاراپلاس/](https://tajrobe.github.io/%DB%8C%D8%A7%D8%B1%D8%A7%D9%BE%D9%84%D8%A7%D8%B3/)
