### ISSUE TITLE
توسعه خدمات الکترونیک آدونیس

### ISSUE THREAD

**Issue by Goodman1133** [tajrobe/tajrobe.github.io#49]
##### نام شرکت
title: "آدونیس"

##### نام انگلیسی شرکت
name_en: "Adonis"

##### دسته‌ی فعالیت شرکت
industry: "تجهیزات بانکی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۶۰۰"

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by Goodman1133** [comment]
اوایل دهه ۹۰ که واردش شدم بد نبود ، ولی رفته رفته ، رو به سرازیری گذاشت ، پرداخت حقوق و مزایا به تاخیر افتاد ، به جای نیروهای با تجربه ای که شرکت رو ترک می‌کردن نیرویی نمی آوردن و طبیعتا بار اونها بر دوش بقیه تقسیم‌میشد ، مدیران خوبی رو از دست میدادن و به حاش مدیران نالایق و پاچه خوار می اوردن ، یکی از مهم ترین مسائل ، بیمه تکمیلی هست ، اینجا شما رو بیمه تکمیلی نمی کنن و به جاش می‌گن خود شرکت هزینه های درمانیتونو مانند بیمه تکمیلی پرداخت می‌کنه ، ولی باید ۱۵ سال بمونی تا موقع ترک شرکت اون پول رو ازت کم‌نکنه ، اینو از دوستانی که رفتن و ازشون تمام و کمال کسر شده براتون گفتم ، حقوق پایه تش خیلی پایینه ، اینجا اصلا کارمند مهم نیست ، خود مدیر عاملش بارها در همایش ها گفت که : هرکس ناراحته بره ، من یک ارتش دارم
توصیه منب‌که سالهاست دارم اینجا کار می‌کنم و یه دوره واقعا بهش علاقه داشتم اینه: وارد این شرکت نشید
شما هیچ اررشی برای مدیرانش ندارید

**Comment by tajrobe** [comment]
[tajrobe.github.io/آدونیس/](https://tajrobe.github.io/%D8%A2%D8%AF%D9%88%D9%86%DB%8C%D8%B3/)
