### ISSUE TITLE
مرکز‌آهن

### ISSUE THREAD

**Issue by markazeahan706** [tajrobe/tajrobe.github.io#494]
##### نام شرکت
title: "مرکز‌آهن"

##### نام انگلیسی شرکت
name_en: "markazeahan"

##### دسته‌ی فعالیت شرکت
industry: " آهن آلات"

##### موقعیت مکانی شرکت
city: "Isfahan"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "https://www.markazeahan.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مرکزآهن، به عنوان یکی از بزرگترین مجموعه‌های تخصصی در حوزه آهن‌آلات، فعالیت خود را 30 سال پیش به همت بهرام خانی آغاز کرد. امروز، این تیم با واحدهای مختلف از جمله بازرگانی، خرید و فروش، ترابری، مالی و تحقیق و توسعه، خدمات متنوعی را به سازمان‌های دولتی، شرکت‌های خصوصی و مشتریان فردی به‌صورت شبانه‌روزی ارائه می‌دهد."

**Comment by markazeahan706** [comment]
کار کردن در مرکزآهن برای من یک تجربه فوق‌العاده بود. در طول یک سالی که اونجا بودم، از کار تیمی و فضای حرفه‌ای شرکت خیلی یاد گرفتم و فرصتی برای رشد داشتم. محیط دوستانه و حمایت همکاران باعث شد که همیشه انگیزه داشته باشم. حتی بعد از مهاجرت، درس‌ها و تجربیاتی که از مرکزآهن کسب کردم، همیشه همراهم بوده و کمک زیادی به من کرده. اگر دنبال یه محیط پویا و یادگیری مداوم هستید، مرکزآهن جای عالی‌ایه.

**Comment by tajrobe** [comment]
[tajrobe.github.io/مرکزآهن/](https://tajrobe.github.io/%D9%85%D8%B1%DA%A9%D8%B2%D8%A2%D9%87%D9%86/)
