### ISSUE TITLE
شرکت طرح پردازان آذرخش

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#496]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "تولید نرم افزارهای اداری و مالی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "https://www.tpazarakhsh.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت مهندسی طرح پردازان آذرخش، از سال ۱۳۷۸ با هدف مشاوره، طراحی و تولید سیستم های اداری، مالی و پشتیبانی برای وزارتخانه ها و دستگاه های دولتی کار خود را آغاز نمود. با توجه به گستردگی واحدهای سازمانی در اقصا نقاط کشور و حجم سنگین اطلاعات و عملیات در مجموعه وزارت بهداشت، درمان و آموزش پزشکی، این وزارتخانه و دانشگاه علوم پزشکی و خدمات بهداشتی درمانی مشهد به عنوان پایلوت انتخاب گردید تا در فضایی واقعی سیستم ها آزمایش شوند.

"

**Comment by tajrobe** [comment]
[tajrobe.github.io/طرح-پردازان-آذرخش/](https://tajrobe.github.io/%D8%B7%D8%B1%D8%AD-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%D8%A7%D9%86-%D8%A2%D8%B0%D8%B1%D8%AE%D8%B4/)
