### ISSUE TITLE
طرح پردازان آذرخش

### ISSUE THREAD

**Issue by mirandaalison1987** [tajrobe/tajrobe.github.io#497]
##### نام شرکت
title: "طرح پردازان آذرخش"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "تولید نرم افزار های اداری مالی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "100"

##### آدرس سایت شرکت
site: "https://www.tpazarakhsh.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/طرح-پردازان-آذرخش/](https://tajrobe.github.io/%D8%B7%D8%B1%D8%AD-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2%D8%A7%D9%86-%D8%A2%D8%B0%D8%B1%D8%AE%D8%B4/)
