### ISSUE TITLE
شرکت مهندسی و توسعه پترو سازه مبین

### ISSUE THREAD

**Issue by zoheironline** [tajrobe/tajrobe.github.io#498]
##### نام شرکت
title: "شرکت مهندسی و توسعه پترو سازه مبین
"

##### نام انگلیسی شرکت
name_en: "psmco"

##### دسته‌ی فعالیت شرکت
industry: "نفت و گاز"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "400-1000"

##### آدرس سایت شرکت
site: "https://psm.co.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by zoheironline** [comment]
تجربه کاری

**Comment by tajrobe** [comment]
[tajrobe.github.io/پتروسازه-مبین/](https://tajrobe.github.io/%D9%BE%D8%AA%D8%B1%D9%88%D8%B3%D8%A7%D8%B2%D9%87-%D9%85%D8%A8%DB%8C%D9%86/)
