### ISSUE TITLE
درخواست مدیر برندینگ شرکت آریا بنیز

### ISSUE THREAD

**Issue by Aisa-Asghari** [tajrobe/tajrobe.github.io#499]
سلام، این پیام برای من از طریق تلگرام ارسال شده. لطفا رسیدگی کنید.

سلام وقت شما بخیر.
بنده مدیر برندینگ گروه آریا بنیز هستم.

در پروفایل 《آریا بنیز》 سایت تجربه های کاری، به مدت یک سال و نیم هست که به طور پیوسته داره نظراتی ثبت میشه که اکثر اون ها خلاف واقع هست و همگی این نظرات طوری مطرح میشن که انگار از سوی اشخاص مستقل ثبت شدن. این در حالیه که نفرات خروجی دفتر ما طی دو سال اخیر بیش از ۳ نفر نبودن! اگه این صفحه رو الان مشاهده کنید می‌بينيد که رسما به میدون جنگ تبدیل شده و جایی برای تبادل تجربه کاری نیست. لازم میدونم عرض کنم که مطلقا حتی یک نفر از اعضای فعلی شرکت در جهت حمایت نظری ثبت نکردن اما به طور پیوسته اون شخص یا اشخاص دارن نام نفرات حاضر در شرکت رو مطرح میکنن و به اون ها توهین میکنن و تهمت میزنن.

از اون جایی که ثبت نظرات به صورت ناشناس هست، متاسفانه هیچ راهی هم برای اعاده حیثیت و شکایت از این شخص یا اشخاص وجود نداره. این نظرات هم به هویت افراد و هم شرکت داره آسیب جدی وارد میکنه.

متاسفانه ثبت پیوسته این نظرات موجب شده که با سرچ کردن نام شرکت ما در گوگل، سایت تجربه های کاری در همون دو مورد اول صفحه سرچ قرار بگیره و این مسئله کاملا به برند ما داره آسیب میزنه و دیگه صرفا مسئله تجربه کاری مطرح نیست.

فکر میکنم در حال حاضر بیشترین نظر ثبت شده در پروفایل شرکت ما باشه! از شما خواهش میکنم به این مسئله رسیدگی کنید، نظرات پروفایل آریا بنیز رو ساماندهی کنید و حداقل برای مدتی صفحه رو از دسترس خارج کنید که شاید از ادامه روند این شخص یا اشخاص جلوگیری کنه. 
و ازتون میخوام در آینده رویه ای رو پیش بگیرید که افراد اگر خواستن ادعای خاصی رو مطرح کنن (به طور مثال عدم پرداخت حقوق)، با هویت حقیقی و ارائه سند این کارو انجام بدن چون همین مسئله به شدت بر روی تعداد نظرات اسپم تاثیر گذاره.
ممنونم از شما.

**Comment by tajrobe** [comment]
سلام
این مورد رو بررسی می‌کنیم، ولی لزومی نداره برای شما پیام بفرستن و شما رو درگیر کنن، همه جا قید کردیم فقط میتونن ایمیل بزنن.

**Comment by Behrouz-m** [comment]
سلام روز بخیر
لطفا یه سری به صفحه مذکور بزنید
کامنتها به فحش ناموسی کشیده شده
چرا هیج بررسی ای برای تایید کامنت ها قبل از انتشارشون انجام نمیدهید؟

لطفا این پیج را بررسی کنید و ساماندهی کنید
با تشکر

[](https://tajrobe.github.io/آریا-بنیز/)
