### ISSUE TITLE
افرا فایل

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#50]
##### نام شرکت
title: "افرافایل"

##### نام انگلیسی شرکت
name_en: "afrafile"

##### دسته‌ی فعالیت شرکت
industry: "فروشگاه اینترنتی"

##### موقعیت مکانی شرکت
city: "اهواز"

##### تعداد نفرات شرکت
size: "5"

##### آدرس سایت شرکت
site: "https://afrafile.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "افرافایل وب سایت خرید و فروش فایل و محتوای دیجیتاله که پاییز ۱۳۹۹ فعالیتش رو شروع کرد و کاری می کنه تا افرادی مثل طراح های گرافیک، موشن گرافیک کارها، دانشجوها، فریلنسرها، برنامه نویس‌ها، طراح های پروژه های سه بعدی، طراح های پروژه های مهندسی و هرکسی که مهارت دیجیتال داره و می تونه پروژه یا فایل های دیجیتالی آماده کنه فایل ها و پروژه های خودش رو تو این وب‌سایت برای فروش بزاره. و از طرفی هر کسی که نیاز به این پروژه ها و فایل های آماده داره بتونه بیاد تو افرافایل و فایلش رو پیدا کنه و بعد از پرداخت مبلغ مورد نظر فروشنده اون فایل، بلافاصله بعد از پرداخت فایلش رو دانلود و استفاده کنه."

**Comment by tajrobe** [comment]
[tajrobe.github.io/افرافایل/](https://tajrobe.github.io/%D8%A7%D9%81%D8%B1%D8%A7%D9%81%D8%A7%DB%8C%D9%84/)
