### ISSUE TITLE
شرکت دیجیتال مارکتینگ لوتوس

### ISSUE THREAD

**Issue by hassan-honarmand** [tajrobe/tajrobe.github.io#501]
##### نام شرکت
title: "شرکت دیجیتال مارکتینگ لوتوس"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "دیجیتال مارکتینگ"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "متوسط"

##### آدرس سایت شرکت
site: "https://lotus-digital-marketing.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت دیجیتال مارکتینگ لوتوس ارائه دهنده خدمات نتیجه‌محور با استانداردهای بین المللی؛ دارای دو شعبه در تهران و دبی، با بیش از ۱۸ سال سابقه فعالیت حرفه‌ای در حوزه بازاریابی و برندسازی دیجیتال، صادقانه و کمال‌گرایانه، به شما کمک می‌کند تا سهم بازار خود را افزایش دهید و پلی می‌سازد میان شما و مشتریان بالقوه کسب و کار شما."

**Comment by tajrobe** [comment]
[tajrobe.github.io/دیجیتال-مارکتینگ-لوتوس/](https://tajrobe.github.io/%D8%AF%DB%8C%D8%AC%DB%8C%D8%AA%D8%A7%D9%84-%D9%85%D8%A7%D8%B1%DA%A9%D8%AA%DB%8C%D9%86%DA%AF-%D9%84%D9%88%D8%AA%D9%88%D8%B3/)
