### ISSUE TITLE
کالا عمران

### ISSUE THREAD

**Issue by kalaomran** [tajrobe/tajrobe.github.io#502]
##### نام شرکت
title: "کالا عمران"

##### نام انگلیسی شرکت
name_en: "kalaomran"

##### دسته‌ی فعالیت شرکت
industry: "فروش ابزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "kalaomran.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه کالا عمران با بیش از 20 سال سابقه در زمینه فروش و خدمات ابزارآلات تخصصی و 10 هزار کالا از برترین برندهای اروپایی – آمریکایی و آسیایی یکی از معتبرترین فروشگاه های اینترنتی در این حوزه می باشد. علاوه بر مشاهده و بررسی تخصصی محصولات به صورت آنلاین امکان خرید حضوری محصولات در فروشگلاه مرکزی این مجموعه نیز امکان پذیر است. ارسال سریع با بسته بندی استاندارد برای تهران و شهرستان و همچنین داشتن تعمیرگاه تخصصی انواع ابزارآلات از ویژگی ها و خدمات برجسته این مجموعه به شمار می رود."

**Comment by kalaomran** [comment]
تخخصی ترین سایت فروش ابزار در ایران

**Comment by tajrobe** [comment]
[tajrobe.github.io/کالا-عمران/](https://tajrobe.github.io/%DA%A9%D8%A7%D9%84%D8%A7-%D8%B9%D9%85%D8%B1%D8%A7%D9%86/)
