### ISSUE TITLE
دی کامپیوتر

### ISSUE THREAD

**Issue by Naeimshayan** [tajrobe/tajrobe.github.io#504]
description: 'شرح تجربه‌ی شما'

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'نام شرکت'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by tajrobe** [comment]
[tajrobe.github.io/دی-کامپیوتر/](https://tajrobe.github.io/%D8%AF%DB%8C-%DA%A9%D8%A7%D9%85%D9%BE%DB%8C%D9%88%D8%AA%D8%B1/)
