### ISSUE TITLE
رایانکار

### ISSUE THREAD

**Issue by harsini** [tajrobe/tajrobe.github.io#505]
##### نام شرکت
title: "رایانکار"

##### نام انگلیسی شرکت
name_en: "Rayankar"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "40-50"

##### آدرس سایت شرکت
site: "https://www.rayankar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "حوزه فعالیت شرکت "رایانکار" ارائه خدمات مشاوره و برنامه نویسی به شرکت های ایرانی اروپایی و آمریکایی است. "

**Comment by harsini** [comment]
Could you please add a comment why the company won't be added?

**Comment by tajrobe** [comment]
[tajrobe.github.io/رایانکار/](https://tajrobe.github.io/%D8%B1%D8%A7%DB%8C%D8%A7%D9%86%DA%A9%D8%A7%D8%B1/)
