### ISSUE TITLE
پیمان خطوط شرق

### ISSUE THREAD

**Issue by amirjoon** [tajrobe/tajrobe.github.io#508]
##### نام شرکت
title: "پیمان خطوط شرق"

##### نام انگلیسی شرکت
name_en: "peyman khotoot shargh"

##### دسته‌ی فعالیت شرکت
industry: "اتوماسیون پست و پایانه های راه دور"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "40"

##### آدرس سایت شرکت
site: "https://pks-co.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت دانش‌بنیان پیمان خطوط شرق (PKS) در سال ۱۳۸۵با هدف بومی‌سازی فناوری در سیستم‌های اتوماسیون و کنترل تأسیس گردید. فعالیت‌های شرکت در حوزه‌ مهندسی برق و ارتباطات، با طراحی و ساخت ماژول‎های پیشرفته‌ پایانه راه دور (RTU) به منظور مانیتورینگ پست‌های برق فشار قوی آغاز شد و به تدریج به ظهور توانمندی شرکت در طراحی و پیاده‌سازی جامع سیستم‌های پیشرفته HMI، PLC، SCADAو DCS در سطح فوق توزیع و انتقال صنعت برق و دیگر صنایع زیرساختی انجامید. امروز پیمان خطوط شرق به پشتوانه‌ سابقه درخشان پانزده ساله در بیش از ۴۰۰ پروژه طراحی، ساخت و ارائه خدمات مهندسی در حوزه‌های فوق‌الذکر و نیز دارا بودن ظرفیت تولید سالانه ۴۵۰۰ دستگاه پایانه راه دور، به عنوان رهبر بازار شناخته می‌شود. صدور تأییدیه‌های معتبر از‌ مراجع ذی‌صلاح از جمله سازمان پدافند غیرعامل، شرکت توانیر، شرکت مدیریت شبکه برق ایران، پژوهشگاه نیرو، شرکت ملی نفت ایران و شرکت‌های برق منطقه‌ای گواه به‌کارگیری پیشرفته‌ترین روش‌ها و مواد اولیه‌‌ با کیفیت در کنار اندوخته‌ دانشی بی‌رقیب این شرکت می‌باشد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیمان-خطوط-شرق/](https://tajrobe.github.io/%D9%BE%DB%8C%D9%85%D8%A7%D9%86-%D8%AE%D8%B7%D9%88%D8%B7-%D8%B4%D8%B1%D9%82/)
