### ISSUE TITLE
گنجینه پاوان

### ISSUE THREAD

**Issue by neginmasihi** [tajrobe/tajrobe.github.io#509]
##### نام شرکت
title: "گنجینه پاوان"

##### نام انگلیسی شرکت
name_en: "Ganjine pavan"

##### دسته‌ی فعالیت شرکت
industry: "fire fighting equipment"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/گنجینه-پاوان/](https://tajrobe.github.io/%DA%AF%D9%86%D8%AC%DB%8C%D9%86%D9%87-%D9%BE%D8%A7%D9%88%D8%A7%D9%86/)
