### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by talebtash76** [tajrobe/tajrobe.github.io#51]
##### نام شرکت
title: "دانشکار"

##### نام انگلیسی شرکت
name_en: "Daneshkar"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات (پلتفرم کاریابی)"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://daneshkar.net/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تیم دانشکار فعالیت خود را از سال 1396 با هدف ایجاد یک پل ارتباطی بین دانشجویان یا فارغ‌التحصیلان دانشگاهی و شرکت‌ها و کسب‌وکارهای مختلف آغاز کرده است. دانشجویان و فارغ‌التحصیلان با استفاده خدمات مختلف دانشکار از جمله فرصت‌های کارآموزی و استخدام، بوت‌کمپ‌های تخصصی، رویدادهای آموزشی و تست‌های شخصیت‌شناسی می‌توانند با فراگیری مهارت‌های موردنیاز، مسیر شغلی خود را یافته و وارد شرکت‌های مورد علاقه خود شوند. کسب و کارها نیاز با اعلام نیازمندی‌های شغلی خود، به رزومه افراد مستعد و متخصص دسترسی خواهند داشت."

**Comment by talebtash76** [comment]
سلام من در آبان 99 برای شغل کارشناس دیجیتال مارکتینگ  در دانشکار دعوت به مصاحبه شدم. دو مرحله مصاحبه داشت. مرحله اول با مدیر مارکتینگ و مرحله دوم با مدیرعامل که خیلی خوب و محترمانه برخورد کردند. الان در این شرکت مشغول به  کارم.

**Comment by tajrobe** [comment]
added new company: [tajrobe.github.io/دانشکار/](https://tajrobe.github.io/%D8%AF%D8%A7%D9%86%D8%B4%DA%A9%D8%A7%D8%B1/)

لطفا تجربه‌ی کاری خود را در [این صفحه](https://tajrobe.github.io/%D8%AF%D8%A7%D9%86%D8%B4%DA%A9%D8%A7%D8%B1/) بنویسید.
