### ISSUE TITLE
لاویسان

### ISSUE THREAD

**Issue by azadi-behzad** [tajrobe/tajrobe.github.io#510]
##### لاویسان (زیرمجموعه خدمات انفورماتیک)
title: ""

##### Iranian technology services 
name_en: ""

##### فناوری و کامپیوتر
industry: ""

##### ساختمان خدمات انفورماتیک
city: ""

##### کمتر از ده نفر
size: ""

##### itscom.ir
site: ""

##### برنامه نویسی
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/آکو-رایان/](https://tajrobe.github.io/%D8%A2%DA%A9%D9%88-%D8%B1%D8%A7%DB%8C%D8%A7%D9%86/)
