### ISSUE TITLE
موبایلت

### ISSUE THREAD

**Issue by 1mehdifaraji** [tajrobe/tajrobe.github.io#512]
##### نام شرکت
title: "موبایلت"

##### نام انگلیسی شرکت
name_en: "Mobillet"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "https://mobillet.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت راهکار یکی از شرکت‌های تابعه بانک سامان از سال 1395 فعالیت خود را با معرفی اپلیکیشن موبایلت در حوزه فینتک آغاز نمود. امروزه راهکارهای مالی هوشمند سامان با مشارکت در توسعه بلو محبوب ترین وبزرگترین نئوبانک ایران و تولیدات ارزنده دیگری مانند بالون که در حوزه لندتک فعالیت میکند، سعی در ایفای نقشی موثر و پیشرو در حوزه فینتک دارد. بهترین ایده ها اغلب از دیدگاه های تازه به دست می آیند. در راهکار، تیم روشن فکر، متنوع و فراگیر ما همیشه در حال یادگیری از یکدیگر هستند. ما کارهای چالش‌برانگیز رو به کارهای معمولی ترجیح می‌دهیم. به تیم ما آزادی عمل و پشتیبانی قابل توجهی داده می‌شود تا آنچه را که برای تبدیل راهکار به مکانی بهتر لازمه دنبال کنند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/موبایلت/](https://tajrobe.github.io/%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84%D8%AA/)
