### ISSUE TITLE
نویان طب مانلی

### ISSUE THREAD

**Issue by noyantebmanely** [tajrobe/tajrobe.github.io#515]
##### نویان طب مانلی
title: ""

##### noyantebmanely
name_en: ""

##### تجهیزات پزشکی و زیبایی
industry: ""

##### تهران و شیراز
city: ""

##### 30
size: ""

##### (https://noyantebmanely.com/)
site: ""

##### شرکت نویان طب مانلی با شعار”ما همیشه یک قدم جلوتر هستیم“برترین وارد کننده و تولیدکننده تجهیزات زیبایی و کلینیکی می باشد، نویان طب مانلی دارنده بروزترین گواهی‌نامه‌های بین المللی در حوزه استاندارد و تجهیزات پزشکی همراه با کادری مجرب و متخصص در تمامی مراحل نصب، راه‌اندازی، آموزش و خدمات پس از فروش می باشد.

نویان طب مانلی وارد کننده انواع دستگاه لیزر از جمله : دستگاه لیزر تیتانیوم، دستگاه لاغری، دستگاه جوانسازی و دستگاه کیوسوئیچ می باشد.

همچنین در آکادمی نویان، دوره های آموزشی کار با دستگاه لیزر ، دستگاه های لاغری، دستگاه های جوانساز و دستگاه کیوسوئیچ به صورت ماهانه و حضوری برگزار میگردد.
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/نویان-طب-مانلی/](https://tajrobe.github.io/%D9%86%D9%88%DB%8C%D8%A7%D9%86-%D8%B7%D8%A8-%D9%85%D8%A7%D9%86%D9%84%DB%8C/)
