### ISSUE TITLE
شبکه مترجمین ایران

### ISSUE THREAD

**Issue by mehdi-maroofian** [tajrobe/tajrobe.github.io#516]
##### شبکه مترجمین ایران
title: ""

##### Transnet
name_en: ""

##### خدمات ترجمه
industry: ""

##### تهران، شمال میدان ونک، ابتدای خیابان ولیعصر، بن‌بست صیرفی، بازار ونک، واحد 404
city: ""

##### 10-50
size: ""

##### https://transnet.ir
site: ""

##### شبکه مترجمین ایران با هدف ارائه خدمات مدرن ترجمه توسط عده‌ای از متخصصین ایرانی صنعت فن‌آوری اطلاعات و استادان فن ترجمه دایر شده‌است. ما با همکاری با مجموعه‌ای از بهترین مترجمان داخلی و خارجی در تمام زمینه‌های تخصصی، بستری را برای ارائه خدمات مطمئن، سریع و با کیفیت فراهم کرده‌ایم.
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/شبکه-مترجمین-ایران/](https://tajrobe.github.io/%D8%B4%D8%A8%DA%A9%D9%87-%D9%85%D8%AA%D8%B1%D8%AC%D9%85%DB%8C%D9%86-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86/)
