### ISSUE TITLE
ترنسیس

### ISSUE THREAD

**Issue by mehdi-maroofian** [tajrobe/tajrobe.github.io#517]
##### ترنسیس
title: "ترنسیس"

##### Transis
name_en: "Transis"

##### خدمات ترجمه
industry: "Translation Industry"

##### تهران - خ شهید مطهری - خ کوه نور - کوچه دوم - پلاک 8 - طبقه پنجم - واحد A
city: "tehran"

##### 10-50
size: "10-50"

##### https://transis.me/
site: "https://transis.me/"

##### گلچینی از بهترین مترجمین و ویراستاران متخصص در یک پلتفرم کاربرپسند حضور دارند تا سفارش شما را با بالاترین کیفیت انجام دهند. ترنسیس را به گونه‌ای طراحی کرده‌ایم تا بتوانید همواره مناسب‌ترین گزینه را برای انجام سفارش خود انتخاب کنید.
content: "گلچینی از بهترین مترجمین و ویراستاران متخصص در یک پلتفرم کاربرپسند حضور دارند تا سفارش شما را با بالاترین کیفیت انجام دهند. ترنسیس را به گونه‌ای طراحی کرده‌ایم تا بتوانید همواره مناسب‌ترین گزینه را برای انجام سفارش خود انتخاب کنید."

**Comment by tajrobe** [comment]
[tajrobe.github.io/ترنسیس/](https://tajrobe.github.io/%D8%AA%D8%B1%D9%86%D8%B3%DB%8C%D8%B3/)
