### ISSUE TITLE
دارالترجمه رسمی مرکزی تهران

### ISSUE THREAD

**Issue by mehdi-maroofian** [tajrobe/tajrobe.github.io#518]
##### نام شرکت
title: "دارالترجمه رسمی مرکزی تهران"

##### نام انگلیسی شرکت
name_en: "centraltranslator"

##### دسته‌ی فعالیت شرکت
industry: "ترجمه رسمی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "5-10"

##### آدرس سایت شرکت
site: "https://centraltranslator.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجموعه‌­ی دارالترجمه رسمی مرکزی تهران، با سال‌ها تجربه در زمینه ترجمه رسمی به همه­‌ی زبان‌های زنده‌ی دنیا زیر نظر قوه قضاییه، اکنون توانسته است به یکی از معتبرترین و با کیفیت ترین مراکز ترجمه رسمی و ترجمه فوری در تهران و ایران تبدیل شود."

**Comment by tajrobe** [comment]
[tajrobe.github.io/دارالترجمه-مرکزی/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%B1%D8%A7%D9%84%D8%AA%D8%B1%D8%AC%D9%85%D9%87-%D9%85%D8%B1%DA%A9%D8%B2%DB%8C/)
