### ISSUE TITLE
کلینیک پوست و مو هلیا

### ISSUE THREAD

**Issue by golbaraan** [tajrobe/tajrobe.github.io#519]
##### نام شرکت
title: ""
کلینیک پوست و مو هلیا

##### نام انگلیسی شرکت
name_en: ""  
Helia Clinic

##### دسته‌ی فعالیت شرکت
industry: ""
 زیبایی و کاشت مو

##### موقعیت مکانی شرکت
city: ""
تهران فرمانیه 
##### تعداد نفرات شرکت
size: "" 30

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
کارهای زیبایی مثل کاشت مو ابرو ریش و سبیل

**Comment by golbaraan** [comment]
🤦🏻‍♀️

**Comment by tajrobe** [comment]
[tajrobe.github.io/کلینیک-هلیا/](https://tajrobe.github.io/%DA%A9%D9%84%DB%8C%D9%86%DB%8C%DA%A9-%D9%87%D9%84%DB%8C%D8%A7/)
