### ISSUE TITLE
نشر میلکان

### ISSUE THREAD

**Issue by radm3758** [tajrobe/tajrobe.github.io#523]
##### نام شرکت
title: "نشر میلکان"

##### نام انگلیسی شرکت
name_en: "Milkan Publication"

##### دسته‌ی فعالیت شرکت
industry: "صنعت نشر"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "https://milkan.ir/"

##### میلکان ناشر عمومی است و در حوزه‌های رمان، مدیریت، کسب‌وکار، روان‌شناسی، توسعه‌ی فردی، فلسفه، تاریخ، هنر، سیاست، ورزش، کودک فعالیت می‌کند و کتاب‌های دانشگاهی یا تخصصی منتشر نمی‌کند.

content: "میلکان ناشر عمومی است و در حوزه‌های رمان، مدیریت، کسب‌وکار، روان‌شناسی، توسعه‌ی فردی، فلسفه، تاریخ، هنر، سیاست، ورزش، کودک فعالیت می‌کند و کتاب‌های دانشگاهی یا تخصصی منتشر نمی‌کند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/نشر-میلکان/](https://tajrobe.github.io/%D9%86%D8%B4%D8%B1-%D9%85%DB%8C%D9%84%DA%A9%D8%A7%D9%86/)
