### ISSUE TITLE
نشر ثالث

### ISSUE THREAD

**Issue by radm3758** [tajrobe/tajrobe.github.io#524]
##### نام شرکت
title: "نشر ثالث"

##### نام انگلیسی شرکت
name_en: "Sales Publications"

##### دسته‌ی فعالیت شرکت
industry: "صنعت نشر"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-50"

##### آدرس سایت شرکت
site: "https://salesspublication.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "نتشارات ثالث فعالیت رسمی خود را از سال 1375 شمسی آغاز کرده است. نشر ثالث از سال 1383 فروشگاه خود را با هدف ایجاد رابطه مستقیم با مخاطب و راه اندازی کتابفروشی مدرن به سبک اروپایی در خیابان کریم خان افتتاح کرد. فروشگاه اینترنتی کتاب نشر ثالث برای تسهیل خرید کتاب برای اهل فرهنگ در سال 1394 آغاز به کار کرد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/نشر-ثالث/](https://tajrobe.github.io/%D9%86%D8%B4%D8%B1-%D8%AB%D8%A7%D9%84%D8%AB/)
