### ISSUE TITLE
پارسا پیشخوان

### ISSUE THREAD

**Issue by fxsoldier001** [tajrobe/tajrobe.github.io#526]
##### پارسا پیشخوان
title: ""

##### parsapishkhan
name_en: ""

##### دفتر پیشخوان دولت
industry: ""

##### تهران
city: ""

##### 
size: ""

##### www.parsapishkhan.ir
site: ""

##### نوبت دهی تعویض پلاک ، تسویه مالیات خوردو ، خلافی ، احراز هویت سخا و کلیه خدمات مرتبط با خودرو
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پارسا-پیشخوان/](https://tajrobe.github.io/%D9%BE%D8%A7%D8%B1%D8%B3%D8%A7-%D9%BE%DB%8C%D8%B4%D8%AE%D9%88%D8%A7%D9%86/)
