### ISSUE TITLE
دانایان

### ISSUE THREAD

**Issue by ehsah34** [tajrobe/tajrobe.github.io#527]
description: 'شرح تجربه‌ی شما'

state: کارآموز|فریلنسر|ریموت|پاره وقت|تمام وقت

job_name: 'عنوان شغلی شما'

company_slug: 'نام شرکت'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by tajrobe** [comment]
[tajrobe.github.io/گروه-مالی-دانایان/](https://tajrobe.github.io/%DA%AF%D8%B1%D9%88%D9%87-%D9%85%D8%A7%D9%84%DB%8C-%D8%AF%D8%A7%D9%86%D8%A7%DB%8C%D8%A7%D9%86/)
