### ISSUE TITLE
گروه مالی دانایان

### ISSUE THREAD

**Issue by ehsah34** [tajrobe/tajrobe.github.io#528]
##### نام شرکت
title: ""
'گروه مالی دانایان
##### نام انگلیسی شرکت
name_en: ""
danayan
##### دسته‌ی فعالیت شرکت
industry: ""
مالی و سرمایه گذاری
##### موقعیت مکانی شرکت
city: ""
تهران 
##### تعداد نفرات شرکت
size: ""250 نفر

##### آدرس سایت شرکت
site: ""
https://danayan.com/
##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""
گروه مالی دانایان (سهامی عام) توسط جمعی از فعالان اقتصادی بخش خصوصی شکل گرفته و تحت نظارت سازمان بورس و اوراق بهادار فعالیت می‌کند. دانایان در حال حاضر طیف وسیع خدمات خود را در چهار حوزه‌ی اصلی مدیریت دارایی، خدمات مالی، تأمین مالی و آموزش و پژوهش از طریق شرکت‌های تخصصی زیرمجموعه‌ی خود به مشتریانش ارائه می‌دهد. ضمن ایجاد یکپارچگی در ارائه‌ی جامع خدمات مالی و سرمایه‌گذاری، گروه مالی دانایان می‌کوشد دانش و تجربه‌ی سرمایه‌ی انسانی خود را با تسلط بر فرایند‌های اجرایی تلفیق کند تا بتواند راه‌کارهای مقتضی، هوشمندانه و بهینه‌ای را به گروه‌های مختلف مشتریانش ارائه دهد. غیر از ارائه‌ی خدمات یاد‌شده، گروه مالی از طریق شرکت سرمایه‌گذاری دانایان، نقش آفرینی‌های متعددی در قالب تأمین منابع مالی و اجرای پروژه‌های صنعتی و ساختمانی در بخش واقعی اقتصاد داشته است که توسعه‌ی شرکت صنایع پتروشیمی زنجان و اجرای پروژه‌های شاخص در صنعت ساختمان از مهم‌ترین آن‌هاست.

**Comment by ehsah34** [comment]
شرکت خوب و منظم بهمراه نظم فرآیندی بالا اما در موارد بازاریابی و برندینگ ضعف قابل توجهی دارد

**Comment by tajrobe** [comment]
[tajrobe.github.io/گروه-مالی-دانایان/](https://tajrobe.github.io/%DA%AF%D8%B1%D9%88%D9%87-%D9%85%D8%A7%D9%84%DB%8C-%D8%AF%D8%A7%D9%86%D8%A7%DB%8C%D8%A7%D9%86/)
