### ISSUE TITLE
پیوند آزاد شبکه

### ISSUE THREAD

**Issue by NETSECMAN** [tajrobe/tajrobe.github.io#529]
پیوند آزاد شبکه 

Peyvand Azad Shabakeh 

خدمات و پشتیبانی IT

تهران میدان فاطمی 

100 نفر 

http://peyvandazad.net
شرکت پیوند آزاد شبکه، در سال 1385 با هدف ارایه خدمات و راه‌حل‌های مبتنی بر فناوری اطلاعات و ارتباطات تأسیس گردیده و دارای ۵ رتبه در رسته های متنوع از شورای عالی انفورماتیک میباشد.

**Comment by NETSECMAN** [comment]
سلام
حدود یک سال به عنوان کارشناس شبکه مشغول به کار بودم 
به هیچ عنوان توصیه نمیکنم افراد با تجربه با این شرکت همکاری کنن چون مدیرانی بشدت بی سواد و پدرسوخته دارد .
اکثر پروژه ها 24*7 میباشد و می بایست شیفت های طولانی (مثلا 24 ساعت یا 36 ساعت )در این پروژه ها حضور داشته باشید .
و هیچ اضافه کاری به شما تعلق نمیگیرد .
شرکت هیچ ساختاری درست و حسابی ندارد و فاقد واحد  منابع انسانی و واحد  مالی میباشد .
ساعت کاری هیچ جای مشخصی ثبت نمیشود و باید بصورت دستی اعلام شود .
هیچ گونه مزایای خاصی ندارد و حتی بعضا بیمه ها را رد نمیکنند .
مدام بابت عدم پرداحت حقوق از این شرکت شکایت میکنند .

**Comment by tajrobe** [comment]
[tajrobe.github.io/پیوند-آزاد-شبکه/](https://tajrobe.github.io/%D9%BE%DB%8C%D9%88%D9%86%D8%AF-%D8%A2%D8%B2%D8%A7%D8%AF-%D8%B4%D8%A8%DA%A9%D9%87/)
