### ISSUE TITLE
آکادمی یاسان

### ISSUE THREAD

**Issue by ghanimimohammad** [tajrobe/tajrobe.github.io#53]
##### نام شرکت
title: آکادمی یاسان

##### نام انگلیسی شرکت
name_en: "yasan academy"

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: تهران

##### تعداد نفرات شرکت
size: 170

##### آدرس سایت شرکت
site: Yasanacademy.ir

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/آکادمی-یاسان/](https://tajrobe.github.io/%D8%A2%DA%A9%D8%A7%D8%AF%D9%85%DB%8C-%DB%8C%D8%A7%D8%B3%D8%A7%D9%86/)
