### ISSUE TITLE
آریابنیز

### ISSUE THREAD

**Issue by mohamad1054** [tajrobe/tajrobe.github.io#530]
##### نام شرکت
title: ""

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: ""

##### موقعیت مکانی شرکت
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by mohamad1054** [comment]
متاسفانه صفحه قبلی این شرکت با 200 و خورده ای کامنت منفی از دسترس خارج شده از این به بعد اینجا نظارت مثبت و منفی خود را اعلام نمایید.

**Comment by tajrobe** [comment]
[tajrobe.github.io/آریا-بنیز/](https://tajrobe.github.io/%D8%A2%D8%B1%DB%8C%D8%A7-%D8%A8%D9%86%DB%8C%D8%B2/)
