### ISSUE TITLE
پیشرو سامانه آراد

### ISSUE THREAD

**Issue by alireza-salehi** [tajrobe/tajrobe.github.io#531]
##### نام شرکت
title: "پیشرو سامانه آراد"

##### نام انگلیسی شرکت
name_en: "Pishro Samaneh ARAD"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "https://arad.co"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "پیشرو سامانه آراد یک شرکت نرم افزاری است و در سال 1391 تاسیس گردیده و در زمینه های زیر فعالیت میکند: طراحی و تولید راه کارهای جامع وب و موبایل
طراحی و تولید نرم افزارهای سازمانی و سفارش مشتری
طراحی و تولید نرم افزارهای موبایل
طراحی و تولید وب سایت / پرتال
خدمات تخصصی پایگاه داده ها
تولید طیف متنوعی از نرم افزارهای جامع و چند منظوره، نرم افزارهای وب پایه، نرم افزارهای موبایل، نرم افزارهای تخصصی و کاربردی و سامانه های هوشمند و همچنین خدمات تخصصی برای سامانه های نرم افزاری سازمانی و خدمات تخصصی پایگاه داده ها، ارائه مشاوره و پشتیبانی سامانه های مشتریان و ارائه آموزش های تخصصی در حوزه نرم افزار اهم فعالیت های پیشرو سامانه آراد است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/گروه-آراد/](https://tajrobe.github.io/%D9%BE%DB%8C%D8%B4%D8%B1%D9%88-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87-%D8%A2%D8%B1%D8%A7%D8%AF/)
