### ISSUE TITLE
ابرناک

### ISSUE THREAD

**Issue by mhsalehpor** [tajrobe/tajrobe.github.io#54]
##### نام شرکت
title: "ابرناک"

##### نام انگلیسی شرکت
name_en: "abrNOC"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۰ نفر"

##### آدرس سایت شرکت
site: "https://abrnoc.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "ابرناک به‌عنوان شرکتی مستقل با تجربه حضور در فضای بین‌الملل در بهار ۱۳۹۹ با هدف نوآوری و توسعه نرم افزارهای مبتنی بر ابر فعالیتش را در ایران آغاز کرد. در ابرناک برای ساختن محصولات و خدمات سقفی وجود ندارد و فارغ از محدودیت های زمانی و مکانی همواره در تلاشیم که بهترین خودمان باشیم تا ایده‌ها و خلاقیت هایی بر اساس نیاز جامعه جهانی در مقیاس و استاندارد بین‌المللی برای مخاطبان ارائه دهیم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/ابرناک/](https://tajrobe.github.io/%D8%A7%D8%A8%D8%B1%D9%86%D8%A7%DA%A9/)
