### ISSUE TITLE
remove pros cons in salpa reviews

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#59]
سالپا مزایا و معایب نداره برای همین بهتره شرط بزارید و پاکش کنید چون الان جاش خالیه و یکم زشتش کرده
برای چیزایی ک از سالپا وارد شده میتونین ایکون سالپا رو به شکل بدج به رویو اضافه کنین که یکم متمایز شه 
اینو برای جابگای و چیزایی ک برای خود سایت تجربه است هم میتونیم انجام بدیم

**Comment by tajrobe** [comment]
الان شرطی اضافه کردیم که اگر همزمان معایب و مزایا خالی بود، آن قسمت نشان داده نشود، ولی اگر فقط یکی خالی باشد هر دو را نشان می‌دهیم، به نظر من این برای تجربه‌های کاری که یکطرفه ثبت می‌شوند مفید خواهد بود.

در خصوص تجربه‌های وارد شده از سالپا به کمک css، الان یک نوار آبی رنگ در کنار کادر تجربه نمایش می‌دهیم.

وجه تمایز تجربه‌های سالپا مقادیر خالی date و rate در فایل yml تجربه‌هاست، متاسفانه برای جابگای، وجه تمایزی به این سادگی نداریم، پیشنهادی به نظرتان می‌رسد؟

**Comment by pooooriya** [comment]
اگ من آیدی اضافه نمیکردم ، فک کنم اونایی ک از جابگای اضافه کردید آیدی نداشت
ولی خب حالا چون برای من آیدی داره ،مگر اینکه بگی آیدی داشت ولی ریت و دیت
نداشت بشه سالپا ، ایدی داشت و ریت و دیت بشه تجربه خود سایت ، آیدی نداشت بشه
جابگای

**Comment by tajrobe** [comment]
آیدی جواب نداد ولی با استفاده از مقایسه تاریخ، تجربه‌های جابینجا هم متمایز شدند.
