### ISSUE TITLE
پی استار

### ISSUE THREAD

**Issue by m-mohammadi1** [tajrobe/tajrobe.github.io#61]
##### پی استار
title: ""

##### paystar.ir
name_en: ""

##### خدمات بانکی
industry: ""

##### تهران
city: ""

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: ""

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/پی-استار/](https://tajrobe.github.io/%D9%BE%DB%8C-%D8%A7%D8%B3%D8%AA%D8%A7%D8%B1/)
