### ISSUE TITLE
نام شرکت را اینجا نیز وارد کنید | ترجیحا فارسی

### ISSUE THREAD

**Issue by ahmadalavina** [tajrobe/tajrobe.github.io#62]
##### نام شرکت
title: "نواندیشان بازار سرمایه"

##### نام انگلیسی شرکت
name_en: ""

##### دسته‌ی فعالیت شرکت
industry: "کارگزاری"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-50"

##### آدرس سایت شرکت
site: "noadndishan.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/نواندیشان-بازار-سرمایه/](https://tajrobe.github.io/%D9%86%D9%88%D8%A7%D9%86%D8%AF%DB%8C%D8%B4%D8%A7%D9%86-%D8%A8%D8%A7%D8%B2%D8%A7%D8%B1-%D8%B3%D8%B1%D9%85%D8%A7%DB%8C%D9%87/)
