### ISSUE TITLE
طراحان داتیس ایرانیان

### ISSUE THREAD

**Issue by amirhosseinh73** [tajrobe/tajrobe.github.io#63]
##### نام شرکت
title: "طراحان داتیس ایرانیان"

##### نام انگلیسی شرکت
name_en: "Tarahan Datis Iranian"

##### دسته‌ی فعالیت شرکت
industry: "طراحی وب سایت"

##### موقعیت مکانی شرکت
city: "اصفهان"

##### تعداد نفرات شرکت
size: "1-10"

##### آدرس سایت شرکت
site: "irwebdesign.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحان ایرانیان بیش از 15 سال است در حوزۀ فناوری‌های دیجیتال فعالیت می‌کند. تجربۀ این سال‌ها به ما نشان داده است که رسانه‌های دیجیتال می‌توانند نقشی کلیدی در افزایش کیفیت زندگی همۀ ما ایرانی‌ها ایفا کنند. دقیقاً همین نگاه بود که باعث شد ما وارد عرصۀ بازاریابی دیجیتال شویم. به این امید که بتوانیم نقشی کوچک در بهبود و توسعۀ رسانه‌های دیجیتال فارسی داشته باشیم."

**Comment by amirhosseinh73** [comment]
من یکسال و 1 ماه برای این شرکت کار کردم، حقوق پایه اداره کار بستن ولی 5 ماه حقوق نمیداد، و یهو یه چک میداد، بیمه کلا 5 ماه رد کرد، اخر کارم عیدی و سنوات و اضافه کاری هیچی نداد و عملا تو سال 98، 7 میلیون به من نداد، شکایتم کردم، رییس شرکت یه پسر 75 ایه، که حتی سال تولدشم به دروغ بیشتر میگه، تا الانم دوتا شکایت دیگه میدونم ازشون شده

**Comment by tajrobe** [comment]
سلام @amirhoseinh73 
لطفا تجربه‌ی خود را در صفحه زیر بنویسید:
[tajrobe.github.io/طراحان-داتیس/](https://tajrobe.github.io/%D8%B7%D8%B1%D8%A7%D8%AD%D8%A7%D9%86-%D8%AF%D8%A7%D8%AA%DB%8C%D8%B3/)

**Comment by amirhosseinh73** [comment]
ممنون
