### ISSUE TITLE
SEO improvement

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#64]
متاسفانه ورودی های خوبی از گوگل نداره سایت بخاطر سئو ضعیف باید یه سری تمهیداتی اندیشیده شه که بتونیم سئو رو ایمپرو کنیم روی سایت
ایده ای براش ندارید؟

**Comment by tajrobe** [comment]
چون تکنولوژی مورد استفاده jekyll هست دستمون زیاد برای سئو باز نیست، سه پلاگین در دسترس برای گیتهاب‌پیج ( jekyll-sitemap, jekyll-feed,  jekyll-seo-tag ) نصب شده‌اند، ولی گیتهاب‌پیج  مثل وردپرس نیست که پلاگینهای زیادی براش باشه و جامعه‌ی توسعه‌دهنده‌ی فعالی داشته باشه. 
به نظر یه راه دادن بک لینک از وبلاگها یا شبکه‌های اجتماعی به به صفحات شرکت‌هاست. با توجه به اینکه وقت آزاد ما محدود هست به نظر باید افراد داوطلب بیشتری با تخصص سئو یا UX در این پروژه مشارکت کنن.
