### ISSUE TITLE
بهترینو

### ISSUE THREAD

**Issue by evakdev** [tajrobe/tajrobe.github.io#65]
##### نام شرکت
title: "بهترینو"

##### نام انگلیسی شرکت
name_en: "Behtarino"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۱۱ تا ۵۰ نفر"

##### آدرس سایت شرکت
site: "https://behtarino.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/بهترینو/](https://tajrobe.github.io/%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86%D9%88/)
