### ISSUE TITLE
هنری

### ISSUE THREAD

**Issue by hosseinfti** [tajrobe/tajrobe.github.io#66]
##### نام شرکت
title: "هنری"

##### نام انگلیسی شرکت
name_en: "Honari"

##### دسته‌ی فعالیت شرکت
industry: "مواد و ابزار هنری"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "10_20"

##### آدرس سایت شرکت
site: "https://honari.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "فروشگاه مواد و ابزار هنری و خرازی آنلاین"

**Comment by hosseinfti** [comment]
ready to deploy

**Comment by tajrobe** [comment]
[tajrobe.github.io/هنری/](https://tajrobe.github.io/%D9%87%D9%86%D8%B1%DB%8C/)
