### ISSUE TITLE
کی دبلیو رنک

### ISSUE THREAD

**Issue by pourya1** [tajrobe/tajrobe.github.io#67]
##### نام شرکت
title: "کی دبلیو رنک"

##### نام انگلیسی شرکت
name_en: "KWRank"

##### دسته‌ی فعالیت شرکت
industry: "سرویس بررسی رتبه سایت"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10"

##### آدرس سایت شرکت
site: "kwrank.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "کی دبلیو رنک سرویس بررسی موقعیت وب سایت در جستجوی کلمات کلیدی از طریق کشور، شهر و دستگاه های مدنظر شما به صورت خودکار در گوگل است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/کی-دبلیو-رنک/](https://tajrobe.github.io/%DA%A9%DB%8C-%D8%AF%D8%A8%D9%84%DB%8C%D9%88-%D8%B1%D9%86%DA%A9/)
