### ISSUE TITLE
کلیک هاب

### ISSUE THREAD

**Issue by yasanglass** [tajrobe/tajrobe.github.io#68]
##### نام شرکت
title: "کلیک هاب (شرکت نوآوران داده پرداز کلیک)"

##### نام انگلیسی شرکت
name_en: "ClickHub"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران، تهران"

##### تعداد نفرات شرکت
size: "5-10"

##### آدرس سایت شرکت
site: "https://clickhub.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "هدف کلیک ایجاد نوآوری در زمینه ی فناوری و مکانیزه سازی فرآیند های کسب و کار ها است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/کلیک-هاب/](https://tajrobe.github.io/%DA%A9%D9%84%DB%8C%DA%A9-%D9%87%D8%A7%D8%A8/)
