### ISSUE TITLE
هف هشتاد

### ISSUE THREAD

**Issue by yasanglass** [tajrobe/tajrobe.github.io#69]
##### نام شرکت
title: "هف هشتاد"

##### نام انگلیسی شرکت
name_en: "Hafhashtad"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات و اینترنت"

##### موقعیت مکانی شرکت
city: "تهران، تهران"

##### تعداد نفرات شرکت
size: "۲۰۱ تا ۵۰۰ نفر"

##### آدرس سایت شرکت
site: "https://780.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "امروزه به مدد توسعه جهانی تکنولوژي، گسترش زیرساخت‌‌های ارتباطی در ایران و بالارفتن سواد دیجیتال در جامعه، انواع اپلیکیشن‌‌ها و به طور خاص نرم‌افزارهای پرداخت الکترونیک محبوبیت بالایی نزد ایرانی‌ها کسب کرده‌اند.
مجموعه تهران‌اینترنت نیز به پشتوانه بیش از ۲۰ سال حضور فعال در عرصه فناوری، تلاش کرده است نقشی فعال و اثربخش در همراه کردن هموطنان با استفاده از خدمات غیرحضوری و اینترنتی به ويژه کد دستوری و اپلیکیشن هف‌هشتاد داشته باشد. اثربخشی هف‌هشتاد در این زمینه از میزان محبوبیت آن قابل ارزیابی است؛ چنان که با استناد به آمار اعلامی بانک مرکزی، هف‌هشتاد با پشتیبانی بیش از ۳۰ درصد از تراکنش‌های موبایلی، رهبر امروز بازار پرداخت الکترونیک بر بستر موبایل محسوب می‌شود.
ما در هف‌هشتاد با همراهی گروهی از متخصص‌ترین و کاربلدترین‌ نیروها تلاش می‌کنیم با مبنا قرار دادن نیاز بازار و با هدف توسعه کاربری تکنولوژی در بین عموم جامعه، طیف وسیعی از خدمات پرداخت الکترونیک را به شیوه‌ای هوشمندانه، ساده و کاربردی در بستر اپلیکیشن و کددستوری ۷۸۰ به عموم هموطنان ارائه کنیم و به دنبال آن هستیم که در آینده این خدمات را توسعه دهیم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/هف-هشتاد/](https://tajrobe.github.io/%D9%87%D9%81-%D9%87%D8%B4%D8%AA%D8%A7%D8%AF/)
