### ISSUE TITLE
رادار فراتک هوشمند

### ISSUE THREAD

**Issue by malihe1991** [tajrobe/tajrobe.github.io#70]
##### نام شرکت
title: "رادار فراتک هوشمند"

##### نام انگلیسی شرکت
name_en: "radar fratech hooshmand"

##### دسته‌ی فعالیت شرکت
industry: "ردیاب خودرو و فناوری اطلاعات"

##### موقعیت مکانی شرکت
city: "مشهد"

##### تعداد نفرات شرکت
size: "60"

##### آدرس سایت شرکت
site: "radargps.org"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "در زمینه ردیاب خودرو فعالیت دارد"

**Comment by tajrobe** [comment]
[tajrobe.github.io/رادار-فراتک-هوشمند/](https://tajrobe.github.io/%D8%B1%D8%A7%D8%AF%D8%A7%D8%B1-%D9%81%D8%B1%D8%A7%D8%AA%DA%A9-%D9%87%D9%88%D8%B4%D9%85%D9%86%D8%AF/)
