### ISSUE TITLE
کندا ایده

### ISSUE THREAD

**Issue by mhsalehpor** [tajrobe/tajrobe.github.io#71]
##### نام شرکت
title: "کندا ایده"

##### نام انگلیسی شرکت
name_en: "kandaidea"

##### دسته‌ی فعالیت شرکت
industry: "کامپیوتر، فناوری اطلاعات"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "۵۰ - ۱۰۰"

##### آدرس سایت شرکت
site: "kandaidea.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/کندا-ایده/](https://tajrobe.github.io/%DA%A9%D9%86%D8%AF%D8%A7-%D8%A7%DB%8C%D8%AF%D9%87/)
