### ISSUE TITLE
داده‌ورزی فرادیس البرز

### ISSUE THREAD

**Issue by pedy** [tajrobe/tajrobe.github.io#73]
##### نام شرکت
title: "داده‌ورزی فرادیس البرز"

##### نام انگلیسی شرکت
name_en: "Faradis Alborz (DFA)"

##### دسته‌ی فعالیت شرکت
industry: "پرداخت و بانکداری الکترونیک"

##### موقعیت مکانی شرکت
city: "تهران، قزوین، سایر نقاط کشور"

##### تعداد نفرات شرکت
size: "1000"

##### آدرس سایت شرکت
site: "http://www.faradis.net"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "تأمین، تولید، توسعه و پشتیبانی سخت‌افزاری و نرم‌افزاری راهکارهای پرداخت و بانکداری الکترونیک"

**Comment by tajrobe** [comment]
[tajrobe.github.io/داده-ورزی-فرادیس/](https://tajrobe.github.io/%D8%AF%D8%A7%D8%AF%D9%87-%D9%88%D8%B1%D8%B2%DB%8C-%D9%81%D8%B1%D8%A7%D8%AF%DB%8C%D8%B3/)
