### ISSUE TITLE
عرفان سلامت

### ISSUE THREAD

**Issue by MahdiGharooni** [tajrobe/tajrobe.github.io#74]
##### نام شرکت
title: "عرفان سلامت"

##### نام انگلیسی شرکت
name_en: "erfan salamat"

##### دسته‌ی فعالیت شرکت
industry: "خدمات درمانی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "https://www.erfansalamat.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه خدمات درمانی عرفان سلامت با بهره گیری از حدود دو دهه تجربیات ارزشمند مجموعه بیمارستان های عرفان سعادت آباد و عرفان نیایش، با هدف گسترش رویکرد جدیدی در ارائه خدمات درمانی متناسب با نیاز بیماران به صورت اختصاصی در بیمارستان و منزل آماده خدمات رسانی است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/عرفان-سلامت/](https://tajrobe.github.io/%D8%B9%D8%B1%D9%81%D8%A7%D9%86-%D8%B3%D9%84%D8%A7%D9%85%D8%AA/)
