### ISSUE TITLE
پرداخت نوین

### ISSUE THREAD

**Issue by MahdiGharooni** [tajrobe/tajrobe.github.io#75]
##### نام شرکت
title: "پرداخت نوین"

##### نام انگلیسی شرکت
name_en: "Pardakht Novin"

##### دسته‌ی فعالیت شرکت
industry: "Financial"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "200"

##### آدرس سایت شرکت
site: "https://pna.co.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت پرداخت نوین با هدف گسترش شبکه و ارایه خدمات نوین پرداخت الکترونیک تاسیس گردید و در حال حاضر به عنوان یکی از شرکت‌های دارای مجوز از بانک مرکزی و شاپرک در حوزه پرداخت الکترونیک مشغول به فعالیت است. این شرکت با برخـورداری از تجربه چندین ساله و دانش و تخصـص مدیران و کارکنان ماهر به عنوان یک گروه توانمند با تکیه بر فناوری‌های روز دنیا، طیف گسترده ای از خدمات پرداخت الکترونیک را بر بستر ایمن ارایه می‌نماید."

**Comment by tajrobe** [comment]
[tajrobe.github.io/پرداخت-نوین/](https://tajrobe.github.io/%D9%BE%D8%B1%D8%AF%D8%A7%D8%AE%D8%AA-%D9%86%D9%88%DB%8C%D9%86/)
