### ISSUE TITLE
فناوری های اطلاعاتی و مالی توزیع شده یکتا ققنوس پارس

### ISSUE THREAD

**Issue by cipherbullet** [tajrobe/tajrobe.github.io#78]
##### نام شرکت
title: "فناوری های اطلاعاتی و مالی توزیع شده یکتا ققنوس پارس"

##### نام انگلیسی شرکت
name_en: "Kuknos"

##### دسته‌ی فعالیت شرکت
industry: "BlockChain"

##### موقعیت مکانی شرکت
city: "Tehran"

##### تعداد نفرات شرکت
size: "50"

##### آدرس سایت شرکت
site: "kuknos.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: ""

**Comment by tajrobe** [comment]
[tajrobe.github.io/ققنوس/](https://tajrobe.github.io/%D9%82%D9%82%D9%86%D9%88%D8%B3/)
