### ISSUE TITLE
تجربه کار در گلپینو

### ISSUE THREAD

**Issue by mohammadjavadhoseinpoor** [tajrobe/tajrobe.github.io#79]
من حدود چهار ماه در گلپینو مشغول کار هستم و وظیفه مدیریت شبکه های اجتماعی بر عهده م هست. تجربه کاری من در این مدت بسیار مثبت هست و از نظم و انضباط تیمی لذت میبرم. همچنین محیط کاری بسیار دوستانه و صمیمی میباشد، پرداخت حقوق به موقع انجام میشود. با وجود این که در گذشته مشکلاتی وجود داشت اما با مدیریت جدید بسیاری از مشکلات حل شده و کارکنان و مدیر جدید واقعا حرفه ای و درجه یک هستند. در کل من بسیار از عملکرد تیم گلپینو راضی هستم.'

**Comment by mohammadjavadhoseinpoor** [comment]
من حدود چهار ماه در گلپینو مشغول کار هستم و وظیفه مدیریت شبکه های اجتماعی بر عهده م هست. تجربه کاری من در این مدت بسیار مثبت هست و از نظم و انضباط تیمی لذت میبرم. همچنین محیط کاری بسیار دوستانه و صمیمی میباشد، پرداخت حقوق به موقع انجام میشود. با وجود این که در گذشته مشکلاتی وجود داشت اما با مدیریت جدید بسیاری از مشکلات حل شده و کارکنان و مدیر جدید واقعا حرفه ای و درجه یک هستند. در کل من بسیار از عملکرد تیم گلپینو راضی هستم.

**Comment by tajrobe** [comment]
Done.  [tajrobe.github.io/گلپینو/](https://tajrobe.github.io/%DA%AF%D9%84%D9%BE%DB%8C%D9%86%D9%88/)
