### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by hatamiarash7** [tajrobe/tajrobe.github.io#8]
Hey there
You should have these files in your published repository:

- `Gemfile`
- `Gemfile.lock`
- `package.json`

Fix this, so we can contribute to this project easily

**Comment by tajrobe** [comment]
سلام آرش

[انجام شد.](https://github.com/tajrobe/tajrobe.github.io/commit/fa12eec7905740dc08a13cb7396e66e1196442b2)
## توضیح بیشتر
این پروژه یک [GitHub Pages](https://pages.github.com/) است. مبتنی بر سایت ساز استاتیک به نام [جیکیل](https://jekyllrb.com/docs/) .
بعد از هر push اسکریپت تولید صفحات استاتیک در محیطی ایزوله همانند داکر اجرا می‌شود و صفحات استاتیک HTML سایت را می‌سازد.
فرانت این سایت مبتنی بر HTML، css و مقدار بسیار کم جاواسکریپت است. تلاش ما توسعه و نمایش سایت به صورت حداقل استفاده از ابزارهای موجود و استفاده‌ی کمتر از منابع سیستم شخص بازدیدکننده است. ما از چیزی مثل nodeJs،  Angular، React و Vue.js استفاده نمی‌کنیم. 
برای نمونه دو فایل gitignore دو مخزن دیگر github pages را ببینید.
[jekyll-now/.gitignore ](https://github.com/barryclark/jekyll-now/blob/master/.gitignore)
[sleek/.gitignore ](https://github.com/janczizikow/sleek/blob/master/.gitignore)
