### ISSUE TITLE
بهسا - بهپرداز همراه سامانه اول

### ISSUE THREAD

**Issue by yrostami** [tajrobe/tajrobe.github.io#80]
##### نام شرکت
title: "بهسا - بهپرداز همراه سامانه اول"

##### نام انگلیسی شرکت
name_en: "Behsa"

##### دسته‌ی فعالیت شرکت
industry: "تلکام"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "500-1000"

##### آدرس سایت شرکت
site: "www.behsacorp.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت بهپرداز همراه سامانه اول (بهسا) از مشارکت میان بزرگترین اپراتور خاورمیانه (همراه اول) و یکی از پیشگامان فناوری اطلاعات در ایران (بهپرداز جهان)، در تاریخ ۱۰/۰۴/۱۳۹۶ در قالب سهامی خاص تاسیس شد. بهسا شرکت ارائه دهنده خدمات طراحی، تولید، ارائه و پشتیبانی نرم‌افزارهای رایانه‌ای اعم از سفارش مشتری است. همچنین در حوزه واردات و پشتیبانی نرم‌افزارهای رایانه‌ای خارجی و نظارت بر اجرای پروژه‌های انفورماتیکی فعالیت دارد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/بهسا-همراه-اول/](https://tajrobe.github.io/%D8%A8%D9%87%D8%B3%D8%A7-%D9%87%D9%85%D8%B1%D8%A7%D9%87-%D8%A7%D9%88%D9%84/)
