### ISSUE TITLE
شرکت طرفه نگار

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#81]
description: روز ده اردیبهشت به من زنگ ردند که بیا شرکت طرفه نگار با رقم نه میلیون کارکنید، تا 31 اردیبهشت قرارداد دارم گفت قراردادت فسخ کن بیا اینجا کارکنید من قرارداد فسخ کردم و در روز شنبه اونجا مشغول به کار شدم تا روز دوشنبه با من قرارداد نبستند که من شک کردم روز دوشنبه که شد طرف سوال فنی پرسید که git base چیست که نمی دونستم که بعد سرچ کردم منظورش فهمیدم git rebase  نه git base  که ای کاش شک می کردم بعد گفت من نمی تونم با رقم نه میلیون اینجا کارکنید با حقوق وزارت کاری کار کنید که 5/700 که من قبول نکردم می گفت شما کمتر ازجونیور شما در حد کاراموز هستید من در شرکت هاکوپیان اواژنگ دکترکارافرینی 4 سال سابقه کار دارم حتی سابقه خودم از بیمه تامین اجتماعی گرفتم بعد نمونه کار قبول نداشت کپی زدید از سایتی و دروغ میگویید شما بین جونیور میدلولی شما درحدکاراموزهستید و حقوقت وزارت کاری است'

state: تمام وقت

job_name: 'فرانت اند دولوپر'

company_slug: 'طرفه نگار'

pros: 'مزایا - با کاما (,) جدا شود'

cons: 'مزایا - با کاما (,) جدا شود'

rate: بین 1.0 تا 5.0

**Comment by tajrobe** [comment]
[tajrobe.github.io/طرفه-نگار/](https://tajrobe.github.io/%D8%B7%D8%B1%D9%81%D9%87-%D9%86%DA%AF%D8%A7%D8%B1/#:~:text=%D8%B1%D9%88%D8%B2%20%D8%AF%D9%87%20%D8%A7%D8%B1%D8%AF%DB%8C%D8%A8%D9%87%D8%B4%D8%AA,%D8%A7%DB%8C%D9%86%20%D8%AA%D8%AC%D8%B1%D8%A8%D9%87%E2%80%8C%DB%8C%20%DA%A9%D8%A7%D8%B1%DB%8C)
