### ISSUE TITLE
عدم ارسال ریت در فرم تا زمانی که تغییری در ریت داده بشه 

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#82]
هنگامی که ریت بدون تغییر باشه ، ولیو ای برای سرور ارسال نمیشه مگر اینکه یوزر تغییری تو عددش بده
![image](https://user-images.githubusercontent.com/65160744/168461281-c6ceee18-d797-4d19-8356-c73961f3cabb.png)

**Comment by tajrobe** [comment]
[fixed](https://github.com/tajrobe/tajrobe.github.io/commit/1a28d799887f3ed783c94415971f37fd6cb41f1b)
