### ISSUE TITLE
گروه شرکت‌های ایبکو

### ISSUE THREAD

**Issue by behrouzdoushabi** [tajrobe/tajrobe.github.io#83]
##### نام شرکت 
title: "گروه شرکت‌های ایبکو"

##### نام انگلیسی شرکت
name_en: "IBKO"

##### دسته‌ی فعالیت شرکت
industry: "صنعتی و معدنی"

##### موقعیت مکانی شرکت
city: "تهران، کرمان، ، بم ، ساوه"

##### تعداد نفرات شرکت
size: "1200"

##### آدرس سایت شرکت
site: "WWW.ibkogroup.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه شرکت‌های ایبکو (ایده بنیان کارمانیا اورنگ) در دهه 80 با فعالیت‌های اکتشافی در معدن روی خان خاتون آغاز به کار کرد و طی سال‌ها فعالیت مستمر توانسته است توانایی‌های خود را در بخش‌های معدنی و صنایع معدنی و پس‌ازآن در صنایع کشاورزی و بیولوژیک، به نحوی توسعه دهد که اکنون به یکی از بزرگ‌ترین گروه‌های صنعتی خصوصی در کشور ایران تبدیل‌شده است و محصولات و خدمات خود را در بخش‌های مذکور ارائه می‌دهد. همچنین این مجموعه در منطقه خاورمیانه نیز در حال فعالیت می‌باشد.
بر اساس بیانیه چشم‌انداز شرکت، گروه شرکت‌های ایبکو، یک خانواده پرجمعیت و چندملیتی، یک جامعه به هم مرتبط، باشهرت جهانی خواهد بود. این مجموعه مفتخر به بومی‌سازی دانش نه‌تنها درون مجموعه بلکه در سطح استان کرمان و در چشم‌انداز آینده، در کشور ایران می‌باشد.
 "

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایبکو/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%A8%DA%A9%D9%88/)
