### ISSUE TITLE
فناوری اطلاعات رجا

### ISSUE THREAD

**Issue by hasanrabiee** [tajrobe/tajrobe.github.io#84]
##### نام شرکت
title: "فناوری اطلاعات رجاء"

##### نام انگلیسی شرکت
name_en: "Raja information technology"

##### دسته‌ی فعالیت شرکت
industry: "فناوری اطلاعات "

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://www.rajaco.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "کار در حوزه پشتیبانی از بانک ها و سازمان های دولتی "

**Comment by tajrobe** [comment]
[tajrobe.github.io/رجا/](https://tajrobe.github.io/%D8%B1%D8%AC%D8%A7/)
