### ISSUE TITLE
ایده سیستم پرداز کیش

### ISSUE THREAD

**Issue by ghost** [tajrobe/tajrobe.github.io#86]
##### نام شرکت
title: "ایده سیستم پرداز کیش"

##### نام انگلیسی شرکت
name_en: "Idea System Process"

##### دسته‌ی فعالیت شرکت
industry: "توسعه نرم افزار"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "10-20"

##### آدرس سایت شرکت
site: "jafamhis.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "توسعه نرم افزار"

**Comment by tajrobe** [comment]
[tajrobe.github.io/ایده-پرداز-کیش/](https://tajrobe.github.io/%D8%A7%DB%8C%D8%AF%D9%87-%D9%BE%D8%B1%D8%AF%D8%A7%D8%B2-%DA%A9%DB%8C%D8%B4/)
