### ISSUE TITLE
rename datetime field to date

### ISSUE THREAD

**Issue by tajrobe** [tajrobe/tajrobe.github.io#87]
سلام. 
توی [propertyهایی](https://github.com/pooooriya/Tajrobe/blob/ebcc2be1db5420b580c47133998ca2eff3a79943/pages/api/tajrobe/review.js#L75) که برای هر تجربه‌ی کاری داریم باید فیلد datetime رو به date تغییر بدیم تا نمایش تاریخ هر تجربه درست نشون داده بشه.

**Comment by pooooriya** [comment]
done

**Comment by tajrobe** [comment]
ممنون 🙏
آره اگر یادت باشه سر تمایز تجربه‌های سالپا و جابگای و تجربه از همین فیلد date استفاده کردیم. البته الان با تغییر شما درست شد.
