### ISSUE TITLE
تعریف شرکت کاریزما

### ISSUE THREAD

**Issue by navid6117** [tajrobe/tajrobe.github.io#88]
##### نام شرکت
title: "گروه مالی کاریزما"

##### نام انگلیسی شرکت
name_en: "Charisma Financial Group"

##### دسته‌ی فعالیت شرکت
industry: "بازارهای مالی و بورس"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "400"

##### آدرس سایت شرکت
site: "https://charisma.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه مالی کاریزما به پشتوانه تجربه بالا در زمینه فعالیت در بازار سرمایه و نیروی انسانی متخصص با بیش از 200 هزار میلیارد ریال دارایی تحت مدیریت، به عنوان یک هلدینگ مالی آماده ارائه خدمات متنوع به مشتریان حقیقی و حقوقی خود می باشد. گروه مالی کاریزما در حال حاضر متشکل از8 شرکت تخصصی و بیش از 400 نفر پرسنل فعال می باشد که زنجیره خدمات کاریزما را برای مشتریان گرامی ایجاد کرده اند."

**Comment by tajrobe** [comment]
[tajrobe.github.io/کاریزما/](https://tajrobe.github.io/%DA%A9%D8%A7%D8%B1%DB%8C%D8%B2%D9%85%D8%A7/)
