### ISSUE TITLE
افزودن شرکت افزیر

### ISSUE THREAD

**Issue by navid6117** [tajrobe/tajrobe.github.io#89]
##### نام شرکت
title: "شرکت مقاوم‌سازی افزیر"

##### نام انگلیسی شرکت
name_en: "Afzir Strengthening Company"

##### دسته‌ی فعالیت شرکت
industry: "مقاوم‌سازی و ساخت و ساز"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://www.afzir.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "افزیر پیشرو و متخصص در زمینه مقاوم‌سازی با مصالح، تجهیزات و فن آوری های نوین در ایران است که با بهره گیری از متخصصین کارآزموده و نیروی فنی ماهر و آموزش دیده در طراحی، تامین و اجرا پروژه ها فعالیت میکند.

این شرکت دارای گواهی نامه صلاحیت پیمانکاری و گواهی نامه صلاحیت خدمات مشاوره از سازمان برنامه و بودجه کشور و کارت بازرگانی از اتاق بازرگانی، صنایع، معادن و کشاورزی تهران می باشد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/افزير/](https://tajrobe.github.io/%D8%A7%D9%81%D8%B2%D9%8A%D8%B1/)
