### ISSUE TITLE
اتراب

### ISSUE THREAD

**Issue by alihemmatnia** [tajrobe/tajrobe.github.io#9]
##### نام شرکت
title: "اتراب"

##### نام انگلیسی شرکت
name_en: "etraab"

##### دسته‌ی فعالیت شرکت
industry: "IT"

##### موقعیت مکانی شرکت
city: "Urmia"

##### تعداد نفرات شرکت
size: "40"

##### آدرس سایت شرکت
site: "etraav.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content:"اتراب شرکت در حوزه نرم افزار فعالیت دارد و با "

**Comment by tajrobe** [comment]
Done :)
[هلدینگ اتراب ](https://tajrobe.github.io/هلدینگ-اتراب/)
