### ISSUE TITLE
ثبت شرکت تیم یار

### ISSUE THREAD

**Issue by Alvarkheili** [tajrobe/tajrobe.github.io#90]
##### نام شرکت
title: "تیم یار"

##### نام انگلیسی شرکت
name_en: "TeamYar"

##### دسته‌ی فعالیت شرکت
industry: "برنامه نویسی/ نرم افزار"

##### موقعیت مکانی شرکت
city: "کرج"

##### تعداد نفرات شرکت
size: "120"

##### آدرس سایت شرکت
site: "www.teamyar.com"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت تیم‌یار‌ کیش از سال ۱۳۸۸ با رویکردی دانش‌بنیان و با هدف تولید یک «نرم‌افزار مدیریت جامع یکپارچه کسب‌وکار» که در میانه راه «تیم‌یار»، «TeamYar Modern ERP» نام گرفت آغاز به کار کرد.
ERP تیم‌یار تنها محصول شرکت تیم‌یار کیش است.
این شرکت با یک برنامه منسجم و هدفمند و با بهره‌گیری از کارشناسان متخصص، متعهد و کارآزموده خود توانسته زیرساخت نرم‌افزار یکپارچه منحصربه‌فردی را توسعه دهد که در بیش‌تر کسب‌و‌کارها کارآمد است. یکپارچگی، امنیت، انعطاف‌پذیری و تمام ایرانی‌بودن هم در طراحی و هم در تولید، «تیم‌یار» را از دیگر رقبای خود متفاوت و متمایز ساخته است.
شرکت تیم‌یار‌ کیش همگام با آخرین دستاوردها و استانداردهای جهانی در حوزه فناوری اطلاعات و توسعه نرم‌افزاری یکپارچه؛ در جهت تحقق هدف دیجیتالی‌ شدن کسب‌و‌کارها گام برداشته و امکان مدیریت، سازماندهی و تجارتی امن، سریع و آسان را برای کاربران ERP ایرانی تیم‌یار فراهم کرده است.
نرم‌افزار جامع، قدرتمند و تحت‌وب ERP تیم‌یار برای استفاده صاحبان کسب‌و‌کارهای کوچک تا سازمان‌ها و تشکیلات بزرگ توصیه و عرضه می‌شود"

**Comment by tajrobe** [comment]
@Alvarkheili [tajrobe.github.io/تیم-یار/](https://tajrobe.github.io/%D8%AA%DB%8C%D9%85-%DB%8C%D8%A7%D8%B1/)

**Comment by Alvarkheili** [comment]
شرکت تیم یار قبلا ساختمانش در تهران بوده ولی مدتی ه توی پارک علم و فناوری دانشگاه تهران (ساختمان البرز) در شهرک بنفشه کرج هست. و شرط استخدامش هم اینه که ساکن کرج و اطراف کرج باشی. اکثر اونایی تو اون شرکت کار میکنن یا از رفت و آمد هر روزه بین تهران و کرج برای کار کردن خسته شدن، یا ترجیح میدن نزدیک محل زندگی شون سر کار برن. 
در نگاه اول شرکت یه ساختمون بزرگ 5 طبقه نزدیک مترو کرج داره که دسترسی ش خوبه، داخل ساختمون هم تمیزه و خیلی خوب دیزاین شده، در وهله اول آدم حس میکنه وارد یه شرکت خفنی شده.  ناهار گرم و رایگان، پارکینگ رایگان، سالن بازی (میز بیلیارد، میز پینگ پونگ و  فوتبال دستی) ! تا همین جاش فقط خوبه....
برای مصاحبه که چندبار می یارن می برنت و شایدم بگن 3 روز آزمایشی بیا کار کن تا بهت اوکی بدن. 
موقع بستن قرارداد هم میگن که بیمه و سنواتت پایه وزارت کار رد میشه! و یه سفته به مبلغ 200 میلیون تومن هم ازت میگیرن!! قراردادت هم به هیج عنوان بهت نمیدن!!!
 برای مبلغ قرارداد هم سر 100 تومن 200 تومن باهات چک و چونه میزنن! بعد حقوقت که واریز میشه متوجه میشی که عددی که توافق کردی ناخالص بوده و یه بیمه هم ازت کم شده!! 
حقوقش همیشه سر وقت واریز میشه، ولی در 2 قسمت!!! یعنی واریز اول پایه وزارت کاری هست که طبق اون بیمه رد میکنن و قسمت دوم به عنوان پاداش یا هر اسمی دیگه از حساب شخص (مثلا منشی شرکت) واریز میشه!!! آخر هر سال عیدی تقریبا به اندازه سقف عیدی که هر ساله اعلام میکنن واریز میشه ولی سنوات بعد اتمام همکاری با شرکت تسویه میشه. تاریخ چک تسویه هم تقریبا یک سال بعد از اتمام همکاری با اون شرکت هست!!!
این شرکت یه دفترچه قوانین  حدود 20 یا 30 صفحه ای داره که قبل از امضای قرارداد باید همه صفحاتش رو امضا کنی. این قوانین هر 6 ماه یکبار یا هر وقت که مدیران صلاح دونستن متمم و اصلاحیه میخوره و کارمند هیچ گونه اراده ای در امضا نکردن اون نداره و بعد از امضا حتما باید بهش پایبند باشه. طبق این قوانین پرسنل شرکت حق استفاده از گوشی همراه رو در زمان کاری ندارن و گوشی رو باید تو کمد مخصوص گوشی قرار بدن. در صورت انجام ندادن این کار جریمه نقدی میشن!  طبق این قوانین بعد از استعفا گذاشتن باید 3 ماه تو شرکت بمونی تا نیرو جدید بگیرن و کار تحویل اون شخص داده بشه، در غیر این صورت شرکت میتونه از مطالباتی که پیش شون داری و یا سفته هات طلب خسارت کنه و .....
همه جای شرکت دوربین مداربسته هست که هم صدا و هم تصویر ضبط و آرشیو میشه!!
