### ISSUE TITLE
ثبت فراگستر

### ISSUE THREAD

**Issue by Alvarkheili** [tajrobe/tajrobe.github.io#91]
##### نام شرکت
title: "فراگستر"

##### نام انگلیسی شرکت
name_en: "Faragostar"

##### دسته‌ی فعالیت شرکت
industry: " تولید نرم افزار اتوماسیون"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://www.faragostar.net/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت فراگستر که در سال 1380 بصورت سهامی خاص تاسیس گردید، با بیش از دو دهه فعالیت مستمر و پویا، هم‌اکنون در زمره شرکتهای برتر ارائه دهنده نرم‌افزارهای اتوماسیون کسب و کار در کشور شناخته ‌می‌شود. ما شرکتی دانش بنیان، دارای رتبه یک شورایعالی انفورماتیک و همچنین تندیس طلایی رعایت حقوق مصرف کنندگان در طی 5 سال متوالی هستیم. در کارنامه فراگستر اجرای پروژه‌های موفق با سازمانها و نهادهای بزرگی مانند بانک ملی ایران، ایرانسل، دیوان عدالت اداری و … وجود دارد. در حال حاضر بیش از 2600 سازمان با گستردگی 600 هزار کاربر با نرم‌افزار فراگستر، بهره‌وری تیمشان را افزایش داده‌اند."

**Comment by tajrobe** [comment]
@Alvarkheili [tajrobe.github.io/فراگستر/](https://tajrobe.github.io/%D9%81%D8%B1%D8%A7%DA%AF%D8%B3%D8%AA%D8%B1/)

**Comment by Alvarkheili** [comment]
من برای مصاحبه به این شرکت مراجعه کردم. 
مصاحبه شون که حضوری بود. وقتی هم تماس گرفتن برای هماهنگ کردن روز مصاحبه، بهم گفتن فلان روز ساعت 11 منم چون فاصله شرکتم تا شرکت فراگستر یکم زیاد بود، بهشون گفتم اگه امکانش هست زودتر باشه یا اینکه آخر وقت بذارید مصاحبه بنده رو. خانمی که پشت خط بود گفت برای شما همین ساعت در نظر گرفته شده و امکان جابجایی وجود نداره. من چند دقیقه زودتر رسیدم اونجا ولی نیم ساعت منو اونجا کاشتن تا شخصی که باید ازم مصاحبه کنه تشریف بیاره. 
یه آقای اخمویی اومد و بدون اینکه خودشو معرفی کنه سوال پرسیدن رو شروع کرد. بعد از یکی دو تا سوال، ازم پرسید همسرت چیکاره است و کجا کار میکنه؟! منم نفهمیدم چرا این سوال رو پرسید و چه ربطی به مصاحبه  و استخدام شدن من داره؟! ولی قبل اینکه بتونم به این سوال های ذهنی م جواب بدم، جواب سوال شو دادم... بعد  شروع کرد شغل همسر منو مسخره کردن!! و اینکه ما تو شرکتمون همچین کاری نمیکنیم... 
یعنی نمیدونم چجوری خودمو نگه داشتم تا چیزی نگم. به عنوان یه خانوم اونجا کاملا احساس نا امنی کردم و فقط منتظر بودم از اون شرکت خراب شده بزنم بیرون. خیلی عصبانی از اونجا اومدم بیرون و کم کم حرفاش داشت تو ذهنم میچرخید که چرا این حرفارو زد و چه منظوری داشت از این حرفا؟! 
هر جور فکر میکردم نمیتونستم راجع به این شرکت و آدماش مثبت فکر کنم!!!
