### ISSUE TITLE
ثبت شرکت تهران اینترنت - *#780

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#92]
##### نام شرکت

title: "تهران اینترنت - *780#"

##### نام انگلیسی شرکت
name_en: "tehran internet *780"

##### دسته‌ی فعالیت شرکت
industry: "فن آوری اطلاعات "

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: "1-1500"

##### آدرس سایت شرکت
site: "https://780.ir/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گروه شرکت‌های تهران اینترنت بیش از 20 سال است که به عنوان یکی از پیشروان حوزه فناوری اطلاعات در کشور فعالیت و خدمت رسانی می نماید. این مجموعه دانش بنیان با تکیه بر دانش فنی متخصصین زبده همواره با نوآوری و نوآفرینی در حوزه های تله‌کام، تجارت الکترونیک و پرداخت‌های الکترونیک ممتاز گردیده و با ادبیاتی نافذ و آموزنده گام‌های مؤثری در تغییر رفتار مصرف کننده و ترویج استفاده از روش های الکترونیک در پرداخت برداشته است. این شرکت با هدف توسعه خدمات به کاربران نهایی در حوزه موبایل اقدام به ایجاد کد دستوری [*780#](tel:*780%23') (با برند ثبت شده هفـ‌هشتاد) و تهیه اپلیکیشن هفـ‌هشتاد نموده و توانسته است بیش از 2.000.000 تراکنش روزانه را در کارنامه فعالیت خود ثبت نماید.. برند هفـ‌هشتاد با اهتمام بر مسئولیت های اجتماعی با برگزاری بزرگ ترین کمپین های اجتماعی مانند قطره قطره و کتابخوانی، در ترویج مطالعه و حمایت از تولیدات فرهنگی، علاوه بر تلاش های تجاری، محبوبیت و مقبولیت اجتماعی کسب نموده است. سامانه سرويس [*780#](tel:*780%23') براي تمام مشترکين شبکه تلفن همراه ایران، بدون پرداخت هيچ گونه هزينه اي و به صورت رايگان فعال است. براي استفاده از اين سامانه حتي نياز به نصب هيچ گونه نرم افزار بر روي گوشي تلفن همراه و يا استفاده از گوشي هاي مدرن و هوشمند نیست و تنها کافيست با استفاده از رمز اينترنتي(رمز دوم) یا رمز دوم پویای کارت بانکي عضو شبکه شتاب از خدمات این سامانه استفاده نمائید."

**Comment by tajrobe** [comment]
[tajrobe.github.io/تهران-اینترنت/](https://tajrobe.github.io/%D8%AA%D9%87%D8%B1%D8%A7%D9%86-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA/)
