### ISSUE TITLE
ثبت شرکت جدید 

### ISSUE THREAD

**Issue by TheNerdOne** [tajrobe/tajrobe.github.io#93]
##### نام شرکت
title: "ایده پژوهان آویژه"

##### نام انگلیسی شرکت
name_en: "Avijeh"

##### دسته‌ی فعالیت شرکت
industry: "گردشگری"

##### موقعیت مکانی شرکت
city: "تهران گاندی"

##### تعداد نفرات شرکت
size: "۱۰"

##### آدرس سایت شرکت
site: "avijeh.ir"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "طراحی و توسعه نرم‌افزار های گردشگری و مدیریت محتوا"

**Comment by tajrobe** [comment]
[tajrobe.github.io/آویژه/](https://tajrobe.github.io/%D8%A2%D9%88%DB%8C%DA%98%D9%87/)
