### ISSUE TITLE
تراز سامانه

### ISSUE THREAD

**Issue by amirpeace1080** [tajrobe/tajrobe.github.io#94]
##### نام شرکت
title: "تراز سامانه"

##### نام انگلیسی شرکت
name_en: "tarazgroup"

##### دسته‌ی فعالیت شرکت
industry: "سیستم پردازشگر حوزه مالی"

##### موقعیت مکانی شرکت
city: "تهران"

##### تعداد نفرات شرکت
size: ""

##### آدرس سایت شرکت
site: "https://tarazgroup.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "شرکت دانش‌بنیان تراز سامانه ، از جمله شرکت های نرم‌افزاری حاضر در کشور است که با گذشت نزدیک به دو دهه عرضه‌ی راهکارهای نرم‌افزاری به کسب‌ و کارهای ایرانی، بیش از هزار مشتری در کسب‌وکارهای بزرگ، متوسط، کوچک و خاص دارد."

**Comment by tajrobe** [comment]
[tajrobe.github.io/تراز-سامانه/](https://tajrobe.github.io/%D8%AA%D8%B1%D8%A7%D8%B2-%D8%B3%D8%A7%D9%85%D8%A7%D9%86%D9%87/)
