### ISSUE TITLE
ایراد در vercel

### ISSUE THREAD

**Issue by pooooriya** [tajrobe/tajrobe.github.io#95]
مثل اینکه ورسل هم مارو تحریم کرده و روی isp من بالا نمیاد ولی api اش داره درست میکنه ، میتونیم رول بک کنیم به وضعیت قبلی تا من api جدید با اون فرمی که داری سینکش کنم که این دوتا با هم کار کنن ، البته که شایدم بشه اون فرم خروجی ازش گرفت و گذاشت روی گیت هاب پیج منتهی من روتینگ ایناشو بلد نیستم واقعیت چه شکلی میشه

**Comment by pooooriya** [comment]
البته خب اینم با فیلتر کار میکنه اونم با فیلتر کار میکنه شاید اینکه نتونه باز کنه مجبور کنه یوزر که اولش فیلترشو روشن کنه تا اینکه فرم سند کنه و فرمه نره تازه بفهمه ای بابا فیلتر شکنش روشن نبوده !

**Comment by pooooriya** [comment]
#96

**Comment by tajrobe** [comment]
سلام
منم تست کردم. دقیقا شد مشکلی بود با Heroku داشتیم 🫠، احتمالا راه دیگه‌ای هم پیدا کنیم دیر یا زود این مشکل براش تکرار بشه... به نظرم میتونیم بذاریم همینجوری بمونه که افراد یا با فیلترشکن فرم رو بفرستند یا مستقیما از طیق issue گیت‌هاب تجربه‌شون رو مطرح کنند.

**Comment by pooooriya** [comment]
من کامیت قبلی روی مستر پاک کردم یه بار خودت دستی اددش کن چون یه مشکلی داشت موقع کامیت بهش دقت نکرده بودم @tajrobe
