### ISSUE TITLE
شرکت اشترن ایکس تکنولوژی

### ISSUE THREAD

**Issue by navid6117** [tajrobe/tajrobe.github.io#97]
##### نام شرکت
title: "اشترن ایکس تکنولوژی"

##### نام انگلیسی شرکت
name_en: "SternX Technology"

##### دسته‌ی فعالیت شرکت
industry: "it"

##### موقعیت مکانی شرکت
city: "آلمان"

##### تعداد نفرات شرکت
size: "11-50"

##### آدرس سایت شرکت
site: "https://sternx.de/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "گستردگی دنیای فناوری بر هیچکس پوشیده نیست. چشم انداز ما برای آسان کردن زندگی‎ها دست به دست تشکیل تیم حرفه‎ای‎مان داد. ما در اشترن ایکس، در محیطی پویا و خلاق با عشق و علاقه کنار هم کار می‎کنیم و برای اهدافمان برنامه ‎ریزی می‎کنیم. برنامه ها، آسان ترین روش برای ارائه طیفی گسترده از خدمات به پایه کاربری با تعداد بالا هستند. کار ما در اشترن ایکس توسعه برنامه های پیشرفته با کاربری آسان است. این کار را به لطف تیم قویمان و اهداف هوشمندانه به انجام می‎رسانیم. اعضای تیم ما وفاداری و تعهدشان را با احترام متقابل، جدیت در کار و انعطاف ثابت کرده ‎اند. ما از انتقاد سازنده بسیار استقبال می‎کنیم و محیطی که همیشه در آن چیز جدیدی برای یادگیری وجود دارد را پایه گذاری کرده ایم. اشترن ایکس به شدت از کارمندان خود مراقبت می‎کند و به آن‎ها نشان می‎دهد که مشارکت آنان در دنیای گسترده دیجیتال و فناوری حائز اهمیت است."

**Comment by tajrobe** [comment]
[tajrobe.github.io/اشترن-ایکس/](https://tajrobe.github.io/%D8%A7%D8%B4%D8%AA%D8%B1%D9%86-%D8%A7%DB%8C%DA%A9%D8%B3/)
