### ISSUE TITLE
مجتمع بین المللی تهران

### ISSUE THREAD

**Issue by pooriaashkevarvakili** [tajrobe/tajrobe.github.io#99]
##### نام شرکت
title: "مجتمع بین المللی تهران"

##### نام انگلیسی شرکت
name_en: "mojtamae bin malaly tehtan"

##### دسته‌ی فعالیت شرکت
industry: "software"

##### موقعیت مکانی شرکت
city: "tehran"

##### تعداد نفرات شرکت
size: "20"

##### آدرس سایت شرکت
site: "https://tehrantc.com/"

##### توضیحی درباره شرکت و فعالیت‌هایش
content: "مجتمع بین المللی تهران با چندین سال تجربه ارزشمند در حوزه فرآیند سازی، طراحی و تولید نرم افزارهای تخصصی و سازمانی به صورت سفارشی برای مشتریان ارزشمند خود، و همچنین با دارا بودن تیم جوان، خلاق و حرفه ای در کنار آن تجربه ارزشمند در چند سال اخیر ” تولید نرم افزارهای خاص، با اهداف خاص و برای بازارهای خاص” را جزء اهداف تیم های اجرایی خود قرار داده و به موفقیت های بزرگ و ارزشمندی در این حوزه رسیده است.

استفاده از تکنولوژی “داده‌کاوی” و استفاده از مزایای فراوان این علم روز در آینده یکی از ارکان اساسی در تحقیقات و ایده پردازی تیم تحقیق و توسعه این مجتمع می باشد که نمود عینی آن در اکثر نرم افزارهای تولیدی این شرکت چه نرم افزارهای سفارشی و چه نرم افزارهای تخصصی قابل مشاهده و دفاع می باشد.

امیدواریم با تلاش مضاعف و حفظ مسیر ایجاد شده هر روز سازنده خبرها و اتفاقات خوب و آینده دار باشیم."

**Comment by tajrobe** [comment]
[tajrobe.github.io/مجتمع-تهران/](https://tajrobe.github.io/%D9%85%D8%AC%D8%AA%D9%85%D8%B9-%D8%AA%D9%87%D8%B1%D8%A7%D9%86/)
